/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aPlus.
 * 
 * aPlus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aPlus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aPlus.  If not, see <http://www.gnu.org/licenses/>.
 */

#define _GNU_SOURCE
#include <sched.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/memory.h>
#include <aplus/task.h>
#include <aplus/ipc.h>
#include <aplus/elf.h>
#include <aplus/errno.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/signal.h>

#include <hal/cpu.h>
#include <hal/vmm.h>
#include <hal/timer.h>
#include <hal/userspace.h>



static inline uintptr_t __sbrk(uintptr_t incr) {

    uintptr_t brk = sys_brk(0);
    uintptr_t new = sys_brk(brk + incr);

    if(new == brk && incr)
         kpanicf("sys_execve(): out of memory!\n");

    return brk;

}



/***
 * Name:        execve
 * Description: execute program
 * URL:         http://man7.org/linux/man-pages/man2/execve.2.html
 *
 * Input Parameters:
 *  0: 0x3B
 *  1: const char __user *
 *  2: const char __user **
 *  3: const char __user **
 *
 * Auto-generated by extra/utils/gen-syscalls.js
 */


SYSCALL(59, execve,
long sys_execve (const char __user * filename, const char __user ** argv, const char __user ** envp) {
    
    
    if(unlikely(!filename))
        return -EINVAL;

    if(unlikely(!argv))
        return -EINVAL;

    if(unlikely(!envp))
        return -EINVAL;

    if(unlikely(!ptr_check(filename, R_OK)))
        return -EFAULT;

    if(unlikely(!ptr_check(argv, R_OK)))
        return -EFAULT;

    if(unlikely(!ptr_check(envp, R_OK)))
        return -EFAULT;


    int e;

    struct stat st;
    if((e = sys_newstat(filename, &st)) < 0)
        return e;



    e = 0;

    if(st.st_mode & S_IXUSR)
        e = (st.st_uid == current_task->uid);

    else if(st.st_mode & S_IXGRP)
        e = (st.st_gid == current_task->gid);
    
    else if(st.st_mode & S_IXOTH)
        e = 1;


    if(!e)
        return -EPERM;




    int fd;
    if((fd = sys_open(filename, O_RDONLY, 0)) < 0)
        return fd;


    Elf_Ehdr head;
    if((e = sys_read(fd, &head, sizeof(head))) < 0)
        return e;



    if(head.e_ident[0] == '#' &&
       head.e_ident[1] == '!')
        return -ENOEXEC; // TODO: Read Scripts


    if(
        (head.e_ident[EI_MAG0] != ELFMAG0) ||
        (head.e_ident[EI_MAG1] != ELFMAG1) ||
        (head.e_ident[EI_MAG2] != ELFMAG2) ||
        (head.e_ident[EI_MAG3] != ELFMAG3) ||
        (head.e_type != ET_EXEC)           ||
        (head.e_entry == 0)
    ) return -ENOEXEC;



    



    #define RXX(a, b, c) {                                                  \
        if((e = sys_lseek(fd, (off_t) (b), SEEK_SET)) < 0)                  \
            return e;                                                       \
                                                                            \
        if((e = sys_read(fd, (void*)(a), (size_t)(c))) != (size_t)(c)) {    \
            if(e < 0)                                                       \
                return e;                                                   \
            else                                                            \
                return -EIO;                                                \
        }                                                                   \
    }



    uintptr_t end;
    uintptr_t flags;

    __lock(&current_task->lock, {


        //arch_userspace_release(); // TODO

        current_task->userspace.start = ~0UL;
        current_task->userspace.end   =  0UL;


        int i;
        for(i = 0; i < head.e_phnum; i++) {

            Elf_Phdr phdr;
            RXX(&phdr, head.e_phoff + (i * head.e_phentsize), head.e_phentsize);


            switch(phdr.p_type) {

                case PT_LOAD:                    
                case PT_TLS:

                    DEBUG_ASSERT(phdr.p_vaddr);
                    DEBUG_ASSERT(phdr.p_memsz);
                    DEBUG_ASSERT(phdr.p_filesz <= phdr.p_memsz);


                    end = phdr.p_vaddr + phdr.p_memsz;
                    end = (end & ~(phdr.p_align - 1)) + phdr.p_align;


                    if(phdr.p_vaddr < current_task->userspace.start)
                        current_task->userspace.start = phdr.p_vaddr;

                    if(end > current_task->userspace.end)
                        current_task->userspace.end = end;


                    flags = 0;
                    
                    if(!(phdr.p_flags & PF_X))
                        flags |= ARCH_VMM_MAP_NOEXEC;
                    
                    if( (phdr.p_flags & PF_W))
                        flags |= ARCH_VMM_MAP_RDWR;


                    arch_vmm_map (current_task->address_space, phdr.p_vaddr, -1, phdr.p_memsz,
                                    ARCH_VMM_MAP_RDWR      |
                                    ARCH_VMM_MAP_USER      |
                                    ARCH_VMM_MAP_TYPE_PAGE);


#if defined(DEBUG) && DEBUG_LEVEL >= 4
                    kprintf("sys_execve: PT_LOAD at address(%p) size(%p) alignsize(%p)\n", phdr.p_vaddr, phdr.p_memsz, end - phdr.p_vaddr);
#endif

                    RXX(phdr.p_vaddr, phdr.p_offset, phdr.p_filesz);


                    arch_vmm_mprotect (current_task->address_space, phdr.p_vaddr, phdr.p_memsz,
                                    flags                  |
                                    ARCH_VMM_MAP_USER      |
                                    ARCH_VMM_MAP_TYPE_PAGE);

                    break;


                case PT_GNU_EH_FRAME:
                    
                    kprintf("execve: WARN! PT_GNU_EH_FRAME not yet supported\n");
                    break;

                case PT_DYNAMIC:

                    kpanicf("execve: PANIC! PT_DYNAMIC not supported at kernel-level");
                    break;

                default:
                    continue;

            }
        }

        current_task->userspace.end = (current_task->userspace.end & ~(arch_vmm_getpagesize() - 1)) + arch_vmm_getpagesize();

    });


    DEBUG_ASSERT(current_task->userspace.start);
    DEBUG_ASSERT(current_task->userspace.end);
    DEBUG_ASSERT(current_task->userspace.start < current_task->userspace.end);
    DEBUG_ASSERT(current_task->fd[fd].ref);

    current_task->exe = (current_task->fd[fd].ref->inode);

    sys_close(fd);



    int i;
    for(i = 0; i < OPEN_MAX; i++) {

        if(!current_task->fd[i].ref)
            continue;

        if(!current_task->fd[i].close_on_exec)
            continue;

        
        sys_close(i);

    }



#if defined(DEBUG) && DEBUG_LEVEL >= 0

    for(i = 0; argv[i]; i++)
        DEBUG_ASSERT(ptr_check(argv[i], R_OK));

    for(i = 0; envp[i]; i++)
        DEBUG_ASSERT(ptr_check(envp[i], R_OK));

#endif


    size_t argc;
    for(argc = 0; argv[argc]; argc++)
        ;

    size_t envc;
    for(envc = 0; envp[envc]; envc++)
        ;
    

    __sbrk(current_task->rlimits[RLIMIT_STACK].rlim_cur);
    uintptr_t stack    = __sbrk(0);

    __sbrk(SIGSTKSZ);
    uintptr_t sigstack = __sbrk(0);

    

    char** argq = (char**) __sbrk(sizeof(char*) * (argc + 1));
    char** envq = (char**) __sbrk(sizeof(char*) * (envc + 1));

    for(i = 0; argv[i]; i++) {
     
        char* p = (char*) __sbrk(strlen(argv[i]));
        strcpy(p, argv[i]);

        *argq++ = p;
        *argq   = NULL;
    }

    for(i = 0; envp[i]; i++) {
     
        char* p = (char*) __sbrk(strlen(envp[i]));
        strcpy(p, envp[i]);

        *envq++ = p;
        *envq   = NULL;
    
    }

    // TODO: implement AUXV


    uintptr_t* args = (uintptr_t*) __sbrk(sizeof(uintptr_t) * 4);

    args[0] = (uintptr_t) argc;
    args[1] = (uintptr_t) argq;
    args[2] = (uintptr_t) envq;
    //*args++ = (uintptr_t) auxv;



    current_task->userspace.stack    = stack;
    current_task->userspace.sigstack = sigstack;


    arch_userspace_enter(head.e_entry, stack, args);

    return -EINVAL;
});
