/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aPlus.
 * 
 * aPlus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aPlus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aPlus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <aplus/smp.h>
#include <aplus/mm.h>
#include <stdint.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>


/***
 * Name:        newfstat
 * Description: 
 * URL:         http://man7.org/linux/man-pages/man2/newfstat.2.html
 *
 * Input Parameters:
 *  0: 0x05
 *  1: unsigned int fd
 *  2: struct stat __user * statbuf
 *
 * Auto-generated by extra/utils/gen-syscalls.js
 */

SYSCALL(5, newfstat,
long sys_newfstat (unsigned int fd, struct stat __user * statbuf) {

    if(fd < 0)
        return -EBADF;

    if(fd > TASK_NFD)
        return -EBADF;

    if(!statbuf)
        return -EINVAL;

    if(!ptr_check(statbuf, R_OK | W_OK))
        return -EFAULT;


    DEBUG_ASSERT(current_task->fd[fd].inode);
    DEBUG_ASSERT(current_task->fd[fd].inode->ino);

    if(unlikely(!current_task->fd[fd].inode))
        return -EBADF;



    __lock(&current_task->fd[fd].inode->ino->lock, {

        memcpy(statbuf, &current_task->fd[fd].inode->ino->st, sizeof(struct stat));

    });

    return 0;
});
