/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aPlus.
 * 
 * aPlus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aPlus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aPlus.  If not, see <http://www.gnu.org/licenses/>.
 */

#define _GNU_SOURCE
#include <sched.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <aplus/mm.h>
#include <aplus/smp.h>
#include <aplus/task.h>
#include <aplus/ipc.h>
#include <aplus/elf.h>
#include <stdint.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>


/***
 * Name:        execve
 * Description: execute program
 * URL:         http://man7.org/linux/man-pages/man2/execve.2.html
 *
 * Input Parameters:
 *  0: 0x3B
 *  1: const char __user *
 *  2: const char __user **
 *  3: const char __user **
 *
 * Auto-generated by extra/utils/gen-syscalls.js
 */


SYSCALL(59, execve,
long sys_execve (const char __user * filename, const char __user ** argv, const char __user ** envp) {
    
    if(unlikely(!filename))
        return -EINVAL;

    if(unlikely(!argv))
        return -EINVAL;

    if(unlikely(!envp))
        return -EINVAL;

    if(unlikely(!ptr_check(filename, R_OK)))
        return -EFAULT;

    if(unlikely(!ptr_check(argv, R_OK)))
        return -EFAULT;

    if(unlikely(!ptr_check(envp, R_OK)))
        return -EFAULT;


    int e;
    struct stat st;
    if((e = sys_newstat(filename, &st)) < 0)
        return e;


    if(st.st_uid == current_task->uid && !(st.st_mode & S_IXUSR))
        return -EPERM;

    else if(st.st_gid == current_task->gid && !(st.st_mode & S_IXGRP))
        return -EPERM;
    
    else if(!(st.st_mode & S_IXOTH))
        return -EPERM;



    int fd;
    if((fd = sys_open(filename, O_RDONLY, 0)) < 0)
        return fd;


    Elf_Ehdr head;
    if((e = sys_read(fd, &head, sizeof(head))) < 0)
        return e;


    if(head.e_ident[0] == '#' &&
       head.e_ident[1] == '!')
        return -ENOEXEC; /* TODO: Read Scripts */


    
    if(
        (head.e_ident[EI_MAG0] != ELFMAG0) ||
        (head.e_ident[EI_MAG1] != ELFMAG1) ||
        (head.e_ident[EI_MAG2] != ELFMAG2) ||
        (head.e_ident[EI_MAG3] != ELFMAG3) ||
        (head.e_type != ET_EXEC)
    ) return -ENOEXEC;



    


    uintptr_t i_base = ~0L;
    uintptr_t i_end = 0L;
    size_t size;



    #define RXX(a, b, c) {                                                  \
        if((e = sys_lseek(fd, (off_t) (b), SEEK_SET)) < 0)                  \
            return e;                                                       \
                                                                            \
        if((e = sys_read(fd, (void*)(a), (size_t)(c))) != (size_t)(c)) {    \
            if(e < 0)                                                       \
                return e;                                                   \
            else                                                            \
                return -EIO;                                                \
        }                                                                   \
    }



    __lock(&current_task->lock, {


        aspace_free(current_task->aspace);


        current_task->aspace->start =  0UL;
        current_task->aspace->end   = ~0UL;


        int i;
        for(i = 0; i < head.e_phnum; i++) {

            Elf_Phdr phdr;
            RXX(&phdr, head.e_phoff + (i * head.e_phentsize), head.e_phentsize);


            switch(phdr.p_type) {

                case PT_LOAD:

                    size = (phdr.p_memsz + phdr.p_align - 1) & ~(phdr.p_align - 1);

                    if(phdr.p_vaddr < i_base)
                        i_base = phdr.p_vaddr;

                    if((size + phdr.p_vaddr > i_end))
                        i_end = size + phdr.p_vaddr;



                    aspace_add_map (
                        current_task->aspace,
                        
                        (phdr.p_flags & PF_X)
                            ? ASPACE_TYPE_CODE
                            : ASPACE_TYPE_DATA
                            ,
                        
                        phdr.p_vaddr, 
                        phdr.p_vaddr + size - 1,

                        //((phdr.p_flags & PF_R) ? ARCH_MAP_USER : 0) |
                        //((phdr.p_flags & PF_W) ? ARCH_MAP_RDWR : 0) |  /* FIXME: Add protection */
                        //((phdr.p_flags & PF_X) ? 0 : ARCH_MAP_NOEXEC)

                        ARCH_MAP_USER | ARCH_MAP_RDWR
                    );


                    RXX(phdr.p_vaddr, phdr.p_offset, phdr.p_filesz);
                    break;

                case PT_TLS:

                    size = (phdr.p_memsz + phdr.p_align - 1) & ~(phdr.p_align - 1);

                    aspace_add_map ( 
                        current_task->aspace, ASPACE_TYPE_TLS, 
                        phdr.p_vaddr, 
                        phdr.p_vaddr + size, 
                        ARCH_MAP_USER | ARCH_MAP_RDWR | ARCH_MAP_NOEXEC
                    );

                    break;

                case PT_GNU_EH_FRAME:
                    
                    kprintf("execve: WARN! PT_GNU_EH_FRAME not yet supported\n");
                    break;

                case PT_DYNAMIC:

                    kpanic("execve: FAIL! PT_DYNAMIC not supported");
                    break;

                default:
                    continue;

            }
        }


        current_task->aspace->start = (i_base & ~(PAGE_SIZE - 1));
        current_task->aspace->end   = (i_end  & ~(PAGE_SIZE - 1)) + PAGE_SIZE;
        current_task->exe = current_task->fd[fd].inode;


        aspace_add_map (
            current_task->aspace, ASPACE_TYPE_BRK, 
            current_task->aspace->end, 
            current_task->aspace->end, 
            ARCH_MAP_RDWR | ARCH_MAP_NOEXEC | ARCH_MAP_USER
        );

        current_task->aspace->end = current_task->rlimits[RLIMIT_RSS].rlim_cur;


    });


    sys_close(fd);



    int i;
    for(i = 0; i < TASK_NFD; i++) {

        if(!current_task->fd[i].inode)
            continue;

        if(!current_task->fd[i].close_on_exec)
            continue;

        
        sys_close(i);

    }



#if defined(DEBUG)

    for(i = 0; argv[i]; i++)
        DEBUG_ASSERT(ptr_check(argv[i], R_OK));

    for(i = 0; envp[i]; i++)
        DEBUG_ASSERT(ptr_check(envp[i], R_OK));

#endif



    uintptr_t brk = sys_brk(0);
    uintptr_t top = sys_brk(brk + current_task->rlimits[RLIMIT_STACK].rlim_cur);


    brk += sizeof(uintptr_t);
    brk += sizeof(uintptr_t);

    strcat((char*) brk, filename);
    strcat((char*) brk, " ");

    for(i = 0; argv[i]; i++) {
        strcat((char*) brk, argv[i]);
        strcat((char*) brk, " ");
    }

    strcat((char*) brk, "\e$$$ ");
        
    for(i = 0; envp[i]; i++) {
        strcat((char*) brk, envp[i]);
        strcat((char*) brk, " ");
    }

    strcat((char*) brk, "\e$$$ ");


    uintptr_t tls_start = 0;
    uintptr_t tls_end   = 0;

    address_space_map_t* tls = NULL;
    aspace_get_maps(current_task->aspace, &tls, ASPACE_TYPE_TLS, 1);


    if(tls)
        tls_start = tls->start,
        tls_end   = tls->end;



    brk -= sizeof(uintptr_t);
    brk -= sizeof(uintptr_t);

    ((uintptr_t*) brk) [0] = tls_start;
    ((uintptr_t*) brk) [1] = tls_end;



    /* BRK Layout
     * 
     * 0-4:     tls_start
     * 4-8:     tls_end
     * 8-n:     argv
     * n-m:     envp
     * ...:     auxv  // TODO...
     */


    DEBUG_ASSERT(current_task->frame.context);
    DEBUG_ASSERT(head.e_entry);


    arch_intr_disable();
    arch_task_set_context(current_task->frame.context, head.e_entry, brk, top, 0);

    if(!(current_cpu->flags & CPU_FLAGS_INTERRUPT))
        arch_task_return_to_context(current_task->frame.context);

});
