/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aPlus.
 * 
 * aPlus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aPlus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aPlus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <stdint.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>


/***
 * Name:        migrate_pages
 * Description: move all pages in a process to another set of nodes
 * URL:         http://man7.org/linux/man-pages/man2/migrate_pages.2.html
 *
 * Input Parameters:
 *  0: 0x100
 *  1: pid_t pid
 *  2: unsigned long maxnode
 *  3: const unsigned long __user * from
 *  4: const unsigned long __user * to
 *
 * Auto-generated by extra/utils/gen-syscalls.js
 */

SYSCALL(256, migrate_pages,
long sys_migrate_pages (pid_t pid, unsigned long maxnode, const unsigned long __user * from, const unsigned long __user * to) {
    return -ENOSYS;
});
