/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aPlus.
 * 
 * aPlus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aPlus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aPlus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <aplus/smp.h>
#include <stdint.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>


/***
 * Name:        pkey_mprotect
 * Description: set protection on a region of memory
 * URL:         http://man7.org/linux/man-pages/man2/pkey_mprotect.2.html
 *
 * Input Parameters:
 *  0: 0x149
 *  1: unsigned long start
 *  2: size_t len
 *  3: unsigned long prot
 *  4: int pkey
 *
 * Auto-generated by extra/utils/gen-syscalls.js
 */

SYSCALL(329, pkey_mprotect,
long sys_pkey_mprotect (unsigned long start, size_t len, unsigned long prot, int pkey) {
    return -ENOSYS;
});
