#!/bin/bash


# Requirements:
#  nodejs -> npm install
#  cmake
#  ninja
#  nasm
#  grub
#  qemu
#  qemu-arch-extra
#  e2fsprogs
#  bash


target="i686"
toolchain=${TOOLCHAIN:-"$(pwd)/sdk/toolchain"}
generator="Ninja"
mode="run"
build="Debug"
project=""
nobuild="no"
norun="no"
novm="no"
noinstall="no"
gdb="no"
builddir="/tmp/aplus-build"


check () {
    if [ ! $? -eq 0 ]; then
        echo "build: failed with $?"
        exit
    fi
}


while [[ $# -gt 0 ]]; do
    case $1 in
        -t|--target)
            target="$2"
            shift
            shift
            ;;

        -g|--generator)
            generator="$2"
            shift
            shift
            ;;

        -p|--project)
            project="$2"
            shift
            shift
            ;;

        -n|--nobuild)
            nobuild="yes"
            shift
            ;;

        -i|--noinstall)
            noinstall="yes"
            shift
            ;;

        -r|--norun)
            norun="yes"
            shift
            ;;

        -b|--build)
            build="$2"
            shift
            shift
            ;;
        
        -v|--novm)
            novm="yes"
            shift
            ;;

        -d|--gdb)
            gdb="yes"
            shift
            ;;

        run)
            mode="run"
            shift
            ;;

        clean)
            mode="clean"
            shift
            ;;

        libc++)
            mode="libc++"
            shift
            ;;


        -h|--help)
            echo " Usage: ./build MODE [-t TARGET] [-g GENERATOR] [-p PROJECT] [-b BUILD] [-nrd]"
            echo ""
            echo "  MODE:                run, rebuild, clean             (default: $mode)"
            echo ""
            echo "    -t, --target       i686, x86-64, arm, aarch64      (default: $target)"
            echo "    -g, --generator    see cmake generators...         (default: $generator)"
            echo "    -p, --project      project to build                (default: all)"
            echo "    -b, --build        build (Release, Debug)          (default: $build)"
            echo "    -n, --nobuild      configure only"
            echo "    -i, --noinstall    configure and build only"
            echo "    -r, --norun        configure, build and install only"
            echo "    -v, --novm         configure, build, install and gen image only"
            echo "    -d, --gdb          run vm with gdb support"
            echo ""
            exit
            ;;

        *)
            echo "build: unknown argument $1"
            exit
            ;;
    esac
done


case $mode in
    run)
        mkdir -p $builddir
        srcdir=$(pwd)

        ./extra/utils/check-root
        check

        ./extra/utils/gen-files
        check

        pushd $builddir &> /dev/null

            cmake -DCMAKE_BUILD_TYPE=$build -DTOOLCHAIN=$toolchain -DTOOLCHAIN_PREFIX=$toolchain/$target-aplus -DTARGET=$target -DCMAKE_TOOLCHAIN_FILE=$srcdir/cmake/toolchain.cmake -G"$generator" $srcdir
            check

            if [ "$nobuild" = "yes" ]; then
                exit
            fi

            case $generator in
                Ninja)
                    ninja $project
                    check
                    
                    if [ "$noinstall" = "no" ]; then
                        ninja install
                        check
                    fi
            
                    ;;
                "Unix Makefiles")
                    make $project
                    check

                    if [ "$noinstall" = "no" ]; then
                        make install
                        check
                    fi

                    ;;
                *)
                    echo "Sorry, I have no idea what i'm doing :("
                    exit
                    ;;
            esac

        popd &> /dev/null


        if [ "$norun" = "yes" ]; then
            exit
        fi

        ./extra/utils/gen-grubcfg > $(pwd)/root/boot/grub/grub.cfg
        check

        ./extra/utils/gen-image
        check

        
        if [ "$novm" = "yes" ]; then
            exit
        fi
        
        
        if [ "$gdb" = "yes" ]; then
            ./extra/utils/run-qemu $target --debug
        else
            ./extra/utils/run-qemu $target
        fi

        ;;
    
    clean)
        rm -rf $builddir
        ;;

    libc++)
    
        $0 -i -r -g $generator -t $target -p libc.a
        $0 -i -r -g $generator -t $target -p libm.a
        $0 -i -r -g $generator -t $target -p crt0
        $0 -i -r -g $generator -t $target -p crti
        $0 -i -r -g $generator -t $target -p crtn
        $0 -i -r -g $generator -t $target -p rcrt1
        $0 -i -r -g $generator -t $target -p Scrt1

        echo " -- Installing libc" && cp /tmp/aplus-build/sdk/libs/c/libc.a $toolchain/$target-aplus/lib
        echo " -- Installing libm" && cp /tmp/aplus-build/sdk/libs/m/libm.a $toolchain/$target-aplus/lib
        echo " -- Installing crt0" && cp /tmp/aplus-build/sdk/libs/crt/CMakeFiles/crt0.dir/crt0.c.obj $toolchain/$target-aplus/lib/crt0.o
        echo " -- Installing crti" && cp /tmp/aplus-build/sdk/libs/crt/CMakeFiles/crti.dir/crti.s.obj $toolchain/$target-aplus/lib/crti.o
        echo " -- Installing crtn" && cp /tmp/aplus-build/sdk/libs/crt/CMakeFiles/crtn.dir/crtn.s.obj $toolchain/$target-aplus/lib/crtn.o
        echo " -- Installing rcrt1" && cp /tmp/aplus-build/sdk/libs/crt/CMakeFiles/rcrt1.dir/rcrt1.c.obj $toolchain/$target-aplus/lib/rcrt1.o
        echo " -- Installing Scrt1" && cp /tmp/aplus-build/sdk/libs/crt/CMakeFiles/Scrt1.dir/Scrt1.c.obj $toolchain/$target-aplus/lib/Scrt1.o
        
        ;;
esac



