
VMM		:= qemu-system-arm -kernel aplus -initrd bin/initrd -M raspi -cpu arm1176 -serial stdio -m 256M

CFLAGS	+= -Ofast -mfpu=vfp -Wa,-mcpu=arm1176jzf-s -fpic -I $(TOP)/src/include/arch/rpi/csud
LIBS	:= -lcsud $(LIBS)
