
SRCDIRS	 := .
INCLUDES := $(ROOTDIR)/include
DEFINES	 := KERNEL=1 MODULE=1
LIBS	 := 

CFLAGS   := -include $(ROOTDIR)/config.h
ASFLAGS  := -include $(ROOTDIR)/config.h
RUSTFLAGS := --extern rustk=/opt/prj/aplus/lib/rustk/librustk.rlib --sysroot=/opt/prj/aplus/lib/rustk/target/sysroot

include $(ROOTDIR)/build/cross.mk
include $(ROOTDIR)/build/build-ko.mk