.PHONY: all

CXX			?=
ROOT		?=
OUTPUT		:= $(ROOT)/bin/usr/sbin/$(notdir $(PWD))

CXXFILES	:=  $(shell $(FIND) $(PWD)/* -type f -name "*.cpp")
OFILES		:=  $(CXXFILES:.cpp=.o)

CXXFLAGS	:=  -pipe -I include -std=c++17 -O3  -c
SFLAGS		:=  -c -I include

all: $(OUTPUT)
$(OUTPUT): $(OFILES)
	@echo "  CCLD   " $(subst $(ROOT)/,,$@)
	@$(CXX) -pipe -O3 -s -o $@ $(OFILES) -laplus -lpthread -lcairo -lpixman-1 -lfreetype -lwebp -lpng -lz -lstdc++ -lc -lm -lsupc++ -lgcc

.cpp.o:
	@echo "  CXX    " $(subst $(ROOT)/,,$@)
	@$(CXX) $(CXXFLAGS) -o $@ $<

	
clean:
	$(RM) $(OFILES) $(OUTPUT)