#!/bin/bash
#
# usage: update-webp-copies [dir]
#


find $1 -regextype posix-egrep \
    -type f \
    -iregex '.*\.png$' \
    -exec test '{}'.webp -ot '{}' \; \
    -execdir "scripts/webp/convert-png-to-webp" '{}' \;
