INCLUDES += $(ROOTDIR)/include
INCLUDES += $(ROOTDIR)/lib/aplus/ui/include
LDFLAGS  += -L$(ROOTDIR)/lib/aplus/ui
LIBS     += ui z
include $(ROOTDIR)/build/cross.mk
include $(ROOTDIR)/build/build-binary.mk
