
PREFIX := /usr/local/cross/i586-elf/lib
SRC := link.ld

CP := cp

.PHONY: all install

all: install

install:
	@$(CP) $(SRC) $(PREFIX)
	@$(CP) $(SRC) $(PREFIX)/ldscripts/elf_i386.x
	@$(CP) $(SRC) $(PREFIX)/ldscripts/elf_i386.xd
	@$(CP) $(SRC) $(PREFIX)/ldscripts/elf_i386.xn
	@$(CP) $(SRC) $(PREFIX)/ldscripts/elf_i386.xsc
	@$(CP) $(SRC) $(PREFIX)/ldscripts/elf_i386.xw
	@$(CP) $(SRC) $(PREFIX)/ldscripts/elf_i386.xbn
	@$(CP) $(SRC) $(PREFIX)/ldscripts/elf_i386.xdc
	@$(CP) $(SRC) $(PREFIX)/ldscripts/elf_i386.xr
	@$(CP) $(SRC) $(PREFIX)/ldscripts/elf_i386.xsw
	@$(CP) $(SRC) $(PREFIX)/ldscripts/elf_i386.xc
	@$(CP) $(SRC) $(PREFIX)/ldscripts/elf_i386.xdw
	@$(CP) $(SRC) $(PREFIX)/ldscripts/elf_i386.xs
	@$(CP) $(SRC) $(PREFIX)/ldscripts/elf_i386.xu