INCLUDES += $(ROOTDIR)/include
INCLUDES += $(SYSROOT)/usr/include
INCLUDES += $(SYSROOT)/usr/include/freetype2
LIBS 	 += tsm cairo freetype pixman-1 png z
include $(ROOTDIR)/build/cross.mk
include $(ROOTDIR)/build/build-binary.mk