INCLUDES += $(ROOTDIR)/include
INCLUDES += $(SYSROOT)/usr/include
CFLAGS   += -include $(ROOTDIR)/config.h
CFLAGS   += -Wno-parentheses
include $(ROOTDIR)/build/cross.mk
include $(ROOTDIR)/build/build-binary.mk
