
SRCDIRS	 := arch/$(PLATFORM) kernel
INCLUDES := ../include
DESTDIR  := $(SYSROOT)/boot

include ./arch/$(PLATFORM)/config.mk
include $(ROOTDIR)/extra/build/cross.mk
include $(ROOTDIR)/extra/build/build.mk