#!/bin/bash

# Usage
#   gen-initrd SYSROOT

# This script generates an initrd for the given sysroot.


set -euo pipefail

TMPDIR="/tmp/aplus-initrd"

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    echo "Usage: gen-initrd SYSROOT"
    echo "  SYSROOT: The sysroot to generate an initrd for."
    exit 0
fi

if [ -z "${1:-}" ] || [ ! -d "$1" ]; then
    echo "No valid sysroot specified." >&2
    exit 1
fi

SYSROOT="$1"

rm -rf "$TMPDIR"
mkdir -p "$TMPDIR"

pushd "$SYSROOT" &> /dev/null

mkisofs -R -l -o "$TMPDIR/initrd.img" -find . \
    ! -path "./boot/*" \
    ! -path "./boot" \
    ! -path "./usr/lib/modules/*" \
    ! -path "./usr/lib/modules" \
    &> /dev/null

popd &> /dev/null
