#!/bin/bash

# Usage
#   gen-grubcfg [OPTIONS] SYSROOT [EXTRA_KARGS] [EXTRA_MARGS]

# This script generates a grub.cfg file for the given sysroot.

LIVE_MODE=0

while $1; do
    case $1 in
    -h | --help)
        echo "Usage: gen-grubcfg [SYSROOT] [EXTRA_KARGS] [EXTRA_MARGS]"
        echo "  SYSROOT: The sysroot to generate grub.cfg for."
        echo "  EXTRA_KARGS: Extra kernel arguments to pass to the kernel."
        echo "  EXTRA_MARGS: Extra arguments to pass to the modules."
        exit 0
        ;;
    --live)
        LIVE_MODE=1
        shift
        ;;
    *)
        echo "Unknown option: $1"
        exit 1
        ;;
    esac
done

if [ -z "$1" ]; then
    echo "No sysroot specified."
    exit 1
else
    SYSROOT="$1"
fi

if [ -z "$2" ]; then
    EXTRA_KARGS=""
else
    EXTRA_KARGS="$2"
fi

if [ -z "$3" ]; then
    EXTRA_MARGS=""
else
    EXTRA_MARGS="$3"
fi

DEFAULT_KARGS="smp=auto network=off"

header() {
    echo -e "default 0"
    echo -e "timeout 5"
    echo -e ""
}

entry() {

    echo -e "menuentry \"$1\" {"
    echo -e "   multiboot2 /boot/aplus.gz $2"

    if [ $LIVE_MODE -eq 1 ]; then
        echo -e "   module2 /boot/initrd.img.gz type=ramdisk"
    fi

    if [ -e $SYSROOT/usr/lib/modules/exports.gz ]; then
        echo -e "   module2 /usr/lib/modules/exports.gz type=exports"
    fi

    pushd $SYSROOT &>/dev/null

    for ko in $(find usr/lib/modules -type f -iname "*.ko"); do
        test -f "$ko" || continue
        echo -e "   module2 /$ko.gz type=module $3"
    done

    popd &>/dev/null

    echo -e "   boot"
    echo -e "}"
    echo -e ""

}

header >$SYSROOT/boot/grub/grub.cfg

if [ $LIVE_MODE -eq 1 ]; then
    entry "aplus" "root=/dev/ram0 rootfs=iso9660 $DEFAULT_KARGS $EXTRA_KARGS" "$EXTRA_MARGS" >>$SYSROOT/boot/grub/grub.cfg
    entry "aplus-nographics" "root=/dev/ram0 rootfs=iso9660 $DEFAULT_KARGS graphics=off $EXTRA_KARGS" "$EXTRA_MARGS" >>$SYSROOT/boot/grub/grub.cfg
    entry "aplus-builtin-graphics" "root=/dev/ram0 rootfs=iso9660 $DEFAULT_KARGS graphics=builtin $EXTRA_KARGS" "$EXTRA_MARGS" >>$SYSROOT/boot/grub/grub.cfg
else
    entry "aplus" "root=/dev/sda2 rootfs=ext2 $DEFAULT_KARGS $EXTRA_KARGS" "$EXTRA_MARGS" >>$SYSROOT/boot/grub/grub.cfg
    entry "aplus-nographics" "root=/dev/sda2 rootfs=ext2 $DEFAULT_KARGS graphics=off $EXTRA_KARGS" "$EXTRA_MARGS" >>$SYSROOT/boot/grub/grub.cfg
    entry "aplus-builtin-graphics" "root=/dev/sda2 rootfs=ext2 $DEFAULT_KARGS graphics=builtin $EXTRA_KARGS" "$EXTRA_MARGS" >>$SYSROOT/boot/grub/grub.cfg
fi
