#!/bin/sh

# Usage
#   gen-initrd SYSROOT

# This script generates an initrd for the given sysroot.


TMPDIR="/tmp/aplus-initrd"

if [ -z "$1" ]; then
    echo "No sysroot specified."
    exit 1
else
    SYSROOT="$1"
fi

if [ -e $TMPDIR ]; then
    rm -rf $TMPDIR
fi

mkdir -p $TMPDIR


pushd $SYSROOT &> /dev/null

    mkisofs -R -l -o $TMPDIR/initrd.img -find .         \
        ! -path "./boot/*"                              \
        ! -path "./boot"                                \
        ! -path "./usr/lib/modules/*"                   \
        ! -path "./usr/lib/modules"                     \
    &> /dev/null

popd &> /dev/null

exit 0