#!/bin/bash
# Usage: gen-license [SOURCES]

while $1; do
    case $1 in
    -h | --help)
        echo "Usage: gen-license [SOURCES]"
        exit 0
        ;;
    *)
        echo "Unknown option: $1"
        exit 1
        ;;
    esac
done

LICENSE="\
/*                                                                      \n\
 * Author(s):                                                           \n\
 *      Antonino Natale <antonio.natale97@hotmail.com>                  \n\
 *                                                                      \n\
 * Copyright (c) 2013-2019 Antonino Natale                              \n\
 *                                                                      \n\
 *                                                                      \n\
 * This file is part of aplus.                                          \n\
 *                                                                      \n\
 * aplus is free software: you can redistribute it and/or modify        \n\
 * it under the terms of the GNU General Public License as published by \n\
 * the Free Software Foundation, either version 3 of the License, or    \n\
 * (at your option) any later version.                                  \n\
 *                                                                      \n\
 * aplus is distributed in the hope that it will be useful,             \n\
 * but WITHOUT ANY WARRANTY; without even the implied warranty of       \n\
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        \n\
 * GNU General Public License for more details.                         \n\
 *                                                                      \n\
 * You should have received a copy of the GNU General Public License    \n\
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.       \n\
 */                                                                     \n\
                                                                        \n"

for i in $@; do
    if ! cat $i | grep "Copyright (c)" &>/dev/null; then
        echo -e "$LICENSE$(cat $i)" >$i
    fi
done
