#!/bin/sh

# Usage
#   gen-initrd SYSROOT

# This script generates an initrd for the given sysroot.


TMPDIR="/tmp/aplus-initrd"

while $1; do
    case $1 in
    -h | --help)
        echo "Usage: gen-initrd SYSROOT"
        echo "  SYSROOT: The sysroot to generate an initrd for."
        exit 0
        ;;
    *)
        echo "Unknown option: $1"
        exit 1
        ;;
    esac
done

if [ -z "$1" ]; then
    echo "No sysroot specified."
    exit 1
else
    SYSROOT="$1"
fi

if [ -e $TMPDIR ]; then
    rm -rf $TMPDIR
fi

mkdir -p $TMPDIR


pushd $SYSROOT &> /dev/null

    mkisofs -R -l -o $TMPDIR/initrd.img -find .         \
        ! -path "./boot/*"                              \
        ! -path "./boot"                                \
        ! -path "./usr/lib/modules/*"                   \
        ! -path "./usr/lib/modules"                     \
    &> /dev/null

popd &> /dev/null

exit 0