#!/bin/bash
#
# Usage: gen-exports SYSROOT TARGET
#

while [ -n "$1" ]; do
    case $1 in
        -h|--help)
            echo "Usage: $0 <SYSROOT> <TARGET>"
            exit 0
            ;;
        -*)
            echo "Unknown option: $1"
            exit 1
            ;;
        *)
            break
            ;;
    esac
done

if [ -z $1 ] || [ -z $2 ]; then
    echo "Usage: $0 <SYSROOT> <TARGET>"
    exit 1
fi

for i in $(find $1/usr/lib/modules -type f -name *.ko); do
    d="$d $($2-aplus-nm -uP $i)"
done

echo $d | awk -v RS="[ \n]+" '!n[$0]++' | sed "s/U//g" | sed '/^$/d' | sort