/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <fcntl.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/memory.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/vfs.h>



/***
 * Name:        newfstat
 * Description:
 * URL:         http://man7.org/linux/man-pages/man2/newfstat.2.html
 *
 * Input Parameters:
 *  0: 0x05
 *  1: unsigned int fd
 *  2: struct stat  * statbuf
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(
    5, newfstat, long sys_newfstat(unsigned int fd, struct stat* statbuf) {
        if (unlikely(fd >= CONFIG_OPEN_MAX))
            return -EBADF;

        if (unlikely(!statbuf))
            return -EINVAL;

        if (unlikely(!uio_check(statbuf, R_OK | W_OK)))
            return -EFAULT;



        int e = 0;
        struct stat __statbuf = {0};

        shared_ptr_access(current_task->fd, fds, {
            if (unlikely(!fds->descriptors[fd].ref))
                return -EBADF;

            scoped_lock(&fds->descriptors[fd].ref->lock) {
                e = vfs_getattr(fds->descriptors[fd].ref->inode, &__statbuf);
            }
        });


        if (e < 0)
            return -errno;

        uio_memcpy_s2u(statbuf, &__statbuf, sizeof(struct stat));

        return 0;
    });
