/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <fcntl.h>
#include <poll.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/memory.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/vfs.h>

#if defined(CONFIG_HAVE_NETWORK)
    #include <aplus/network.h>
#endif



/***
 * Name:        poll
 * Description: wait for some event on a file descriptor
 * URL:         http://man7.org/linux/man-pages/man2/poll.2.html
 *
 * Input Parameters:
 *  0: 0x07
 *  1: struct pollfd  * ufds
 *  2: unsigned int nfds
 *  3: int timeout
 *
 * Auto-generated by scripts/gen-syscalls.js
 */


SYSCALL(
    7, poll, long sys_poll(struct pollfd* ufds, unsigned int nfds, int timeout) {
        if (unlikely(nfds > current_task->rlimits[RLIMIT_NOFILE].rlim_cur))
            return -EINVAL;

        if (unlikely(nfds && !ufds))
            return -EINVAL;

        if (unlikely(nfds && !uio_check(ufds, R_OK | W_OK)))
            return -EFAULT;

        //? uio_check() validates one address, not a range, so every entry has
        //? to be checked as it is reached.


        //? Readiness is asked for, never remembered. Every attempt -- including
        //? each restart after a sleep -- rescans from scratch, so a descriptor
        //? that became ready while nobody was looking is still reported.

        size_t ready = 0;

        for (size_t i = 0; i < nfds; i++) {

            struct pollfd pfd;

            if (unlikely(!uio_check(&ufds[i], R_OK | W_OK)))
                return -EFAULT;

            uio_memcpy_u2s(&pfd, &ufds[i], sizeof(struct pollfd));

            //? POSIX: revents is output only, so whatever the caller left in it
            //? is discarded rather than merged into the answer.
            pfd.revents = 0;

            //? A negative fd is how callers park a slot they are not interested
            //? in for now; it is skipped, not an error.
            if (pfd.fd < 0) {

                uio_memcpy_s2u(&ufds[i], &pfd, sizeof(struct pollfd));
                continue;
            }


#if defined(CONFIG_HAVE_NETWORK)

            if (NETWORK_IS_SOCKFD(pfd.fd)) {

                struct pollfd sfd = {.fd = NETWORK_SOCKFD(pfd.fd), .events = pfd.events, .revents = 0};

                if (lwip_poll_from_syscall(&sfd, 1, NULL, false) < 0)
                    return -errno;

                pfd.revents = sfd.revents & (pfd.events | POLLHUP | POLLERR | POLLNVAL);

            } else

#endif

            {

                if (pfd.fd >= CONFIG_OPEN_MAX) {

                    pfd.revents = POLLNVAL;

                } else {

                    shared_ptr_access(current_task->fd, fds, {
                        if (fds->descriptors[pfd.fd].ref == NULL || fds->descriptors[pfd.fd].ref->inode == NULL) {

                            pfd.revents = POLLNVAL;

                        } else {

                            pfd.revents = vfs_poll(fds->descriptors[pfd.fd].ref->inode, pfd.events);
                        }
                    });
                }
            }


            if (pfd.revents)
                ready++;

            uio_memcpy_s2u(&ufds[i], &pfd, sizeof(struct pollfd));
        }


        if (ready > 0)
            return current_task->syscall.deadline_valid = false, (long)ready;

        //? A zero timeout is a readiness probe, not a wait.
        if (timeout == 0)
            return current_task->syscall.deadline_valid = false, 0;


        struct timespec tm  = {0, 0};
        struct timespec* to = NULL;

        if (timeout > 0) {

            //? The deadline is stamped once and reused by every restart; each
            //? attempt sleeps only for what is left of it. Recomputing the full
            //? timeout here is what used to keep poll() from ever timing out.
            if (!current_task->syscall.deadline_valid) {

                uint64_t now = arch_timer_generic_getns() + ((uint64_t)timeout * 1000000ULL);

                current_task->syscall.deadline.tv_sec  = (time_t)(now / 1000000000ULL);
                current_task->syscall.deadline.tv_nsec = (long)(now % 1000000000ULL);
                current_task->syscall.deadline_valid   = true;
            }


            uint64_t deadline = ((uint64_t)current_task->syscall.deadline.tv_sec * 1000000000ULL) + (uint64_t)current_task->syscall.deadline.tv_nsec;
            uint64_t now      = arch_timer_generic_getns();

            if (now >= deadline)
                return current_task->syscall.deadline_valid = false, 0;


            tm.tv_sec  = (time_t)((deadline - now) / 1000000000ULL);
            tm.tv_nsec = (long)((deadline - now) % 1000000000ULL);

            to = &tm;
        }


        //? futex_wait() registers rather than blocks, so every descriptor is
        //? armed first and the task suspends once: it wakes on whichever of
        //? them moves first.

        size_t armed = 0;

        for (size_t i = 0; i < nfds; i++) {

            struct pollfd pfd;

            if (unlikely(!uio_check(&ufds[i], R_OK | W_OK)))
                return -EFAULT;

            uio_memcpy_u2s(&pfd, &ufds[i], sizeof(struct pollfd));

            if (pfd.fd < 0)
                continue;


#if defined(CONFIG_HAVE_NETWORK)

            if (NETWORK_IS_SOCKFD(pfd.fd)) {

                struct pollfd sfd = {.fd = NETWORK_SOCKFD(pfd.fd), .events = pfd.events, .revents = 0};

                if (lwip_poll_from_syscall(&sfd, 1, to, true) < 0)
                    return -errno;

                armed++;
                continue;
            }

#endif

            //? Re-validate: this is a fresh read of user memory and a sibling
            //? thread may have changed the fd since the scan above.
            if (pfd.fd >= CONFIG_OPEN_MAX)
                continue;

            shared_ptr_access(current_task->fd, fds, {
                if (fds->descriptors[pfd.fd].ref != NULL && fds->descriptors[pfd.fd].ref->inode != NULL) {

                    shared_ptr_nullable_access(fds->descriptors[pfd.fd].ref->inode->ev, ev, {
                        futex_wait(current_task, &ev->futex, ev->futex, to);
                        armed++;
                    });
                }
            });
        }


        //? Nothing to watch -- poll(NULL, 0, ms) is a plain sleep. Park on a
        //? word nobody ever touches so that only the deadline can wake it.
        if (armed == 0 && to != NULL)
            futex_wait(current_task, &current_task->syscall.deadline_futex, current_task->syscall.deadline_futex, to);


#if DEBUG_LEVEL_TRACE
        kprintf("poll: task %d waiting for %d events\n", current_task->tid, nfds);
#endif

        thread_suspend(current_task);
        thread_restart_sched(current_task);
        thread_restart_syscall(current_task);

        return -EINTR;
    });
