/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aplus.
 * 
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdint.h>
#include <fcntl.h>
#include <time.h>
#include <poll.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <aplus/memory.h>
#include <aplus/vfs.h>
#include <aplus/smp.h>
#include <aplus/errno.h>
#include <aplus/hal.h>




/***
 * Name:        poll
 * Description: wait for some event on a file descriptor
 * URL:         http://man7.org/linux/man-pages/man2/poll.2.html
 *
 * Input Parameters:
 *  0: 0x07
 *  1: struct pollfd __user * ufds
 *  2: unsigned int nfds
 *  3: int timeout
 *
 * Auto-generated by extra/utils/gen-syscalls.js
 */


SYSCALL(7, poll,
long sys_poll (struct pollfd __user * ufds, unsigned int nfds, int timeout) {

    DEBUG_ASSERT(current_task);
    DEBUG_ASSERT(current_task->fd);


    if(unlikely(!ufds))
        return -EINVAL;
    
    if(unlikely(!uio_check(ufds, R_OK | W_OK)))
        return -EFAULT;

    if(unlikely(nfds == 0))
        return -EINVAL;

    if(unlikely(nfds > current_task->rlimits[RLIMIT_NOFILE].rlim_cur))
        return -EINVAL;



    size_t e = 0;
    
    for(size_t i = 0; i < nfds; i++) {

        if(unlikely(!uio_check(&ufds[i], R_OK | W_OK)))
            return -EFAULT;


        struct pollfd* pfd = (struct pollfd*) uio_get_ptr(&ufds[i]);

        if(pfd->fd < 0 || pfd->fd >= CONFIG_OPEN_MAX)
            return -EBADF;

        if(current_task->fd->descriptors[pfd->fd].ref == NULL)
            return -EBADF;


        if(current_task->fd->descriptors[pfd->fd].ref->ev.revents & pfd->events) {

            pfd->revents = current_task->fd->descriptors[pfd->fd].ref->ev.revents & pfd->events;

            current_task->fd->descriptors[pfd->fd].ref->ev.revents &= ~pfd->events;
            current_task->fd->descriptors[pfd->fd].ref->ev.events  &= ~pfd->events;

            e++;

        }

    }


    if(e == 0) {

        struct timespec tm;

        if(timeout > 0) {
            tm.tv_sec  = (timeout / 1000);
            tm.tv_nsec = (timeout % 1000) * 1000000;
        }


        for(size_t i = 0; i < nfds; i++) {

            struct pollfd* pfd = (struct pollfd*) uio_get_ptr(&ufds[i]);

            current_task->fd->descriptors[pfd->fd].ref->ev.revents &= ~pfd->events;
            current_task->fd->descriptors[pfd->fd].ref->ev.events  |=  pfd->events;
            current_task->fd->descriptors[pfd->fd].ref->ev.futex    = 0;

            futex_wait(current_task, &current_task->fd->descriptors[pfd->fd].ref->ev.futex, 0, timeout > 0 ? &tm : NULL);

        }


#if defined(DEBUG) && DEBUG_LEVEL >= 4
        kprintf("poll: task %d waiting for %d events\n", current_task->tid, nfds);
#endif

        thread_suspend(current_task);
        thread_postpone_resched(current_task);
        thread_postpone_syscall(current_task);

        return -EINTR;

    } 

    return e;

});

