/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <fcntl.h>
#include <stdint.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <unistd.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/memory.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/vfs.h>



/***
 * Name:        mmap
 * Description: map or unmap files or devices into memory
 * URL:         http://man7.org/linux/man-pages/man2/mmap.2.html
 *
 * Input Parameters:
 *  0: 0x09
 *  1: undefined
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(
    9, mmap, long sys_mmap(unsigned long addr, unsigned long len, int prot, int flags, int fd, long offset) {
        DEBUG_ASSERT(current_task);
        DEBUG_ASSERT(current_task->address_space);
        DEBUG_ASSERT(current_task->address_space->mmap.heap_start);
        DEBUG_ASSERT(current_task->address_space->mmap.heap_end);


        /* These used to be PANIC_ASSERT, which is compiled in unconditionally: any program
           calling mmap() with MAP_SHARED or MAP_FIXED brought the whole kernel down. */
        if (unlikely((flags & MAP_TYPE) == MAP_SHARED || (flags & MAP_TYPE) == MAP_SHARED_VALIDATE))
            return -ENOTSUP;

        if (unlikely(flags & (MAP_FIXED | MAP_FIXED_NOREPLACE)))
            return -ENOTSUP;

        if (unlikely(flags & MAP_GROWSDOWN))
            return -ENOTSUP;


        // Silenty ignored
        DEBUG_ASSERT(!(flags & MAP_SYNC));
        DEBUG_ASSERT(!(flags & MAP_NORESERVE));
        DEBUG_ASSERT(!(flags & MAP_32BIT));
        DEBUG_ASSERT(!(flags & MAP_NONBLOCK));


        if (unlikely(flags == 0))
            return -EINVAL;

        if (unlikely(len == 0))
            return -EINVAL;


        if (unlikely(!(flags & MAP_PRIVATE) && !(flags & MAP_SHARED) && !(flags & MAP_SHARED_VALIDATE)))
            return -EINVAL;


        uintptr_t pagesize = arch_vmm_getpagesize();
        uintptr_t start    = 0UL;



        if (!(flags & MAP_ANONYMOUS)) {

            if (unlikely(fd >= CONFIG_OPEN_MAX))
                return -EBADF;

            shared_ptr_access(current_task->fd, fds, {
                if (unlikely(!fds->descriptors[fd].ref))
                    return -EBADF;
            });

            /* A file mapping is only honoured when the contents can be read in up front.
               ARCH_VMM_MAP_TYPE_MMAP exists but the fault handler does not implement it yet,
               so a lazy file mapping would quietly hand back zeroed anonymous memory instead
               of the file. Refusing is the lesser evil. */
            if (unlikely(!(flags & (MAP_POPULATE | MAP_LOCKED))))
                return -ENOTSUP;
        }



        int arch_flags = 0;


        if (prot != PROT_NONE)
            arch_flags |= ARCH_VMM_MAP_USER;

        // if(!(prot & PROT_READ))
        //     arch_flags |= ARCH_VMM_MAP_USER;

        if (!(prot & PROT_EXEC))
            arch_flags |= ARCH_VMM_MAP_NOEXEC;

        if ((prot & PROT_WRITE))
            arch_flags |= ARCH_VMM_MAP_RDWR;


#if defined(CONFIG_DEMAND_PAGING)
        if (!(flags & MAP_POPULATE) && !(flags & MAP_LOCKED))
            arch_flags |= ARCH_VMM_MAP_DEMAND;
#endif


        if (flags & MAP_HUGETLB) {

            arch_flags |= ARCH_VMM_MAP_HUGETLB;


            switch ((flags & MAP_HUGE_MASK)) {

                case MAP_HUGE_2MB:
                    arch_flags |= ARCH_VMM_MAP_HUGE_2MB;
                    pagesize = arch_vmm_gethugepagesize(ARCH_VMM_MAP_HUGE_2MB);
                    break;
                case MAP_HUGE_1GB:
                    arch_flags |= ARCH_VMM_MAP_HUGE_1GB;
                    /* Was asking for the 2MiB size here, so a 1GiB mapping was aligned and
                       rounded as if it were 2MiB. */
                    pagesize = arch_vmm_gethugepagesize(ARCH_VMM_MAP_HUGE_1GB);
                    break;

                default:
                    return -EINVAL;
            }
        }


        if (unlikely(addr & (pagesize - 1)))
            return -EINVAL;

        if (unlikely(offset & (pagesize - 1)))
            return -EINVAL;


        if (unlikely(len & (pagesize - 1))) {

            if (unlikely(len + pagesize < len))
                return -ENOMEM;

            len = (len & ~(pagesize - 1)) + pagesize;
        }


        int i;

        spinlock_lock(&current_task->address_space->lock);

        {
            /* Align the cursor first, then carve the region out of it. The bookkeeping used to
               be filled in from the *unaligned* cursor before it advanced, so every recorded
               mapping described the region below the one actually returned. */
            uintptr_t cursor = current_task->address_space->mmap.heap_end;

            if (cursor & (pagesize - 1))
                cursor = (cursor & ~(pagesize - 1)) + pagesize;


            /* Keep the cursor inside the window it was seeded from. It only ever grows --
               munmap does not rewind it -- so without this it eventually walks out of the
               mmap area and into whatever lies above. */
            if (unlikely(cursor + len < cursor || cursor + len > current_task->address_space->mmap.heap_limit)) {

                spinlock_unlock(&current_task->address_space->lock);
                return -ENOMEM;
            }


            for (i = 0; i < CONFIG_MMAP_MAX; i++) {

                if (current_task->address_space->mmap.mappings[i].start != 0UL)
                    continue;


                current_task->address_space->mmap.mappings[i].start  = cursor;
                current_task->address_space->mmap.mappings[i].end    = cursor + len;
                current_task->address_space->mmap.mappings[i].fd     = (flags & MAP_ANONYMOUS) ? (uintptr_t)-1 : (uintptr_t)fd;
                current_task->address_space->mmap.mappings[i].offset = offset;

                start = cursor;

                current_task->address_space->mmap.heap_end = cursor + len;

                break;
            }
        }

        spinlock_unlock(&current_task->address_space->lock);


        if (i == CONFIG_MMAP_MAX)
            return -ENOMEM;



        uintptr_t ret = arch_vmm_map(current_task->address_space, start, -1, len, arch_flags);

        if (unlikely(ret == ARCH_VMM_MAP_FAILED)) {

            /* Hand the slot back. The cursor itself is left where it is: another thread may
               already have carved a region above it. */
            scoped_lock(&current_task->address_space->lock) {
                memset(&current_task->address_space->mmap.mappings[i], 0, sizeof(mmap_mapping_t));
            }

            return -ENOMEM;
        }


        if (!(flags & MAP_ANONYMOUS)) {

            /* Anonymous pages already come back zeroed from arch_vmm_map(). */
            uio_lock(start, len);

            long e = sys_read(fd, (void*)start, len);

            uio_unlock(start, len);

            if (unlikely(e < 0)) {

                arch_vmm_unmap(current_task->address_space, start, len);

                scoped_lock(&current_task->address_space->lock) {
                    memset(&current_task->address_space->mmap.mappings[i], 0, sizeof(mmap_mapping_t));
                }

                return e;
            }
        }


        return ret;
    });
