/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <fcntl.h>
#include <stdint.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <unistd.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/memory.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/vfs.h>



/***
 * Name:        munmap
 * Description: map or unmap files or devices into memory
 * URL:         http://man7.org/linux/man-pages/man2/munmap.2.html
 *
 * Input Parameters:
 *  0: 0x0b
 *  1: unsigned long addr
 *  2: size_t len
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(
    11, munmap, long sys_munmap(unsigned long addr, size_t len) {
        DEBUG_ASSERT(current_task);
        DEBUG_ASSERT(current_task->address_space);


        const uintptr_t pagesize = arch_vmm_getpagesize();

        if (unlikely(len == 0))
            return -EINVAL;

        if (unlikely(addr & (pagesize - 1)))
            return -EINVAL;


        if (unlikely(len & (pagesize - 1))) {

            if (unlikely(len + pagesize < len))
                return -EINVAL;

            len = (len & ~(pagesize - 1)) + pagesize;
        }


        const uintptr_t start = addr;
        const uintptr_t end   = addr + len;

        if (unlikely(end < start))
            return -EINVAL;


        /* Only the mmap window. The program image and its heap belong to brk(2). */
        if (unlikely(start < current_task->address_space->mmap.heap_start || end > current_task->address_space->mmap.heap_end))
            return -EINVAL;


        scoped_lock(&current_task->address_space->lock) {

            mmap_mapping_t* m = current_task->address_space->mmap.mappings;

            for (int i = 0; i < CONFIG_MMAP_MAX; i++) {

                if (m[i].start == 0UL)
                    continue;

                /* Disjoint? */
                if (m[i].end <= start || m[i].start >= end)
                    continue;


                const uintptr_t lo = m[i].start > start ? m[i].start : start;
                const uintptr_t hi = m[i].end < end ? m[i].end : end;

                arch_vmm_unmap(current_task->address_space, lo, hi - lo);


                if (m[i].start >= start && m[i].end <= end) {

                    /* Wholly covered. */
                    memset(&m[i], 0, sizeof(mmap_mapping_t));

                } else if (m[i].start < start && m[i].end > end) {

                    /* Punched in the middle: the tail needs a slot of its own. */
                    int j;

                    for (j = 0; j < CONFIG_MMAP_MAX; j++) {

                        if (m[j].start == 0UL)
                            break;
                    }

                    if (unlikely(j == CONFIG_MMAP_MAX)) {

                        /* Nowhere to record the tail. The pages are already gone, so report
                           the bookkeeping failure rather than silently forgetting the region. */
                        m[i].end = start;
                        return -ENOMEM;
                    }

                    m[j].start  = end;
                    m[j].end    = m[i].end;
                    m[j].fd     = m[i].fd;
                    m[j].offset = m[i].offset + (end - m[i].start);

                    m[i].end = start;

                } else if (m[i].start < start) {

                    m[i].end = start;

                } else {

                    m[i].offset += end - m[i].start;
                    m[i].start = end;
                }
            }


            /* Reclaim the cursor if the top of the window is now free, so that a
               map/unmap loop does not march it out of the window. */
            uintptr_t top = current_task->address_space->mmap.heap_start;

            for (int i = 0; i < CONFIG_MMAP_MAX; i++) {

                if (m[i].start == 0UL)
                    continue;

                if (m[i].end > top)
                    top = m[i].end;
            }

            if (top < current_task->address_space->mmap.heap_end)
                current_task->address_space->mmap.heap_end = top;
        }


        return 0;
    });
