/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <fcntl.h>
#include <stdint.h>
#include <sys/types.h>
#include <unistd.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/memory.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/vfs.h>



/***
 * Name:        brk
 * Description: change data segment size
 * URL:         http://man7.org/linux/man-pages/man2/brk.2.html
 *
 * Input Parameters:
 *  0: 0x0c
 *  1: unsigned long new_brk
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(
    12, brk, long sys_brk(unsigned long new_brk) {
        DEBUG_ASSERT(current_task->address_space);

        vmm_address_space_t* space = current_task->address_space;

        DEBUG_ASSERT(space->brk.start);
        DEBUG_ASSERT(space->brk.end);


        scoped_lock(&space->lock) {

            if (new_brk == 0)
                return space->brk.end;

            if (new_brk < space->brk.start)
                return space->brk.end;



#if DEBUG_LEVEL_TRACE
            // kprintf("sys_brk: pid(%d) brk(0x%lX) new(0x%lX)\n", current_task->tid, space->brk.end, new_brk);
#endif

            // TODO: Use less memory

            if (new_brk & (arch_vmm_getpagesize() - 1)) {

                if (unlikely(new_brk + arch_vmm_getpagesize() < new_brk))
                    return space->brk.end;

                new_brk = (new_brk & ~(arch_vmm_getpagesize() - 1)) + arch_vmm_getpagesize();
            }


            if (unlikely(new_brk > space->mmap.heap_start))
                return space->brk.end;


            if (new_brk > space->brk.end) {

                uintptr_t e = arch_vmm_map(space, space->brk.end, -1, new_brk - space->brk.end,
                                 ARCH_VMM_MAP_RDWR        |
                                 ARCH_VMM_MAP_USER        |
                                 ARCH_VMM_MAP_NOEXEC      |
#if defined(CONFIG_DEMAND_PAGING) && 0 // TODO: Fix demand paging on brk
                                 ARCH_VMM_MAP_DEMAND      |
#endif
                                 ARCH_VMM_MAP_TYPE_PAGE );

                if (unlikely(e == ARCH_VMM_MAP_FAILED))
                    return space->brk.end;

            } else if (new_brk < space->brk.end) {

                arch_vmm_unmap(space, new_brk, space->brk.end - new_brk);
            }


            space->brk.end = new_brk;
        }

        return new_brk;
    });
