/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aPlus.
 * 
 * aPlus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aPlus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aPlus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <aplus/memory.h>
#include <aplus/vfs.h>
#include <aplus/smp.h>
#include <aplus/errno.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>

#include <aplus/hal.h>




/***
 * Name:        rt_sigprocmask
 * Description: examine and change blocked signals
 * URL:         http://man7.org/linux/man-pages/man2/rt_sigprocmask.2.html
 *
 * Input Parameters:
 *  0: 0x0e
 *  1: int how
 *  2: sigset_t __user * set
 *  3: sigset_t __user * oset
 *  4: size_t sigsetsize
 *
 * Auto-generated by extra/utils/gen-syscalls.js
 */

SYSCALL(14, rt_sigprocmask,
long sys_rt_sigprocmask (int how, sigset_t __user * set, sigset_t __user * oset, size_t sigsetsize) {

    if(unlikely(set && !uio_check(set, R_OK)))
        return -EFAULT;

    if(unlikely(oset && !uio_check(oset, R_OK | W_OK)))
        return -EFAULT;



    DEBUG_ASSERT(current_task);
    DEBUG_ASSERT(current_task->sighand);
    

    if(oset)
        memcpy(oset, &current_task->sighand->sigmask, sigsetsize);


    if(set) {

        int i;
     
        switch(how) {

            case SIG_BLOCK:
                
                for(i = 0; i < sigsetsize; i += sizeof(unsigned long))
                    current_task->sighand->sigmask.__bits[i] |= set->__bits[i];

                break;

            case SIG_UNBLOCK:

                for(i = 0; i < sigsetsize; i += sizeof(unsigned long))
                    current_task->sighand->sigmask.__bits[i] &= ~set->__bits[i];

                break;

            case SIG_SETMASK:
                
                for(i = 0; i < sigsetsize; i += sizeof(unsigned long))
                    current_task->sighand->sigmask.__bits[i] = set->__bits[i];

                break;

            default:
                return -EINVAL;

        }

    }




    size_t i;
    for(i = current_task->sigpending.size; i > 0; i--) {

        siginfo_t* info;
        if((info = queue_pop(&current_task->sigpending))) {

            if(unlikely(current_task->sighand->sigmask.__bits[info->si_signo / (sizeof(long) << 3)] & (1 << (info->si_signo % (sizeof(long) << 3)))))
                queue_enqueue(&current_task->sigpending, info, 0);
            else
                queue_enqueue(&current_task->sigqueue, info, 0);

        }

    }


    return 0;

});
