/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/memory.h>
#include <aplus/poll.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/vfs.h>
#include <fcntl.h>
#include <limits.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/uio.h>
#include <unistd.h>

#include <aplus/hal.h>
#include <aplus/network.h>


/***
 * Name:        writev
 * Description: read or write
       data into multiple buffers
 * URL:         http://man7.org/linux/man-pages/man2/writev.2.html
 *
 * Input Parameters:
 *  0: 0x14
 *  1: unsigned long fd
 *  2: const struct iovec  * vec
 *  3: unsigned long vlen
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(
    20, writev, long sys_writev(unsigned long fd, const struct iovec* vec, unsigned long vlen) {
        if (unlikely(!vec))
            return -EINVAL;

        if (unlikely(!uio_check(vec, R_OK)))
            return -EFAULT;

        if (unlikely(vlen > INT_MAX))
            return -EINVAL;

        if (unlikely(vlen == 0))
            return 0;


        int flags         = 0;
        struct file* file = fd_get((unsigned int)fd, &flags);

        if (unlikely(!file))
            return -EBADF;

        if (unlikely(!((flags & O_WRONLY) || (flags & O_RDWR)))) {
            fd_put(file);
            return -EPERM;
        }


        volatile uint32_t* word = poll_event_word(file->inode);
        uint32_t seq            = word ? *word : 0;

        bool whole   = socket_from_inode(file->inode) >= 0;
        bool stopped = false;

        size_t done = current_task->syscall.progress;
        size_t skip = done;
        ssize_t e   = 0;

        for (unsigned long i = 0; i < vlen; i++) {

            struct iovec iovec;
            uio_memcpy_u2s(&iovec, &vec[i], sizeof(struct iovec));


            if (unlikely(!iovec.iov_base))
                continue;

            if (unlikely(!iovec.iov_len))
                continue;

            if (skip >= iovec.iov_len) {
                skip -= iovec.iov_len;
                continue;
            }

            if (unlikely(!uio_check(iovec.iov_base, R_OK))) {
                e      = -EFAULT;
                stopped = true;
                break;
            }


            const uint8_t* base = (const uint8_t*)iovec.iov_base + skip;
            size_t len          = iovec.iov_len - skip;

            skip = 0;


            uio_lock(base, len);

            e = fd_write(file, base, len);

            uio_unlock(base, len);


            if (e > 0) {
                done += (size_t)e;
                current_task->iostat.write_bytes += (uint64_t)e;
            }

            if (e <= 0 || (size_t)e < len) {
                stopped = true;
                break;
            }
        }


        current_task->iostat.syscw += 1;

        if (stopped && !(flags & O_NONBLOCK) && ((e == -EAGAIN && (done == 0 || whole)) || (e > 0 && whole))) {

            current_task->syscall.progress = done;

            e = poll_wait_event(word, seq, socket_timeout(file->inode, true));

            if (e == -EAGAIN && done)
                e = (ssize_t)done;

        } else if (done || !stopped) {

            e = (ssize_t)done;
        }

        fd_put(file);

        return e;
    });
