/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aplus.
 * 
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <aplus/smp.h>
#include <aplus/errno.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>


/***
 * Name:        select
 * Description: synchronous I/O
       multiplexing
 * URL:         http://man7.org/linux/man-pages/man2/select.2.html
 *
 * Input Parameters:
 *  0: 0x17
 *  1: int n
 *  2: fd_set __user * inp
 *  3: fd_set __user * outp
 *  4: fd_set __user * exp
 *  5: struct timeval __user * tvp
 *
 * Auto-generated by extra/utils/gen-syscalls.js
 */

SYSCALL(23, select,
long sys_select (int n, fd_set __user * inp, fd_set __user * outp, fd_set __user * exp, struct timeval __user * tvp) {
    return -ENOSYS;
});
