/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/unix.h>
#include <aplus/task.h>
#include <fcntl.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include <aplus/network.h>



/***
 * Name:        connect
 * Description: initiate a connection on a socket
 * URL:         http://man7.org/linux/man-pages/man2/connect.2.html
 *
 * Input Parameters:
 *  0: 0x2a
 *  1: int
 *  2: struct sockaddr  *
 *  3: int
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(
    42, connect, long sys_connect(int fd, struct sockaddr* sockaddr, socklen_t socklen) {

        struct unix_sock* us;

        if ((us = unix_sock_from_fd(fd)) != NULL) {

            long e = unix_connect(us, sockaddr, socklen);

            unix_sock_put(us);

            return e;
        }


        if (unlikely(socklen == 0 || socklen > SOCKADDR_MAX))
            return -EINVAL;

        if (unlikely(!sockaddr))
            return -EINVAL;

        if (unlikely(!uio_check(sockaddr, R_OK)))
            return -EFAULT;


        int flags         = 0;
        struct file* file = fd_get((unsigned int)fd, &flags);

        if (unlikely(!file))
            return -EBADF;


        uint64_t addr[SOCKADDR_MAX / sizeof(uint64_t)];
        uio_memcpy_u2s(addr, sockaddr, socklen);

        long e = socket_connect(file->inode, (struct sockaddr*)addr, socklen, !!(flags & O_NONBLOCK));

        fd_put(file);

        return e;
    });
