/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/unix.h>
#include <aplus/task.h>
#include <fcntl.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include <aplus/network.h>


/***
 * Name:        listen
 * Description: listen for connections on a socket
 * URL:         http://man7.org/linux/man-pages/man2/listen.2.html
 *
 * Input Parameters:
 *  0: 0x32
 *  1: int
 *  2: int
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(
    50, listen, long sys_listen(int fd, int backlog) {

        struct unix_sock* us;

        if ((us = unix_sock_from_fd(fd)) != NULL)
            return unix_listen(us, backlog);


        int socket = socket_from_fd(fd);

        if (unlikely(socket < 0))
            return -ENOTSOCK;


        ssize_t e;

        if ((e = lwip_listen(socket, backlog)) < 0)
            return -errno;

        return e;
    });
