/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/unix.h>
#include <aplus/task.h>
#include <fcntl.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#if defined(CONFIG_HAVE_NETWORK)
    #include <aplus/network.h>
#endif


/***
 * Name:        getpeername
 * Description: get name of connected peer socket
 * URL:         http://man7.org/linux/man-pages/man2/getpeername.2.html
 *
 * Input Parameters:
 *  0: 0x34
 *  1: int
 *  2: struct sockaddr  *
 *  3: int  *
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(
    52, getpeername, long sys_getpeername(int fd, struct sockaddr* sockaddr, int* socklen) {

        struct unix_sock* us;

        if ((us = unix_sock_from_fd(fd)) != NULL)
            return unix_getpeername(us, sockaddr, (uint32_t*)socklen);


#if defined(CONFIG_HAVE_NETWORK)
        int socket = socket_from_fd(fd);

        if (unlikely(socket < 0))
            return -ENOTSOCK;

        if (unlikely(!sockaddr || !socklen))
            return -EINVAL;

        if (unlikely(!uio_check(socklen, R_OK | W_OK)))
            return -EFAULT;

        socklen_t __socklen = (socklen_t)uio_r32((uint32_t*)socklen);

        if (unlikely(!uio_check(sockaddr, R_OK | W_OK)))
            return -EFAULT;


        char __sockaddr[__socklen];
        uio_memcpy_u2s(__sockaddr, sockaddr, __socklen);

        ssize_t e;

        if ((e = lwip_getpeername(socket, (struct sockaddr*)__sockaddr, &__socklen)) < 0)
            return -errno;

        uio_w32((uint32_t*)socklen, __socklen);
        uio_memcpy_s2u(sockaddr, __sockaddr, __socklen);

        return e;

#else
    return -ENOSYS;
#endif
    });
