/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <fcntl.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/task.h>



/***
 * Name:        exit
 * Description: terminate the calling process
 * URL:         http://man7.org/linux/man-pages/man2/exit.2.html
 *
 * Input Parameters:
 *  0: 0x3c
 *  1: int error_code
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

/* The exit status is worked out first and published last. A ZOMBIE is reapable the instant
   another CPU sees it -- sched_dequeue() frees the task_t and the kernel stack this call is
   running on -- so setting the status before the teardown below hands a parent on another
   CPU the memory this code is still using. Waiters are woken after the status for the same
   reason: a parent released here finds a status that is already final. */

SYSCALL(
    60, exit, long sys_exit(int status) {
        PANIC_ASSERT(current_task->tid != 1);


        if (status & (1U << 31))
            current_task->exit.value = status & 0x7FFF;
        else
            current_task->exit.value = (status & 0377) << 8;


#if DEBUG_LEVEL_TRACE
        kprintf("exit: task %d (%s) %s with %X\n", current_task->tid, current_task->argv[0], WIFSTOPPED(current_task->exit.value) ? "stopped" : "exited", current_task->exit.value & 0xFFFF);
#endif


        const long exit_status = (WIFSTOPPED(current_task->exit.value)) ? TASK_STATUS_STOP : TASK_STATUS_ZOMBIE;


        // TODO: implements signal
        // if(current_task->parent) {
        //     siginfo_t si;
        //     si.si_code = SI_KERNEL;
        //     si.si_pid = current_task->pid;
        //     si.si_uid = current_task->uid;
        //     si.si_value.sival_int = current_task->exit.value;

        //     sched_sigqueueinfo(current_task->parent, SIGCHLD, &si);
        // }



        if (exit_status != TASK_STATUS_STOP) {

            shared_ptr_free_with_dtor(current_task->fd, fds, {
                for (size_t i = 0; i < CONFIG_OPEN_MAX; i++) {

                    if (!fds->descriptors[i].ref)
                        continue;

                    fd_remove(fds->descriptors[i].ref, true);

                    fds->descriptors[i].ref   = NULL;
                    fds->descriptors[i].flags = 0;
                }
            });


            shared_ptr_free(current_task->fs);
            shared_ptr_free(current_task->sighand);

            arch_vmm_free_address_space(current_task->address_space);

            /* A task stays on the run queue as a ZOMBIE until someone reaps it, so everything
               freed just above outlives its own pointers -- and a reader walking the queue
               (ps, via /proc) finds them still set and follows them into freed memory.
               shared_ptr_free() does not clear the caller's variable, so clear them here and
               let shared_ptr_nullable_access() do the rest. */
            current_task->fd            = NULL;
            current_task->fs            = NULL;
            current_task->sighand       = NULL;
            current_task->address_space = NULL;

            //? Nothing left to borrow, so let a parent parked in vfork() go. A
            //? task that only stopped is skipped along with the teardown above:
            //? it can still be continued and is still holding the loan.
            do_vfork_release();
        }


        current_task->status = exit_status;

        list_each(current_task->wait_queue, q) {

            if (exit_status == TASK_STATUS_STOP && !(q->wait_options & WUNTRACED))
                continue;

#if DEBUG_LEVEL_TRACE
            kprintf("exit: waking up waiter task(%d) for task(%d)\n", q->tid, current_task->tid);
#endif
            thread_wake(q);
        }


        thread_restart_sched(current_task);
        return 0;
    });
