/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <fcntl.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>



/***
 * Name:        wait4
 * Description: wait for process to change state, BSD style
 * URL:         http://man7.org/linux/man-pages/man2/wait4.2.html
 *
 * Input Parameters:
 *  0: 0x3d
 *  1: pid_t pid
 *  2: int  * stat_addr
 *  3: int options
 *  4: struct rusage  * ru
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

struct rusage;

SYSCALL(
    61, wait4, long sys_wait4(pid_t pid, int* status, int options, struct rusage* rusage) {
        if (unlikely(status && !uio_check(status, R_OK | W_OK))) {
            return -EFAULT;
        }

        if (unlikely(rusage && !uio_check(rusage, R_OK | W_OK))) {
            return -EFAULT;
        }


        size_t count = 0;

        current_task->wait_options = options;
        current_task->wait_rusage  = !rusage ? NULL : (void*)uio_get_ptr(rusage);
        current_task->wait_status  = !status ? NULL : (void*)uio_get_ptr(status);


        /* The scan only decides; it never frees and never writes to user memory. Holding
         * cpu->sched_lock is what keeps every task on the queue alive while it is looked at
         * -- sched_dequeue() unlinks and destroys under that same lock -- and this walk used
         * to run with no lock at all, reaping a child on one CPU while another CPU was
         * walking the very queue it was being unlinked from. That is the crash: the CPU
         * mid-walk follows `next` into freed memory and `current_task` becomes rubbish.
         *
         * The reaping itself is deferred to after the lock: sched_dequeue() retakes the
         * queue lock for whichever CPU owns the task, and taking a second CPU's queue lock
         * while holding the first is how a lock-order cycle between two CPUs starts.
         */

        task_t* reap = NULL; //? A child to unlink and free once the queue lock is back down.
        pid_t reported = -1; //? The child to report, if the scan found one to report.

        int exit_value = 0;
        struct rusage exit_rusage;


        cpu_foreach_if(cpu, reported < 0) {

            scoped_lock(&cpu->sched_lock) {

                for (task_t* tmp = cpu->sched_queue; tmp; tmp = tmp->next) {

                    if (unlikely(tmp == current_task))
                        continue;

                    if (unlikely(tmp->parent != current_task))
                        continue;


#define continue_if(pid, cond) \
    if (pid) {                 \
        if (cond)              \
            continue;          \
    }


                    continue_if(pid < -1, tmp->pgrp != -pid);
                    continue_if(pid == 0, tmp->pgrp != current_task->pgrp);
                    continue_if(pid > 0, tmp->tid != pid);
                    continue_if(pid == -1, 0);

                    if (tmp->status == TASK_STATUS_STOP && !(options & WUNTRACED))
                        continue;



                    if (tmp->status == TASK_STATUS_STOP || tmp->status == TASK_STATUS_ZOMBIE) {

                        exit_value = tmp->exit.value;

                        memcpy(&exit_rusage, &tmp->rusage, sizeof(struct rusage));

                        reported = tmp->tid;

                        if (tmp->status == TASK_STATUS_ZOMBIE) {
                            reap = tmp;
                        }

                        break;


                    } else if (tmp->status == TASK_STATUS_DEAD) {

                        //? One per pass, since the reap happens after this walk has ended.
                        //? Any others are picked up by the next call, which is where they
                        //? would have been left anyway had this one found a child to report.
                        if (!reap) {
                            reap = tmp;
                        }

                    } else {

                        if (!(options & WNOHANG)) {
                            list_push(tmp->wait_queue, current_task);
                        }

                        count++;
                    }
                }
            }
        }


        if (reap) {
            sched_dequeue(reap);
        }

        if (reported >= 0) {

            //? Written now rather than during the walk: this is user memory, so storing to
            //? it can fault, and faulting is not something to do holding a run queue.
            if (current_task->wait_status)
                *current_task->wait_status = exit_value;

            if (current_task->wait_rusage)
                memcpy(current_task->wait_rusage, &exit_rusage, sizeof(struct rusage));

            return reported;
        }


        if (count == 0)
            return -ECHILD;

        if (options & WNOHANG)
            return 0;



#if DEBUG_LEVEL_TRACE
        kprintf("wait: task %d waiting for %ld tasks\n", current_task->tid, count);
#endif


        thread_suspend(current_task);
        thread_restart_sched(current_task);
        thread_restart_syscall(current_task);

        return -EINTR;
    });
