/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <fcntl.h>
#include <poll.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/memory.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/vfs.h>

#include <aplus/network.h>


/**
 * @brief The file status flags F_SETFL may change; the access mode and the creation flags stay as opened.
 */
#define FCNTL_SETFL_MASK (O_APPEND | O_ASYNC | O_DIRECT | O_NOATIME | O_NONBLOCK)


/***
 * Name:        fcntl
 * Description: manipulate file descriptor
 * URL:         http://man7.org/linux/man-pages/man2/fcntl.2.html
 *
 * Input Parameters:
 *  0: 0x48
 *  1: unsigned int fd
 *  2: unsigned int cmd
 *  3: unsigned long arg
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(
    72, fcntl, long sys_fcntl(unsigned int fd, unsigned int cmd, unsigned long arg) {

        {

            if (unlikely(fd >= CONFIG_OPEN_MAX))
                return -EBADF;


            shared_ptr_access(current_task->fd, fds, {
                if (unlikely(!fds->descriptors[fd].ref))
                    return -EBADF;
            });


            switch (cmd) {

                case F_DUPFD:
                case F_DUPFD_CLOEXEC:

                    if (unlikely(arg >= CONFIG_OPEN_MAX))
                        return -EINVAL;

                    return fd_dup(fd, (unsigned int)arg, cmd == F_DUPFD_CLOEXEC);

                case F_GETFD:

                    shared_ptr_access(current_task->fd, fds, { return fds->descriptors[fd].close_on_exec ? FD_CLOEXEC : 0; });

                case F_SETFD:

                    shared_ptr_access(current_task->fd, fds, { fds->descriptors[fd].close_on_exec = !!(arg & FD_CLOEXEC); });

                    return 0;

                case F_GETFL: {

                    int flags         = 0;
                    struct file* file = fd_get(fd, &flags);

                    if (unlikely(!file))
                        return -EBADF;

                    fd_put(file);

                    return flags;
                }

                case F_SETFL: {

                    struct file* file = fd_get(fd, NULL);

                    if (unlikely(!file))
                        return -EBADF;

                    fd_set_flags(file, FCNTL_SETFL_MASK, (int)arg);
                    fd_put(file);

                    return 0;
                }

                case F_SETPIPE_SZ:
                case F_GETPIPE_SZ:
                    /* TODO: Implements pipe size routines for fcntl */
                    return -ENOSYS;
            }


            return -EINVAL;
        }
    });
