/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aplus.
 * 
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <aplus/smp.h>
#include <aplus/errno.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>

extern long sys_dup(unsigned int);


/***
 * Name:        fcntl
 * Description: manipulate file descriptor
 * URL:         http://man7.org/linux/man-pages/man2/fcntl.2.html
 *
 * Input Parameters:
 *  0: 0x48
 *  1: unsigned int fd
 *  2: unsigned int cmd
 *  3: unsigned long arg
 *
 * Auto-generated by extra/utils/gen-syscalls.js
 */

SYSCALL(72, fcntl,
long sys_fcntl (unsigned int fd, unsigned int cmd, unsigned long arg) {
    
    if(unlikely(fd > CONFIG_OPEN_MAX))
        return -EBADF;

    if(unlikely(!current_task->fd->descriptors[fd].ref))
        return -EBADF;


    long e1, e2;

    switch(cmd) {

        case F_DUPFD:
            return sys_dup(fd);

        case F_DUPFD_CLOEXEC:

            if((e1 = sys_dup(fd) < 0))
                return e1;

            if((e2 = sys_fcntl(e1, F_SETFD, FD_CLOEXEC) < 0))
                return e2;

            return e1;

        case F_GETFD:
            return current_task->fd->descriptors[fd].close_on_exec;

        case F_SETFD:
            current_task->fd->descriptors[fd].close_on_exec = arg;
            return 0;

        case F_GETFL:
            return current_task->fd->descriptors[fd].flags;

        case F_SETFL:
            current_task->fd->descriptors[fd].flags = arg;
            return 0;

        case F_SETPIPE_SZ:
        case F_GETPIPE_SZ:
            /* TODO: Implements pipe size routines for fcntl */
            return -ENOSYS;

    }


    return -EINVAL;

});
