/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aplus.
 * 
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <aplus/smp.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <stdint.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>


#ifndef PATH_MAX
#define PATH_MAX 1024
#endif


static int __append(char* buf, size_t size, const char* name) {

    DEBUG_ASSERT(buf);
    DEBUG_ASSERT(name);
    DEBUG_ASSERT(strlen(name));

    if(strlen(buf) + strlen(name) + 1 > size)
        return -ERANGE;

    memmove(buf + strlen(name), buf, strlen(buf) + 1);
    memcpy(buf, name, strlen(name));

    return 0;

}


/***
 * Name:        getcwd
 * Description: get current working directory
 * URL:         http://man7.org/linux/man-pages/man2/getcwd.2.html
 *
 * Input Parameters:
 *  0: 0x4f
 *  1: char __user * buf
 *  2: unsigned long size
 *
 * Auto-generated by extra/utils/gen-syscalls.js
 */

SYSCALL(79, getcwd,
long sys_getcwd (char __user * ubuf, unsigned long size) {
    
    DEBUG_ASSERT(current_task);
    DEBUG_ASSERT(current_task->fs);
    DEBUG_ASSERT(current_task->fs->root);


    if(unlikely(!ubuf))
        return -EINVAL;

    if(unlikely(!size))
        return -EINVAL;

    if(unlikely(!uio_check(ubuf, R_OK | W_OK)))
        return -EFAULT;

    if(unlikely(size > PATH_MAX))
        size = PATH_MAX;


    struct inode* inode = current_task->fs->cwd;

    if(unlikely(!inode))
        inode = current_task->fs->root;


    char buf[size];
    memset(buf, 0, size);

    for(; inode != current_task->fs->root && inode->parent != NULL; inode = inode->parent) {

        if(__append(buf, size, inode->name) < 0)
            return -ERANGE;

        if(__append(buf, size, "/") < 0)
            return -ERANGE;

    }

    if(__append(buf, size, "/") < 0)
        return -ERANGE;



    uio_memcpy_s2u(ubuf, buf, size);

    return (long) ubuf;

});
