/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aplus.
 * 
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <aplus/smp.h>
#include <aplus/errno.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>


/***
 * Name:        mkdir
 * Description: create a directory
 * URL:         http://man7.org/linux/man-pages/man2/mkdir.2.html
 *
 * Input Parameters:
 *  0: 0x53
 *  1: const char __user * pathname
 *  2: umode_t mode
 *
 * Auto-generated by extra/utils/gen-syscalls.js
 */

SYSCALL(83, mkdir,
long sys_mkdir (const char __user * pathname, mode_t mode) {
    
    int fd = sys_open(pathname, O_CREAT | O_EXCL | O_RDONLY, S_IFDIR | (mode & 0777));
    if(fd < 0)
        return fd;

    if((fd = sys_close(fd)) < 0)
        return fd;

    return 0;
});
