/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <fcntl.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>


/***
 * Name:        setpgid
 * Description: set/get process group
 * URL:         http://man7.org/linux/man-pages/man2/setpgid.2.html
 *
 * Input Parameters:
 *  0: 0x6d
 *  1: pid_t pid
 *  2: pid_t pgid
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

/**
 * @brief Moves a task into a process group within its own session.
 *
 * @param pid The task to move, or 0 for the caller.
 * @param pgid The group to move it to, or 0 for the task's own pid.
 * @return 0 on success, or a negative errno.
 */

SYSCALL(
    109, setpgid, long sys_setpgid(pid_t pid, pid_t pgid) {

        pid_t target_tid = 0;
        pid_t target_sid = 0;

        bool found = false;
        bool owned = false;


        if (likely(pid == 0)) {

            target_tid = current_task->tid;
            target_sid = current_task->sid;

            found = owned = true;

        } else {

            cpu_foreach_if(cpu, !found) {

                scoped_lock(&cpu->sched_lock) {

                    for (task_t* tmp = cpu->sched_queue; tmp; tmp = tmp->next) {

                        if (tmp->tid != pid)
                            continue;

                        target_tid = tmp->tid;
                        target_sid = tmp->sid;

                        owned = (tmp->parent == current_task);
                        found = true;

                        break;
                    }
                }
            }
        }

        if (unlikely(!found))
            return -ESRCH;

        if (unlikely(!owned))
            return -ESRCH;

        if (unlikely(target_sid != current_task->sid))
            return -EPERM;

        if (unlikely(target_tid == target_sid))
            return -EPERM;

        if (unlikely(pgid < 0))
            return -EINVAL;

        if (pgid == 0) {

            pgid = target_tid;

        } else if (pgid != target_tid) {

            bool same_session = false;
            bool pgid_found   = false;

            cpu_foreach_if(cpu, !pgid_found) {

                scoped_lock(&cpu->sched_lock) {

                    for (task_t* tmp = cpu->sched_queue; tmp; tmp = tmp->next) {

                        if (tmp->tid != pgid)
                            continue;

                        same_session = (tmp->sid == target_sid);
                        pgid_found   = true;

                        break;
                    }
                }
            }

            if (unlikely(!pgid_found))
                return -EPERM;

            if (unlikely(!same_session))
                return -EPERM;
        }


        if (likely(pid == 0)) {

            scoped_lock(&current_task->lock) {
                current_task->pgrp = pgid;
            }

            return 0;
        }


        bool applied = false;

        cpu_foreach_if(cpu, !applied) {

            scoped_lock(&cpu->sched_lock) {

                for (task_t* tmp = cpu->sched_queue; tmp; tmp = tmp->next) {

                    if (tmp->tid != pid)
                        continue;

                    scoped_lock(&tmp->lock) {
                        tmp->pgrp = pgid;
                    }

                    applied = true;

                    break;
                }
            }
        }

        if (unlikely(!applied))
            return -ESRCH;

        return 0;
    });
