/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aplus.
 * 
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <aplus/smp.h>
#include <aplus/errno.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>


/***
 * Name:        capget
 * Description: set/get capabilities of thread(s)
 * URL:         http://man7.org/linux/man-pages/man2/capget.2.html
 *
 * Input Parameters:
 *  0: 0x7d
 *  1: cap_user_header_t header
 *  2: cap_user_data_t dataptr
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

typedef long cap_user_data_t;
typedef long cap_user_header_t;

SYSCALL(125, capget,
long sys_capget (cap_user_header_t header, cap_user_data_t dataptr) {
    return -ENOSYS;
});
