/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <fcntl.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/task.h>


/***
 * Name:        getpriority
 * Description: get/set program scheduling priority
 * URL:         http://man7.org/linux/man-pages/man2/getpriority.2.html
 *
 * Input Parameters:
 *  0: 0x8c
 *  1: int which
 *  2: int who
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(
    140, getpriority, long sys_getpriority(int which, int who) {
        switch (which) {

            case PRIO_PROCESS:
                if (who == 0)
                    who = current_task->tid;
                break;

            case PRIO_PGRP:
                if (who == 0)
                    who = current_task->pgrp;
                break;

            case PRIO_USER:
                if (who == 0)
                    who = current_task->uid;
                break;

            default:
                return -EINVAL;
        }



        cpu_foreach(cpu) {

            task_t* tmp;
            for (tmp = cpu->sched_queue; tmp; tmp = tmp->next) {

                switch (which) {

                    case PRIO_PROCESS:
                        if (tmp->tid != who)
                            continue;
                        break;

                    case PRIO_PGRP:
                        if (tmp->pgrp != who)
                            continue;
                        break;

                    case PRIO_USER:
                        if (tmp->uid != who)
                            continue;
                        break;

                    default:
                        return -EINVAL;
                }


                if (!(tmp->euid == current_task->euid || tmp->euid == current_task->uid))
                    return -EPERM;


                return 20 + tmp->priority;
            }
        }


        return -ESRCH;
    });
