/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aPlus.
 * 
 * aPlus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aPlus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aPlus.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdint.h>
#include <signal.h>
#include <unistd.h>
#include <sys/types.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <aplus/smp.h>
#include <aplus/errno.h>



/***
 * Name:        tkill
 * Description: send a signal to a thread
 * URL:         http://man7.org/linux/man-pages/man2/tkill.2.html
 *
 * Input Parameters:
 *  0: 0xc8
 *  1: pid_t tid
 *  2: int sig
 *
 * Auto-generated by extra/utils/gen-syscalls.js
 */

SYSCALL(200, tkill,
long sys_tkill (pid_t tid, int sig) {

    if(unlikely(tid == 1 && current_task->tid != 1))
        return -EINVAL;

    if(unlikely(sig < 0))
        return -EINVAL;

    if(unlikely(sig > _NSIG - 1))
        return -EINVAL;


    
    cpu_foreach(cpu) {

        task_t* tmp;
        for(tmp = cpu->sched_queue; tmp; tmp = tmp->next) {

            if(tmp->tid != tid)
                continue;

            if(tmp->sigqueue.size > tmp->rlimits[RLIMIT_SIGPENDING].rlim_cur)
                return -EAGAIN;

            if(!(current_task->euid == tmp->uid || current_task->uid == tmp->uid))
                return -EPERM;      

            if(sig == 0)
                return 0;

            // TODO: Check sigmask

            if(tmp->sighand->action[sig].handler == SIG_IGN)
                return 0;

            if(tmp->sighand->action[sig].handler == SIG_DFL)
                return 0; // FIXME

            
            siginfo_t* siginfo = (siginfo_t*) kcalloc(1, sizeof(siginfo_t), GFP_KERNEL);

            siginfo->si_signo = sig;
            siginfo->si_code  = 0;
            siginfo->si_errno = 0;

            queue_enqueue(&current_task->sigqueue, siginfo, 0);

            return 0;

        }

    }


    return -ESRCH;

});
