/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <fcntl.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/ipc.h>
#include <aplus/poll.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/task.h>



/**
 * @brief Waits on a futex word with the restart protocol, until a wakeup, the timeout or a signal ends the wait.
 *
 * The first attempt checks the word and parks; any later attempt was woken, and reports a timeout if the deadline
 * has passed and a wakeup otherwise.
 *
 * @param kaddr The word, as the kernel reaches it.
 * @param val The value the caller expects the word to hold.
 * @param utime The relative timeout in userspace, or NULL to wait for a wakeup alone.
 * @return 0 once woken, -EAGAIN, -EINVAL or -ETIMEDOUT, or -EINTR with the syscall parked for restart.
 */
static long __futex_wait(uint32_t* kaddr, uint32_t val, const struct timespec* utime) {

    uint64_t timeout_ns = POLL_TIMEOUT_FOREVER;

    if (utime) {

        struct timespec ts;

        uio_memcpy_u2s(&ts, utime, sizeof(ts));

        if (unlikely(ts.tv_sec < 0 || ts.tv_nsec < 0 || ts.tv_nsec >= 1000000000L))
            return poll_finish(-EINVAL);

        if ((uint64_t)ts.tv_sec < (POLL_TIMEOUT_FOREVER / 1000000000ULL) - 1)
            timeout_ns = (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
    }


    struct timespec remaining;

    poll_deadline_t deadline = poll_deadline(timeout_ns, &remaining);

    if (current_task->syscall.started)
        return poll_finish(deadline == POLL_DEADLINE_EXPIRED ? -ETIMEDOUT : 0);

    if (atomic_load_explicit(kaddr, memory_order_acquire) != val)
        return poll_finish(-EAGAIN);

    if (deadline == POLL_DEADLINE_EXPIRED)
        return poll_finish(-ETIMEDOUT);


    current_task->syscall.started = true;

    futex_wait(current_task, kaddr, val, deadline == POLL_DEADLINE_REMAINING ? &remaining : NULL);

    return poll_suspend(true, NULL);
}


/***
 * Name:        futex
 * Description: fast user-space locking
 * URL:         http://man7.org/linux/man-pages/man2/futex.2.html
 *
 * Input Parameters:
 *  0: 0xca
 *  1: undefined
 *
 * Auto-generated by scripts/gen-syscalls.js
 */


SYSCALL(
    202, futex, long sys_futex(uint32_t* uaddr, int op, uint32_t val, long __val2, uint32_t* uaddr2, uint32_t val3) {
        if (unlikely(!uaddr || ((uintptr_t)uaddr & (sizeof(uint32_t) - 1))))
            return -EINVAL;

        if (unlikely(!uio_check(uaddr, R_OK)))
            return -EFAULT;


        uint32_t* kaddr = uio_get_ptr(uaddr);


        switch (op & FUTEX_CMD_MASK) {

            case FUTEX_WAIT:

            {

                const struct timespec* utime = (const struct timespec*)__val2;

                if (unlikely(utime && !uio_check(utime, R_OK)))
                    return -EFAULT;

                return __futex_wait(kaddr, val, utime);
            }


            case FUTEX_WAKE:
                return (long)futex_wakeup(kaddr, val);


            case FUTEX_CMP_REQUEUE:
            case FUTEX_REQUEUE:

            {

                if (unlikely(!uaddr2 || ((uintptr_t)uaddr2 & (sizeof(uint32_t) - 1))))
                    return -EINVAL;

                if (unlikely(!uio_check(uaddr2, R_OK)))
                    return -EFAULT;

                if ((op & FUTEX_CMD_MASK) == FUTEX_CMP_REQUEUE && atomic_load_explicit(kaddr, memory_order_acquire) != val3)
                    return -EAGAIN;


                uint32_t* kaddr2 = uio_get_ptr(uaddr2);

                size_t woken = futex_wakeup(kaddr, val);

                return (long)(woken + futex_requeue(kaddr, kaddr2, (uint32_t)__val2));
            }


            default:
                return -ENOSYS;
        }
    });
