/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aplus.
 * 
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <aplus/smp.h>
#include <aplus/hal.h>
#include <aplus/errno.h>



/***
 * Name:        sched_setaffinity
 * Description: set  and get a thread's CPU
       affinity mask
 * URL:         http://man7.org/linux/man-pages/man2/sched_setaffinity.2.html
 *
 * Input Parameters:
 *  0: 0xcb
 *  1: pid_t pid
 *  2: unsigned int len
 *  3: unsigned long  * user_mask_ptr
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(203, sched_setaffinity,
long sys_sched_setaffinity (pid_t pid, unsigned int len, unsigned long  * user_mask_ptr) {
    
    if(unlikely(len != CPU_SETSIZE))
        return -EINVAL;

    if(unlikely(!user_mask_ptr))
        return -EINVAL;

    if(unlikely(!uio_check(user_mask_ptr, R_OK)))
        return -EFAULT;

    
    cpu_set_t empty_mask;
    CPU_ZERO(&empty_mask);

    cpu_set_t user_mask;
    uio_memcpy_u2s(&user_mask, user_mask_ptr, sizeof(cpu_set_t));


    if(unlikely(CPU_EQUAL(&user_mask_ptr, &empty_mask)))
        return -EINVAL;


    if(pid == 0)
        pid = current_task->tid;



    cpu_foreach(cpu) {

        task_t* tmp;
        for(tmp = cpu->sched_queue; tmp; tmp = tmp->next) {

            if(tmp->tid != pid)
                continue;

            if(!(tmp->euid == current_task->euid || tmp->uid == current_task->euid))
                return -EPERM;

            
            CPU_ZERO(&tmp->affinity);
            CPU_OR(&tmp->affinity, &tmp->affinity, &user_mask);
            
            return CPU_SETSIZE;

        }

    }


    return -ESRCH;

});
