/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <fcntl.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <signal.h>
#include <string.h>
#include <unistd.h>


/***
 * Name:        exit_group
 * Description: exit all threads in a process
 * URL:         http://man7.org/linux/man-pages/man2/exit_group.2.html
 *
 * Input Parameters:
 *  0: 0xe7
 *  1: int error_code
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(
    231, exit_group, long sys_exit_group(int error_code) {
        DEBUG_ASSERT(current_task);


        /* exit(3) ends the process, not just the thread that called it.
         *
         * While this was a stub, musl fell back to plain exit(2) and only the calling
         * thread died -- harmless for as long as pthread_create() could not succeed, and
         * not harmless afterwards: a sibling left running after main() returned kept
         * executing on a stack its joiner had already handed back, faulting on it forever
         * and, on a uniprocessor, starving everything else.
         *
         * CLONE_THREAD gives every thread of a process the same pid, so the thread group is
         * exactly the set sched_sigqueueinfo() selects by pid. SIGKILL cannot be caught or
         * blocked, so this reaches all of them. The caller is in that set too; it never
         * returns to userspace to act on the signal, and sys_exit() below makes it a zombie
         * first. */
        siginfo_t si;

        memset(&si, 0, sizeof(si));

        si.si_signo = SIGKILL;
        si.si_code  = SI_KERNEL;
        si.si_pid   = current_task->pid;
        si.si_uid   = current_task->uid;

        sched_sigqueueinfo(-1, current_task->pid, -1, SIGKILL, &si);


        return sys_exit(error_code);
    });
