/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 * 
 * Copyright (c) 2013-2019 Antonino Natale
 * 
 * 
 * This file is part of aplus.
 * 
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <aplus/smp.h>
#include <aplus/hal.h>
#include <aplus/errno.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>


extern long sys_openat (int dfd, const char __user * filename, int flags, mode_t mode);


/***
 * Name:        readlinkat
 * Description: read value of a symbolic link
 * URL:         http://man7.org/linux/man-pages/man2/readlinkat.2.html
 *
 * Input Parameters:
 *  0: 0x10b
 *  1: int dfd
 *  2: const char __user * path
 *  3: char __user * buf
 *  4: int bufsiz
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(267, readlinkat,
long sys_readlinkat (int dfd, const char __user * path, char __user * buf, int size) {
   
    DEBUG_ASSERT(current_task);

    current_task->iostat.rchar += (uint64_t) size;
    current_task->iostat.syscr += 1;

    
    if(unlikely(size == 0))
        return 0;

    if(unlikely(size < 0))
        return -EINVAL;

    if(unlikely(!buf))
        return -EINVAL;

    if(unlikely(!uio_check(buf, R_OK | W_OK)))
        return -EFAULT;

    if(unlikely(!path))
        return -EINVAL;

    if(unlikely(!uio_check(path, R_OK)))
        return -EFAULT;


    int fd = -1;

    if((fd = sys_openat(dfd, path, O_RDONLY | O_NOFOLLOW, 0)) < 0)
        return fd;


    inode_t* inode = NULL;

    shared_ptr_access(current_task->fd, fds, {

        DEBUG_ASSERT(fds->descriptors[fd].ref);
        DEBUG_ASSERT(fds->descriptors[fd].ref->inode);

        inode = fds->descriptors[fd].ref->inode;

    });

    DEBUG_ASSERT(inode);
    

    if((fd = sys_close(fd)) < 0)
        return fd;


    struct stat st = { 0 };

    if(unlikely(vfs_getattr(inode, &st) < 0))
        return -EIO;
    
    if(unlikely(!S_ISLNK(st.st_mode)))
        return -EINVAL;



    ssize_t e = 0;


    uio_lock(buf, size);

    {

        if((e = vfs_readlink(inode, buf, size)) > 0) {
            current_task->iostat.read_bytes += (uint64_t) e;
        }

    }

    uio_unlock(buf, size);


    if(e < 0)
        return -errno;

    return e; 

});
