/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <fcntl.h>
#include <signal.h>
#include <stdint.h>
#include <sys/select.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/poll.h>
#include <aplus/smp.h>
#include <aplus/syscall.h>
#include <aplus/task.h>


//? pselect6() takes seven arguments and a syscall only carries six, so the mask
//? and its size travel together behind one pointer.
struct pselect6_sigmask {

    const sigset_t* ss;
    size_t ss_len;
};


/***
 * Name:        pselect6
 * Description: synchronous I/O
       multiplexing
 * URL:         http://man7.org/linux/man-pages/man2/pselect6.2.html
 *
 * Input Parameters:
 *  0: 0x10e
 *  1: int n
 *  2: fd_set  * inp
 *  3: fd_set  * outp
 *  4: fd_set  * exp
 *  5: struct timespec  * tsp
 *  6: void  * sig
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

SYSCALL(
    270, pselect6, long sys_pselect6(int n, fd_set* inp, fd_set* outp, fd_set* exp, struct timespec* tsp, void* sig) {
        uint64_t timeout_ns;

        int err;

        if ((err = poll_timeout_timespec(tsp, &timeout_ns)) < 0)
            return poll_finish(err);


        if (sig != NULL) {

            if (unlikely(!uio_check(sig, R_OK)))
                return poll_finish(-EFAULT);


            struct pselect6_sigmask sm;
            uio_memcpy_u2s(&sm, sig, sizeof(struct pselect6_sigmask));

            //? Blocking the signals the caller asked to ignore is the whole point
            //? of pselect6() over select(): it closes the window between changing
            //? the mask and starting to wait, where a signal could arrive unseen
            //? and the wait would then block forever. poll_finish() puts the old
            //? mask back.
            if ((err = poll_sigmask_install(sm.ss, sm.ss_len)) < 0)
                return poll_finish(err);
        }


        return poll_finish(poll_wait_fdset(n, inp, outp, exp, timeout_ns));
    });
