/*
 * Author:
 *      Antonino Natale <antonio.natale97@hotmail.com>
 *
 * Copyright (c) 2013-2019 Antonino Natale
 *
 *
 * This file is part of aplus.
 *
 * aplus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aplus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aplus.  If not, see <http://www.gnu.org/licenses/>.
 */


#include <aplus.h>
#include <aplus/debug.h>
#include <aplus/errno.h>
#include <aplus/hal.h>
#include <aplus/smp.h>
#include <aplus/ipc.h>
#include <aplus/syscall.h>
#include <aplus/unix.h>
#include <aplus/task.h>
#include <fcntl.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>


/***
 * Name:        accept4
 * Description: accept a connection on a socket
 * URL:         http://man7.org/linux/man-pages/man2/accept4.2.html
 *
 * Input Parameters:
 *  0: 0x120
 *  1: int
 *  2: struct sockaddr  *
 *  3: int  *
 *  4: int
 *
 * Auto-generated by scripts/gen-syscalls.js
 */

#include <aplus/network.h>


SYSCALL(
    288, accept4, long sys_accept4(int fd, struct sockaddr* sockaddr, int* socklen, int flags) {

        struct unix_sock* us;

        if ((us = unix_sock_from_fd(fd)) != NULL) {

            uint32_t seq = unix_sock_seq(us);

            long e = unix_accept(us, sockaddr, (uint32_t*)socklen, flags);

            if (e != -EAGAIN) {
                unix_sock_put(us);
                return e;
            }


            bool nonblock = !!(flags & O_NONBLOCK);

            if (!nonblock) {

                shared_ptr_access(current_task->fd, fds, {
                    if (fds->descriptors[fd].ref)
                        nonblock = !!(fds->descriptors[fd].flags & O_NONBLOCK);
                });
            }

            if (nonblock) {
                unix_sock_put(us);
                return -EAGAIN;
            }


            unix_sock_wait(us, seq);
            unix_sock_put(us);

            thread_suspend(current_task);
            thread_restart_sched(current_task);
            thread_restart_syscall(current_task);

            return -EINTR;
        }


        if (sockaddr) {

            if (unlikely(!socklen || !uio_check(socklen, R_OK | W_OK)))
                return -EFAULT;

            if (unlikely(!uio_check(sockaddr, R_OK | W_OK)))
                return -EFAULT;
        }


        int fdflags       = 0;
        struct file* file = fd_get((unsigned int)fd, &fdflags);

        if (unlikely(!file))
            return -EBADF;


        struct sockaddr_storage peer;
        socklen_t peerlen = sizeof(peer);

        long e = socket_accept(file->inode, sockaddr ? (struct sockaddr*)&peer : NULL, sockaddr ? &peerlen : NULL, !!(fdflags & O_NONBLOCK));

        fd_put(file);

        if (e < 0)
            return e;


        if (sockaddr) {

            socklen_t room = (socklen_t)uio_r32((uint32_t*)socklen);

            uio_memcpy_s2u(sockaddr, &peer, room < peerlen ? room : peerlen);
            uio_w32((uint32_t*)socklen, peerlen);
        }

        return socket_install((int)e, flags);
    });
