#ifndef _SLIRP_H
#define _SLIRP_H

#define SLIRP_PACKET_END		0xC0
#define SLIRP_PACKET_ESC		0xDB
#define SLIRP_PACKET_ESC_END	0xDC
#define SLIRP_PACKET_ESC_ESC	0xDD

#define SLIRP_BUFSIZ			1006
#define SLIRP_MTU				65536

#define SLIRP_MAGIC				0x100200FF


#endif
