.TH "__DIR" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DIR \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dirent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "int \fBposition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file dirent\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int __DIR::fd"

.PP
Definition at line 30 of file dirent\&.h\&.
.SS "int __DIR::position"

.PP
Definition at line 31 of file dirent\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
