.TH "__pthread_key" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__pthread_key \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pthread_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBused\fP"
.br
.ti -1c
.RI "void(* \fBdtor\fP )(void *)"
.br
.ti -1c
.RI "void * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file pthread_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void(* __pthread_key::dtor)(void *)"

.PP
Definition at line 33 of file pthread_internal\&.h\&.
.SS "char __pthread_key::used"

.PP
Definition at line 32 of file pthread_internal\&.h\&.
.SS "void* __pthread_key::value"

.PP
Definition at line 34 of file pthread_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
