.TH "__syscall" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__syscall \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <syscall\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBhandler\fP"
.br
.ti -1c
.RI "int \fBnumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file syscall\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* __syscall::handler"

.PP
Definition at line 10 of file syscall\&.h\&.
.SS "int __syscall::number"

.PP
Definition at line 11 of file syscall\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
