.TH "usr/src/libposix/src/_execve.c" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/_execve.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBexecve\fP (const char *filename, char *const args[], char *const env[])"
.br
.ti -1c
.RI "int \fB_execve\fP (const char *filename, char *const args[], char *const env[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int _execve (const char *filename, char *constargs[], char *constenv[])"

.PP
Definition at line 8 of file _execve\&.c\&.
.PP
References execve()\&.
.PP
.nf
8                                                                          {
9     return execve(filename, args, env);
10 }
.fi
.SS "int execve (const char *filename, char *constargs[], char *constenv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
