.TH "src/syscall/_exit.c" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syscall/_exit.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <aplus\&.h>\fP
.br
\fC#include <aplus/syscall\&.h>\fP
.br
\fC#include <aplus/task\&.h>\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "void \fBsys_exit\fP (int status)"
.br
.ti -1c
.RI "\fBSYSCALL\fP (\fBsys_exit\fP, 0)"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "void sys_exit (intstatus)"

.PP
Definizione alla linea 6 del file _exit\&.c\&.
.PP
Referenzia schedule_exit()\&.
.PP
.nf
6                           {
7     schedule_exit(status);
8 }
.fi
.SS "SYSCALL (\fBsys_exit\fP, 0)"

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
