.TH "src/syscall Directory Reference" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syscall Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB_exit\&.c\fP"
.br
.ti -1c
.RI "file \fBchown\&.c\fP"
.br
.ti -1c
.RI "file \fBclone\&.c\fP"
.br
.ti -1c
.RI "file \fBclose\&.c\fP"
.br
.ti -1c
.RI "file \fBexecve\&.c\fP"
.br
.ti -1c
.RI "file \fBfcntl\&.c\fP"
.br
.ti -1c
.RI "file \fBfork\&.c\fP"
.br
.ti -1c
.RI "file \fBfstat\&.c\fP"
.br
.ti -1c
.RI "file \fBgetgroups\&.c\fP"
.br
.ti -1c
.RI "file \fBgetpid\&.c\fP"
.br
.ti -1c
.RI "file \fBgettimeofday\&.c\fP"
.br
.ti -1c
.RI "file \fBioctl\&.c\fP"
.br
.ti -1c
.RI "file \fBisatty\&.c\fP"
.br
.ti -1c
.RI "file \fBkill\&.c\fP"
.br
.ti -1c
.RI "file \fBlink\&.c\fP"
.br
.ti -1c
.RI "file \fBlseek\&.c\fP"
.br
.ti -1c
.RI "file \fBmount\&.c\fP"
.br
.ti -1c
.RI "file \fBopen\&.c\fP"
.br
.ti -1c
.RI "file \fBopenpty\&.c\fP"
.br
.ti -1c
.RI "file \fBread\&.c\fP"
.br
.ti -1c
.RI "file \fBreaddir\&.c\fP"
.br
.ti -1c
.RI "file \fBsbrk\&.c\fP"
.br
.ti -1c
.RI "file \fBstat\&.c\fP"
.br
.ti -1c
.RI "file \fBsymlink\&.c\fP"
.br
.ti -1c
.RI "file \fBtest\&.c\fP"
.br
.ti -1c
.RI "file \fBtime\&.c\fP"
.br
.ti -1c
.RI "file \fBtimes\&.c\fP"
.br
.ti -1c
.RI "file \fBumount\&.c\fP"
.br
.ti -1c
.RI "file \fBunlink\&.c\fP"
.br
.ti -1c
.RI "file \fBwait\&.c\fP"
.br
.ti -1c
.RI "file \fBwrite\&.c\fP"
.br
.ti -1c
.RI "file \fByield\&.c\fP"
.br
.in -1c
