.TH "usr/src/libpthread/src/platform Directory Reference" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libpthread/src/platform Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBposix\fP"
.br
.ti -1c
.RI "directory \fBwin32\fP"
.br
.in -1c
