.TH "Riferimenti per la directory usr/src/libposix/src" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Riferimenti per la directory usr/src/libposix/src \- 
.SH SYNOPSIS
.br
.PP
.SS "File"

.in +1c
.ti -1c
.RI "file \fB_execve\&.c\fP"
.br
.ti -1c
.RI "file \fBalarm\&.c\fP"
.br
.ti -1c
.RI "file \fBalphasort\&.c\fP"
.br
.ti -1c
.RI "file \fBclosedir\&.c\fP"
.br
.ti -1c
.RI "file \fBconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBdup2\&.c\fP"
.br
.ti -1c
.RI "file \fBenviron\&.c\fP"
.br
.ti -1c
.RI "file \fBerrno\&.c\fP"
.br
.ti -1c
.RI "file \fBexecl\&.c\fP"
.br
.ti -1c
.RI "file \fBexecle\&.c\fP"
.br
.ti -1c
.RI "file \fBexeclp\&.c\fP"
.br
.ti -1c
.RI "file \fBexecv\&.c\fP"
.br
.ti -1c
.RI "file \fBexecvp\&.c\fP"
.br
.ti -1c
.RI "file \fBgetcwd\&.c\fP"
.br
.ti -1c
.RI "file \fBgid\&.c\fP"
.br
.ti -1c
.RI "file \fBlstat\&.c\fP"
.br
.ti -1c
.RI "file \fBnanosleep\&.c\fP"
.br
.ti -1c
.RI "file \fBopendir\&.c\fP"
.br
.ti -1c
.RI "file \fBreaddir\&.c\fP"
.br
.ti -1c
.RI "file \fBrewinddir\&.c\fP"
.br
.ti -1c
.RI "file \fBscandir\&.c\fP"
.br
.ti -1c
.RI "file \fBsched\&.c\fP"
.br
.ti -1c
.RI "file \fBseekdir\&.c\fP"
.br
.ti -1c
.RI "file \fBsleep\&.c\fP"
.br
.ti -1c
.RI "file \fBtelldir\&.c\fP"
.br
.ti -1c
.RI "file \fBuid\&.c\fP"
.br
.ti -1c
.RI "file \fBusleep\&.c\fP"
.br
.in -1c
