.TH "Riferimenti per la directory src" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Riferimenti per la directory src \- 
.SH SYNOPSIS
.br
.PP
.SS "Directory"

.in +1c
.ti -1c
.RI "directory \fBarch\fP"
.br
.ti -1c
.RI "directory \fBfs\fP"
.br
.ti -1c
.RI "directory \fBinclude\fP"
.br
.ti -1c
.RI "directory \fBmm\fP"
.br
.ti -1c
.RI "directory \fBnet\fP"
.br
.ti -1c
.RI "directory \fBsyscall\fP"
.br
.in -1c
.SS "File"

.in +1c
.ti -1c
.RI "file \fBbufio\&.c\fP"
.br
.ti -1c
.RI "file \fBdebug\&.c\fP"
.br
.ti -1c
.RI "file \fBexec\&.c\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBpanic\&.c\fP"
.br
.ti -1c
.RI "file \fBsched\&.c\fP"
.br
.ti -1c
.RI "file \fBspinlock\&.c\fP"
.br
.in -1c
