.TH "src/mm Directory Reference" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mm Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBheap\&.c\fP"
.br
.ti -1c
.RI "file \fBkheap\&.c\fP"
.br
.ti -1c
.RI "file \fBmm\&.c\fP"
.br
.ti -1c
.RI "file \fBpaging\&.c\fP"
.br
.in -1c
