.TH "usr/src/libposix/src/alphasort.c" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/alphasort.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dirent\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBalphasort\fP (const struct \fBdirent\fP **a, const struct \fBdirent\fP **b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int alphasort (const struct \fBdirent\fP **a, const struct \fBdirent\fP **b)"

.PP
Definition at line 12 of file alphasort\&.c\&.
.PP
.nf
12                                                                 {
13     return strcoll((*a)->d_name, (*b)->d_name);
14 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
