src/net/arp.c
NAME
src/net/arp.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/list.h>
#include <aplus/netif.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <aplus/net/eth.h>
#include <aplus/net/arp.h>
Functions
arp_cache_entry_t * arp_cache_find_by_macaddr (macaddr_t macaddr)
int arp_cache_add (macaddr_t macaddr, ipv4_t ipv4)
int arp_recv (netif_t *netif, void *buf, size_t length)
int arp_send (netif_t *netif)
Variables
list_t * arp_cache = NULL
Function Documentation
int arp_cache_add (macaddr_tmacaddr, ipv4_tipv4)
Definition at line 33 of file arp.c.
References arp_cache_find_by_macaddr(), netif::ipv4, kmalloc(), kprintf(), list_add(), list_init, list_remove(), and netif_find_by_macaddr().
                                                  {
    if(arp_cache == NULL) {
        list_init(arp_cache);
    }
    arp_cache_entry_t* arp = arp_cache_find_by_macaddr(macaddr);
    if(arp)
        list_remove(arp_cache, (listval_t) arp);
    arp = kmalloc(sizeof(arp_cache_entry_t));
    memcpy(arp->macaddr, macaddr, sizeof(macaddr_t));
    memcpy(arp->ipv4, ipv4, sizeof(ipv4_t));
    //arp->ttl = time(NULL) + ARP_TTL;
#ifdef ARP_DEBUG
    kprintf("arp: added new cache entry (%02x.%02x.%02x.%02x)\n",
        arp->ipv4[0],
        arp->ipv4[1],
        arp->ipv4[2],
        arp->ipv4[3]
    );
#endif
    netif_t* netif = (netif_t*) netif_find_by_macaddr(arp->macaddr);
    if(netif)
        memcpy(netif->ipv4, arp->ipv4, sizeof(ipv4_t));
    return list_add(arp_cache, (listval_t) arp);
}
arp_cache_entry_t* arp_cache_find_by_macaddr (macaddr_tmacaddr)
Definition at line 16 of file arp.c.
References list_empty(), list_foreach, arp_cache_entry::macaddr, and value.
                                                                {
    if(arp_cache == NULL)
        return NULL;
    if(list_empty(arp_cache))
        return NULL;
    list_foreach(value, arp_cache) {
        arp_cache_entry_t* arp = (arp_cache_entry_t*) value;
        if(memcmp(arp->macaddr, macaddr, sizeof(macaddr_t)) == 0)
            return arp;
    }
    return NULL;
}
int arp_recv (netif_t *netif, void *buf, size_tlength)
Definition at line 67 of file arp.c.
References arp_cache_add(), ARP_OPERATION_REPLY, length, and netif::macaddr.
                                                       {
    arp_header_t* arp = (arp_header_t*) buf;
    if(arp->operation == ARP_OPERATION_REPLY)
        if(memcmp(netif->macaddr, arp->tha, sizeof(macaddr_t)) == 0)
            arp_cache_add(arp->tha, arp->tpa);
    return length;
}
int arp_send (netif_t *netif)
Definition at line 79 of file arp.c.
References ARP_HWLEN, ARP_HWTYPE, ARP_OPERATION_REQUEST, ARP_PRLEN, ARP_PRTYPE, eth_send(), kfree(), kmalloc(), kprintf(), netif::macaddr, netif::name, and NETIF_ARP.
                             {
    arp_header_t* arp = (arp_header_t*) kmalloc(sizeof(arp_header_t));
    arp->hwtype = ARP_HWTYPE;
    arp->prtype = ARP_PRTYPE;
    arp->hwlen = ARP_HWLEN;
    arp->prlen = ARP_PRLEN;
    arp->operation = ARP_OPERATION_REQUEST;
    
    memcpy(arp->sha, netif->macaddr, sizeof(macaddr_t));
    memset(arp->tha, 0, sizeof(macaddr_t));
    memset(arp->spa, 0, sizeof(ipv4_t));
    memset(arp->tpa, 0, sizeof(ipv4_t));
#ifdef ARP_DEBUG
    kprintf("arp: sending request for %s\n", netif->name);
#endif
    int ret = eth_send(netif, arp, sizeof(arp_header_t), NETIF_ARP);
    kfree(arp);
    
    return ret;
}
Variable Documentation
list_t* arp_cache = NULL
Definition at line 13 of file arp.c.
Author
Generated automatically by Doxygen for aPlus from the source code.