.TH "src/include/aplus/net/arp.h" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/aplus/net/arp.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <aplus/netif\&.h>\fP
.br
\fC#include <aplus/net/eth\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBarp_header\fP"
.br
.ti -1c
.RI "struct \fBarp_cache_entry\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBARP_PRTYPE\fP   \fBETH_TYPE_IPV4\fP"
.br
.ti -1c
.RI "#define \fBARP_PRLEN\fP   4"
.br
.ti -1c
.RI "#define \fBARP_HWTYPE\fP   0x0001"
.br
.ti -1c
.RI "#define \fBARP_HWLEN\fP   6"
.br
.ti -1c
.RI "#define \fBARP_OPERATION_REQUEST\fP   1"
.br
.ti -1c
.RI "#define \fBARP_OPERATION_REPLY\fP   2"
.br
.ti -1c
.RI "#define \fBARP_TTL\fP   600		/* 10min */"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBarp_cache_entry\fP \fBarp_cache_entry_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBarp_header\fP \fB__attribute__\fP ((packed)) arp_header_t"
.br
.RI "\fIAlloc memory from Kernel Heap\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuint16_t\fP \fBhwtype\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBprtype\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBhwlen\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBprlen\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBoperation\fP"
.br
.ti -1c
.RI "\fBmacaddr_t\fP \fBsha\fP"
.br
.ti -1c
.RI "\fBipv4_t\fP \fBspa\fP"
.br
.ti -1c
.RI "\fBmacaddr_t\fP \fBtha\fP"
.br
.ti -1c
.RI "\fBipv4_t\fP \fBtpa\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARP_HWLEN   6"

.PP
Definition at line 16 of file arp\&.h\&.
.SS "#define ARP_HWTYPE   0x0001"

.PP
Definition at line 15 of file arp\&.h\&.
.SS "#define ARP_OPERATION_REPLY   2"

.PP
Definition at line 19 of file arp\&.h\&.
.SS "#define ARP_OPERATION_REQUEST   1"

.PP
Definition at line 18 of file arp\&.h\&.
.SS "#define ARP_PRLEN   4"

.PP
Definition at line 13 of file arp\&.h\&.
.SS "#define ARP_PRTYPE   \fBETH_TYPE_IPV4\fP"

.PP
Definition at line 12 of file arp\&.h\&.
.SS "#define ARP_TTL   600		/* 10min */"

.PP
Definition at line 21 of file arp\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBarp_cache_entry\fP  \fBarp_cache_entry_t\fP"

.SH "Function Documentation"
.PP 
.SS "struct \fBarp_header\fP __attribute__ ((packed))"

.PP
Alloc memory from Kernel Heap\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP Size of data to alloc\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Virtual Address of data\&. 
.RE
.PP

.PP
Definition at line 44 of file desc\&.c\&.
.PP
.nf
46                        {
47     uint16_t limit;
48     uint32_t base;
49 } __attribute__((packed)) gdt_ptr_t;
.fi
.SH "Variable Documentation"
.PP 
.SS "\fBuint8_t\fP hwlen"

.PP
Definition at line 71 of file arp\&.h\&.
.SS "\fBuint16_t\fP hwtype"

.PP
Definition at line 69 of file arp\&.h\&.
.SS "\fBuint16_t\fP operation"

.PP
Definition at line 73 of file arp\&.h\&.
.SS "\fBuint8_t\fP prlen"

.PP
Definition at line 72 of file arp\&.h\&.
.SS "\fBuint16_t\fP prtype"

.PP
Definition at line 70 of file arp\&.h\&.
.SS "\fBmacaddr_t\fP sha"

.PP
Definition at line 74 of file arp\&.h\&.
.SS "\fBipv4_t\fP spa"

.PP
Definition at line 75 of file arp\&.h\&.
.SS "\fBmacaddr_t\fP tha"

.PP
Definition at line 76 of file arp\&.h\&.
.SS "\fBipv4_t\fP tpa"

.PP
Definition at line 77 of file arp\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
