.TH "arp_header" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arp_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint16_t\fP \fBhwtype\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBprtype\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBhwlen\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBprlen\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBoperation\fP"
.br
.ti -1c
.RI "\fBmacaddr_t\fP \fBsha\fP"
.br
.ti -1c
.RI "\fBipv4_t\fP \fBspa\fP"
.br
.ti -1c
.RI "\fBmacaddr_t\fP \fBtha\fP"
.br
.ti -1c
.RI "\fBipv4_t\fP \fBtpa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file arp\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint8_t\fP arp_header::hwlen"

.PP
Definition at line 29 of file arp\&.h\&.
.SS "\fBuint16_t\fP arp_header::hwtype"

.PP
Definition at line 27 of file arp\&.h\&.
.SS "\fBuint16_t\fP arp_header::operation"

.PP
Definition at line 31 of file arp\&.h\&.
.SS "\fBuint8_t\fP arp_header::prlen"

.PP
Definition at line 30 of file arp\&.h\&.
.SS "\fBuint16_t\fP arp_header::prtype"

.PP
Definition at line 28 of file arp\&.h\&.
.SS "\fBmacaddr_t\fP arp_header::sha"

.PP
Definition at line 32 of file arp\&.h\&.
.SS "\fBipv4_t\fP arp_header::spa"

.PP
Definition at line 33 of file arp\&.h\&.
.SS "\fBmacaddr_t\fP arp_header::tha"

.PP
Definition at line 34 of file arp\&.h\&.
.SS "\fBipv4_t\fP arp_header::tpa"

.PP
Definition at line 35 of file arp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
