.TH "arp_cache_entry" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arp_cache_entry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arp\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBipv4_t\fP \fBipv4\fP"
.br
.ti -1c
.RI "\fBmacaddr_t\fP \fBmacaddr\fP"
.br
.ti -1c
.RI "time_t \fBttl\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 39 del file arp\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "\fBipv4_t\fP arp_cache_entry::ipv4"

.PP
Definizione alla linea 40 del file arp\&.h\&.
.SS "\fBmacaddr_t\fP arp_cache_entry::macaddr"

.PP
Definizione alla linea 41 del file arp\&.h\&.
.SS "time_t arp_cache_entry::ttl"

.PP
Definizione alla linea 43 del file arp\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
