.TH "usr/src/libatk/src/include/atk.h" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libatk/src/include/atk.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <atk/widget\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBATK_COLOR_BLACK\fP   { 1\&.0f, 0\&.0f, 0\&.0f, 0\&.0f }"
.br
.ti -1c
.RI "#define \fBATK_COLOR_WHITE\fP   { 1\&.0f, 1\&.0f, 1\&.0f, 1\&.0f }"
.br
.ti -1c
.RI "#define \fBATK_COLOR_TRANSPARENT\fP   { 0\&.0f, 0\&.0f, 0\&.0f, 0\&.0f }"
.br
.ti -1c
.RI "#define \fBATK_COLOR_A\fP   3"
.br
.ti -1c
.RI "#define \fBATK_COLOR_R\fP   2"
.br
.ti -1c
.RI "#define \fBATK_COLOR_G\fP   1"
.br
.ti -1c
.RI "#define \fBATK_COLOR_B\fP   0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int atk_v2si \fB__attribute__\fP ((vector_size(sizeof(int)*2)))"
.br
.ti -1c
.RI "typedef atk_v4f \fBatk_color_t\fP"
.br
.ti -1c
.RI "typedef void \fBatk_list_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ATK_COLOR_A   3"

.PP
Definition at line 26 of file atk\&.h\&.
.SS "#define ATK_COLOR_B   0"

.PP
Definition at line 29 of file atk\&.h\&.
.SS "#define ATK_COLOR_BLACK   { 1\&.0f, 0\&.0f, 0\&.0f, 0\&.0f }"

.PP
Definition at line 22 of file atk\&.h\&.
.SS "#define ATK_COLOR_G   1"

.PP
Definition at line 28 of file atk\&.h\&.
.SS "#define ATK_COLOR_R   2"

.PP
Definition at line 27 of file atk\&.h\&.
.SS "#define ATK_COLOR_TRANSPARENT   { 0\&.0f, 0\&.0f, 0\&.0f, 0\&.0f }"

.PP
Definition at line 24 of file atk\&.h\&.
.SS "#define ATK_COLOR_WHITE   { 1\&.0f, 1\&.0f, 1\&.0f, 1\&.0f }"

.PP
Definition at line 23 of file atk\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "__attribute__"

.PP
Definition at line 9 of file atk\&.h\&.
.SS "typedef atk_v4f \fBatk_color_t\fP"

.PP
Definition at line 17 of file atk\&.h\&.
.SS "typedef void \fBatk_list_t\fP"

.PP
Definition at line 18 of file atk\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
