.TH "atk_widget" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
atk_widget \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <widget\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "atk_v2si \fBposition\fP"
.br
.ti -1c
.RI "atk_v2si \fBsize\fP"
.br
.ti -1c
.RI "\fBatk_color_t\fP \fBbackcolor\fP"
.br
.ti -1c
.RI "\fBatk_color_t\fP \fBforecolor\fP"
.br
.ti -1c
.RI "char * \fBtitle\fP"
.br
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "\fBatk_list_t\fP * \fBchilds\fP"
.br
.ti -1c
.RI "struct \fBatk_widget\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct \fB__atk_widget_private\fP \fB__data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file widget\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fB__atk_widget_private\fP atk_widget::__data"

.PP
Definition at line 36 of file widget\&.h\&.
.SS "\fBatk_color_t\fP atk_widget::backcolor"

.PP
Definition at line 24 of file widget\&.h\&.
.SS "\fBatk_list_t\fP* atk_widget::childs"

.PP
Definition at line 33 of file widget\&.h\&.
.SS "int atk_widget::flags"

.PP
Definition at line 30 of file widget\&.h\&.
.SS "\fBatk_color_t\fP atk_widget::forecolor"

.PP
Definition at line 25 of file widget\&.h\&.
.SS "struct \fBatk_widget\fP* atk_widget::parent"

.PP
Definition at line 34 of file widget\&.h\&.
.SS "atk_v2si atk_widget::position"

.PP
Definition at line 21 of file widget\&.h\&.
.SS "atk_v2si atk_widget::size"

.PP
Definition at line 22 of file widget\&.h\&.
.SS "char* atk_widget::text"

.PP
Definition at line 28 of file widget\&.h\&.
.SS "char* atk_widget::title"

.PP
Definition at line 27 of file widget\&.h\&.
.SS "int atk_widget::value"

.PP
Definition at line 31 of file widget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
