.TH "atk_bitmap_lockdata" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
atk_bitmap_lockdata \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bitmap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBatk_rect_t\fP \fBregion\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file bitmap\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* atk_bitmap_lockdata::data"

.PP
Definition at line 12 of file bitmap\&.h\&.
.SS "int atk_bitmap_lockdata::flags"

.PP
Definition at line 10 of file bitmap\&.h\&.
.SS "\fBatk_rect_t\fP atk_bitmap_lockdata::region"

.PP
Definition at line 9 of file bitmap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
