.TH "attribute" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
attribute \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <attribute\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "char \fBname\fP [0x80]"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBvalue\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 25 del file attribute\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "char attribute::name[0x80]"

.PP
Definizione alla linea 26 del file attribute\&.h\&.
.SS "\fBuint32_t\fP attribute::value"

.PP
Definizione alla linea 27 del file attribute\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
