.TH "attribute" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
attribute \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <attribute\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [0x80]"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file attribute\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char attribute::name[0x80]"

.PP
Definition at line 26 of file attribute\&.h\&.
.SS "\fBuint32_t\fP attribute::value"

.PP
Definition at line 27 of file attribute\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
