.TH "usr/src/libatk/src/include/atk/bitmap.h" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libatk/src/include/atk/bitmap.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <atk\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBatk_bitmap_lockdata\fP"
.br
.ti -1c
.RI "struct \fBatk_bitmap\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBATK_BITMAP_LOCK_RDONLY\fP   0"
.br
.ti -1c
.RI "#define \fBATK_BITMAP_LOCK_RDWR\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBatk_bitmap\fP \fBatk_bitmap_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ATK_BITMAP_LOCK_RDONLY   0"

.PP
Definition at line 27 of file bitmap\&.h\&.
.SS "#define ATK_BITMAP_LOCK_RDWR   1"

.PP
Definition at line 28 of file bitmap\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBatk_bitmap\fP  \fBatk_bitmap_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
