.TH "block" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
block \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint16_t\fP \fBmagic\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file mm\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint16_t\fP block::magic"

.PP
Definition at line 45 of file mm\&.c\&.
.SS "size_t block::size"

.PP
Definition at line 46 of file mm\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
