.TH "BootInfo_t" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BootInfo_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grub\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.ti -1c
.RI "unsigned int \fBmem_lower\fP"
.br
.ti -1c
.RI "unsigned int \fBmem_upper\fP"
.br
.ti -1c
.RI "unsigned int \fBboot_device\fP"
.br
.ti -1c
.RI "unsigned int \fBcmdline\fP"
.br
.ti -1c
.RI "unsigned int \fBmods_count\fP"
.br
.ti -1c
.RI "unsigned int ** \fBmods_addr\fP"
.br
.ti -1c
.RI "unsigned int \fBnum\fP"
.br
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.ti -1c
.RI "unsigned int \fBaddr\fP"
.br
.ti -1c
.RI "unsigned int \fBshndx\fP"
.br
.ti -1c
.RI "unsigned int \fBmmap_length\fP"
.br
.ti -1c
.RI "unsigned int \fBmmap_addr\fP"
.br
.ti -1c
.RI "unsigned int \fBdrives_length\fP"
.br
.ti -1c
.RI "unsigned int \fBdrives_addr\fP"
.br
.ti -1c
.RI "unsigned int \fBconfig_table\fP"
.br
.ti -1c
.RI "unsigned int \fBboot_loader_name\fP"
.br
.ti -1c
.RI "unsigned int \fBapm_table\fP"
.br
.ti -1c
.RI "unsigned int \fBvbe_control_info\fP"
.br
.ti -1c
.RI "vesaModeInfo * \fBvbe_mode_info\fP"
.br
.ti -1c
.RI "\fBvesaInfo\fP * \fBvbe_mode\fP"
.br
.ti -1c
.RI "unsigned int \fBvbe_interface_seg\fP"
.br
.ti -1c
.RI "unsigned int \fBvbe_interface_off\fP"
.br
.ti -1c
.RI "unsigned int \fBvbe_interface_len\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 64 del file grub\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "unsigned int BootInfo_t::addr"

.PP
Definizione alla linea 74 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::apm_table"

.PP
Definizione alla linea 82 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::boot_device"

.PP
Definizione alla linea 68 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::boot_loader_name"

.PP
Definizione alla linea 81 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::cmdline"

.PP
Definizione alla linea 69 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::config_table"

.PP
Definizione alla linea 80 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::drives_addr"

.PP
Definizione alla linea 79 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::drives_length"

.PP
Definizione alla linea 78 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::flags"

.PP
Definizione alla linea 65 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::mem_lower"

.PP
Definizione alla linea 66 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::mem_upper"

.PP
Definizione alla linea 67 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::mmap_addr"

.PP
Definizione alla linea 77 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::mmap_length"

.PP
Definizione alla linea 76 del file grub\&.h\&.
.SS "unsigned int** BootInfo_t::mods_addr"

.PP
Definizione alla linea 71 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::mods_count"

.PP
Definizione alla linea 70 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::num"

.PP
Definizione alla linea 72 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::shndx"

.PP
Definizione alla linea 75 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::size"

.PP
Definizione alla linea 73 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::vbe_control_info"

.PP
Definizione alla linea 83 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::vbe_interface_len"

.PP
Definizione alla linea 88 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::vbe_interface_off"

.PP
Definizione alla linea 87 del file grub\&.h\&.
.SS "unsigned int BootInfo_t::vbe_interface_seg"

.PP
Definizione alla linea 86 del file grub\&.h\&.
.SS "\fBvesaInfo\fP* BootInfo_t::vbe_mode"

.PP
Definizione alla linea 85 del file grub\&.h\&.
.SS "vesaModeInfo* BootInfo_t::vbe_mode_info"

.PP
Definizione alla linea 84 del file grub\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
