.TH "BootInfo_t" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BootInfo_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grub\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.ti -1c
.RI "unsigned int \fBmem_lower\fP"
.br
.ti -1c
.RI "unsigned int \fBmem_upper\fP"
.br
.ti -1c
.RI "unsigned int \fBboot_device\fP"
.br
.ti -1c
.RI "unsigned int \fBcmdline\fP"
.br
.ti -1c
.RI "unsigned int \fBmods_count\fP"
.br
.ti -1c
.RI "unsigned int ** \fBmods_addr\fP"
.br
.ti -1c
.RI "unsigned int \fBnum\fP"
.br
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.ti -1c
.RI "unsigned int \fBaddr\fP"
.br
.ti -1c
.RI "unsigned int \fBshndx\fP"
.br
.ti -1c
.RI "unsigned int \fBmmap_length\fP"
.br
.ti -1c
.RI "unsigned int \fBmmap_addr\fP"
.br
.ti -1c
.RI "unsigned int \fBdrives_length\fP"
.br
.ti -1c
.RI "unsigned int \fBdrives_addr\fP"
.br
.ti -1c
.RI "unsigned int \fBconfig_table\fP"
.br
.ti -1c
.RI "unsigned int \fBboot_loader_name\fP"
.br
.ti -1c
.RI "unsigned int \fBapm_table\fP"
.br
.ti -1c
.RI "unsigned int \fBvbe_control_info\fP"
.br
.ti -1c
.RI "vesaModeInfo * \fBvbe_mode_info\fP"
.br
.ti -1c
.RI "\fBvesaInfo\fP * \fBvbe_mode\fP"
.br
.ti -1c
.RI "unsigned int \fBvbe_interface_seg\fP"
.br
.ti -1c
.RI "unsigned int \fBvbe_interface_off\fP"
.br
.ti -1c
.RI "unsigned int \fBvbe_interface_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file grub\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int BootInfo_t::addr"

.PP
Definition at line 74 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::apm_table"

.PP
Definition at line 82 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::boot_device"

.PP
Definition at line 68 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::boot_loader_name"

.PP
Definition at line 81 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::cmdline"

.PP
Definition at line 69 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::config_table"

.PP
Definition at line 80 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::drives_addr"

.PP
Definition at line 79 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::drives_length"

.PP
Definition at line 78 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::flags"

.PP
Definition at line 65 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::mem_lower"

.PP
Definition at line 66 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::mem_upper"

.PP
Definition at line 67 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::mmap_addr"

.PP
Definition at line 77 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::mmap_length"

.PP
Definition at line 76 of file grub\&.h\&.
.SS "unsigned int** BootInfo_t::mods_addr"

.PP
Definition at line 71 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::mods_count"

.PP
Definition at line 70 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::num"

.PP
Definition at line 72 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::shndx"

.PP
Definition at line 75 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::size"

.PP
Definition at line 73 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::vbe_control_info"

.PP
Definition at line 83 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::vbe_interface_len"

.PP
Definition at line 88 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::vbe_interface_off"

.PP
Definition at line 87 of file grub\&.h\&.
.SS "unsigned int BootInfo_t::vbe_interface_seg"

.PP
Definition at line 86 of file grub\&.h\&.
.SS "\fBvesaInfo\fP* BootInfo_t::vbe_mode"

.PP
Definition at line 85 of file grub\&.h\&.
.SS "vesaModeInfo* BootInfo_t::vbe_mode_info"

.PP
Definition at line 84 of file grub\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
