src/bufio.c
NAME
src/bufio.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/list.h>
#include <aplus/spinlock.h>
#include <aplus/mm.h>
#include <aplus/bufio.h>
#include <aplus/task.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
#include <stdio.h>
Functions
int bufio_init ()
BufIO initialization.
void bufio_free_unused ()
Free al unused buffers.
bufio_t * bufio_alloc (size_t size)
Alloc new buffer for current task.
bufio_t * bufio_alloc_raw (void *raw, size_t size)
Create new buffer from allocated data for current task.
void bufio_free (bufio_t *buf)
Free and remove buffer.
int bufio_seek (bufio_t *buf, off_t offset, int dir)
Sets the position indicator associated with the bufio descriptor to a new position.
int bufio_tell (bufio_t *buf)
Returns the current value of the position indicator of the stream.
. "
void bufio_clear (bufio_t *buf)
Clear entire stream of the buffer descriptor.
int bufio_read (bufio_t *buf, void *ptr, size_t len)
This function shall attempt to read nbyte bytes from the stream associated with the bufio descriptor, buf, into the buffer pointed to by ptr.
int bufio_write (bufio_t *buf, void *ptr, size_t len)
This function shall attempt to write nbyte bytes into the stream associated with the bufio descriptor, buf, from the buffer pointed to by ptr.
Variables
static list_t * list_buffers
List of allocated buffers.
static uint64_t buffers_length
Allocated RAM of all buffers.
task_t * current_task
Current task address.
Function Documentation
bufio_t* bufio_alloc (size_tsize)
Alloc new buffer for current task.
Parameters:
size Size in Bytes of data.
Returns:
bufio descriptor.
Definition at line 63 of file bufio.c.
References buffers_length, current_task, kmalloc(), list_add(), lock, bufio::offset, bufio::raw, bufio::size, size, bufio::task, bufio::type, and unlock.
                                  {
    void* addr = (void*) kmalloc(size);
    if(!addr)
        return 0;
        
    lock();
    buffers_length += size;
    bufio_t* buf = (bufio_t*) kmalloc(size);
    buf->raw = addr;
    buf->size = size;
    buf->type = 0;
    buf->offset = (off_t) 0;
    buf->task = current_task;
    list_add(list_buffers, (listval_t) buf);
    unlock();
    return buf;
}
bufio_t* bufio_alloc_raw (void *raw, size_tsize)
Create new buffer from allocated data for current task.
Parameters:
raw Buffer allocated address.
size Size in Bytes of data.
Returns:
bufio descriptor.
Definition at line 92 of file bufio.c.
References buffers_length, current_task, kmalloc(), list_add(), lock, bufio::offset, bufio::raw, bufio::size, size, bufio::task, bufio::type, and unlock.
                                                 {
    if(!raw)
        return 0;
    lock();
    buffers_length += size;
    bufio_t* buf = (bufio_t*) kmalloc(size);
    buf->raw = raw;
    buf->size = size;
    buf->type = 0;
    buf->offset = (off_t) 0;
    buf->task = current_task;
    
    list_add(list_buffers, (listval_t) buf);
    unlock();
    
    return buf;
}
void bufio_clear (bufio_t *buf)
Clear entire stream of the buffer descriptor.
Parameters:
buf Pointer to a bufio descriptor.
Definition at line 186 of file bufio.c.
References bufio::lock, bufio::raw, bufio::size, spinlock_lock(), and spinlock_unlock().
                               {
    spinlock_lock(&buf->lock);
    memset(buf->raw, 0, buf->size);
    spinlock_unlock(&buf->lock);
}
void bufio_free (bufio_t *buf)
Free and remove buffer.
Parameters:
buf bufio descriptor.
Definition at line 118 of file bufio.c.
References buffers_length, kfree(), list_remove(), lock, bufio::raw, bufio::size, and unlock.
                              {
    lock();
    buffers_length -= buf->size;
    
    kfree(buf->raw);
    kfree(buf);
    
    list_remove(list_buffers, (listval_t) buf);
    
    
    unlock();
}
void bufio_free_unused ()
Free al unused buffers.
Definition at line 41 of file bufio.c.
References list_clone(), list_destroy, list_foreach, list_init, and value.
                         {
    list_t* tmp;
    list_init(tmp);
    list_clone(tmp, list_buffers);
    
    list_foreach(value, tmp) {
        //bufio_t* value = (bufio_t*) value;
        
        //if(value->task->state == TASK_STATE_DEAD)
        // bufio_free(value);
    }
    
    list_destroy(tmp);
}
int bufio_init ()
BufIO initialization.
Definition at line 31 of file bufio.c.
References list_init.
                 {
    list_init(list_buffers);
    
    return 0;
}
int bufio_read (bufio_t *buf, void *ptr, size_tlen)
This function shall attempt to read nbyte bytes from the stream associated with the bufio descriptor, buf, into the buffer pointed to by ptr.
Parameters:
buf Pointer to a bufio descriptor.
ptr Pointer to output buffer.
len Size of data to read.
Returns:
Upon successful completion, shall return a non-negative integer indicating the number of bytes actually read.
 Otherwise, the functions shall return -1 and set errno to indicate the error.
Definition at line 203 of file bufio.c.
References bufio::lock, bufio::offset, bufio::raw, bufio::size, spinlock_lock(), and spinlock_unlock().
                                                    {
    spinlock_lock(&buf->lock);
    
    len = (len + buf->offset > buf->size) ? (buf->size - buf->offset) : len;
    memcpy(ptr, (void*) ((off_t) buf->raw + buf->offset), len);
    
    buf->offset += (off_t) len;
    
    spinlock_unlock(&buf->lock);
    
    return (int) len;
}
int bufio_seek (bufio_t *buf, off_toffset, intdir)
Sets the position indicator associated with the bufio descriptor to a new position.
Parameters:
buf Pointer to a bufio descriptor.
offset Number of bytes to offset from dir.
dir Position used as reference for the offset
SEEK_SET: Beginning of stream.
SEEK_CUR: Current position of stream.
SEEK_END: End of stream.
Returns:
If successful return current position of stream, otherwise, it returns non-zero value.
Definition at line 142 of file bufio.c.
References bufio::offset, offset, and bufio::size.
                                                    {
    if(offset > buf->size)
        return -1;
        
    if(dir == SEEK_CUR && (offset + buf->offset) > buf->size)
        return -1;
    switch(dir) {
        case SEEK_SET:
            buf->offset = offset;
            break;
            
        case SEEK_END:
            buf->offset = buf->offset - offset;
            break;
            
        case SEEK_CUR:
            buf->offset += offset;
            break;
            
        default:
            return -1;
    }
    
    return buf->offset;
}
int bufio_tell (bufio_t *buf)
Returns the current value of the position indicator of the stream.
.
Parameters:
buf Pointer to a bufio descriptor.
Returns:
On success, the current value of the position indicator is returned.
 On failure, -1L is returned.
Definition at line 177 of file bufio.c.
References bufio_seek().
                             {
    return bufio_seek(buf, 0, SEEK_CUR);
}
int bufio_write (bufio_t *buf, void *ptr, size_tlen)
This function shall attempt to write nbyte bytes into the stream associated with the bufio descriptor, buf, from the buffer pointed to by ptr.
Parameters:
buf Pointer to a bufio descriptor.
ptr Pointer to input buffer.
len Size of data to write.
Returns:
Upon successful completion, shall return a non-negative integer indicating the number of bytes actually write.
 Otherwise, the functions shall return -1 and set errno to indicate the error.
Definition at line 227 of file bufio.c.
References bufio::lock, bufio::offset, bufio::raw, bufio::size, spinlock_lock(), and spinlock_unlock().
                                                     {
    
    spinlock_lock(&buf->lock);
    
    len = (len + buf->offset > buf->size) ? (buf->size - buf->offset) : len;
    memcpy((void*) ((off_t) buf->raw + buf->offset), ptr, len);
    
    buf->offset += (off_t) len;
    
    spinlock_unlock(&buf->lock);
    
    return (int) len;
}
Variable Documentation
uint64_t buffers_length [static]
Allocated RAM of all buffers.
Definition at line 23 of file bufio.c.
task_t* current_task
Current task address.
Definition at line 35 of file sched.c.
list_t* list_buffers [static]
List of allocated buffers.
Definition at line 18 of file bufio.c.
Author
Generated automatically by Doxygen for aPlus from the source code.