.TH "bufio" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bufio \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bufio\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "void * \fBraw\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "off_t \fBoffset\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBspinlock_t\fP \fBlock\fP"
.br
.ti -1c
.RI "\fBtask_t\fP * \fBtask\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 32 del file bufio\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "\fBspinlock_t\fP bufio::lock"

.PP
Definizione alla linea 37 del file bufio\&.h\&.
.SS "off_t bufio::offset"

.PP
Definizione alla linea 35 del file bufio\&.h\&.
.SS "void* bufio::raw"

.PP
Definizione alla linea 33 del file bufio\&.h\&.
.SS "size_t bufio::size"

.PP
Definizione alla linea 34 del file bufio\&.h\&.
.SS "\fBtask_t\fP* bufio::task"

.PP
Definizione alla linea 38 del file bufio\&.h\&.
.SS "\fBuint32_t\fP bufio::type"

.PP
Definizione alla linea 36 del file bufio\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
