src/syscall/chown.c
NAME
src/syscall/chown.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/syscall.h>
#include <aplus/task.h>
#include <aplus/fs.h>
#include <errno.h>
#include <unistd.h>
#include <fcntl.h>
Functions
int sys_chown (char *filename, uid_t owner, gid_t group)
Changes the ownership of the file specified by pathname, which is dereferenced if it is a symbolic link.
SYSCALL (sys_chown, 21)
Variables
task_t * current_task
Current task address.
Function Documentation
int sys_chown (char *filename, uid_towner, gid_tgroup)
Changes the ownership of the file specified by pathname, which is dereferenced if it is a symbolic link.
Parameters:
filename
owner
group
Returns:
On success, zero is returned. On error, −1 is returned, and errno is set appropriately.
Definition at line 21 of file chown.c.
References errno, task::fd, fs_chown(), im_superuser(), kprintf(), and sys_open().
                                                        {
    if(!im_superuser()) {
        kprintf("sys_chown: only superuser allow to use this function.");
        
        errno = EACCES;
        return -1;
    }
    
    
    int fd = sys_open(filename, O_RDONLY, 0644);
    if(fd < 0)
        return -1;
    
    
    inode_t* ino = current_task->fd[fd];
    return fs_chown(ino, owner, group);
}
SYSCALL (sys_chown, 21)
Variable Documentation
task_t* current_task
Current task address.
Definition at line 37 of file sched.c.
Author
Generated automatically by Doxygen for aPlus from the source code.