.TH "usr/src/libcrt0/src/crt0.c" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libcrt0/src/crt0.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'syscalls\&.c'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int, char **, char **)"
.br
.ti -1c
.RI "int \fB__sigtramp\fP (int sig)"
.br
.ti -1c
.RI "static int \fB__default_sighandler__\fP (int sig)"
.br
.ti -1c
.RI "static void \fB__init_traps\fP ()"
.br
.ti -1c
.RI "\fB__attribute__\fP ((noreturn))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char ** \fBenviron\fP"
.br
.ti -1c
.RI "int \fB__bss_start\fP"
.br
.ti -1c
.RI "int \fB_end\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "__attribute__ ((noreturn))"

.PP
Definition at line 61 of file crt0\&.c\&.
.PP
References __bss_start, __init_traps(), __sigtramp(), _end, environ, and main()\&.
.PP
.nf
62               {
63     
64     int i;
65     for(i = (int) &__bss_start; i < (int) &_end; i++)
66         *(char*) i = 0;
67 
68 
69     environ = (char**) __get_envp();
70     char** argv = (char**) __get_argv();
71 
72     int argc = 0;
73 
74     if(argv)
75         while(argv[argc])
76             argc += 1;
77 
78 
79     open("/dev/stdin", 0, 0644);
80     open("/dev/stdout", 0, 0644);
81     open("/dev/stderr", 0, 0644);
82 
83 
84 
85     __install_sighandler(__sigtramp);
86     _init_signal();
87     __init_traps();
88 
89 #if 0
90     atexit(__do_global_dtors);
91     __do_global_ctors();
92 #endif
93 
94     exit(main(argc, argv, environ));
95 }
.fi
.SS "static int __default_sighandler__ (intsig)\fC [static]\fP"

.PP
Definition at line 17 of file crt0\&.c\&.
.PP
.nf
17                                            {
18     signal(sig, __default_sighandler__);
19     _exit(sig);
20 }
.fi
.SS "static void __init_traps ()\fC [static]\fP"

.PP
Definition at line 51 of file crt0\&.c\&.
.PP
References __default_sighandler__()\&.
.PP
.nf
51                            {
52     signal(SIGABRT, __default_sighandler__);
53     signal(SIGFPE, __default_sighandler__);
54     signal(SIGILL, __default_sighandler__);
55     signal(SIGINT, __default_sighandler__);
56     signal(SIGSEGV, __default_sighandler__);
57     signal(SIGTERM, __default_sighandler__);
58 }
.fi
.SS "int __sigtramp (intsig)"

.SS "int main (int, char **, char **)"

.SH "Variable Documentation"
.PP 
.SS "int __bss_start"

.SS "int _end"

.SS "char** environ"

.PP
Definition at line 3 of file environ\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
