usr/src/libcrt0/src/crt0.c
NAME
usr/src/libcrt0/src/crt0.c -
SYNOPSIS
#include 'syscalls.c'
#include <stdlib.h>
#include <signal.h>
Functions
int main (int, char **, char **)
int __sigtramp (int sig)
static int __default_sighandler__ (int sig)
static void __init_traps ()
__attribute__ ((noreturn))
Variables
char ** environ
int __bss_start
int _end
Function Documentation
__attribute__ ((noreturn))
Definition at line 61 of file crt0.c.
References __bss_start, __init_traps(), __sigtramp(), _end, environ, and main().
              {
    
    int i;
    for(i = (int) &__bss_start; i < (int) &_end; i++)
        *(char*) i = 0;
    environ = (char**) __get_envp();
    char** argv = (char**) __get_argv();
    int argc = 0;
    if(argv)
        while(argv[argc])
            argc += 1;
    open("/dev/stdin", 0, 0644);
    open("/dev/stdout", 0, 0644);
    open("/dev/stderr", 0, 0644);
    __install_sighandler(__sigtramp);
    _init_signal();
    __init_traps();
#if 0
    atexit(__do_global_dtors);
    __do_global_ctors();
#endif
    exit(main(argc, argv, environ));
}
static int __default_sighandler__ (intsig) [static]
Definition at line 17 of file crt0.c.
                                           {
    signal(sig, __default_sighandler__);
    _exit(sig);
}
static void __init_traps () [static]
Definition at line 51 of file crt0.c.
References __default_sighandler__().
                           {
    signal(SIGABRT, __default_sighandler__);
    signal(SIGFPE, __default_sighandler__);
    signal(SIGILL, __default_sighandler__);
    signal(SIGINT, __default_sighandler__);
    signal(SIGSEGV, __default_sighandler__);
    signal(SIGTERM, __default_sighandler__);
}
int __sigtramp (intsig)
int main (int, char **, char **)
Variable Documentation
int __bss_start
int _end
char** environ
Definition at line 3 of file environ.c.
Author
Generated automatically by Doxygen for aPlus from the source code.