src/debug.c
NAME
src/debug.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/spinlock.h>
Functions
void debug_putc (char ch)
Send a character to serial debug port.
void debug_puts (char *str)
Send a string to serial debug port.
static void print_dec (unsigned int value, unsigned int width, char *buf, int *ptr)
Print a number in base 10 into buffer.
static void print_hex (unsigned int value, unsigned int width, char *buf, int *ptr)
Print a number in base 16 into buffer.
size_t vasprintf (char *buf, const char *fmt, va_list args)
Print to allocated string.
The functions asprintf() and vasprintf() are analogs of sprintf(3) and vsprintf(3), except that they allocate a string large enough to hold the output including the terminating null byte, and return a pointer to it via the first argument. This pointer should be passed to free(3) to release the allocated storage when it is no longer needed. "
void kprintf (char *fmt,...)
Formatted output conversion and print to Debug Standard Output.
Function Documentation
void debug_putc (charch)
Send a character to serial debug port.
Parameters:
ch Character to send.
Definition at line 9 of file debug.c.
References serial_send().
                         {
    serial_send(0, ch);
}
void debug_puts (char *str)
Send a string to serial debug port.
Parameters:
str String to send.
See also:
debug_putc
Definition at line 19 of file debug.c.
References debug_putc(), lock, and unlock.
                           {
    lock();
    
    while(*str)
        debug_putc(*str++);
    
    unlock();
}
void kprintf (char *fmt, ...)
Formatted output conversion and print to Debug Standard Output.
Parameters:
fmt Format of string.
... Arguments.
Definition at line 167 of file debug.c.
References debug_puts(), and vasprintf().
                             {
    static char __kprintf_buf[1024];
    memset(__kprintf_buf, 0, 1024);
    
    va_list lst;
    va_start(lst, fmt);
    vasprintf(__kprintf_buf, fmt, lst);
    va_end(lst);
    
    debug_puts(__kprintf_buf);
}
static void print_dec (unsigned intvalue, unsigned intwidth, char *buf, int *ptr) [static]
Print a number in base 10 into buffer.
Parameters:
value Number to convert as string.
width Padding.
buf Buffer output.
ptr Size of returned string.
Definition at line 36 of file debug.c.
                                                                                    {
    unsigned int n_width = 1;
    unsigned int i = 9;
    while (value > i && i < UINT32_MAX) {
        n_width += 1;
        i *= 10;
        i += 9;
    }
    int printed = 0;
    while (n_width + printed < width) {
        buf[*ptr] = '0';
        *ptr += 1;
        printed += 1;
    }
    i = n_width;
    while (i > 0) {
        unsigned int n = value / 10;
        int r = value % 10;
        buf[*ptr + i - 1] = r + '0';
        i--;
        value = n;
    }
    *ptr += n_width;
}
static void print_hex (unsigned intvalue, unsigned intwidth, char *buf, int *ptr) [static]
Print a number in base 16 into buffer.
Parameters:
value Number to convert as string.
width Padding.
buf Buffer output.
ptr Size of returned string.
Definition at line 70 of file debug.c.
                                                                                   {
    int i = width;
    if (i == 0) i = 8;
    unsigned int n_width = 1;
    unsigned int j = 0x0F;
    while (value > j && j < UINT32_MAX) {
        n_width += 1;
        j *= 0x10;
        j += 0x0F;
    }
    while (i > (int)n_width) {
        buf[*ptr] = '0';
        *ptr += 1;
        i--;
    }
    i = (int)n_width;
    while (i-- > 0) {
        buf[*ptr] = "0123456789abcdef"[(value>>(i*4))&0xF];
        *ptr += + 1;
    }
}
size_t vasprintf (char *buf, const char *fmt, va_listargs)
Print to allocated string.
The functions asprintf() and vasprintf() are analogs of sprintf(3) and vsprintf(3), except that they allocate a string large enough to hold the output including the terminating null byte, and return a pointer to it via the first argument. This pointer should be passed to free(3) to release the allocated storage when it is no longer needed.
Parameters:
buf Output buffer just allocated.
fmt Format of string.
args Arguments.
Returns:
When successful, these functions return the number of bytes printed, just like sprintf(3). If memory allocation wasn't possible, or some other error occurs, these functions will return -1, and the contents of strp is undefined.
Definition at line 110 of file debug.c.
References print_dec(), and print_hex().
                                                            {
    int i = 0;
    char *s;
    int ptr = 0;
    int len = strlen(fmt);
    for ( ; i < len && fmt[i]; ++i) {
        if (fmt[i] != '%') {
            buf[ptr++] = fmt[i];
            continue;
        }
        ++i;
        unsigned int arg_width = 0;
        while (fmt[i] >= '0' && fmt[i] <= '9') {
            arg_width *= 10;
            arg_width += fmt[i] - '0';
            ++i;
        }
        /* fmt[i] == '%' */
        switch (fmt[i]) {
            case 's': /* String pointer -> String */
                s = (char *)va_arg(args, char *);
                if (s == NULL) {
                    s = "(null)";
                }
                while (*s) {
                    buf[ptr++] = *s++;
                }
                break;
            case 'c': /* Single character */
                buf[ptr++] = (char)va_arg(args, int);
                break;
            case 'x': /* Hexadecimal number */
                print_hex((unsigned long)va_arg(args, unsigned long), arg_width, buf, &ptr);
                break;
            case 'd': /* Decimal number */
                print_dec((unsigned long)va_arg(args, unsigned long), arg_width, buf, &ptr);
                break;
            case '%': /* Escape */
                buf[ptr++] = '%';
                break;
            default: /* Nothing at all, just dump it */
                buf[ptr++] = fmt[i];
                break;
        }
    }
    /* Ensure the buffer ends in a null */
    buf[ptr] = '\0';
    return ptr;
}
Author
Generated automatically by Doxygen for aPlus from the source code.