src/arch/i386/desc.c
NAME
src/arch/i386/desc.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/spinlock.h>
#include <aplus/mm.h>
#include <grub.h>
#include <stdint.h>
#include <errno.h>
#include <time.h>
#include <sys/times.h>
Data Structures
struct gdt_entry
Macros
#define FAULT_MASK 0x3FFFFFE3
#define PIT_FREQ (CLOCKS_PER_SEC)
#define gdt_set(n, b, l, a, g)
#define idt_set(i, b, s, f)
#define _i(n)
#define _i(n)
#define BCD2BIN(bcd) ((((bcd) & 0x0F) + ((bcd) / 16) * 10))
#define BCD2BIN2(bcd) (((((bcd) & 0x0F) + ((bcd & 0x70) / 16) * 10)) | (bcd & 0x80))
Functions
struct gdt_entry __attribute__ ((packed))
void schedule ()
Perform a scheduling and check TTL (Time To Live) for current task.
void syscall_handler (regs_t *)
__asm__ ('.section .text		\n\
	.global gdt_load	\n\
	gdt_load:			\n\
	lgdt [gdt_p]		\n\
						\n\
	mov ax, 0x10		\n\
	mov ds, ax			\n\
	mov es, ax			\n\
	mov fs, ax			\n\
	mov gs, ax			\n\
	mov ss, ax			\n\
	jmp 0x08:.done		\n\
						\n\
	.done:				\n\
	ret					\n\
						\n\
						\n\
						\n\
						\n\
	.global idt_load	\n\
	idt_load:			\n\
	lidt [idt_p]		\n\
	ret					\n\
						\n\
						\n')"
void isr_handler (regs_t *r)
void irq_handler (regs_t *r)
void pit_handler (regs_t *r)
void pagefault_handler (regs_t *r)
int desc_init ()
int irq_set (int n, void *handler)
int irq_unset (int n)
void * irq_get (int n)
static uint8_t rtc (uint8_t addr)
uint32_t pit_gettime ()
uint32_t pit_getticks ()
Variables
uint16_t limit_l
uint16_t base_l
uint8_t base_m
uint8_t access
uint8_t granularity
uint8_t base_h
static void * irqs [16] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
static gdt_entry_t gdt_e [5]
static gdt_ptr_t gdt_p
static idt_entry_t idt_e [256]
static idt_ptr_t idt_p
static uint32_t pit_ticks
static uint32_t pit_seconds
static uint32_t pit_days
uint8_t keyboard_ready = 0
Macro Definition Documentation
#define _i(n)
Value:
extern void isr##n(); \
		idt_set(n, (uint32_t)isr##n, 0x08, 0x8E)
#define _i(n)
Value:
extern void irq##n(); \
		idt_set(n + 32, (uint32_t)irq##n, 0x08, 0x8E)
#define BCD2BIN(bcd) ((((bcd) & 0x0F) + ((bcd) / 16) * 10))
#define BCD2BIN2(bcd) (((((bcd) & 0x0F) + ((bcd & 0x70) / 16) * 10)) | (bcd & 0x80))
#define FAULT_MASK 0x3FFFFFE3
Definition at line 37 of file desc.c.
#define gdt_set(n, b, l, a, g)
Value:
gdt_e[n].base_l = (b & 0xFFFF); \
		gdt_e[n].base_m = (b >> 16) & 0xFF; \
		gdt_e[n].base_h = (b >> 24) & 0xFF; \
		gdt_e[n].limit_l = (l & 0xFFFF); \
		gdt_e[n].granularity = (l >> 16) & 0x0F; \
		gdt_e[n].granularity |= g & 0xF0; \
		gdt_e[n].access = a
#define idt_set(i, b, s, f)
Value:
idt_e[i].base_l = b & 0xFFFF; \
		idt_e[i].base_h = (b >> 16) & 0xFFFF; \
		idt_e[i].sel = s; \
		idt_e[i].null = 0; \
		idt_e[i].flags = f
#define PIT_FREQ (CLOCKS_PER_SEC)
Definition at line 38 of file desc.c.
Function Documentation
__asm__ ('.section .text \n\ .global gdt_load \n\ gdt_load: \n\ lgdt \n\ \n\ movax[gdt_p], 0x10\n\movds, ax\n\moves, ax\n\movfs, ax\n\movgs, ax\n\movss, ax\n\jmp 0x08:.done\n\\n\.done:\n\ret\n\\n\\n\\n\\n\.global idt_load\n\idt_load:\n\lidt\n\ret\n\\n\\n'[idt_p])
struct gdt_entry __attribute__ ((packed))
Definition at line 44 of file desc.c.
                       {
    uint16_t limit;
    uint32_t base;
} __attribute__((packed)) gdt_ptr_t;
int desc_init ()
Definition at line 195 of file desc.c.
References __asm__(), _i, gdt_set, irq_set(), PIT_FREQ, pit_handler(), uint32_t, and uint8_t.
                {
    __asm__ ("cli");
    
    #define gdt_set(n, b, l, a, g) \
        gdt_e[n].base_l = (b & 0xFFFF); \
        gdt_e[n].base_m = (b >> 16) & 0xFF; \
        gdt_e[n].base_h = (b >> 24) & 0xFF; \
        gdt_e[n].limit_l = (l & 0xFFFF); \
        gdt_e[n].granularity = (l >> 16) & 0x0F; \
        gdt_e[n].granularity |= g & 0xF0; \
        gdt_e[n].access = a
                
    
    memset(&gdt_e, 0, sizeof(gdt_entry_t) * 5);
        
    gdt_p.limit = sizeof(gdt_entry_t) * 5 - 1;
    gdt_p.base = (uint32_t) gdt_e;
        
    gdt_set(0, 0, 0, 0, 0);
    gdt_set(1, 0, 0xFFFFFFFF, 0x9A, 0xCF);
    gdt_set(2, 0, 0xFFFFFFFF, 0x92, 0xCF);
    gdt_set(3, 0, 0xFFFFFFFF, 0xFA, 0xCF);
    gdt_set(4, 0, 0xFFFFFFFF, 0XF2, 0xCF);
    
    gdt_load();
    
    
    idt_p.limit = sizeof(idt_entry_t) * 256 - 1;
    idt_p.base = (uint32_t) idt_e;
    
    memset(idt_e, 0, sizeof(idt_entry_t) * 256);
    
    
    #define idt_set(i, b, s, f) \
        idt_e[i].base_l = b & 0xFFFF; \
        idt_e[i].base_h = (b >> 16) & 0xFFFF; \
        idt_e[i].sel = s; \
        idt_e[i].null = 0; \
        idt_e[i].flags = f
    
    
    #define _i(n) \
        extern void isr##n(); \
        idt_set(n, (uint32_t)isr##n, 0x08, 0x8E)
        
    _i(0);
    _i(1);
    _i(2);
    _i(3);
    _i(4);
    _i(5);
    _i(6);
    _i(7);
    _i(8);
    _i(9);
    _i(10);
    _i(11);
    _i(12);
    _i(13);
    _i(14);
    _i(15);
    _i(16);
    _i(17);
    _i(18);
    _i(19);
    _i(20);
    _i(21);
    _i(22);
    _i(23);
    _i(24);
    _i(25);
    _i(26);
    _i(27);
    _i(28);
    _i(29);
    _i(30);
    _i(31);
    _i(0x80);
    
    idt_load();
    
    #ifdef _i
    #undef _i
    #endif
    
    #define _i(n) \
        extern void irq##n(); \
        idt_set(n + 32, (uint32_t)irq##n, 0x08, 0x8E)
        
    
    outb(0x20, 0x11);
    outb(0xA0, 0x11);
    outb(0x21, 0x20);
    outb(0xA1, 0x28);
    outb(0x21, 0x04);
    outb(0xA1, 0x02);
    outb(0x21, 0x01);
    outb(0xA1, 0x01);
    outb(0x21, 0x00);
    outb(0xA1, 0x00);
    
    _i(0);
    _i(1);
    _i(2);
    _i(3);
    _i(4);
    _i(5);
    _i(6);
    _i(7);
    _i(8);
    _i(9);
    _i(10);
    _i(11);
    _i(12);
    _i(13);
    _i(14);
    _i(15);
    
    
    uint32_t freq = 1193180 / PIT_FREQ;
    outb(0x43, 0x36);
    outb(0x40, (uint8_t) (freq & 0xFF));
    outb(0x40, (uint8_t) ((freq >> 8) & 0xFF));
    
    irq_set(0, (void*) pit_handler);
    
    __asm__ ("sti");
    return 0;
}
void* irq_get (intn)
Definition at line 354 of file desc.c.
References errno.
                     {
    if(n > 16) {
        errno = EINVAL;
        return NULL;
    }
    
    return irqs[n];
}
void irq_handler (regs_t *r)
Definition at line 155 of file desc.c.
                            {
    if(irqs[r->int_no - 32])
        ((void (*)(regs_t*)) irqs[r->int_no - 32]) (r);
    if(r->int_no >= 40)
        outb(0xA0, 0x20);
        
    outb(0x20, 0x20);
}
int irq_set (intn, void *handler)
Definition at line 334 of file desc.c.
References errno.
                                  {
    if(n > 16) {
        errno = EINVAL;
        return -1;
    }
    
    irqs[n] = handler;
    return 0;
}
int irq_unset (intn)
Definition at line 344 of file desc.c.
References errno.
                     {
    if(n > 16) {
        errno = EINVAL;
        return -1;
    }
    
    irqs[n] = 0;
    return 0;
}
void isr_handler (regs_t *r)
Definition at line 151 of file desc.c.
References panic_r().
                            {
    panic_r(exception_messages[r->int_no], r);
}
void pagefault_handler (regs_t *r)
Definition at line 183 of file desc.c.
References __asm__(), kprintf(), panic_r(), and uint32_t.
                                  {
    uint32_t faultaddr;
    __asm__ __volatile__("mov eax, cr2" : "=a"(faultaddr));
    kprintf("Page fault at address: 0x%x\n", faultaddr);
    panic_r("Page Fault", r);
}
uint32_t pit_getticks ()
Definition at line 393 of file desc.c.
                        {
    return ((pit_days * 86400) * 1000) + (pit_seconds * 1000) + pit_ticks;
}
uint32_t pit_gettime ()
Definition at line 373 of file desc.c.
References BCD2BIN, BCD2BIN2, rtc(), and uint32_t.
                       {
    #define BCD2BIN(bcd) ((((bcd) & 0x0F) + ((bcd) / 16) * 10))
    #define BCD2BIN2(bcd) (((((bcd) & 0x0F) + ((bcd & 0x70) / 16) * 10)) | (bcd & 0x80))
    
    static struct tm t;
    t.tm_sec = BCD2BIN(rtc(0));
    t.tm_min = BCD2BIN(rtc(2));
    t.tm_hour = BCD2BIN2(rtc(4)) + 2;
    t.tm_mday = BCD2BIN(rtc(7));
    t.tm_mon = BCD2BIN(rtc(8)) - 1;
    t.tm_year = (BCD2BIN(rtc(9)) + 100);
    t.tm_wday = 0;
    t.tm_yday = 0;
    t.tm_isdst = 0;
    
    return (uint32_t) mktime(&t);
}
void pit_handler (regs_t *r)
Definition at line 166 of file desc.c.
References PIT_FREQ, and schedule().
                            {
    pit_ticks += (1000 / PIT_FREQ);
    
    if(pit_ticks >= 1000) {
        pit_ticks = 0;
        pit_seconds += 1;
    }
    
    if(pit_seconds >= 86400) {
        pit_seconds = 0;
        pit_days += 1;
    }
    
    schedule();
}
static uint8_t rtc (uint8_taddr) [static]
Definition at line 365 of file desc.c.
References __asm__(), and uint8_t.
                                 {
    outb(0x70, addr);
    
    uint8_t r = 0;
    __asm__("inb 0x71" : "=a"(r));
    return r;
}
void schedule ()
Perform a scheduling and check TTL (Time To Live) for current task.
Definition at line 153 of file sched.c.
References task::clock, list_empty(), task::priority, sched_enabled, schedule_next(), schedule_signal(), task::signal_sig, and task_switch().
                {
    if(sched_enabled == 0)
        return;
        
    if(list_empty(task_queue))
        return;
    if(current_task->signal_sig)
        schedule_signal(current_task, current_task->signal_sig);
    current_task->clock += 1;
    
    if(current_task->clock % current_task->priority)
        return;
    
    task_switch(schedule_next());
}
void syscall_handler (regs_t *)
Definition at line 95 of file syscall.c.
References syscall_invoke().
                               {
    return syscall_invoke(r->eax, r->ebx, r->ecx, r->edx, r->esi, r->edi);
}
Variable Documentation
uint8_t access
Definition at line 6 of file desc.c.
uint8_t base_h
Definition at line 6 of file desc.c.
uint16_t base_l
Definition at line 5 of file desc.c.
uint8_t base_m
Definition at line 6 of file desc.c.
gdt_entry_t gdt_e[5] [static]
Definition at line 104 of file desc.c.
gdt_ptr_t gdt_p [static]
Definition at line 105 of file desc.c.
uint8_t granularity
Definition at line 6 of file desc.c.
idt_entry_t idt_e[256] [static]
Definition at line 107 of file desc.c.
idt_ptr_t idt_p [static]
Definition at line 108 of file desc.c.
void* irqs[16] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } [static]
Definition at line 102 of file desc.c.
uint8_t keyboard_ready = 0
Definition at line 115 of file desc.c.
uint16_t limit_l
Definition at line 5 of file desc.c.
uint32_t pit_days [static]
Definition at line 113 of file desc.c.
uint32_t pit_seconds [static]
Definition at line 112 of file desc.c.
uint32_t pit_ticks [static]
Definition at line 111 of file desc.c.
Author
Generated automatically by Doxygen for aPlus from the source code.