src/fs/devfs.c
NAME
src/fs/devfs.c -
SYNOPSIS
#include <stdint.h>
#include <stddef.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <dirent.h>
#include <errno.h>
#include <aplus.h>
#include <aplus/task.h>
Functions
inode_t * devfs_getdevice (dev_t dev)
struct inode * devfs_creat (struct inode *inode, char *name, mode_t mode)
inode_t * devfs_mount ()
Variables
inode_t * vfs_root
task_t * current_task
Current task address.
inode_t * devfs
Function Documentation
struct inode* devfs_creat (struct inode *inode, char *name, mode_tmode)
Definition at line 35 of file devfs.c.
References inode::atime, inode::chown, inode::creat, inode::ctime, inode::dev, inode::finddir, inode::flush, inode::gid, task::gid, inode::ino, inode::ioctl, kmalloc(), inode::link, inode::mode, inode::mtime, inode::name, inode::nlink, inode::parent, inode::rdev, inode::read, inode::readdir, inode::rename, inode::size, sys_time(), inode::uid, task::uid, inode::unlink, vfs_map(), vfs_mapped(), and inode::write.
                                                                         {
    if((void*) vfs_mapped(inode, name) != NULL)
        return NULL;
        
    inode_t* ino = (inode_t*) kmalloc(sizeof(inode_t));
    strcpy(ino->name, name);
    
    ino->dev = inode->dev;
    ino->ino = 0;
    ino->mode = mode;
    ino->nlink = 0;
    ino->uid = current_task->uid;
    ino->gid = current_task->gid;
    ino->rdev = ino->rdev;
    ino->size = (size_t) 0;
    ino->atime = ino->ctime = ino->mtime = sys_time(NULL);
    ino->parent = inode;
    ino->link = NULL;
    
    ino->read = NULL;
    ino->write = NULL;
    ino->readdir = NULL;
    ino->finddir = NULL;
    ino->creat = NULL;
    ino->rename = NULL;
    ino->unlink = NULL;
    ino->chown = NULL;
    ino->flush = NULL;
    ino->ioctl = NULL;
    
    vfs_map(ino);
    
    return ino;
}
inode_t* devfs_getdevice (dev_tdev)
Definition at line 23 of file devfs.c.
References inode::ino, and vfs_mapped_at_index().
                                    {
    int index = 0;
    inode_t* map = NULL;
    while((map = (inode_t*) vfs_mapped_at_index(devfs, index++)) != NULL)
        if(map->ino == dev)
            return map;
    
    return NULL;
}
inode_t* devfs_mount ()
Definition at line 71 of file devfs.c.
References inode::atime, inode::chown, inode::creat, inode::ctime, inode::dev, devfs, devfs_creat(), inode::finddir, inode::flush, inode::gid, GID_ROOT, inode::ino, inode::ioctl, kmalloc(), inode::link, inode::mode, inode::mtime, inode::name, inode::nlink, inode::parent, inode::rdev, inode::read, inode::readdir, inode::rename, inode::size, sys_time(), inode::uid, UID_ROOT, inode::unlink, vfs_root, and inode::write.
                       {
    
    devfs = (inode_t*) kmalloc(sizeof(inode_t));
    strcpy(devfs->name, "dev");
    
    devfs->dev = (dev_t) 0;
    devfs->ino = (ino_t) 0;
    devfs->mode = S_IFDIR;
    devfs->nlink = 0;
    devfs->uid = UID_ROOT;
    devfs->gid = GID_ROOT;
    devfs->rdev = (dev_t) 0;
    devfs->size = (size_t) 0;
    devfs->atime = devfs->ctime = devfs->mtime = sys_time(NULL);
    devfs->parent = vfs_root;
    devfs->link = NULL;
    
    devfs->read = NULL;
    devfs->write = NULL;
    devfs->readdir = NULL;
    devfs->finddir = NULL;
    devfs->creat = devfs_creat;
    devfs->rename = NULL;
    devfs->unlink = NULL;
    devfs->chown = NULL;
    devfs->flush = NULL;
    devfs->ioctl = NULL;
    
    return devfs;
}
Variable Documentation
task_t* current_task
Current task address.
Definition at line 35 of file sched.c.
inode_t* devfs
Definition at line 20 of file devfs.c.
inode_t* vfs_root
Definition at line 19 of file vfs.c.
Author
Generated automatically by Doxygen for aPlus from the source code.