.TH "elf32_shdr" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elf32_shdr \- 
.SH SYNOPSIS
.br
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_name\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_type\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_flags\fP"
.br
.ti -1c
.RI "\fBElf32_Addr\fP \fBsh_addr\fP"
.br
.ti -1c
.RI "\fBElf32_Off\fP \fBsh_offset\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_size\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_link\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_info\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_addralign\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_entsize\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 74 del file exec\&.c\&.
.SH "Documentazione dei campi"
.PP 
.SS "\fBElf32_Addr\fP elf32_shdr::sh_addr"

.PP
Definizione alla linea 78 del file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_addralign"

.PP
Definizione alla linea 83 del file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_entsize"

.PP
Definizione alla linea 84 del file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_flags"

.PP
Definizione alla linea 77 del file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_info"

.PP
Definizione alla linea 82 del file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_link"

.PP
Definizione alla linea 81 del file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_name"

.PP
Definizione alla linea 75 del file exec\&.c\&.
.SS "\fBElf32_Off\fP elf32_shdr::sh_offset"

.PP
Definizione alla linea 79 del file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_size"

.PP
Definizione alla linea 80 del file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_type"

.PP
Definizione alla linea 76 del file exec\&.c\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
