.TH "elf32_hdr" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elf32_hdr \- 
.PP
ELF32 Header\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBe_ident\fP [\fBEI_NIDENT\fP]"
.br
.ti -1c
.RI "\fBElf32_Half\fP \fBe_type\fP"
.br
.ti -1c
.RI "\fBElf32_Half\fP \fBe_machine\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBe_version\fP"
.br
.ti -1c
.RI "\fBElf32_Addr\fP \fBe_entry\fP"
.br
.ti -1c
.RI "\fBElf32_Off\fP \fBe_phoff\fP"
.br
.ti -1c
.RI "\fBElf32_Off\fP \fBe_shoff\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBe_flags\fP"
.br
.ti -1c
.RI "\fBElf32_Half\fP \fBe_ehsize\fP"
.br
.ti -1c
.RI "\fBElf32_Half\fP \fBe_phentsize\fP"
.br
.ti -1c
.RI "\fBElf32_Half\fP \fBe_phnum\fP"
.br
.ti -1c
.RI "\fBElf32_Half\fP \fBe_shentsize\fP"
.br
.ti -1c
.RI "\fBElf32_Half\fP \fBe_shnum\fP"
.br
.ti -1c
.RI "\fBElf32_Half\fP \fBe_shstrndx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ELF32 Header\&. 
.PP
Definition at line 64 of file exec\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBElf32_Half\fP elf32_hdr::e_ehsize"

.PP
Definition at line 73 of file exec\&.c\&.
.SS "\fBElf32_Addr\fP elf32_hdr::e_entry"

.PP
Definition at line 69 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_hdr::e_flags"

.PP
Definition at line 72 of file exec\&.c\&.
.SS "\fBuint8_t\fP elf32_hdr::e_ident[\fBEI_NIDENT\fP]"

.PP
Definition at line 65 of file exec\&.c\&.
.SS "\fBElf32_Half\fP elf32_hdr::e_machine"

.PP
Definition at line 67 of file exec\&.c\&.
.SS "\fBElf32_Half\fP elf32_hdr::e_phentsize"

.PP
Definition at line 74 of file exec\&.c\&.
.SS "\fBElf32_Half\fP elf32_hdr::e_phnum"

.PP
Definition at line 75 of file exec\&.c\&.
.SS "\fBElf32_Off\fP elf32_hdr::e_phoff"

.PP
Definition at line 70 of file exec\&.c\&.
.SS "\fBElf32_Half\fP elf32_hdr::e_shentsize"

.PP
Definition at line 76 of file exec\&.c\&.
.SS "\fBElf32_Half\fP elf32_hdr::e_shnum"

.PP
Definition at line 77 of file exec\&.c\&.
.SS "\fBElf32_Off\fP elf32_hdr::e_shoff"

.PP
Definition at line 71 of file exec\&.c\&.
.SS "\fBElf32_Half\fP elf32_hdr::e_shstrndx"

.PP
Definition at line 78 of file exec\&.c\&.
.SS "\fBElf32_Half\fP elf32_hdr::e_type"

.PP
Definition at line 66 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_hdr::e_version"

.PP
Definition at line 68 of file exec\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
