.TH "elf32_shdr" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elf32_shdr \- 
.PP
ELF32 Section Header\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_name\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_type\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_flags\fP"
.br
.ti -1c
.RI "\fBElf32_Addr\fP \fBsh_addr\fP"
.br
.ti -1c
.RI "\fBElf32_Off\fP \fBsh_offset\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_size\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_link\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_info\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_addralign\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBsh_entsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ELF32 Section Header\&. 
.PP
Definition at line 108 of file exec\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBElf32_Addr\fP elf32_shdr::sh_addr"

.PP
Definition at line 112 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_addralign"

.PP
Definition at line 117 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_entsize"

.PP
Definition at line 118 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_flags"

.PP
Definition at line 111 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_info"

.PP
Definition at line 116 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_link"

.PP
Definition at line 115 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_name"

.PP
Definition at line 109 of file exec\&.c\&.
.SS "\fBElf32_Off\fP elf32_shdr::sh_offset"

.PP
Definition at line 113 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_size"

.PP
Definition at line 114 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_shdr::sh_type"

.PP
Definition at line 110 of file exec\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
