.TH "elf32_phdr" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elf32_phdr \- 
.PP
ELF32 Program Header\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBElf32_Word\fP \fBp_type\fP"
.br
.ti -1c
.RI "\fBElf32_Off\fP \fBp_offset\fP"
.br
.ti -1c
.RI "\fBElf32_Addr\fP \fBp_vaddr\fP"
.br
.ti -1c
.RI "\fBElf32_Addr\fP \fBp_paddr\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBp_filesz\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBp_memsz\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBp_flags\fP"
.br
.ti -1c
.RI "\fBElf32_Word\fP \fBp_align\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ELF32 Program Header\&. 
.PP
Definition at line 115 of file exec\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBElf32_Word\fP elf32_phdr::p_align"

.PP
Definition at line 123 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_phdr::p_filesz"

.PP
Definition at line 120 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_phdr::p_flags"

.PP
Definition at line 122 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_phdr::p_memsz"

.PP
Definition at line 121 of file exec\&.c\&.
.SS "\fBElf32_Off\fP elf32_phdr::p_offset"

.PP
Definition at line 117 of file exec\&.c\&.
.SS "\fBElf32_Addr\fP elf32_phdr::p_paddr"

.PP
Definition at line 119 of file exec\&.c\&.
.SS "\fBElf32_Word\fP elf32_phdr::p_type"

.PP
Definition at line 116 of file exec\&.c\&.
.SS "\fBElf32_Addr\fP elf32_phdr::p_vaddr"

.PP
Definition at line 118 of file exec\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
