.TH "usr/src/libposix/src/environ.c" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/environ.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "static char * \fBp_environ\fP [] = { 0 }"
.br
.ti -1c
.RI "char ** \fBenviron\fP = \fBp_environ\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "char** environ = \fBp_environ\fP"

.PP
Definition at line 3 of file environ\&.c\&.
.SS "char* p_environ[] = { 0 }\fC [static]\fP"

.PP
Definition at line 2 of file environ\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
