.TH "usr/src/libposix/src/errno.c" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/errno.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBerrno\fP = 0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int errno = 0"

.PP
Definition at line 3 of file errno\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
