src/net/eth.c
NAME
src/net/eth.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/list.h>
#include <aplus/netif.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <aplus/net/eth.h>
Macros
#define __params netif, (void*) ((uint32_t) buf + sizeof(eth_header_t)), length - sizeof(eth_header_t)
Functions
int eth_recv (netif_t *netif, void *buf, size_t length)
static int eth_send_packet (netif_t *netif, void *buf, size_t length, int type)
int eth_send (netif_t *netif, void *buf, size_t length, int type)
Macro Definition Documentation
#define __params netif, (void*) ((uint32_t) buf + sizeof(eth_header_t)), length - sizeof(eth_header_t)
Function Documentation
int eth_recv (netif_t *netif, void *buf, size_tlength)
Definition at line 11 of file eth.c.
References __params, arp_recv(), ETH_TYPE_ARP, ETH_TYPE_IPV4, ETH_TYPE_IPV6, ipv4_recv(), ipv6_recv(), length, NETIF_ETH, netif_packets_add(), and netif_packets_create().
                                                       {
    eth_header_t* ethpkt = (eth_header_t*) buf;
    #define __params \
        netif, (void*) ((uint32_t) buf + sizeof(eth_header_t)), length - sizeof(eth_header_t)
    switch(ethpkt->type) {
        case ETH_TYPE_IPV4:
            if(ipv4_recv(__params) == 0)
                return 0;
            return length;
        case ETH_TYPE_IPV6:
            if(ipv6_recv(__params) == 0)
                return 0;
            return length;
        case ETH_TYPE_ARP:
            if(arp_recv(__params) == 0)
                return 0;
            return length;
    }
    /* ETH_TYPE_RAW */
    netif_packets_add (
        netif_packets_create (
                            netif,
                            NETIF_ETH,
                            length,
                            sizeof(eth_header_t),
                            buf
        )
    );
    return length;
}
int eth_send (netif_t *netif, void *buf, size_tlength, inttype)
Definition at line 79 of file eth.c.
References eth_send_packet(), length, netif::mtu, type, and uint32_t.
                                                                 {
    if(length + sizeof(eth_header_t) < netif->mtu) {
        if(eth_send_packet(netif, buf, length, type) > 0)
            return length;
        else
            return 0;
    }
    int delta = netif->mtu - sizeof(eth_header_t);
    int ret = 0;
    for(int i = 0; i < length; i += delta)
        ret += eth_send_packet(netif, (void*) ((uint32_t) buf + i), delta, type);
    if((length % delta) != 0)
        ret += eth_send_packet(netif, (void*) ((uint32_t) buf + length - (length % delta)), length % delta, type);
    
    
    if(ret)
        return length;
    
    return 0;
}
static int eth_send_packet (netif_t *netif, void *buf, size_tlength, inttype) [static]
Definition at line 49 of file eth.c.
References ETH_TYPE_ARP, ETH_TYPE_IPV4, ETH_TYPE_IPV6, ETH_TYPE_RAW, kfree(), kmalloc(), netif::macaddr, NETIF_ARP, NETIF_ETH, NETIF_INET, NETIF_INET6, netif::send, and uint32_t.
                                                                               {
    eth_header_t* ethpkt = kmalloc(length + sizeof(eth_header_t));
    memset((void*) ethpkt->dest, 0xFF, sizeof(macaddr_t));
    memcpy((void*) ethpkt->source, (void*) netif->macaddr, sizeof(macaddr_t));
    memcpy((void*) ((uint32_t) ethpkt + sizeof(eth_header_t)), buf, length);
    switch(type) {
        case NETIF_INET:
            ethpkt->type = ETH_TYPE_IPV4;
            break;
        case NETIF_INET6:
            ethpkt->type = ETH_TYPE_IPV6;
            break;
        case NETIF_ARP:
            ethpkt->type = ETH_TYPE_ARP;
            break;
        default:
            ethpkt->type = ETH_TYPE_RAW;
            break;
    }
    
    length += sizeof(eth_header_t);
    
    int ret = netif->send(netif, ethpkt, length, NETIF_ETH);
    kfree(ethpkt);
    
    return ret;
}
Author
Generated automatically by Doxygen for aPlus from the source code.