.TH "src/include/aplus/net/eth.h" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/aplus/net/eth.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <aplus/netif\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBeth_header\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBETH_TYPE_IPV4\fP   0x0800"
.br
.ti -1c
.RI "#define \fBETH_TYPE_ARP\fP   0x0806"
.br
.ti -1c
.RI "#define \fBETH_TYPE_IPV6\fP   0x86DD"
.br
.ti -1c
.RI "#define \fBETH_TYPE_WAKEONLAN\fP   0x0842"
.br
.ti -1c
.RI "#define \fBETH_TYPE_RARP\fP   0x8035"
.br
.ti -1c
.RI "#define \fBETH_TYPE_RAW\fP   0xFFFF"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBeth_header\fP \fB__attribute__\fP ((packed)) eth_header_t"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmacaddr_t\fP \fBdest\fP"
.br
.ti -1c
.RI "\fBmacaddr_t\fP \fBsource\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBtype\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ETH_TYPE_ARP   0x0806"

.PP
Definition at line 13 of file eth\&.h\&.
.SS "#define ETH_TYPE_IPV4   0x0800"

.PP
Definition at line 12 of file eth\&.h\&.
.SS "#define ETH_TYPE_IPV6   0x86DD"

.PP
Definition at line 14 of file eth\&.h\&.
.SS "#define ETH_TYPE_RARP   0x8035"

.PP
Definition at line 16 of file eth\&.h\&.
.SS "#define ETH_TYPE_RAW   0xFFFF"

.PP
Definition at line 17 of file eth\&.h\&.
.SS "#define ETH_TYPE_WAKEONLAN   0x0842"

.PP
Definition at line 15 of file eth\&.h\&.
.SH "Function Documentation"
.PP 
.SS "struct \fBeth_header\fP __attribute__ ((packed))"

.PP
Definition at line 44 of file desc\&.c\&.
.PP
.nf
46                        {
47     uint16_t limit;
48     uint32_t base;
49 } __attribute__((packed)) gdt_ptr_t;
.fi
.SH "Variable Documentation"
.PP 
.SS "\fBmacaddr_t\fP dest"

.PP
\fBExamples: \fP
.in +1c
\fBlist\&.h\fP\&.
.PP
Definition at line 44 of file eth\&.h\&.
.SS "\fBmacaddr_t\fP source"

.PP
Definition at line 45 of file eth\&.h\&.
.SS "\fBuint16_t\fP type"

.PP
Definition at line 46 of file eth\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
