.TH "eth_header" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eth_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <eth\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmacaddr_t\fP \fBdest\fP"
.br
.ti -1c
.RI "\fBmacaddr_t\fP \fBsource\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file eth\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBmacaddr_t\fP eth_header::dest"

.PP
Definition at line 21 of file eth\&.h\&.
.SS "\fBmacaddr_t\fP eth_header::source"

.PP
Definition at line 22 of file eth\&.h\&.
.SS "\fBuint16_t\fP eth_header::type"

.PP
Definition at line 23 of file eth\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
