.TH "eth_header" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eth_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <eth\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBmacaddr_t\fP \fBdest\fP"
.br
.ti -1c
.RI "\fBmacaddr_t\fP \fBsource\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBtype\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 20 del file eth\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "\fBmacaddr_t\fP eth_header::dest"

.PP
Definizione alla linea 21 del file eth\&.h\&.
.SS "\fBmacaddr_t\fP eth_header::source"

.PP
Definizione alla linea 22 del file eth\&.h\&.
.SS "\fBuint16_t\fP eth_header::type"

.PP
Definizione alla linea 23 del file eth\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
