src/exec.c
NAME
src/exec.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/mm.h>
#include <aplus/task.h>
#include <stdint.h>
#include <errno.h>
#include <grub.h>
Data Structures
struct elf32_hdr
ELF32 Header.
struct elf32_shdr
ELF32 Section Header.
struct elf32_phdr
ELF32 Program Header.
struct elf32_sym_t
ELF32 Symbol.
Macros
#define ELF32_ADDRSPACE_MIN_LENGTH 0x100000
#define EI_NIDENT 16
#define EI_MAG0 0
#define EI_MAG1 1
#define EI_MAG2 2
#define EI_MAG3 3
#define EI_CLASS 4
#define EI_DATA 5
#define EI_VERSION 6
#define EI_PAD 7
#define ELF_MAG0 0x7F
#define ELF_MAG1 'E'
#define ELF_MAG2 'L'
#define ELF_MAG3 'F'
#define ELF_CLASS_32 1
#define ELF_CLASS_64 2
#define ELF_DATA_LSB 1
#define ELF_DATA_MSB 2
#define SHT_NULL 0
#define SHT_PROGBITS 1
#define SHT_SYMTAB 2
#define SHT_STRTAB 3
#define SHT_RELA 4
#define SHT_HASH 5
#define SHT_DYNAMIC 6
#define SHT_NOTE 7
#define SHT_NOBITS 8
#define SHT_REL 9
#define SHT_SHLIB 10
#define SHT_DYNSYM 11
#define SHF_WRITE 1
#define SHF_ALLOC 2
#define SHF_EXECINSTR 4
#define SHF_MASK 0xF0000000
#define PT_NULL 0
#define PT_LOAD 1
#define PT_DYNAMIC 2
#define PT_INTERP 3
#define PT_NOTE 4
#define PT_SHLIB 5
#define PT_PHDR 6
#define PT_LOPROC 0x70000000
#define PT_HIPROC 0x7FFFFFFF
#define ELF32_ST_BIND(i) ((i >> 4))
#define ELF32_ST_TYPE(i) ((i) & 0x0F)
#define ELF_DEBUG
Enable or disable debug for ELF.
#define check(cond)
Typedefs
typedef uint32_t Elf32_Addr
typedef uint16_t Elf32_Half
typedef uint32_t Elf32_Off
typedef int32_t Elf32_Sword
typedef uint32_t Elf32_Word
typedef struct elf32_hdr elf32_hdr_t
ELF32 Header.
typedef struct elf32_shdr elf32_shdr_t
ELF32 Section Header.
typedef struct elf32_phdr elf32_phdr_t
ELF32 Program Header.
typedef struct elf32_sym_t elf32_sym_t
ELF32 Symbol.
Functions
int elf32_check (elf32_hdr_t *hdr)
Check for valid ELF32 header.
int elf32_getspace (elf32_hdr_t *hdr, void **ptr, size_t *size)
Get Address Space of ELF32 Executable.
void * elf32_load (void *image, int *vaddr, int *vsize)
Load a ELF32 Executable image.
char * elf_kernel_lookup (uint32_t symaddr)
Variables
task_t * current_task
Current task address.
Macro Definition Documentation
#define check(cond)
Value:
if(cond) { \
			errno = ENOEXEC; \
            return -1; \
        }
#define EI_CLASS 4
Definition at line 28 of file exec.c.
#define EI_DATA 5
Definition at line 29 of file exec.c.
#define EI_MAG0 0
Definition at line 24 of file exec.c.
#define EI_MAG1 1
Definition at line 25 of file exec.c.
#define EI_MAG2 2
Definition at line 26 of file exec.c.
#define EI_MAG3 3
Definition at line 27 of file exec.c.
#define EI_NIDENT 16
Definition at line 23 of file exec.c.
#define EI_PAD 7
Definition at line 31 of file exec.c.
#define EI_VERSION 6
Definition at line 30 of file exec.c.
#define ELF32_ADDRSPACE_MIN_LENGTH 0x100000
Definition at line 13 of file exec.c.
#define ELF32_ST_BIND(i) ((i >> 4))
Definition at line 76 of file exec.c.
#define ELF32_ST_TYPE(i) ((i) & 0x0F)
Definition at line 77 of file exec.c.
#define ELF_CLASS_32 1
Definition at line 38 of file exec.c.
#define ELF_CLASS_64 2
Definition at line 39 of file exec.c.
#define ELF_DATA_LSB 1
Definition at line 41 of file exec.c.
#define ELF_DATA_MSB 2
Definition at line 42 of file exec.c.
#define ELF_DEBUG
Enable or disable debug for ELF.
Definition at line 82 of file exec.c.
#define ELF_MAG0 0x7F
Definition at line 33 of file exec.c.
#define ELF_MAG1 'E'
Definition at line 34 of file exec.c.
#define ELF_MAG2 'L'
Definition at line 35 of file exec.c.
#define ELF_MAG3 'F'
Definition at line 36 of file exec.c.
#define PT_DYNAMIC 2
Definition at line 67 of file exec.c.
#define PT_HIPROC 0x7FFFFFFF
Definition at line 73 of file exec.c.
#define PT_INTERP 3
Definition at line 68 of file exec.c.
#define PT_LOAD 1
Definition at line 66 of file exec.c.
#define PT_LOPROC 0x70000000
Definition at line 72 of file exec.c.
#define PT_NOTE 4
Definition at line 69 of file exec.c.
#define PT_NULL 0
Definition at line 65 of file exec.c.
#define PT_PHDR 6
Definition at line 71 of file exec.c.
#define PT_SHLIB 5
Definition at line 70 of file exec.c.
#define SHF_ALLOC 2
Definition at line 59 of file exec.c.
#define SHF_EXECINSTR 4
Definition at line 60 of file exec.c.
#define SHF_MASK 0xF0000000
Definition at line 61 of file exec.c.
#define SHF_WRITE 1
Definition at line 58 of file exec.c.
#define SHT_DYNAMIC 6
Definition at line 51 of file exec.c.
#define SHT_DYNSYM 11
Definition at line 56 of file exec.c.
#define SHT_HASH 5
Definition at line 50 of file exec.c.
#define SHT_NOBITS 8
Definition at line 53 of file exec.c.
#define SHT_NOTE 7
Definition at line 52 of file exec.c.
#define SHT_NULL 0
Definition at line 45 of file exec.c.
#define SHT_PROGBITS 1
Definition at line 46 of file exec.c.
#define SHT_REL 9
Definition at line 54 of file exec.c.
#define SHT_RELA 4
Definition at line 49 of file exec.c.
#define SHT_SHLIB 10
Definition at line 55 of file exec.c.
#define SHT_STRTAB 3
Definition at line 48 of file exec.c.
#define SHT_SYMTAB 2
Definition at line 47 of file exec.c.
Typedef Documentation
typedef uint32_t Elf32_Addr
Definition at line 16 of file exec.c.
typedef uint16_t Elf32_Half
Definition at line 17 of file exec.c.
typedef struct elf32_hdr elf32_hdr_t
ELF32 Header.
typedef uint32_t Elf32_Off
Definition at line 18 of file exec.c.
typedef struct elf32_phdr elf32_phdr_t
ELF32 Program Header.
typedef struct elf32_shdr elf32_shdr_t
ELF32 Section Header.
typedef int32_t Elf32_Sword
Definition at line 19 of file exec.c.
typedef struct elf32_sym_t elf32_sym_t
ELF32 Symbol.
typedef uint32_t Elf32_Word
Definition at line 20 of file exec.c.
Function Documentation
int elf32_check (elf32_hdr_t *hdr)
Check for valid ELF32 header.
Parameters:
hdr ELF32 Header.
Returns:
0 for valid header or -1 in case of errors.
Definition at line 154 of file exec.c.
References check, elf32_hdr::e_ident, EI_CLASS, EI_DATA, EI_MAG0, EI_MAG1, EI_MAG2, EI_MAG3, ELF_CLASS_32, ELF_DATA_LSB, ELF_MAG0, ELF_MAG1, ELF_MAG2, ELF_MAG3, and errno.
                                  {
    if(!hdr) {
        errno = EINVAL;
        return -1;
    }
    #define check(cond) \
        if(cond) { \
            errno = ENOEXEC; \
            return -1; \
        }
    check(
        (hdr->e_ident[EI_MAG0] != ELF_MAG0) ||
        (hdr->e_ident[EI_MAG1] != ELF_MAG1) ||
        (hdr->e_ident[EI_MAG2] != ELF_MAG2) ||
        (hdr->e_ident[EI_MAG3] != ELF_MAG3)
    )
    check(hdr->e_ident[EI_CLASS] != ELF_CLASS_32)
    check(hdr->e_ident[EI_DATA] != ELF_DATA_LSB)
    return 0;
}
int elf32_getspace (elf32_hdr_t *hdr, void **ptr, size_t *size)
Get Address Space of ELF32 Executable.
Parameters:
hdr ELF32 Header.
ptr Pointer to start of memory address.
size Size of memory address.
Returns:
if success 0, otherwise -1.
Definition at line 188 of file exec.c.
References elf32_hdr::e_phoff, ELF32_ADDRSPACE_MIN_LENGTH, elf32_check(), kprintf(), elf32_phdr::p_memsz, elf32_phdr::p_vaddr, and uint32_t.
                                                               {
    if(elf32_check(hdr) < 0)
        return -1;
    elf32_phdr_t* phdr = (elf32_phdr_t*) ((uint32_t) hdr->e_phoff + (uint32_t) hdr);
    int pn = hdr->e_phnum;
    int ps = hdr->e_phentsize;
    int p = 0;
    int s = 0;
    for(int i = 0; i < pn; i++) {
        if(!p || p > phdr->p_vaddr)
            p = phdr->p_vaddr;
        s += phdr->p_memsz;
        phdr = (elf32_phdr_t*) ((uint32_t) phdr + ps);
    }
    if(s < ELF32_ADDRSPACE_MIN_LENGTH)
        s = ELF32_ADDRSPACE_MIN_LENGTH;
#ifdef ELF_DEBUG
    kprintf("elf: address space at 0x%x (%d Bytes)\n", p, s);
#endif
    if(ptr)
        *ptr = (void*) p;
    if(size)
        *size = s;
    return 0;
}
void* elf32_load (void *image, int *vaddr, int *vsize)
Load a ELF32 Executable image.
Parameters:
image pointer to buffer address of a executable loaded in memory.
vaddr Address of memory space needed.
vsize Size of memory space.
Returns:
Entry Point address.
Definition at line 232 of file exec.c.
References task::context, task::cr3, elf32_hdr::e_shoff, elf32_check(), elf32_getspace(), errno, kprintf(), MM_UBASE, MM_USIZE, panic(), schedule_release(), elf32_shdr::sh_addr, elf32_shdr::sh_offset, elf32_shdr::sh_size, elf32_shdr::sh_type, SHT_NOBITS, uint32_t, vmm_alloc(), VMM_FLAGS_DEFAULT, and VMM_FLAGS_USER.
                                                      {
    if(image == NULL) {
        errno = EINVAL;
        return NULL;
    }
    if(elf32_check(image) < 0)
        return NULL;
    elf32_hdr_t* hdr = (elf32_hdr_t*) image;
    int iptr, isiz;
    if(elf32_getspace(hdr, (void**) &iptr, (size_t*) &isiz) != 0)
        panic("elf: cannot found a valid address space");
    schedule_release(current_task);
    vmm_alloc(current_task->context.cr3, iptr, isiz, VMM_FLAGS_DEFAULT | VMM_FLAGS_USER);
    if(vaddr)
        *vaddr = iptr;
    if(vsize)
        *vsize = isiz;
    elf32_shdr_t* sec = (elf32_shdr_t*) ((uint32_t) hdr->e_shoff + (uint32_t) hdr);
    
    int sn = hdr->e_shnum;
    int ss = hdr->e_shentsize;
    for(int i = 0; i < sn; i++) {
        if(sec->sh_addr && sec->sh_offset) {
#ifdef ELF_DEBUG
            kprintf("elf: copy section to 0x%8x [%d] (%d Bytes)\n", sec->sh_addr, sec->sh_type, sec->sh_size);
#endif
            if((sec->sh_addr + sec->sh_size) < MM_UBASE || (sec->sh_addr + sec->sh_size) > (MM_UBASE + MM_USIZE))
                panic("elf: section overflow");
            
            
            memcpy((void*) sec->sh_addr, (void*) ((uint32_t) hdr + sec->sh_offset), sec->sh_size);
            
            if(sec->sh_type == SHT_NOBITS)
                memset((void*) sec->sh_addr, 0, sec->sh_size);
        }
        sec = (elf32_shdr_t*) ((uint32_t) sec + ss);
    }
#ifdef ELF_DEBUG
    kprintf("elf: entrypoint at 0x%8x\n", hdr->e_entry);
#endif
    return (void*) hdr->e_entry;
}
char* elf_kernel_lookup (uint32_tsymaddr)
Definition at line 291 of file exec.c.
References BootInfo_t::addr, ELF32_ST_TYPE, mbd, name, elf32_shdr::sh_addr, elf32_shdr::sh_size, BootInfo_t::shndx, and uint32_t.
                                          {
    elf32_shdr_t* shdr = (elf32_shdr_t*) mbd->addr;
    
    uint32_t shstrtab = shdr[mbd->shndx].sh_addr;
    
    const char* strtab = NULL;
    elf32_sym_t* symtab = NULL;
    uint32_t symtabsz = 0;
    for(int i = 0; i < mbd->num; i++) {
        const char* name = (const char*) (shstrtab + shdr[i].sh_name);
        if(strcmp(name, ".strtab") == 0)
            strtab = (const char*) shdr[i].sh_addr;
        
        if(strcmp(name, ".symtab") == 0) {
            symtab = (elf32_sym_t*) shdr[i].sh_addr;
            symtabsz = shdr[i].sh_size;
        }
    }
    for(int i = 0; i < (symtabsz / sizeof(elf32_sym_t)); i++) {
        if(ELF32_ST_TYPE(symtab[i].st_info) != 0x02)
            continue;
        if((symaddr >= symtab[i].st_value) && (symaddr < (symtab[i].st_value + symtab[i].st_size))) {
            const char* name = (const char*) ((uint32_t) strtab + symtab[i].st_name);
            return (char*) name;
        }
    }
    return NULL;
}
Variable Documentation
task_t* current_task
Current task address.
Definition at line 37 of file sched.c.
Author
Generated automatically by Doxygen for aPlus from the source code.