.TH "usr/src/libposix/src/execv.c" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/execv.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <_ansi\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fB_execve\fP (const char *filename, char *const args[], char *const env[])"
.br
.ti -1c
.RI "int \fB_DEFUN\fP (execv,(path, argv), const char *path _AND char *const argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static char *** \fBp_environ\fP = &\fBenviron\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int _DEFUN (execv, (path, argv), const char *path _AND char *constargv[])"

.PP
Definition at line 17 of file execv\&.c\&.
.PP
References _execve(), and p_environ\&.
.PP
.nf
20 {
21   return _execve (path, (char * _CONST *) argv, *p_environ);
22 }
.fi
.SS "int _execve (const char *filename, char *constargs[], char *constenv[])"

.PP
Definition at line 8 of file _execve\&.c\&.
.PP
References execve()\&.
.PP
.nf
8                                                                          {
9     return execve(filename, args, env);
10 }
.fi
.SH "Variable Documentation"
.PP 
.SS "char*** p_environ = &\fBenviron\fP\fC [static]\fP"

.PP
Definition at line 13 of file execv\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
