.TH "fs" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fs \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fs\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "char \fBname\fP [255]"
.br
.ti -1c
.RI "int(* \fBmount\fP )(struct \fBinode\fP *idev, struct \fBinode\fP *idir, int flags)"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 75 del file fs\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "int(* fs::mount)(struct \fBinode\fP *idev, struct \fBinode\fP *idir, int flags)"

.PP
Definizione alla linea 77 del file fs\&.h\&.
.SS "char fs::name[255]"

.PP
Definizione alla linea 76 del file fs\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
