src/fs/fs.c
NAME
src/fs/fs.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/fs.h>
#include <aplus/mm.h>
#include <stdint.h>
#include <stddef.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <dirent.h>
#include <errno.h>
Functions
int fs_read (struct inode *inode, char *ptr, int len)
int fs_write (struct inode *inode, char *ptr, int len)
struct dirent * fs_readdir (struct inode *inode, int index)
struct inode * fs_finddir (struct inode *inode, char *name)
struct inode * fs_creat (struct inode *inode, char *name, mode_t mode)
int fs_rename (struct inode *inode, char *oldname, char *newname)
int fs_unlink (struct inode *inode, char *name)
int fs_chown (struct inode *inode, uid_t owner, gid_t group)
void fs_flush (struct inode *inode)
int fs_ioctl (struct inode *inode, int req, void *buf)
Function Documentation
int fs_chown (struct inode *inode, uid_towner, gid_tgroup)
Definition at line 94 of file fs.c.
References inode::chown, and errno.
                                                             {
    if(inode->chown)
        return inode->chown(inode, owner, group);
        
    errno = ENOSYS;
    return -1;
}
struct inode* fs_creat (struct inode *inode, char *name, mode_tmode)
Definition at line 70 of file fs.c.
References inode::creat, and errno.
                                                                      {
    if(inode->creat)
        return inode->creat(inode, name, mode);
    
    errno = ENOSYS;
    return NULL;
}
struct inode* fs_finddir (struct inode *inode, char *name)
Definition at line 51 of file fs.c.
References errno, inode::finddir, inode::parent, and vfs_mapped().
                                                           {
    if(strcmp(name, ".") == 0)
        return inode;
    if(strcmp(name, "..") == 0)
        return inode->parent;
    inode_t* map = NULL;
    if((map = (inode_t*) vfs_mapped(inode, name)) != NULL)
        return map;
    if(inode->finddir)
        return inode->finddir(inode, name);
        
    errno = ENOSYS;
    return NULL;
}
void fs_flush (struct inode *inode)
Definition at line 102 of file fs.c.
References errno, and inode::flush.
                                   {
    if(inode->flush)
        inode->flush(inode);
        
    errno = ENOSYS;
    return;
}
int fs_ioctl (struct inode *inode, intreq, void *buf)
Definition at line 110 of file fs.c.
References errno, and inode::ioctl.
                                                      {
    if(inode->ioctl)
        return inode->ioctl(inode, req, buf);
    
    errno = ENOSYS;
    return -1;
}
int fs_read (struct inode *inode, char *ptr, intlen)
Definition at line 17 of file fs.c.
References errno, and inode::read.
                                                      {
    if(inode->read)
        return inode->read(inode, ptr, len);
    
    errno = ENOSYS;
    return 0;
}
struct dirent* fs_readdir (struct inode *inode, intindex)
Definition at line 33 of file fs.c.
References dirent::d_ino, dirent::d_name, errno, inode::ino, kmalloc(), inode::name, inode::readdir, vfs_mapped_at_index(), and vfs_mapped_count().
                                                           {
    inode_t* map = NULL;
    if((map = (inode_t*) vfs_mapped_at_index(inode, index)) != NULL) {
        struct dirent* ent = (struct dirent*) kmalloc(sizeof(struct dirent));
        strcpy(ent->d_name, map->name);
        ent->d_ino = map->ino;
        
        return ent;
    }
    if(inode->readdir)
        return inode->readdir(inode, index - vfs_mapped_count(inode));
        
    errno = ENOSYS;
    return NULL;
}
int fs_rename (struct inode *inode, char *oldname, char *newname)
Definition at line 78 of file fs.c.
References errno, and inode::rename.
                                                                  {
    if(inode->rename)
        return inode->rename(inode, oldname, newname);
    
    errno = ENOSYS;
    return -1;
}
int fs_unlink (struct inode *inode, char *name)
Definition at line 86 of file fs.c.
References errno, and inode::unlink.
                                                {
    if(inode->unlink)
        return inode->unlink(inode, name);
        
    errno = ENOSYS;
    return -1;
}
int fs_write (struct inode *inode, char *ptr, intlen)
Definition at line 25 of file fs.c.
References errno, and inode::write.
                                                       {
    if(inode->write)
        return inode->write(inode, ptr, len);
        
    errno = ENOSYS;
    return 0;
}
Author
Generated automatically by Doxygen for aPlus from the source code.