.TH "src/syscall/fstat.c" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syscall/fstat.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <aplus\&.h>\fP
.br
\fC#include <aplus/syscall\&.h>\fP
.br
\fC#include <aplus/fs\&.h>\fP
.br
\fC#include <aplus/task\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsys_fstat\fP (int fd, struct stat *st)"
.br
.RI "\fIThis function shall obtain information about an open file associated with the file descriptor fildes, and shall write it to the area pointed to by buf\&. \fP"
.ti -1c
.RI "\fBSYSCALL\fP (\fBsys_fstat\fP, 4)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtask_t\fP * \fBcurrent_task\fP"
.br
.RI "\fICurrent task address\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int sys_fstat (intfd, struct stat *st)"

.PP
This function shall obtain information about an open file associated with the file descriptor fildes, and shall write it to the area pointed to by buf\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfd\fP File descriptor 
.br
\fIst\fP Stat structure 
.RE
.PP
\fBReturns:\fP
.RS 4
Upon successful completion, 0 shall be returned\&.
.br
 Otherwise, -1 shall be returned and errno set to indicate the error\&. 
.RE
.PP

.PP
Definition at line 24 of file fstat\&.c\&.
.PP
References inode::atime, inode::ctime, inode::dev, errno, task::fd, inode::gid, inode::ino, inode::mode, inode::mtime, inode::nlink, inode::rdev, inode::size, TASK_MAX_FD, and inode::uid\&.
.PP
.nf
24                                        {
25     if(!st) {
26         errno = EINVAL;
27         return -1;
28     }
29 
30     if(fd < 0 || fd > TASK_MAX_FD) {
31         errno = EBADF;
32         return -1;
33     }
34     
35 
36     inode_t* ino = current_task->fd[fd];
37     if(!ino) {
38         errno = EBADF;
39         return -1;
40     }
41     
42     st->st_mode = ino->mode;
43     st->st_ino = ino->ino;
44     st->st_dev = ino->dev;
45     st->st_uid = ino->uid;
46     st->st_gid = ino->gid;
47     st->st_atime = ino->atime;
48     st->st_ctime = ino->ctime;
49     st->st_mtime = ino->mtime;
50     st->st_nlink = ino->nlink;
51     st->st_size = ino->size;
52     st->st_rdev = ino->rdev;
53     st->st_blksize = 512;
54     st->st_blocks = st->st_size / st->st_blksize;
55     
56     return 0;
57 }
.fi
.SS "SYSCALL (\fBsys_fstat\fP, 4)"

.SH "Variable Documentation"
.PP 
.SS "\fBtask_t\fP* current_task"

.PP
Current task address\&. 
.PP
Definition at line 37 of file sched\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
