usr/src/libposix/src/getcwd.c
NAME
usr/src/libposix/src/getcwd.c -
SYNOPSIS
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>
Functions
static char * strcat_inv (char *dest, char *str)
char * getcwd (char *buf, size_t size)
Function Documentation
char* getcwd (char *buf, size_tsize)
Definition at line 17 of file getcwd.c.
References closedir(), dirent::d_ino, dirent::d_name, opendir(), readdir(), and strcat_inv().
                                     {
    struct stat st;
    char tmpbuf[1024];
    int root_ino = 0;
    int curr_ino = 0;
    if(stat("/", &st) != 0)
        return NULL;
    root_ino = st.st_ino;
    if(stat(".", &st) != 0)
        return NULL;
    curr_ino = st.st_ino;
    memset(buf, 0, size);
    memset(tmpbuf, 0, 1024);
    strcat(tmpbuf, ".");
    if(curr_ino == root_ino) {
        strcat_inv(buf, "/");
        return buf;
    }
    while(curr_ino != root_ino) {
        if(stat(tmpbuf, &st) != 0)
            return NULL;
        curr_ino = st.st_ino;
        if(curr_ino == root_ino)
            break;
        strcat(tmpbuf, "/..");
        DIR* dir = opendir(tmpbuf);
        if(!dir)
            return NULL;
        struct dirent* ent;
        while((ent = readdir(dir))) {
            if(ent->d_ino == curr_ino) {
                strcat_inv(buf, ent->d_name);
                strcat_inv(buf, "/");
            }
            free(ent);
        }
        closedir(dir);
    }
    return buf;
}
static char* strcat_inv (char *dest, char *str) [static]
Definition at line 7 of file getcwd.c.
References dest.
                                               {
    char* res = malloc(strlen(dest) + strlen(str));
    strcpy(res, str);
    strcat(res, dest);
    strcpy(dest, res);
    free(res);
    return dest;
}
Author
Generated automatically by Doxygen for aPlus from the source code.