.TH "src/syscall/getpid.c" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syscall/getpid.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <aplus\&.h>\fP
.br
\fC#include <aplus/syscall\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "pid_t \fBsys_getpid\fP ()"
.br
.ti -1c
.RI "\fBSYSCALL\fP (\fBsys_getpid\fP, 5)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "pid_t sys_getpid ()"

.PP
Definition at line 13 of file getpid\&.c\&.
.PP
References schedule_getpid()\&.
.PP
.nf
13                    {
14     return schedule_getpid();
15 }
.fi
.SS "SYSCALL (\fBsys_getpid\fP, 5)"

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
