.TH "src/syscall/gettimeofday.c" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syscall/gettimeofday.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <aplus\&.h>\fP
.br
\fC#include <aplus/syscall\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <sys/times\&.h>\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBsys_gettimeofday\fP (struct timeval *tv, struct timezone *tz)"
.br
.ti -1c
.RI "\fBSYSCALL\fP (\fBsys_gettimeofday\fP, 18)"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "int sys_gettimeofday (struct timeval *tv, struct timezone *tz)"

.PP
Definizione alla linea 15 del file gettimeofday\&.c\&.
.PP
Referenzia errno, pit_getticks(), e pit_gettime()\&.
.PP
.nf
15                                                               {
16     if(!tv) {
17         errno = EINVAL;
18         return -1;
19     }
20     
21     tv->tv_sec = pit_gettime();
22     tv->tv_usec = pit_getticks() * 1000;
23     
24     return 0;
25 }
.fi
.SS "SYSCALL (\fBsys_gettimeofday\fP, 18)"

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
