.TH "usr/src/libatk/src/include/atk/gfx.h" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libatk/src/include/atk/gfx.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <atk\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBatk_gfx\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBatk_gfx\fP \fBatk_gfx_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBatk_gfx\fP  \fBatk_gfx_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
