usr/src/libatk/src/gfx.c
NAME
usr/src/libatk/src/gfx.c -
SYNOPSIS
#include <atk.h>
#include <atk/gfx.h>
#include <atk/bitmap.h>
#include <stdint.h>
#include <math.h>
#include <errno.h>
#include 'clrconv.h'
Functions
static void __gfx_plot_pixel_32 (void *d, atk_color_t color)
static void __gfx_plot_pixel_24 (void *d, atk_color_t color)
static void __gfx_plot_pixel_16 (void *d, atk_color_t color)
static atk_color_t __gfx_read_pixel_32 (void *d)
static atk_color_t __gfx_read_pixel_24 (void *d)
static atk_color_t __gfx_read_pixel_16 (void *d)
atk_gfx_t * atk_gfx_create (short width, short height, short bpp, void *buffer)
void atk_gfx_set (atk_gfx_t *gfx)
atk_gfx_t * atk_gfx_get ()
int atk_gfx_line (atk_bitmap_t *b, int x0, int y0, int x1, int y1, atk_color_t color)
Variables
atk_gfx_t * __gfx
Function Documentation
static void __gfx_plot_pixel_16 (void *d, atk_color_tcolor) [static]
Definition at line 26 of file gfx.c.
References __alphablend(), ATK_COLOR_A, R5G6B5_TO_V4F, uint16_t, and V4F_TO_R5G6B5.
                                                            {
    atk_color_t dc = R5G6B5_TO_V4F((*(uint16_t*) d));
    atk_color_t df = __alphablend(dc, color, color[ATK_COLOR_A]);
    *(uint16_t*) d = V4F_TO_R5G6B5(df);
}
static void __gfx_plot_pixel_24 (void *d, atk_color_tcolor) [static]
Definition at line 19 of file gfx.c.
References __alphablend(), ATK_COLOR_A, RGB_TO_V4F, uint32_t, and V4F_TO_RGB.
                                                            {
    atk_color_t dc = RGB_TO_V4F((*(uint32_t*) d));
    atk_color_t df = __alphablend(dc, color, color[ATK_COLOR_A]);
    *(uint32_t*) d = V4F_TO_RGB(df);
}
static void __gfx_plot_pixel_32 (void *d, atk_color_tcolor) [static]
Definition at line 12 of file gfx.c.
References __alphablend(), ARGB_TO_V4F, ATK_COLOR_A, uint32_t, and V4F_TO_ARGB.
                                                            {
    atk_color_t dc = ARGB_TO_V4F((*(uint32_t*) d));
    atk_color_t df = __alphablend(dc, color, color[ATK_COLOR_A]);
    *(uint32_t*) d = V4F_TO_ARGB(df);
}
static atk_color_t __gfx_read_pixel_16 (void *d) [static]
Definition at line 45 of file gfx.c.
References R5G6B5_TO_V4F, and uint16_t.
                                                {
    atk_color_t dc = R5G6B5_TO_V4F((*(uint16_t*) d));
    return dc;
}
static atk_color_t __gfx_read_pixel_24 (void *d) [static]
Definition at line 39 of file gfx.c.
References RGB_TO_V4F, and uint32_t.
                                                {
    atk_color_t dc = RGB_TO_V4F((*(uint32_t*) d));
    return dc;
}
static atk_color_t __gfx_read_pixel_32 (void *d) [static]
Definition at line 33 of file gfx.c.
References ARGB_TO_V4F, and uint32_t.
                                                {
    atk_color_t dc = ARGB_TO_V4F((*(uint32_t*) d));
    return dc;
}
atk_gfx_t* atk_gfx_create (shortwidth, shortheight, shortbpp, void *buffer)
Definition at line 53 of file gfx.c.
References atk_gfx::__get, __gfx_plot_pixel_16(), __gfx_plot_pixel_24(), __gfx_plot_pixel_32(), __gfx_read_pixel_16(), __gfx_read_pixel_24(), __gfx_read_pixel_32(), atk_gfx::__plot, atk_gfx::bpp, bpp, errno, atk_gfx::framebuffer, atk_gfx::height, atk_gfx::stride, and atk_gfx::width.
                                                                              {
    if(!(width && height && bpp && buffer)) {
        errno = EINVAL;
        return NULL;
    }
    atk_gfx_t* gfx = (atk_gfx_t*) malloc(width * height * (bpp / 8));
    gfx->width = width;
    gfx->height = height;
    gfx->bpp = bpp;
    gfx->stride = width * (bpp / 8);
    gfx->framebuffer = buffer;
    switch(bpp) {
        case 16:
            gfx->__plot = __gfx_plot_pixel_16;
            gfx->__get = __gfx_read_pixel_16;
            break;
        case 24:
            gfx->__plot = __gfx_plot_pixel_24;
            gfx->__get = __gfx_read_pixel_24;
            break;
        case 32:
            gfx->__plot = __gfx_plot_pixel_32;
            gfx->__get = __gfx_read_pixel_32;
            break;
        default:
            free(gfx);
            errno = EINVAL;
            return NULL;
    }
    return gfx;
}
atk_gfx_t* atk_gfx_get ()
Definition at line 92 of file gfx.c.
References __gfx.
                         {
    return __gfx;
}
int atk_gfx_line (atk_bitmap_t *b, intx0, inty0, intx1, inty1, atk_color_tcolor)
Definition at line 98 of file gfx.c.
References atk_gfx::__plot, __SWAP, ATK_BITMAP_LOCK_RDWR, atk_bitmap_lockbits(), atk_bitmap_unlockbits(), ATK_COLOR_A, atk_gfx::bpp, bpp, errno, and uint32_t.
                                                                                     {
    if(!b) {
        errno = EINVAL;
        return -1;
    }
    if(x0 > x1)
        __SWAP(x0, x1)
    if(y0 > y1)
        __SWAP(y0, y1)
    atk_rect_t region = { x0, y0, x1, y1 };
    void* buffer = atk_bitmap_lockbits(b, region, ATK_BITMAP_LOCK_RDWR);
    if(!buffer)
        return -1;
    
    x1 -= x0;
    y1 -= y1;
    x0 = 0;
    y0 = 0;
    
    int x2 = 0;
    int sx = 0;
    int sy = 0;
    int dx = x1;
    int dy = y1;
    int e = dx - dy;
    int e2 = 0;
    int ed = dx + dy == 0 ? 1 : sqrt((float) (dx * dx) + (float) (dy * dy));
    int bpp = __gfx->bpp >> 3;
    int stride = x1 * bpp;
    for(;;) {
        color[ATK_COLOR_A] = abs(e - dx + dy) / ed;
        __gfx->__plot((void*) ((uint32_t) buffer + (y0 * stride) + (x0 * bpp)), color);
        
        e2 = e;
        x2 = x0;
        if((e2 << 1) >= -dx) {
            if(x0 == x1)
                break;
            if(e2 + dy < ed) {
                color[ATK_COLOR_A] = abs(e2 - dy) / ed;
                __gfx->__plot((void*) ((uint32_t) buffer + ((y0 + sy) * stride) + (x0 * bpp)), color);
            }
            e -= dy;
            x0 += sx;
        }
        if((e2 << 1) <= dy) {
            if(y0 == y1)
                break;
            if(dx - e2 < ed) {
                color[ATK_COLOR_A] = abs(dx - e2) / ed;
                __gfx->__plot((void*) ((uint32_t) buffer + (y0 * stride) + ((x2 + sx) * bpp)), color);
            }
            e += dx;
            y0 += sy;
        }
    }
    
    atk_bitmap_unlockbits(b);
}
void atk_gfx_set (atk_gfx_t *gfx)
Definition at line 88 of file gfx.c.
                                 {
    __gfx = gfx;
}
Variable Documentation
atk_gfx_t* __gfx
Definition at line 10 of file gfx.c.
Author
Generated automatically by Doxygen for aPlus from the source code.