.TH "usr/src/libposix/src/gid.c" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/gid.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include 'config\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "gid_t \fBgetgid\fP (void)"
.br
.ti -1c
.RI "gid_t \fBgetegid\fP (void)"
.br
.ti -1c
.RI "int \fBgetgroups\fP (int len, gid_t *\fBlist\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "gid_t getegid (void)"

.PP
Definition at line 14 of file gid\&.c\&.
.PP
References getgid()\&.
.PP
.nf
14                     {
15     return getgid();
16 }
.fi
.SS "gid_t getgid (void)"

.PP
Definition at line 6 of file gid\&.c\&.
.PP
.nf
6                    {
7     struct stat st;
8     if(fstat(STDIN_FILENO, &st) != 0)
9         return -1;
10 
11     return st\&.st_gid;
12 }
.fi
.SS "int getgroups (intlen, gid_t *list)"

.PP
Definition at line 18 of file gid\&.c\&.
.PP
.nf
18                                     {
19     return __os_getgroups(len, list);
20 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
