.TH "src/include/grub.h" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/grub.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBvesaInfo_t\fP"
.br
.ti -1c
.RI "struct \fBvesaModeInfo_t\fP"
.br
.ti -1c
.RI "struct \fBBootInfo_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMULTIBOOT_FLAG_MEM\fP   0x001"
.br
.ti -1c
.RI "#define \fBMULTIBOOT_FLAG_DEVICE\fP   0x002"
.br
.ti -1c
.RI "#define \fBMULTIBOOT_FLAG_CMDLINE\fP   0x004"
.br
.ti -1c
.RI "#define \fBMULTIBOOT_FLAG_MODS\fP   0x008"
.br
.ti -1c
.RI "#define \fBMULTIBOOT_FLAG_AOUT\fP   0x010"
.br
.ti -1c
.RI "#define \fBMULTIBOOT_FLAG_ELF\fP   0x020"
.br
.ti -1c
.RI "#define \fBMULTIBOOT_FLAG_MMAP\fP   0x040"
.br
.ti -1c
.RI "#define \fBMULTIBOOT_FLAG_CONFIG\fP   0x080"
.br
.ti -1c
.RI "#define \fBMULTIBOOT_FLAG_LOADER\fP   0x100"
.br
.ti -1c
.RI "#define \fBMULTIBOOT_FLAG_APM\fP   0x200"
.br
.ti -1c
.RI "#define \fBMULTIBOOT_FLAG_VBE\fP   0x400"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBvesaInfo_t\fP \fBvesaInfo\fP"
.br
.ti -1c
.RI "typedef struct \fBBootInfo_t\fP \fBBootInfo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBvesaModeInfo_t\fP \fB__attribute__\fP ((packed)) vesaModeInfo"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned short \fBattributes\fP"
.br
.ti -1c
.RI "unsigned char \fBwinA\fP"
.br
.ti -1c
.RI "unsigned char \fBwinB\fP"
.br
.ti -1c
.RI "unsigned short \fBgranularity\fP"
.br
.ti -1c
.RI "unsigned short \fBwinsize\fP"
.br
.ti -1c
.RI "unsigned short \fBsegmentA\fP"
.br
.ti -1c
.RI "unsigned short \fBsegmentB\fP"
.br
.ti -1c
.RI "unsigned int \fBrealFctPtr\fP"
.br
.ti -1c
.RI "unsigned short \fBpitch\fP"
.br
.ti -1c
.RI "unsigned short \fBXres\fP"
.br
.ti -1c
.RI "unsigned short \fBYres\fP"
.br
.ti -1c
.RI "unsigned char \fBWchar\fP"
.br
.ti -1c
.RI "unsigned char \fBYchar\fP"
.br
.ti -1c
.RI "unsigned char \fBplanes\fP"
.br
.ti -1c
.RI "unsigned char \fBbpp\fP"
.br
.ti -1c
.RI "unsigned char \fBbanks\fP"
.br
.ti -1c
.RI "unsigned char \fBmemory_model\fP"
.br
.ti -1c
.RI "unsigned char \fBbank_size\fP"
.br
.ti -1c
.RI "unsigned char \fBimage_pages\fP"
.br
.ti -1c
.RI "unsigned char \fBreserved0\fP"
.br
.ti -1c
.RI "unsigned char \fBred_mask\fP"
.br
.ti -1c
.RI "unsigned char \fBred_position\fP"
.br
.ti -1c
.RI "unsigned char \fBgreen_mask\fP"
.br
.ti -1c
.RI "unsigned char \fBgreen_position\fP"
.br
.ti -1c
.RI "unsigned char \fBblue_mask\fP"
.br
.ti -1c
.RI "unsigned char \fBblue_position\fP"
.br
.ti -1c
.RI "unsigned char \fBrsv_mask\fP"
.br
.ti -1c
.RI "unsigned char \fBrsv_position\fP"
.br
.ti -1c
.RI "unsigned char \fBdirectcolor_attributes\fP"
.br
.ti -1c
.RI "unsigned int \fBphysbase\fP"
.br
.ti -1c
.RI "unsigned int \fBreserved1\fP"
.br
.ti -1c
.RI "short \fBreserved2\fP"
.br
.ti -1c
.RI "\fBBootInfo\fP * \fBmbd\fP"
.br
.ti -1c
.RI "unsigned int \fBmagic\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MULTIBOOT_FLAG_AOUT   0x010"

.PP
Definition at line 99 of file grub\&.h\&.
.SS "#define MULTIBOOT_FLAG_APM   0x200"

.PP
Definition at line 104 of file grub\&.h\&.
.SS "#define MULTIBOOT_FLAG_CMDLINE   0x004"

.PP
Definition at line 97 of file grub\&.h\&.
.SS "#define MULTIBOOT_FLAG_CONFIG   0x080"

.PP
Definition at line 102 of file grub\&.h\&.
.SS "#define MULTIBOOT_FLAG_DEVICE   0x002"

.PP
Definition at line 96 of file grub\&.h\&.
.SS "#define MULTIBOOT_FLAG_ELF   0x020"

.PP
Definition at line 100 of file grub\&.h\&.
.SS "#define MULTIBOOT_FLAG_LOADER   0x100"

.PP
Definition at line 103 of file grub\&.h\&.
.SS "#define MULTIBOOT_FLAG_MEM   0x001"

.PP
Definition at line 95 of file grub\&.h\&.
.SS "#define MULTIBOOT_FLAG_MMAP   0x040"

.PP
Definition at line 101 of file grub\&.h\&.
.SS "#define MULTIBOOT_FLAG_MODS   0x008"

.PP
Definition at line 98 of file grub\&.h\&.
.SS "#define MULTIBOOT_FLAG_VBE   0x400"

.PP
Definition at line 105 of file grub\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBBootInfo_t\fP  \fBBootInfo\fP"

.SS "typedef struct \fBvesaInfo_t\fP  \fBvesaInfo\fP"

.SH "Function Documentation"
.PP 
.SS "struct \fBvesaModeInfo_t\fP __attribute__ ((packed))"

.PP
Definition at line 44 of file desc\&.c\&.
.PP
.nf
46                        {
47     uint16_t limit;
48     uint32_t base;
49 } __attribute__((packed)) gdt_ptr_t;
.fi
.SH "Variable Documentation"
.PP 
.SS "unsigned short attributes"

.PP
Definition at line 140 of file grub\&.h\&.
.SS "unsigned char bank_size"

.PP
Definition at line 150 of file grub\&.h\&.
.SS "unsigned char banks"

.PP
Definition at line 149 of file grub\&.h\&.
.SS "unsigned char blue_mask"

.PP
Definition at line 155 of file grub\&.h\&.
.SS "unsigned char blue_position"

.PP
Definition at line 155 of file grub\&.h\&.
.SS "unsigned char bpp"

.PP
Definition at line 149 of file grub\&.h\&.
.SS "unsigned char directcolor_attributes"

.PP
Definition at line 157 of file grub\&.h\&.
.SS "unsigned short granularity"

.PP
Definition at line 142 of file grub\&.h\&.
.SS "unsigned char green_mask"

.PP
Definition at line 154 of file grub\&.h\&.
.SS "unsigned char green_position"

.PP
Definition at line 154 of file grub\&.h\&.
.SS "unsigned char image_pages"

.PP
Definition at line 150 of file grub\&.h\&.
.SS "unsigned int magic"

.PP
Definition at line 42 of file mm\&.c\&.
.SS "\fBBootInfo\fP* mbd"

.SS "unsigned char memory_model"

.PP
Definition at line 150 of file grub\&.h\&.
.SS "unsigned int physbase"

.PP
Definition at line 159 of file grub\&.h\&.
.SS "unsigned short pitch"

.PP
Definition at line 146 of file grub\&.h\&.
.SS "unsigned char planes"

.PP
Definition at line 149 of file grub\&.h\&.
.SS "unsigned int realFctPtr"

.PP
Definition at line 145 of file grub\&.h\&.
.SS "unsigned char red_mask"

.PP
Definition at line 153 of file grub\&.h\&.
.SS "unsigned char red_position"

.PP
Definition at line 153 of file grub\&.h\&.
.SS "unsigned char reserved0"

.PP
Definition at line 151 of file grub\&.h\&.
.SS "unsigned int reserved1"

.PP
Definition at line 160 of file grub\&.h\&.
.SS "short reserved2"

.PP
Definition at line 161 of file grub\&.h\&.
.SS "unsigned char rsv_mask"

.PP
Definition at line 156 of file grub\&.h\&.
.SS "unsigned char rsv_position"

.PP
Definition at line 156 of file grub\&.h\&.
.SS "unsigned short segmentA"

.PP
Definition at line 144 of file grub\&.h\&.
.SS "unsigned short segmentB"

.PP
Definition at line 144 of file grub\&.h\&.
.SS "unsigned char Wchar"

.PP
Definition at line 149 of file grub\&.h\&.
.SS "unsigned char winA"

.PP
Definition at line 141 of file grub\&.h\&.
.SS "unsigned char winB"

.PP
Definition at line 141 of file grub\&.h\&.
.SS "unsigned short winsize"

.PP
Definition at line 143 of file grub\&.h\&.
.SS "unsigned short Xres"

.PP
Definition at line 148 of file grub\&.h\&.
.SS "unsigned char Ychar"

.PP
Definition at line 149 of file grub\&.h\&.
.SS "unsigned short Yres"

.PP
Definition at line 148 of file grub\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
