.TH "src/mm/heap.c" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mm/heap.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <aplus/mm\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBhalloc\fP (\fBheap_t\fP *\fBheap\fP, size_t \fBsize\fP)"
.br
.ti -1c
.RI "void \fBhfree\fP (\fBheap_t\fP *\fBheap\fP, void *addr, size_t \fBsize\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* halloc (\fBheap_t\fP *heap, size_tsize)"

.PP
Definition at line 28 of file heap\&.c\&.
.PP
References heap::alloc\&.
.PP
.nf
28                                         {
29     if(heap)
30         if(heap->alloc)
31             return heap->alloc(heap, size);
32             
33     return 0;
34 }
.fi
.SS "void hfree (\fBheap_t\fP *heap, void *addr, size_tsize)"

.PP
Definition at line 36 of file heap\&.c\&.
.PP
References heap::free\&.
.PP
.nf
36                                                   {
37     if(heap)
38         if(heap->free)
39             heap->free(heap, addr, size);
40 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
