.TH "usr/src/libpthread/src/platform/win32/hooks.h" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libpthread/src/platform/win32/hooks.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <windows\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__os_thread_create\fP(e, a, p)   ((int) CreateThread(0, 0, e, a, 0))"
.br
.ti -1c
.RI "#define \fB__os_thread_kill\fP(t, s)   TerminateThread(t, s)"
.br
.ti -1c
.RI "#define \fB__os_gettid\fP()   GetCurrentThreadId()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __os_gettid()   GetCurrentThreadId()"

.PP
Definition at line 11 of file hooks\&.h\&.
.SS "#define __os_thread_create(e, a, p)   ((int) CreateThread(0, 0, e, a, 0))"

.PP
Definition at line 9 of file hooks\&.h\&.
.SS "#define __os_thread_kill(t, s)   TerminateThread(t, s)"

.PP
Definition at line 10 of file hooks\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
