.TH "inode" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [255]"
.br
.ti -1c
.RI "dev_t \fBdev\fP"
.br
.ti -1c
.RI "ino_t \fBino\fP"
.br
.ti -1c
.RI "mode_t \fBmode\fP"
.br
.ti -1c
.RI "nlink_t \fBnlink\fP"
.br
.ti -1c
.RI "uid_t \fBuid\fP"
.br
.ti -1c
.RI "gid_t \fBgid\fP"
.br
.ti -1c
.RI "dev_t \fBrdev\fP"
.br
.ti -1c
.RI "off_t \fBsize\fP"
.br
.ti -1c
.RI "off_t \fBposition\fP"
.br
.ti -1c
.RI "time_t \fBatime\fP"
.br
.ti -1c
.RI "time_t \fBmtime\fP"
.br
.ti -1c
.RI "time_t \fBctime\fP"
.br
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.ti -1c
.RI "int(* \fBread\fP )(struct \fBinode\fP *\fBinode\fP, char *ptr, int len)"
.br
.ti -1c
.RI "int(* \fBwrite\fP )(struct \fBinode\fP *\fBinode\fP, char *ptr, int len)"
.br
.ti -1c
.RI "struct \fBdirent\fP *(* \fBreaddir\fP )(struct \fBinode\fP *\fBinode\fP, int index)"
.br
.ti -1c
.RI "struct \fBinode\fP *(* \fBfinddir\fP )(struct \fBinode\fP *\fBinode\fP, char *\fBname\fP)"
.br
.ti -1c
.RI "struct \fBinode\fP *(* \fBcreat\fP )(struct \fBinode\fP *\fBinode\fP, char *\fBname\fP, mode_t \fBmode\fP)"
.br
.ti -1c
.RI "int(* \fBrename\fP )(struct \fBinode\fP *\fBinode\fP, char *oldname, char *newname)"
.br
.ti -1c
.RI "int(* \fBunlink\fP )(struct \fBinode\fP *\fBinode\fP, char *\fBname\fP)"
.br
.ti -1c
.RI "int(* \fBchown\fP )(struct \fBinode\fP *\fBinode\fP, uid_t owner, gid_t group)"
.br
.ti -1c
.RI "void(* \fBflush\fP )(struct \fBinode\fP *\fBinode\fP)"
.br
.ti -1c
.RI "int(* \fBioctl\fP )(struct \fBinode\fP *\fBinode\fP, int req, void *buf)"
.br
.ti -1c
.RI "struct \fBinode\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct \fBinode\fP * \fBlink\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file fs\&.h\&.
.SH "Field Documentation"
.PP 
.SS "time_t inode::atime"

.PP
Definition at line 50 of file fs\&.h\&.
.SS "int(* inode::chown)(struct \fBinode\fP *\fBinode\fP, uid_t owner, gid_t group)"

.PP
Definition at line 65 of file fs\&.h\&.
.SS "struct \fBinode\fP*(* inode::creat)(struct \fBinode\fP *\fBinode\fP, char *\fBname\fP, mode_t \fBmode\fP)"

.PP
Definition at line 61 of file fs\&.h\&.
.SS "time_t inode::ctime"

.PP
Definition at line 52 of file fs\&.h\&.
.SS "dev_t inode::dev"

.PP
Definition at line 40 of file fs\&.h\&.
.SS "struct \fBinode\fP*(* inode::finddir)(struct \fBinode\fP *\fBinode\fP, char *\fBname\fP)"

.PP
Definition at line 60 of file fs\&.h\&.
.SS "void(* inode::flush)(struct \fBinode\fP *\fBinode\fP)"

.PP
Definition at line 66 of file fs\&.h\&.
.SS "gid_t inode::gid"

.PP
Definition at line 45 of file fs\&.h\&.
.SS "ino_t inode::ino"

.PP
Definition at line 41 of file fs\&.h\&.
.SS "int(* inode::ioctl)(struct \fBinode\fP *\fBinode\fP, int req, void *buf)"

.PP
Definition at line 68 of file fs\&.h\&.
.SS "struct \fBinode\fP* inode::link"

.PP
Definition at line 72 of file fs\&.h\&.
.SS "mode_t inode::mode"

.PP
Definition at line 42 of file fs\&.h\&.
.SS "time_t inode::mtime"

.PP
Definition at line 51 of file fs\&.h\&.
.SS "char inode::name[255]"

.PP
Definition at line 38 of file fs\&.h\&.
.SS "nlink_t inode::nlink"

.PP
Definition at line 43 of file fs\&.h\&.
.SS "struct \fBinode\fP* inode::parent"

.PP
Definition at line 71 of file fs\&.h\&.
.SS "off_t inode::position"

.PP
Definition at line 48 of file fs\&.h\&.
.SS "dev_t inode::rdev"

.PP
Definition at line 46 of file fs\&.h\&.
.SS "int(* inode::read)(struct \fBinode\fP *\fBinode\fP, char *ptr, int len)"

.PP
Definition at line 56 of file fs\&.h\&.
.SS "struct \fBdirent\fP*(* inode::readdir)(struct \fBinode\fP *\fBinode\fP, int index)"

.PP
Definition at line 59 of file fs\&.h\&.
.SS "int(* inode::rename)(struct \fBinode\fP *\fBinode\fP, char *oldname, char *newname)"

.PP
Definition at line 63 of file fs\&.h\&.
.SS "off_t inode::size"

.PP
Definition at line 47 of file fs\&.h\&.
.SS "uid_t inode::uid"

.PP
Definition at line 44 of file fs\&.h\&.
.SS "int(* inode::unlink)(struct \fBinode\fP *\fBinode\fP, char *\fBname\fP)"

.PP
Definition at line 64 of file fs\&.h\&.
.SS "void* inode::userdata"

.PP
Definition at line 54 of file fs\&.h\&.
.SS "int(* inode::write)(struct \fBinode\fP *\fBinode\fP, char *ptr, int len)"

.PP
Definition at line 57 of file fs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
