.TH "ipv4_header" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ipv4_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ipv4\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBinfo\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBtos\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBlength\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBid\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBoffset\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBttl\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBprotocol\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBchecksum\fP"
.br
.ti -1c
.RI "\fBipv4_t\fP \fBsource\fP"
.br
.ti -1c
.RI "\fBipv4_t\fP \fBdest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file ipv4\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint16_t\fP ipv4_header::checksum"

.PP
Definition at line 38 of file ipv4\&.h\&.
.SS "\fBipv4_t\fP ipv4_header::dest"

.PP
Definition at line 41 of file ipv4\&.h\&.
.SS "\fBuint16_t\fP ipv4_header::id"

.PP
Definition at line 34 of file ipv4\&.h\&.
.SS "\fBuint8_t\fP ipv4_header::info"

.PP
Definition at line 31 of file ipv4\&.h\&.
.SS "\fBuint16_t\fP ipv4_header::length"

.PP
Definition at line 33 of file ipv4\&.h\&.
.SS "\fBuint16_t\fP ipv4_header::offset"

.PP
Definition at line 35 of file ipv4\&.h\&.
.SS "\fBuint8_t\fP ipv4_header::protocol"

.PP
Definition at line 37 of file ipv4\&.h\&.
.SS "\fBipv4_t\fP ipv4_header::source"

.PP
Definition at line 40 of file ipv4\&.h\&.
.SS "\fBuint8_t\fP ipv4_header::tos"

.PP
Definition at line 32 of file ipv4\&.h\&.
.SS "\fBuint8_t\fP ipv4_header::ttl"

.PP
Definition at line 36 of file ipv4\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
