.TH "src/include/aplus/net/ipv4.h" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/aplus/net/ipv4.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <aplus/netif\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBipv4_header\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_IPV4_h\fP"
.br
.ti -1c
.RI "#define \fBIPV4_FLAGS_DF\fP   0x01	/* Don't fragment */"
.br
.ti -1c
.RI "#define \fBIPV4_FLAGS_MF\fP   0x02	/* More fragment */"
.br
.ti -1c
.RI "#define \fBIPV4_CHECK_VERSION\fP(head)   ((head->\fBinfo\fP & 0x0F) == 4)"
.br
.ti -1c
.RI "#define \fBIPV4_HEADER_LENGTH\fP(head)   (((head->\fBinfo\fP & 0xF0) >> 4) * 4)"
.br
.ti -1c
.RI "#define \fBIPV4_FLAGS\fP(head)   (head->\fBoffset\fP & 3)"
.br
.ti -1c
.RI "#define \fBIPV4_OFFSET\fP(head)   ((head->\fBoffset\fP >> 2) * 8)"
.br
.ti -1c
.RI "#define \fBIPV4_TOS_PRIORITY\fP(\fBtos\fP)   (\fBtos\fP & 3)"
.br
.ti -1c
.RI "#define \fBIPV4_TOS_LATENCY\fP(\fBtos\fP)   ((\fBtos\fP >> 2) & 1)"
.br
.ti -1c
.RI "#define \fBIPV4_TOS_TROUGHPUT\fP(\fBtos\fP)   ((\fBtos\fP >> 3) & 1)"
.br
.ti -1c
.RI "#define \fBIPV4_TOS_RELIABILITY\fP(\fBtos\fP)   ((\fBtos\fP >> 4) & 1)"
.br
.ti -1c
.RI "#define \fBIPV4_PROTO_RAW\fP   0"
.br
.ti -1c
.RI "#define \fBIPV4_PROTO_ICMP\fP   1"
.br
.ti -1c
.RI "#define \fBIPV4_PROTO_TCP\fP   6"
.br
.ti -1c
.RI "#define \fBIPV4_PROTO_UDP\fP   17"
.br
.ti -1c
.RI "#define \fBIPV4_MAX_LENGTH\fP   65536"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBipv4_header\fP \fB__attribute__\fP ((packed)) ipv4_header_t"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBinfo\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBtos\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBlength\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBid\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBoffset\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBttl\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBprotocol\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBchecksum\fP"
.br
.ti -1c
.RI "\fBipv4_t\fP \fBsource\fP"
.br
.ti -1c
.RI "\fBipv4_t\fP \fBdest\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _IPV4_h"

.PP
Definition at line 2 of file ipv4\&.h\&.
.SS "#define IPV4_CHECK_VERSION(head)   ((head->\fBinfo\fP & 0x0F) == 4)"

.PP
Definition at line 11 of file ipv4\&.h\&.
.SS "#define IPV4_FLAGS(head)   (head->\fBoffset\fP & 3)"

.PP
Definition at line 13 of file ipv4\&.h\&.
.SS "#define IPV4_FLAGS_DF   0x01	/* Don't fragment */"

.PP
Definition at line 8 of file ipv4\&.h\&.
.SS "#define IPV4_FLAGS_MF   0x02	/* More fragment */"

.PP
Definition at line 9 of file ipv4\&.h\&.
.SS "#define IPV4_HEADER_LENGTH(head)   (((head->\fBinfo\fP & 0xF0) >> 4) * 4)"

.PP
Definition at line 12 of file ipv4\&.h\&.
.SS "#define IPV4_MAX_LENGTH   65536"

.PP
Definition at line 27 of file ipv4\&.h\&.
.SS "#define IPV4_OFFSET(head)   ((head->\fBoffset\fP >> 2) * 8)"

.PP
Definition at line 14 of file ipv4\&.h\&.
.SS "#define IPV4_PROTO_ICMP   1"

.PP
Definition at line 23 of file ipv4\&.h\&.
.SS "#define IPV4_PROTO_RAW   0"

.PP
Definition at line 22 of file ipv4\&.h\&.
.SS "#define IPV4_PROTO_TCP   6"

.PP
Definition at line 24 of file ipv4\&.h\&.
.SS "#define IPV4_PROTO_UDP   17"

.PP
Definition at line 25 of file ipv4\&.h\&.
.SS "#define IPV4_TOS_LATENCY(\fBtos\fP)   ((\fBtos\fP >> 2) & 1)"

.PP
Definition at line 17 of file ipv4\&.h\&.
.SS "#define IPV4_TOS_PRIORITY(\fBtos\fP)   (\fBtos\fP & 3)"

.PP
Definition at line 16 of file ipv4\&.h\&.
.SS "#define IPV4_TOS_RELIABILITY(\fBtos\fP)   ((\fBtos\fP >> 4) & 1)"

.PP
Definition at line 19 of file ipv4\&.h\&.
.SS "#define IPV4_TOS_TROUGHPUT(\fBtos\fP)   ((\fBtos\fP >> 3) & 1)"

.PP
Definition at line 18 of file ipv4\&.h\&.
.SH "Function Documentation"
.PP 
.SS "struct \fBipv4_header\fP __attribute__ ((packed))"

.PP
Definition at line 44 of file desc\&.c\&.
.PP
.nf
46                        {
47     uint16_t limit;
48     uint32_t base;
49 } __attribute__((packed)) gdt_ptr_t;
.fi
.SH "Variable Documentation"
.PP 
.SS "\fBuint16_t\fP checksum"

.PP
Definition at line 54 of file ipv4\&.h\&.
.SS "\fBipv4_t\fP dest"

.PP
Definition at line 57 of file ipv4\&.h\&.
.SS "\fBuint16_t\fP id"

.PP
Definition at line 50 of file ipv4\&.h\&.
.SS "\fBuint8_t\fP info"

.PP
Definition at line 47 of file ipv4\&.h\&.
.SS "\fBuint16_t\fP length"

.PP
Definition at line 49 of file ipv4\&.h\&.
.SS "\fBuint16_t\fP offset"

.PP
Definition at line 51 of file ipv4\&.h\&.
.SS "\fBuint8_t\fP protocol"

.PP
Definition at line 53 of file ipv4\&.h\&.
.SS "\fBipv4_t\fP source"

.PP
Definition at line 56 of file ipv4\&.h\&.
.SS "\fBuint8_t\fP tos"

.PP
Definition at line 48 of file ipv4\&.h\&.
.SS "\fBuint8_t\fP ttl"

.PP
Definition at line 52 of file ipv4\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
