.TH "ipv6_header" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ipv6_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ipv6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBversion\fP:4"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBtraffic\fP:8"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBflow\fP:20"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBlength\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBprotocol\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBttl\fP"
.br
.ti -1c
.RI "\fBipv6_t\fP \fBsource\fP"
.br
.ti -1c
.RI "\fBipv6_t\fP \fBdest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file ipv6\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBipv6_t\fP ipv6_header::dest"

.PP
Definition at line 25 of file ipv6\&.h\&.
.SS "\fBuint32_t\fP ipv6_header::flow"

.PP
Definition at line 18 of file ipv6\&.h\&.
.SS "\fBuint16_t\fP ipv6_header::length"

.PP
Definition at line 20 of file ipv6\&.h\&.
.SS "\fBuint8_t\fP ipv6_header::protocol"

.PP
Definition at line 21 of file ipv6\&.h\&.
.SS "\fBipv6_t\fP ipv6_header::source"

.PP
Definition at line 24 of file ipv6\&.h\&.
.SS "\fBuint32_t\fP ipv6_header::traffic"

.PP
Definition at line 17 of file ipv6\&.h\&.
.SS "\fBuint8_t\fP ipv6_header::ttl"

.PP
Definition at line 22 of file ipv6\&.h\&.
.SS "\fBuint32_t\fP ipv6_header::version"

.PP
Definition at line 16 of file ipv6\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
