.TH "src/syscall/isatty.c" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syscall/isatty.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <aplus\&.h>\fP
.br
\fC#include <aplus/syscall\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsys_isatty\fP (int fd)"
.br
.ti -1c
.RI "\fBSYSCALL\fP (\fBsys_isatty\fP, 6)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int sys_isatty (intfd)"

.PP
Definition at line 5 of file isatty\&.c\&.
.PP
.nf
5                        {
6     return (fd < 3);
7 }
.fi
.SS "SYSCALL (\fBsys_isatty\fP, 6)"

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
