.TH "iso9660_volume_descriptor" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iso9660_volume_descriptor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iso9660\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int8_t \fBtype\fP"
.br
.ti -1c
.RI "char \fBid\fP [5]"
.br
.ti -1c
.RI "int8_t \fBversion\fP"
.br
.ti -1c
.RI "char \fBdata\fP [2041]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file iso9660\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char iso9660_volume_descriptor::data[2041]"

.PP
Definition at line 33 of file iso9660\&.h\&.
.SS "char iso9660_volume_descriptor::id[5]"

.PP
Definition at line 31 of file iso9660\&.h\&.
.SS "int8_t iso9660_volume_descriptor::type"

.PP
Definition at line 30 of file iso9660\&.h\&.
.SS "int8_t iso9660_volume_descriptor::version"

.PP
Definition at line 32 of file iso9660\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
