src/fs/iso9660/iso9660_read.c
NAME
src/fs/iso9660/iso9660_read.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/fs.h>
#include <aplus/task.h>
#include <aplus/spinlock.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <dirent.h>
#include <fcntl.h>
#include <sys/types.h>
#include 'iso9660.h'
Functions
int iso9660_read (inode_t *ino, char *buf, int size)
Function Documentation
int iso9660_read (inode_t *ino, char *buf, intsize)
Definition at line 16 of file iso9660_read.c.
References inode::dev, devfs_getdevice(), fs_read(), ISO9660_SECTOR_SIZE, kfree(), kmalloc(), inode::position, inode::size, size, uint32_t, and inode::userdata.
                                                    {
    if(!ino)
        return 0;
        
    if(!buf)
        return 0;
        
    if(size > ino->size)
        size = ino->size;
        
    if(ino->position > ino->size)
        ino->position = ino->size;
        
    if(ino->position + size > ino->size)
        size = ino->size - ino->position;
        
    if(!size)
        return 0;
    inode_t* dev = (inode_t*) devfs_getdevice(ino->dev);
    if(!dev)
        return 0;
    void* tbuf = (void*) kmalloc(((size / ISO9660_SECTOR_SIZE) + 1) * ISO9660_SECTOR_SIZE);
    
    dev->position = (off_t) ino->userdata + (ino->position / ISO9660_SECTOR_SIZE);
    fs_read(dev, tbuf, ((size / ISO9660_SECTOR_SIZE) + 1) * ISO9660_SECTOR_SIZE);
    memcpy(buf, (void*) ((uint32_t) tbuf + (ino->position % ISO9660_SECTOR_SIZE)), size);
    kfree(tbuf);
    return size;
}
Author
Generated automatically by Doxygen for aPlus from the source code.