.TH "iso9660_pvd" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iso9660_pvd \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iso9660\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int8_t \fBtype\fP"
.br
.ti -1c
.RI "char \fBid\fP [5]"
.br
.ti -1c
.RI "int8_t \fBversion\fP"
.br
.ti -1c
.RI "int8_t \fBunused\fP"
.br
.ti -1c
.RI "char \fBsysid\fP [32]"
.br
.ti -1c
.RI "char \fBvolid\fP [32]"
.br
.ti -1c
.RI "char \fBnull0\fP [8]"
.br
.ti -1c
.RI "uint64_t \fBvolsize\fP"
.br
.ti -1c
.RI "char \fBnull1\fP [32]"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBvolsetsize\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBvolnumber\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBlogical_blksize\fP"
.br
.ti -1c
.RI "uint64_t \fBpath_size\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBpath_lba\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBoptpath_lba\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBpath_lba_msb\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBoptpath_lba_msb\fP"
.br
.ti -1c
.RI "char \fBrootdir\fP [34]"
.br
.ti -1c
.RI "char \fBvolsetid\fP [128]"
.br
.ti -1c
.RI "char \fBpubid\fP [128]"
.br
.ti -1c
.RI "char \fBdataid\fP [128]"
.br
.ti -1c
.RI "char \fBappid\fP [128]"
.br
.ti -1c
.RI "char \fBcopyid\fP [38]"
.br
.ti -1c
.RI "char \fBabstractfileid\fP [36]"
.br
.ti -1c
.RI "char \fBbibid\fP [37]"
.br
.ti -1c
.RI "char \fBcdate\fP [17]"
.br
.ti -1c
.RI "char \fBmdate\fP [17]"
.br
.ti -1c
.RI "char \fBedate\fP [17]"
.br
.ti -1c
.RI "char \fBefdate\fP [17]"
.br
.ti -1c
.RI "int8_t \fBfileversion\fP"
.br
.ti -1c
.RI "int8_t \fBunused0\fP"
.br
.ti -1c
.RI "char \fBnull2\fP [512]"
.br
.ti -1c
.RI "char \fBreserved\fP [653]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file iso9660\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char iso9660_pvd::abstractfileid[36]"

.PP
Definition at line 65 of file iso9660\&.h\&.
.SS "char iso9660_pvd::appid[128]"

.PP
Definition at line 63 of file iso9660\&.h\&.
.SS "char iso9660_pvd::bibid[37]"

.PP
Definition at line 66 of file iso9660\&.h\&.
.SS "char iso9660_pvd::cdate[17]"

.PP
Definition at line 67 of file iso9660\&.h\&.
.SS "char iso9660_pvd::copyid[38]"

.PP
Definition at line 64 of file iso9660\&.h\&.
.SS "char iso9660_pvd::dataid[128]"

.PP
Definition at line 62 of file iso9660\&.h\&.
.SS "char iso9660_pvd::edate[17]"

.PP
Definition at line 69 of file iso9660\&.h\&.
.SS "char iso9660_pvd::efdate[17]"

.PP
Definition at line 70 of file iso9660\&.h\&.
.SS "int8_t iso9660_pvd::fileversion"

.PP
Definition at line 71 of file iso9660\&.h\&.
.SS "char iso9660_pvd::id[5]"

.PP
Definition at line 38 of file iso9660\&.h\&.
.SS "\fBuint32_t\fP iso9660_pvd::logical_blksize"

.PP
Definition at line 52 of file iso9660\&.h\&.
.SS "char iso9660_pvd::mdate[17]"

.PP
Definition at line 68 of file iso9660\&.h\&.
.SS "char iso9660_pvd::null0[8]"

.PP
Definition at line 44 of file iso9660\&.h\&.
.SS "char iso9660_pvd::null1[32]"

.PP
Definition at line 48 of file iso9660\&.h\&.
.SS "char iso9660_pvd::null2[512]"

.PP
Definition at line 73 of file iso9660\&.h\&.
.SS "\fBuint32_t\fP iso9660_pvd::optpath_lba"

.PP
Definition at line 55 of file iso9660\&.h\&.
.SS "\fBuint32_t\fP iso9660_pvd::optpath_lba_msb"

.PP
Definition at line 57 of file iso9660\&.h\&.
.SS "\fBuint32_t\fP iso9660_pvd::path_lba"

.PP
Definition at line 54 of file iso9660\&.h\&.
.SS "\fBuint32_t\fP iso9660_pvd::path_lba_msb"

.PP
Definition at line 56 of file iso9660\&.h\&.
.SS "uint64_t iso9660_pvd::path_size"

.PP
Definition at line 53 of file iso9660\&.h\&.
.SS "char iso9660_pvd::pubid[128]"

.PP
Definition at line 61 of file iso9660\&.h\&.
.SS "char iso9660_pvd::reserved[653]"

.PP
Definition at line 74 of file iso9660\&.h\&.
.SS "char iso9660_pvd::rootdir[34]"

.PP
Definition at line 59 of file iso9660\&.h\&.
.SS "char iso9660_pvd::sysid[32]"

.PP
Definition at line 42 of file iso9660\&.h\&.
.SS "int8_t iso9660_pvd::type"

.PP
Definition at line 37 of file iso9660\&.h\&.
.SS "int8_t iso9660_pvd::unused"

.PP
Definition at line 40 of file iso9660\&.h\&.
.SS "int8_t iso9660_pvd::unused0"

.PP
Definition at line 72 of file iso9660\&.h\&.
.SS "int8_t iso9660_pvd::version"

.PP
Definition at line 39 of file iso9660\&.h\&.
.SS "char iso9660_pvd::volid[32]"

.PP
Definition at line 43 of file iso9660\&.h\&.
.SS "\fBuint32_t\fP iso9660_pvd::volnumber"

.PP
Definition at line 51 of file iso9660\&.h\&.
.SS "char iso9660_pvd::volsetid[128]"

.PP
Definition at line 60 of file iso9660\&.h\&.
.SS "\fBuint32_t\fP iso9660_pvd::volsetsize"

.PP
Definition at line 50 of file iso9660\&.h\&.
.SS "uint64_t iso9660_pvd::volsize"

.PP
Definition at line 46 of file iso9660\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
