src/fs/iso9660/iso9660_readdir.c
NAME
src/fs/iso9660/iso9660_readdir.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/fs.h>
#include <aplus/task.h>
#include <aplus/spinlock.h>
#include <aplus/mm.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <dirent.h>
#include <fcntl.h>
#include <sys/types.h>
#include 'iso9660.h'
Functions
struct dirent * iso9660_readdir (inode_t *ino, int index)
Function Documentation
struct dirent* iso9660_readdir (inode_t *ino, intindex)
Definition at line 16 of file iso9660_readdir.c.
References dirent::d_ino, dirent::d_name, inode::dev, devfs_getdevice(), fs_read(), iso9660_checkname(), iso9660_getlsb32(), ISO9660_SECTOR_SIZE, kfree(), kmalloc(), inode::position, uint32_t, and inode::userdata.
                                                        {
    if(!ino)
        return NULL;
        
    if(!ino->dev)
        return NULL;
    if(!ino->userdata)
        return NULL;
    inode_t* dev = (inode_t*) devfs_getdevice(ino->dev);
    if(!dev)
        return NULL;
    iso9660_dir_t* dir = (iso9660_dir_t*) ino->userdata;
    iso9660_dir_t* nodes = (iso9660_dir_t*) kmalloc(iso9660_getlsb32(dir->length));
    iso9660_dir_t* snodes = nodes;
    dev->position = iso9660_getlsb32(dir->lba) * ISO9660_SECTOR_SIZE;
    if(fs_read(dev, nodes, iso9660_getlsb32(dir->length)) != iso9660_getlsb32(dir->length)) {
        kfree(nodes);
        return NULL;
    }
    /* Skip dots (".", "..") */
    nodes = (iso9660_dir_t*) ((uint32_t) nodes + nodes->size);
    nodes = (iso9660_dir_t*) ((uint32_t) nodes + nodes->size);
    for(int i = 0; i < index; i++) {
        if(nodes->size == 0) {
            kfree(snodes);
            return NULL;
        }
        
        nodes = (iso9660_dir_t*) ((uint32_t) nodes + nodes->size);
    }
    if(nodes->size == 0) {
        kfree(snodes);
        return NULL;
    }
    struct dirent* ent = (struct dirent*) kmalloc(sizeof(struct dirent));
    memset(ent, 0, sizeof(struct dirent));
    
    strncpy(ent->d_name, nodes->reserved, nodes->idlen);
    iso9660_checkname(ent->d_name);
    ent->d_ino = 0;
    kfree(snodes);
    return ent;
}
Author
Generated automatically by Doxygen for aPlus from the source code.