src/fs/iso9660/iso9660_finddir.c
NAME
src/fs/iso9660/iso9660_finddir.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/fs.h>
#include <aplus/task.h>
#include <aplus/spinlock.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <dirent.h>
#include <fcntl.h>
#include <sys/types.h>
#include 'iso9660.h'
Functions
int iso9660_read (inode_t *, char *, int)
struct dirent * iso9660_readdir (inode_t *, int)
inode_t * iso9660_finddir (inode_t *ino, char *name)
Function Documentation
inode_t* iso9660_finddir (inode_t *ino, char *name)
Definition at line 20 of file iso9660_finddir.c.
References inode::atime, inode::chown, inode::creat, inode::ctime, inode::dev, devfs_getdevice(), inode::finddir, inode::flush, fs_read(), inode::gid, inode::ino, inode::ioctl, iso9660_checkname(), iso9660_finddir(), ISO9660_FLAGS_DIRECTORY, iso9660_getlsb32(), iso9660_read(), iso9660_readdir(), ISO9660_SECTOR_SIZE, kfree(), kmalloc(), inode::link, inode::mode, inode::mtime, inode::name, inode::nlink, inode::parent, inode::position, inode::rdev, inode::read, inode::readdir, inode::rename, inode::size, sys_time(), inode::uid, uint32_t, inode::unlink, inode::userdata, and inode::write.
                                                   {
    if(!ino)
        return NULL;
        
    if(!ino->dev)
        return NULL;
    if(!ino->userdata)
        return NULL;
    if(!name || strlen(name) == 0)
        return NULL;
    inode_t* dev = (inode_t*) devfs_getdevice(ino->dev);
    if(!dev)
        return NULL;
    iso9660_dir_t* dir = (iso9660_dir_t*) ino->userdata;
    iso9660_dir_t* nodes = (iso9660_dir_t*) kmalloc(iso9660_getlsb32(dir->length));
    iso9660_dir_t* snodes = nodes;
    dev->position = iso9660_getlsb32(dir->lba) * ISO9660_SECTOR_SIZE;
    if(fs_read(dev, nodes, iso9660_getlsb32(dir->length)) != iso9660_getlsb32(dir->length)) {
        kfree(nodes);
        return NULL;
    }
    for(;;) {
        if(nodes->size == 0) {
            kfree(snodes);
            return 0;
        }
        char* nodename = (char*) kmalloc(nodes->idlen);
        memset(nodename, 0, nodes->idlen);
        strncpy(nodename, nodes->reserved, nodes->idlen);
        iso9660_checkname(nodename);
        if(strcmp(nodename, name) == 0)
            break;
        kfree(nodename);
        nodes = (iso9660_dir_t*) ((uint32_t) nodes + nodes->size);
    }
    inode_t* f = (inode_t*) kmalloc(sizeof(inode_t));
    memset(f, 0, sizeof(inode_t));
    strcpy(f->name, name);
    
    f->dev = ino->dev;
    f->ino = 0;
    f->nlink = 0;
    f->uid = ino->uid;
    f->gid = ino->gid;
    f->rdev = ino->rdev;
    f->size = (size_t) iso9660_getlsb32(nodes->length);
    f->atime = f->ctime = f->mtime = sys_time(NULL);
    f->parent = ino;
    f->link = NULL;
    
    if(nodes->flags & ISO9660_FLAGS_DIRECTORY) {
        f->readdir = iso9660_readdir;
        f->finddir = iso9660_finddir;
        f->mode = S_IFDIR;
        iso9660_dir_t* entry = (iso9660_dir_t*) kmalloc(ISO9660_SECTOR_SIZE);
        memset(entry, 0, ISO9660_SECTOR_SIZE);
        dev->position = iso9660_getlsb32(nodes->lba) * ISO9660_SECTOR_SIZE;
        fs_read(dev, entry, ISO9660_SECTOR_SIZE);
        f->userdata = (void*) entry;
    } else {
        f->read = iso9660_read;
        f->write = NULL; /* Read Only */
        f->mode = S_IFREG;
        f->userdata = (void*) (iso9660_getlsb32(nodes->lba) * ISO9660_SECTOR_SIZE);
    }
    f->creat = NULL;
    f->rename = NULL;
    f->unlink = NULL;
    f->chown = NULL;
    f->flush = NULL;
    f->ioctl = NULL;
    
    kfree(snodes);
    return f;
}
int iso9660_read (inode_t *, char *, int)
Definition at line 16 of file iso9660_read.c.
References inode::dev, devfs_getdevice(), fs_read(), ISO9660_SECTOR_SIZE, kfree(), kmalloc(), inode::position, inode::size, size, uint32_t, and inode::userdata.
                                                    {
    if(!ino)
        return 0;
        
    if(!buf)
        return 0;
        
    if(size > ino->size)
        size = ino->size;
        
    if(ino->position > ino->size)
        ino->position = ino->size;
        
    if(ino->position + size > ino->size)
        size = ino->size - ino->position;
        
    if(!size)
        return 0;
    inode_t* dev = (inode_t*) devfs_getdevice(ino->dev);
    if(!dev)
        return 0;
    void* tbuf = (void*) kmalloc(((size / ISO9660_SECTOR_SIZE) + 1) * ISO9660_SECTOR_SIZE);
    
    dev->position = (off_t) ino->userdata + (ino->position / ISO9660_SECTOR_SIZE);
    fs_read(dev, tbuf, ((size / ISO9660_SECTOR_SIZE) + 1) * ISO9660_SECTOR_SIZE);
    memcpy(buf, (void*) ((uint32_t) tbuf + (ino->position % ISO9660_SECTOR_SIZE)), size);
    kfree(tbuf);
    return size;
}
struct dirent* iso9660_readdir (inode_t *, int)
Definition at line 15 of file iso9660_readdir.c.
                                                        {
    if(!ino)
        return NULL;
        
    if(!ino->dev)
        return NULL;
    if(!ino->userdata)
        return NULL;
    inode_t* dev = (inode_t*) devfs_getdevice(ino->dev);
    if(!dev)
        return NULL;
    iso9660_dir_t* dir = (iso9660_dir_t*) ino->userdata;
    iso9660_dir_t* nodes = (iso9660_dir_t*) kmalloc(iso9660_getlsb32(dir->length));
    iso9660_dir_t* snodes = nodes;
    dev->position = iso9660_getlsb32(dir->lba) * ISO9660_SECTOR_SIZE;
    if(fs_read(dev, nodes, iso9660_getlsb32(dir->length)) != iso9660_getlsb32(dir->length)) {
        kfree(nodes);
        return NULL;
    }
    /* Skip dots (".", "..") */
    nodes = (iso9660_dir_t*) ((uint32_t) nodes + nodes->size);
    nodes = (iso9660_dir_t*) ((uint32_t) nodes + nodes->size);
    for(int i = 0; i < index; i++) {
        if(nodes->size == 0) {
            kfree(snodes);
            return NULL;
        }
        
        nodes = (iso9660_dir_t*) ((uint32_t) nodes + nodes->size);
    }
    if(nodes->size == 0) {
        kfree(snodes);
        return NULL;
    }
    struct dirent* ent = (struct dirent*) kmalloc(sizeof(struct dirent));
    memset(ent, 0, sizeof(struct dirent));
    
    strncpy(ent->d_name, nodes->reserved, nodes->idlen);
    iso9660_checkname(ent->d_name);
    ent->d_ino = 0;
    kfree(snodes);
    return ent;
}
Author
Generated automatically by Doxygen for aPlus from the source code.