.TH "iso9660_dir" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iso9660_dir \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iso9660\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBexattr\fP"
.br
.ti -1c
.RI "uint64_t \fBlba\fP"
.br
.ti -1c
.RI "uint64_t \fBlength\fP"
.br
.ti -1c
.RI "char \fBdate\fP [7]"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBunitsize\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBgapsize\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBvolnumber\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBidlen\fP"
.br
.ti -1c
.RI "char \fBreserved\fP [0]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file iso9660\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char iso9660_dir::date[7]"

.PP
Definition at line 83 of file iso9660\&.h\&.
.SS "\fBuint8_t\fP iso9660_dir::exattr"

.PP
Definition at line 80 of file iso9660\&.h\&.
.SS "\fBuint8_t\fP iso9660_dir::flags"

.PP
Definition at line 84 of file iso9660\&.h\&.
.SS "\fBuint8_t\fP iso9660_dir::gapsize"

.PP
Definition at line 86 of file iso9660\&.h\&.
.SS "\fBuint8_t\fP iso9660_dir::idlen"

.PP
Definition at line 88 of file iso9660\&.h\&.
.SS "uint64_t iso9660_dir::lba"

.PP
Definition at line 81 of file iso9660\&.h\&.
.SS "uint64_t iso9660_dir::length"

.PP
Definition at line 82 of file iso9660\&.h\&.
.SS "char iso9660_dir::reserved[0]"

.PP
Definition at line 89 of file iso9660\&.h\&.
.SS "\fBuint8_t\fP iso9660_dir::size"

.PP
Definition at line 79 of file iso9660\&.h\&.
.SS "\fBuint8_t\fP iso9660_dir::unitsize"

.PP
Definition at line 85 of file iso9660\&.h\&.
.SS "\fBuint32_t\fP iso9660_dir::volnumber"

.PP
Definition at line 87 of file iso9660\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
