src/mm/kheap.c
NAME
src/mm/kheap.c -
SYNOPSIS
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <sys/types.h>
#include <aplus/mm.h>
#include <grub.h>
Macros
#define BITMAP_SET(bmp, bit) bmp[bit / 32] |= (1 << (bit % 32))
#define BITMAP_CLR(bmp, bit) bmp[bit / 32] &= ~(1 << (bit % 32))
#define BITMAP_TST(bmp, bit) (bmp[bit / 32] & (1 << (bit % 32)))
#define GETBIT(addr) ((uint32_t) addr / BLKSIZE)
Functions
static int bitmap_first (heap_t *heap, size_t size)
void * bitmap_alloc (heap_t *heap, size_t size)
void bitmap_free (heap_t *heap, void *addr, size_t size)
int kheap_init ()
Variables
static heap_t kheap
uint32_t memsize
static uint8_t __bitmap [131072]
Macro Definition Documentation
#define BITMAP_CLR(bmp, bit) bmp[bit / 32] &= ~(1 << (bit % 32))
Definition at line 34 of file kheap.c.
#define BITMAP_SET(bmp, bit) bmp[bit / 32] |= (1 << (bit % 32))
Definition at line 31 of file kheap.c.
#define BITMAP_TST(bmp, bit) (bmp[bit / 32] & (1 << (bit % 32)))
Definition at line 37 of file kheap.c.
#define GETBIT(addr) ((uint32_t) addr / BLKSIZE)
Definition at line 41 of file kheap.c.
Function Documentation
void* bitmap_alloc (heap_t *heap, size_tsize)
Definition at line 77 of file kheap.c.
References heap::bitmap, bitmap_first(), BITMAP_SET, BLKSIZE, heap::size, size, and heap::used.
                                              {
    if(!heap)
        return 0;
        
    if(!heap->bitmap)
        return 0;
        
    if(heap->used >= heap->size)
        return 0;
    if(!size)
        return 0;
        
    
    
    size /= BLKSIZE;
    size += 1;
    
    int index = bitmap_first(heap, size);
    if(index == -1)
        return 0;
                
    for(int i = 0; i < size; i++)
        BITMAP_SET(heap->bitmap, (index + i));
    
    
    heap->used += (size * BLKSIZE);
    
    return (void*) (index * BLKSIZE);
}
static int bitmap_first (heap_t *heap, size_tsize) [static]
Definition at line 54 of file kheap.c.
References heap::bitmap, BITMAP_TST, BLKSIZE, heap::size, and size.
                                                   {
    if(size == 0)
        return -1;
        
    int hsize = heap->size / BLKSIZE;
    for(int i = 0; i < hsize; i++) {
        for(int j = 0, f = 0; j < size; j++) {
            if(BITMAP_TST(heap->bitmap, (i + j)))
                continue;
            
            f++;
            if(f == size)
                return i;
        }
    }
    
    return -1;
}
void bitmap_free (heap_t *heap, void *addr, size_tsize)
Definition at line 109 of file kheap.c.
References heap::bitmap, BITMAP_CLR, BLKSIZE, GETBIT, size, and heap::used.
                                                        {
    if(!heap)
        return;
        
    if(!heap->bitmap)
        return;
        
    if(size % BLKSIZE) {
        size /= BLKSIZE;
        size += 1;
    }else {
        size /= BLKSIZE;
    }
    
    int index = GETBIT(addr);
    for(int i = 0; i < size; i++)
        BITMAP_CLR(heap->bitmap, (index + i));
        
        
    heap->used -= (size * BLKSIZE);
}
int kheap_init ()
Definition at line 134 of file kheap.c.
References __bitmap, heap::alloc, heap::bitmap, bitmap_alloc(), bitmap_free(), BLKSIZE, heap::free, halloc(), memsize, mm_setheap(), heap::size, and uint32_t.
                 {
    kheap.bitmap = (uint32_t*) __bitmap;
    kheap.size = memsize;
    kheap.alloc = bitmap_alloc;
    kheap.free = bitmap_free;
    
    memset(kheap.bitmap, 0, (kheap.size / BLKSIZE));
    
    mm_setheap(&kheap);
    
    // Alloc first 4MB (reserved physical kernel area)
    halloc(&kheap, (size_t) 0x400000);
    
    return 0;
}
Variable Documentation
uint8_t __bitmap[131072] [static]
Definition at line 51 of file kheap.c.
heap_t kheap [static]
Definition at line 47 of file kheap.c.
uint32_t memsize
See also:
aplus/mm.h
Definition at line 44 of file mm.c.
Author
Generated automatically by Doxygen for aPlus from the source code.