.TH "src/syscall/link.c" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syscall/link.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <aplus\&.h>\fP
.br
\fC#include <aplus/syscall\&.h>\fP
.br
\fC#include <aplus/task\&.h>\fP
.br
\fC#include <aplus/fs\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsys_link\fP (char *filename, char *link)"
.br
.ti -1c
.RI "\fBSYSCALL\fP (\fBsys_link\fP, 8)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int sys_link (char *filename, char *link)"

.PP
Definition at line 14 of file link\&.c\&.
.PP
References sys_symlink()\&.
.PP
.nf
14                                          {
15     return sys_symlink(filename, link);
16 }
.fi
.SS "SYSCALL (\fBsys_link\fP, 8)"

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
