.TH "list" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBlist_body_t\fP * \fBbody\fP"
.br
.ti -1c
.RI "\fBspinlock_t\fP \fBlock\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 41 del file list\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "\fBlist_body_t\fP* list::body"

.PP
Definizione alla linea 42 del file list\&.h\&.
.SS "\fBspinlock_t\fP list::lock"

.PP
Definizione alla linea 44 del file list\&.h\&.
.SS "size_t list::size"

.PP
Definizione alla linea 45 del file list\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
