.TH "list_body" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list_body \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBlistval_t\fP \fBvalue\fP"
.br
.ti -1c
.RI "struct \fBlist_body\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file list\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBlist_body\fP* list_body::next"

.PP
Definition at line 38 of file list\&.h\&.
.SS "\fBlistval_t\fP list_body::value"

.PP
Definition at line 36 of file list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
