.TH "list" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBlist_body_t\fP * \fBbody\fP"
.br
.ti -1c
.RI "__list_lock_t \fBlock\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBExamples: \fP
.in +1c
\fBlist\&.h\fP\&.
.PP
Definition at line 50 of file list\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBlist_body_t\fP* list::body"

.PP
\fBExamples: \fP
.in +1c
\fBlist\&.h\fP\&.
.PP
Definition at line 51 of file list\&.h\&.
.SS "__list_lock_t list::lock"

.PP
\fBExamples: \fP
.in +1c
\fBlist\&.h\fP\&.
.PP
Definition at line 53 of file list\&.h\&.
.SS "size_t list::size"

.PP
\fBExamples: \fP
.in +1c
\fBlist\&.h\fP\&.
.PP
Definition at line 54 of file list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
