usr/src/libpthread/test/main.c
NAME
usr/src/libpthread/test/main.c -
SYNOPSIS
#include <stdio.h>
#include <assert.h>
#include <pthread.h>
Functions
static void * __test_pthread_1 (void *p)
int main (int argc, char **argv)
Function Documentation
static void* __test_pthread_1 (void *p) [static]
Definition at line 7 of file main.c.
                                        {
    return (void*) 200;
}
int main (intargc, char **argv)
Definition at line 12 of file main.c.
References __test_pthread_1(), pthread_barrier_destroy(), pthread_barrier_init(), PTHREAD_BARRIER_SERIAL_THREAD, pthread_barrier_wait(), pthread_cond_destroy(), pthread_cond_init(), pthread_create(), pthread_getspecific(), pthread_join(), pthread_key_create(), pthread_key_delete(), pthread_mutex_destroy(), pthread_mutex_init(), pthread_mutex_trylock(), pthread_mutex_unlock(), pthread_rwlock_destroy(), pthread_rwlock_init(), pthread_rwlock_tryrdlock(), pthread_rwlock_trywrlock(), pthread_rwlock_unlock(), pthread_setspecific(), pthread_spin_destroy(), pthread_spin_init(), pthread_spin_trylock(), and pthread_spin_unlock().
                                {
    printf("Test #1 - Create and join thread\n");
    pthread_t ptx_1;
    void* retval_1;
    assert(pthread_create(&ptx_1, NULL, __test_pthread_1, NULL) == 0);
    assert(pthread_join(ptx_1, &retval_1) == 0);
    assert((int) retval_1 == 200 && "bad returned value");
    
    printf("Test #2 - Create and lock/unlock mutex\n");
    pthread_mutex_t mtx_2;
    
    assert(pthread_mutex_init(&mtx_2, NULL) == 0);
    assert(pthread_mutex_trylock(&mtx_2) == 0);
    assert(pthread_mutex_unlock(&mtx_2) == 0);
    assert(pthread_mutex_destroy(&mtx_2) == 0);
        
    printf("Test #3 - Create and lock/unlock spinlock\n");
    pthread_spinlock_t spl_3;
    
    assert(pthread_spin_init(&spl_3, 0) == 0);
    assert(pthread_spin_trylock(&spl_3) == 0);
    assert(pthread_spin_unlock(&spl_3) == 0);
    assert(pthread_spin_destroy(&spl_3) == 0);
    printf("Test #4 - Create and lock/unlock condition\n");
    pthread_cond_t cond_4;
    pthread_mutex_t mtx_4;
    assert(pthread_mutex_init(&mtx_4, NULL) == 0);
    assert(pthread_cond_init(&cond_4, NULL) == 0);
    assert(pthread_cond_destroy(&cond_4) == 0);
    printf("Test #5 - Create and lock/unlock Read-Write lock\n");
    pthread_rwlock_t rw_5;
    
    assert(pthread_rwlock_init(&rw_5, NULL) == 0);
    assert(pthread_rwlock_tryrdlock(&rw_5) == 0);
    assert(pthread_rwlock_unlock(&rw_5) == 0);
    assert(pthread_rwlock_trywrlock(&rw_5) == 0);
    assert(pthread_rwlock_unlock(&rw_5) == 0);
    assert(pthread_rwlock_destroy(&rw_5) == 0);
    printf("Test #6 - Create and wait barrier\n");
    pthread_barrier_t bar_6;
    
    assert(pthread_barrier_init(&bar_6, NULL, 1) == 0);
    assert(pthread_barrier_wait(&bar_6) == PTHREAD_BARRIER_SERIAL_THREAD);
    assert(pthread_barrier_destroy(&bar_6) == 0);
    printf("Test #7 - Store and read from TLS\n");
    pthread_key_t key_7;
    assert(pthread_key_create(&key_7, NULL) == 0);
    assert(pthread_setspecific(key_7, (const void*) 200) == 0);
    assert((int) pthread_getspecific(key_7) == 200 && "bad returned value");
    assert(pthread_key_delete(key_7) == 0);
    printf("\nTest OK\n");
    return 0;
}
Author
Generated automatically by Doxygen for aPlus from the source code.