.TH "src/mm/mm.c" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mm/mm.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <aplus/mm\&.h>\fP
.br
\fC#include <aplus/list\&.h>\fP
.br
\fC#include <grub\&.h>\fP
.br

.SS "Strutture dati"

.in +1c
.ti -1c
.RI "struct \fBblock\fP"
.br
.in -1c
.SS "Funzioni"

.in +1c
.ti -1c
.RI "struct \fBblock\fP \fB__attribute__\fP ((packed))"
.br
.ti -1c
.RI "void \fBkfree\fP (void *ptr)"
.br
.ti -1c
.RI "void * \fBkrealloc\fP (void *ptr, size_t \fBsize\fP)"
.br
.ti -1c
.RI "void \fBmm_setheap\fP (\fBheap_t\fP *\fBheap\fP)"
.br
.ti -1c
.RI "volatile \fBheap_t\fP * \fBmm_getheap\fP ()"
.br
.ti -1c
.RI "int \fBmm_init\fP ()"
.br
.in -1c
.SS "Variabili"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBmemsize\fP"
.br
.ti -1c
.RI "volatile \fBheap_t\fP * \fBcurrent_heap\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP * \fBcurrent_vmm\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP * \fBkernel_vmm\fP"
.br
.ti -1c
.RI "\fBlist_t\fP * \fBvmm_queue\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBmagic\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "struct \fBblock\fP __attribute__ ((packed))"

.PP
Definizione alla linea 47 del file mm\&.c\&.
.PP
.nf
50                            {
51     void* addr = (void*) halloc(current_heap, size);
52     if(!addr)
53         panic("halloc(): failed!");
54 
55 
56     addr = mm_vaddr(addr);
57 
58     block_t* block = (block_t*) addr;
59     block->magic = BLKMAGIC;
60     block->size = size;
61 
62     return (void*) ((uint32_t) block + sizeof(block_t));
63 }
.fi
.SS "void kfree (void *ptr)"

.PP
Definizione alla linea 66 del file mm\&.c\&.
.PP
Referenzia BLKMAGIC, hfree(), mm_align(), mm_paddr(), e size\&.
.PP
.nf
66                       {
67     if(!ptr)
68         return;
69         
70     
71     block_t* block = (block_t*) ptr;
72     if(block->magic != BLKMAGIC)
73         return;
74         
75     size_t size = block->size;
76     block->size = 0;
77     block->magic = 0;
78     
79     
80     hfree(current_heap, mm_paddr(mm_align(ptr)), size);
81 }
.fi
.SS "void* krealloc (void *ptr, size_tsize)"

.PP
Definizione alla linea 84 del file mm\&.c\&.
.PP
Referenzia BLKMAGIC, kfree(), e kmalloc()\&.
.PP
.nf
84                                        {
85     if(ptr == NULL)
86         return kmalloc(size);
87         
88     if(size == 0) {
89         kfree(ptr);
90         return NULL;
91     }   
92 
93     block_t* block = (block_t*) ptr;
94     if(block->magic != BLKMAGIC)
95         return NULL;
96         
97     void* newptr = kmalloc(size);
98     if(!newptr)
99         return NULL;
100         
101     if(size > block->size)
102         size = block->size;
103         
104     memcpy(newptr, ptr, size);
105     kfree(ptr);
106     
107     return newptr;
108 }
.fi
.SS "volatile \fBheap_t\fP* mm_getheap ()"

.PP
Definizione alla linea 117 del file mm\&.c\&.
.PP
Referenzia current_heap\&.
.PP
.nf
117                               {
118     return current_heap;
119 }
.fi
.SS "int mm_init ()"

.PP
Definizione alla linea 122 del file mm\&.c\&.
.PP
Referenzia kheap_init(), mbd, BootInfo_t::mem_lower, BootInfo_t::mem_upper, memsize, vmm_init(), e VMM_MAX_MEMORY\&.
.PP
.nf
122               {
123 
124     memsize = (mbd->mem_upper + mbd->mem_lower) * 1024;
125     if(memsize > VMM_MAX_MEMORY)
126         memsize = VMM_MAX_MEMORY;
127 
128 
129     kheap_init();
130     vmm_init();
131 
132     return 0;
133 }
.fi
.SS "void mm_setheap (\fBheap_t\fP *heap)"

.PP
Definizione alla linea 113 del file mm\&.c\&.
.PP
.nf
113                               {
114     current_heap = heap;
115 }
.fi
.SH "Documentazione delle variabili"
.PP 
.SS "volatile \fBheap_t\fP* current_heap"

.PP
Definizione alla linea 36 del file mm\&.c\&.
.SS "\fBuint32_t\fP* current_vmm"

.PP
Definizione alla linea 46 del file paging\&.c\&.
.SS "\fBuint32_t\fP* kernel_vmm"

.PP
Definizione alla linea 47 del file paging\&.c\&.
.SS "\fBuint16_t\fP magic"

.PP
Definizione alla linea 42 del file mm\&.c\&.
.SS "\fBuint32_t\fP memsize"

.PP
Definizione alla linea 35 del file mm\&.c\&.
.SS "size_t size"

.PP
Definizione alla linea 43 del file mm\&.c\&.
.SS "\fBlist_t\fP* vmm_queue"

.PP
Definizione alla linea 49 del file paging\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
