src/mm/mm.c
NAME
src/mm/mm.c -
SYNOPSIS
#include <sys/types.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <aplus.h>
#include <aplus/mm.h>
#include <aplus/list.h>
#include <aplus/task.h>
#include <grub.h>
Data Structures
struct block
Functions
struct block __attribute__ ((packed))
void * kvmalloc (size_t size)
void kfree (void *ptr)
Free memory from Kernel Heap.
void * krealloc (void *ptr, size_t size)
Realloc memory from Kernel Heap.
void mm_setheap (heap_t *heap)
Set current heap for memory operations.
heap_t * mm_getheap ()
Get current heap for memory operations.
int mm_init ()
Initialize MMU.
Variables
uint32_t memsize
heap_t * current_heap
uint32_t * current_vmm
uint32_t * kernel_vmm
task_t * current_task
Current task address.
task_t * kernel_task
Kernel task address.
list_t * vmm_queue
uint16_t magic
size_t size
Function Documentation
struct block __attribute__ ((packed))
Definition at line 64 of file mm.c.
                                          {
    if(current_task != kernel_task)
        return;
    schedule_disable();
    vmm_disable();
    
    int e = 0;
    for(uint32_t frame = 0; frame < current_heap->size; frame += 0x1000) {
        block_t* block = (block_t*) frame;
        if(block->magic != BLKMAGIC)
            continue;
        if(*(uint32_t*) (frame + block->size + sizeof(block_t)) != CHUNK_MAGIC) {
            kprintf("mm: chunk overflow at 0x%x (%x) allocated from %s (%d)\n", frame, block->size, block->file, block->line);
            e++;
            *(uint32_t*) (frame + block->size + sizeof(block_t)) = CHUNK_MAGIC;
        }
        frame += block->size & ~0xFFF;
    }
    
    if(e)
        kprintf("There was %d chunks overflow\n", e);
    vmm_enable();
    schedule_enable();
}
#endif
#ifdef CHUNKS_CHECKING
void* __kmalloc(size_t size, char* file, int line)
#else
void* kmalloc(size_t size)
#endif
{
    size += sizeof(block_t);
    void* addr = (void*) halloc(current_heap, size);
    if(!addr)
        panic("halloc(): failed!");
    addr = mm_vaddr(addr);
    block_t* block = (block_t*) addr;
    block->magic = BLKMAGIC;
    block->size = size;
#ifdef CHUNKS_CHECKING
    block->file = file;
    block->line = line;
    *(uint32_t*) ((uint32_t) block + size + sizeof(block_t)) = CHUNK_MAGIC;
    __check_all_chunks_overflow();
#endif
    return (void*) ((uint32_t) block + sizeof(block_t));
}
void kfree (void *ptr)
Free memory from Kernel Heap.
Parameters:
ptr Pointer to data allocated.
Definition at line 151 of file mm.c.
References BLKMAGIC, hfree(), mm_align(), and mm_paddr().
                      {
    if(!ptr)
        return;
        
    
    block_t* block = (block_t*) ptr;
    block--;
    if(block->magic != BLKMAGIC)
        return;
    size_t size = block->size;
    block->size = 0;
    block->magic = 0;
    
#ifdef CHUNKS_CHECKING
    block->file = 0;
    block->line = 0;
#endif
    
    hfree(current_heap, mm_paddr(mm_align(ptr)), size);
}
void* krealloc (void *ptr, size_tsize)
Realloc memory from Kernel Heap.
Parameters:
ptr Pointer to data allocated.
size Size of data to alloc.
Returns:
Virtual Address of data.
Definition at line 182 of file mm.c.
References BLKMAGIC, kfree(), and kmalloc().
                                       {
    if(ptr == NULL)
        return kmalloc(size);
        
    if(size == 0) {
        kfree(ptr);
        return NULL;
    }
    block_t* block = (block_t*) ptr;
    block--;
    if(block->magic != BLKMAGIC)
        return NULL;
        
    void* newptr = kmalloc(size);
    if(!newptr)
        return NULL;
        
    if(size > block->size)
        size = block->size;
        
    memcpy(newptr, ptr, size);
    kfree(ptr);
    
    return newptr;
}
void* kvmalloc (size_tsize)
Definition at line 137 of file mm.c.
References halloc(), mm_vaddr(), and panic().
                            {
    void* addr = (void*) halloc(current_heap, size);
    if(!addr)
        panic("halloc(): failed!");
    addr = mm_vaddr(addr);
    return addr;
}
heap_t* mm_getheap ()
Get current heap for memory operations.
Definition at line 222 of file mm.c.
References current_heap.
                     {
    return current_heap;
}
int mm_init ()
Initialize MMU.
Definition at line 230 of file mm.c.
References kheap_init(), mbd, BootInfo_t::mem_lower, BootInfo_t::mem_upper, memsize, vmm_init(), and VMM_MAX_MEMORY.
              {
    memsize = (mbd->mem_upper + mbd->mem_lower) * 1024;
    if(memsize > VMM_MAX_MEMORY)
        memsize = VMM_MAX_MEMORY;
    kheap_init();
    vmm_init();
    return 0;
}
void mm_setheap (heap_t *heap)
Set current heap for memory operations.
Definition at line 215 of file mm.c.
                              {
    current_heap = heap;
}
Variable Documentation
heap_t* current_heap
Definition at line 45 of file mm.c.
task_t* current_task
Current task address.
Definition at line 37 of file sched.c.
uint32_t* current_vmm
Definition at line 46 of file paging.c.
task_t* kernel_task
Kernel task address.
Definition at line 42 of file sched.c.
uint32_t* kernel_vmm
Definition at line 47 of file paging.c.
uint16_t magic
Definition at line 54 of file mm.c.
uint32_t memsize
See also:
aplus/mm.h
Definition at line 44 of file mm.c.
size_t size
Definition at line 55 of file mm.c.
list_t* vmm_queue
Definition at line 49 of file paging.c.
Author
Generated automatically by Doxygen for aPlus from the source code.