src/include/aplus/mm.h
NAME
src/include/aplus/mm.h -
SYNOPSIS
#include <stdint.h>
#include <aplus/task.h>
Data Structures
struct heap
Macros
#define MM_VBASE 0x40000000
#define MM_VSIZE (0xFFFFFFFF - MM_VBASE)
#define MM_LBASE 0x00000000
#define MM_LSIZE 0x00800000
#define MM_UBASE 0x00A00000
#define MM_USIZE (MM_VBASE - MM_UBASE)
#define VMM_FLAGS_PRESENT 0x01
#define VMM_FLAGS_RDWR 0x02
#define VMM_FLAGS_USER 0x04
#define VMM_FLAGS_DEFAULT (VMM_FLAGS_PRESENT | VMM_FLAGS_RDWR)
#define VMM_MAX_MEMORY (0xFFFFFFFF - MM_VBASE)
#define BLKSIZE 0x1000
#define BLKMAGIC 0x1234
Typedefs
typedef struct heap heap_t
Functions
static void * mm_paddr (void *vaddr)
static void * mm_vaddr (void *paddr)
static void * mm_align (void *vaddr)
void * kmalloc (size_t)
void kfree (void *)
Free memory from Kernel Heap.
void * krealloc (void *, size_t)
Realloc memory from Kernel Heap.
Macro Definition Documentation
#define BLKMAGIC 0x1234
Definition at line 61 of file mm.h.
#define BLKSIZE 0x1000
Definition at line 60 of file mm.h.
#define MM_LBASE 0x00000000
Definition at line 44 of file mm.h.
#define MM_LSIZE 0x00800000
Definition at line 45 of file mm.h.
#define MM_UBASE 0x00A00000
Definition at line 47 of file mm.h.
#define MM_USIZE (MM_VBASE - MM_UBASE)
Definition at line 48 of file mm.h.
#define MM_VBASE 0x40000000
Definition at line 41 of file mm.h.
#define MM_VSIZE (0xFFFFFFFF - MM_VBASE)
Definition at line 42 of file mm.h.
#define VMM_FLAGS_DEFAULT (VMM_FLAGS_PRESENT | VMM_FLAGS_RDWR)
Definition at line 55 of file mm.h.
#define VMM_FLAGS_PRESENT 0x01
Definition at line 52 of file mm.h.
#define VMM_FLAGS_RDWR 0x02
Definition at line 53 of file mm.h.
#define VMM_FLAGS_USER 0x04
Definition at line 54 of file mm.h.
#define VMM_MAX_MEMORY (0xFFFFFFFF - MM_VBASE)
Definition at line 57 of file mm.h.
Typedef Documentation
typedef struct heap heap_t
Function Documentation
void kfree (void *ptr)
Free memory from Kernel Heap.
Parameters:
ptr Pointer to data allocated.
Definition at line 151 of file mm.c.
References BLKMAGIC, hfree(), mm_align(), and mm_paddr().
                      {
    if(!ptr)
        return;
        
    
    block_t* block = (block_t*) ptr;
    block--;
    if(block->magic != BLKMAGIC)
        return;
    size_t size = block->size;
    block->size = 0;
    block->magic = 0;
    
#ifdef CHUNKS_CHECKING
    block->file = 0;
    block->line = 0;
#endif
    
    hfree(current_heap, mm_paddr(mm_align(ptr)), size);
}
void* kmalloc (size_t)
void* krealloc (void *ptr, size_tsize)
Realloc memory from Kernel Heap.
Parameters:
ptr Pointer to data allocated.
size Size of data to alloc.
Returns:
Virtual Address of data.
Definition at line 182 of file mm.c.
References BLKMAGIC, kfree(), and kmalloc().
                                       {
    if(ptr == NULL)
        return kmalloc(size);
        
    if(size == 0) {
        kfree(ptr);
        return NULL;
    }
    block_t* block = (block_t*) ptr;
    block--;
    if(block->magic != BLKMAGIC)
        return NULL;
        
    void* newptr = kmalloc(size);
    if(!newptr)
        return NULL;
        
    if(size > block->size)
        size = block->size;
        
    memcpy(newptr, ptr, size);
    kfree(ptr);
    
    return newptr;
}
static void* mm_align (void *vaddr) [inline], [static]
Definition at line 88 of file mm.h.
References uint32_t.
                                          {
    return (void*) ((uint32_t) vaddr & ~0xFFF);
}
static void* mm_paddr (void *vaddr) [inline], [static]
Definition at line 74 of file mm.h.
References MM_VBASE, and uint32_t.
                                          {
    if((uint32_t) vaddr > MM_VBASE)
        vaddr = (void*) ((uint32_t) vaddr - MM_VBASE);
        
    return vaddr;
}
static void* mm_vaddr (void *paddr) [inline], [static]
Definition at line 81 of file mm.h.
References MM_VBASE, and uint32_t.
                                          {
    if((uint32_t) paddr < MM_VBASE)
        paddr = (void*) ((uint32_t) paddr + MM_VBASE);
        
    return paddr;
}
Author
Generated automatically by Doxygen for aPlus from the source code.