src/syscall/mount.c
NAME
src/syscall/mount.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/fs.h>
#include <aplus/task.h>
#include <aplus/list.h>
#include <aplus/attribute.h>
#include <aplus/syscall.h>
#include <aplus/fsys.h>
#include <stdint.h>
#include <unistd.h>
#include <dirent.h>
#include <fcntl.h>
#include <sys/types.h>
#include <errno.h>
Functions
int sys_mount (const char *dev, const char *dir, const char *fstype, int options, const void *data)
SYSCALL (sys_mount, 24)
Variables
task_t * current_task
Current task address.
Function Documentation
int sys_mount (const char *dev, const char *dir, const char *fstype, intoptions, const void *data)
Definition at line 22 of file mount.c.
References attribute(), inode::dev, errno, task::fd, fs, im_superuser(), inode::ino, list_destroy, list_empty(), list_foreach, inode::mode, fsys::mount, fsys::name, O_DIRECTORY, sys_close(), sys_open(), and value.
                                                                                                   {
    if(!current_task)
        return -1;
    if(!im_superuser()) {
        errno = EPERM;
        return -1;
    }
    if(dir == NULL || strlen(dir) == 0) {
        errno = EINVAL;
        return -1;
    }
    inode_t* idev = NULL;
    inode_t* idir = NULL;
    if(dev && strlen(dev) > 0) {
        int dfd = sys_open(dev, O_RDONLY, 0644);
        if(dfd < 0) {
            errno = ENOENT;
            return -1;
        }
        idev = current_task->fd[dfd];
        sys_close(dfd);
    }
    int sfd = sys_open(dir, O_CREAT | O_DIRECTORY | O_RDONLY, S_IFDIR);
    if(sfd < 0) {
        errno = ENOENT;
        return -1;
    }
    idir = current_task->fd[sfd];
    sys_close(sfd);
    list_t* fs = attribute("fs");
    if(list_empty(fs)) {
        errno = ENODEV;
        return -1;
    }
    
    fsys_t* found = NULL;
    list_foreach(value, fs) {
        fsys_t* f = (fsys_t*) value;
        if(strcmp(f->name, fstype) == 0)
            found = f;
    }
    list_destroy(fs);
    if(found == NULL) {
        errno = ENODEV;
        return -1;
    }
    idir->mode |= S_IFMT;
    idir->dev = idev->ino;
    if(found->mount(idev, idir, options) < 0) {
        idir->mode &= ~S_IFMT;
        idir->dev = 0;
        errno = ENODEV;
        return -1;
    }
    return 0;
}
SYSCALL (sys_mount, 24)
Variable Documentation
task_t* current_task
Current task address.
Definition at line 35 of file sched.c.
Author
Generated automatically by Doxygen for aPlus from the source code.