.TH "netif_socket" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netif_socket \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <netif\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line 90 of file netif\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
