.TH "src/include/aplus/netif.h" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/aplus/netif.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <aplus\&.h>\fP
.br
\fC#include <aplus/pci\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBnetif\fP"
.br
.ti -1c
.RI "struct \fBnetif_packet\fP"
.br
.ti -1c
.RI "struct \fBnetif_socket\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNETIF_RAW\fP   0"
.br
.ti -1c
.RI "#define \fBNETIF_INET\fP   1"
.br
.ti -1c
.RI "#define \fBNETIF_INET6\fP   2"
.br
.ti -1c
.RI "#define \fBNETIF_ARP\fP   3"
.br
.ti -1c
.RI "#define \fBNETIF_ETH\fP   4"
.br
.ti -1c
.RI "#define \fBNETIF_UDP\fP   5"
.br
.ti -1c
.RI "#define \fBNETIF_TCP\fP   6"
.br
.ti -1c
.RI "#define \fBNETIF_ICMP\fP   7"
.br
.ti -1c
.RI "#define \fBNETIF_TELNET\fP   8"
.br
.ti -1c
.RI "#define \fBNETIF_FLAGS_ENABLE\fP   1"
.br
.ti -1c
.RI "#define \fBARP_DEBUG\fP"
.br
.ti -1c
.RI "#define \fBRTL8139_DEBUG\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBuint8_t\fP \fBipv4_t\fP [4]"
.br
.ti -1c
.RI "typedef \fBuint16_t\fP \fBipv6_t\fP [8]"
.br
.ti -1c
.RI "typedef \fBuint8_t\fP \fBmacaddr_t\fP [6]"
.br
.ti -1c
.RI "typedef struct \fBnetif\fP \fBnetif_t\fP"
.br
.ti -1c
.RI "typedef struct \fBnetif_packet\fP \fBnetif_packet_t\fP"
.br
.ti -1c
.RI "typedef struct \fBnetif_socket\fP \fBnetif_socket_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARP_DEBUG"

.PP
Definition at line 29 of file netif\&.h\&.
.SS "#define NETIF_ARP   3"

.PP
Definition at line 18 of file netif\&.h\&.
.SS "#define NETIF_ETH   4"

.PP
Definition at line 19 of file netif\&.h\&.
.SS "#define NETIF_FLAGS_ENABLE   1"

.PP
Definition at line 26 of file netif\&.h\&.
.SS "#define NETIF_ICMP   7"

.PP
Definition at line 22 of file netif\&.h\&.
.SS "#define NETIF_INET   1"

.PP
Definition at line 16 of file netif\&.h\&.
.SS "#define NETIF_INET6   2"

.PP
Definition at line 17 of file netif\&.h\&.
.SS "#define NETIF_RAW   0"

.PP
Definition at line 15 of file netif\&.h\&.
.SS "#define NETIF_TCP   6"

.PP
Definition at line 21 of file netif\&.h\&.
.SS "#define NETIF_TELNET   8"

.PP
Definition at line 23 of file netif\&.h\&.
.SS "#define NETIF_UDP   5"

.PP
Definition at line 20 of file netif\&.h\&.
.SS "#define RTL8139_DEBUG"

.PP
Definition at line 30 of file netif\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBuint8_t\fP ipv4_t[4]"

.PP
Definition at line 10 of file netif\&.h\&.
.SS "typedef \fBuint16_t\fP ipv6_t[8]"

.PP
Definition at line 11 of file netif\&.h\&.
.SS "typedef \fBuint8_t\fP macaddr_t[6]"

.PP
Definition at line 12 of file netif\&.h\&.
.SS "typedef struct \fBnetif_packet\fP  \fBnetif_packet_t\fP"

.SS "typedef struct \fBnetif_socket\fP  \fBnetif_socket_t\fP"

.SS "typedef struct \fBnetif\fP  \fBnetif_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
