.TH "netif_packet" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netif_packet \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <netif\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBid\fP"
.br
.ti -1c
.RI "int \fBprotocol\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "void * \fBheader\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "\fBnetif_t\fP * \fBnetif\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 77 of file netif\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* netif_packet::data"

.PP
Definition at line 83 of file netif\&.h\&.
.SS "void* netif_packet::header"

.PP
Definition at line 82 of file netif\&.h\&.
.SS "uint64_t netif_packet::id"

.PP
Definition at line 78 of file netif\&.h\&.
.SS "int netif_packet::length"

.PP
Definition at line 80 of file netif\&.h\&.
.SS "\fBnetif_t\fP* netif_packet::netif"

.PP
Definition at line 85 of file netif\&.h\&.
.SS "int netif_packet::protocol"

.PP
Definition at line 79 of file netif\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
