.TH "netif_packet" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netif_packet \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <netif\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "uint64_t \fBid\fP"
.br
.ti -1c
.RI "int \fBprotocol\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "void * \fBheader\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "\fBnetif_t\fP * \fBnetif\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 77 del file netif\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "void* netif_packet::data"

.PP
Definizione alla linea 83 del file netif\&.h\&.
.SS "void* netif_packet::header"

.PP
Definizione alla linea 82 del file netif\&.h\&.
.SS "uint64_t netif_packet::id"

.PP
Definizione alla linea 78 del file netif\&.h\&.
.SS "int netif_packet::length"

.PP
Definizione alla linea 80 del file netif\&.h\&.
.SS "\fBnetif_t\fP* netif_packet::netif"

.PP
Definizione alla linea 85 del file netif\&.h\&.
.SS "int netif_packet::protocol"

.PP
Definizione alla linea 79 del file netif\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
