src/syscall/open.c
NAME
src/syscall/open.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/syscall.h>
#include <aplus/fs.h>
#include <aplus/task.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/stat.h>
#include <dirent.h>
#include <stdio.h>
Functions
static char * dupstr (char *s)
static inode_t * ino_open (char *filename, int flags, mode_t mode)
int sys_open (char *filename, int flags, mode_t mode)
SYSCALL (sys_open, 10)
Variables
task_t * current_task
Current task address.
inode_t * vfs_root
Function Documentation
static char* dupstr (char *s) [static]
Definition at line 19 of file open.c.
References kmalloc().
                             {
    char* p = (char*) kmalloc(strlen(s));
    strcpy(p, s);
    return p;
}
static inode_t* ino_open (char *filename, intflags, mode_tmode) [static]
Definition at line 27 of file open.c.
References task::cwd, errno, fs_creat(), fs_finddir(), kprintf(), inode::link, inode::mode, O_DIRECTORY, O_NOFOLLOW, and vfs_root.
                                                                 {
    inode_t* cwd = NULL;
    if(filename[0] == '/')
        cwd = vfs_root;
    else
        cwd = current_task->cwd;
    
    if(!cwd) {
        if(!vfs_root) {
            kprintf("sys_open: no root found for cwd.");
        
            errno = ENOENT;
            return NULL;
        }
        
        cwd = vfs_root;
    }
    
    
    if(filename[0] == '/')
        filename++;
        
    if(filename[0] == 0)
        return cwd;
        
    
    char* s = filename;
    char* p = s;
    
    while(*s) {
        if((p = strchr(s, '/'))) {
            *p++ = 0;
        
            cwd = (inode_t*) fs_finddir(cwd, s);
            if(!cwd) {
                errno = ENOENT;
                return NULL;
            }
            while(S_ISLNK(cwd->mode))
                if(cwd->link)
                    cwd = cwd->link;
                else
                    break;
            s = p;
        } else
            break;
    }
    if(*s == 0) {
        errno = ENOENT;
        return NULL;
    }
    inode_t* ent = (inode_t*) fs_finddir(cwd, s);
    if(flags & O_EXCL) {
        if(ent) {
            errno = EEXIST;
            return NULL;
        }
    }
    if(flags & O_CREAT)
        if(!ent)
            ent = (inode_t*) fs_creat(cwd, s, mode);
        
    if(!ent) {
        errno = ENOENT;
        return NULL;
    }
    if(!(flags & O_NOFOLLOW)) {
        while(S_ISLNK(ent->mode)) {
            if(ent == ent->link) {
                errno = ELOOP;
                return NULL;
            }
            if(ent->link)
                ent = ent->link;
            else
                break;
        }
    }
    if(flags & O_DIRECTORY) {
        if(!(S_ISDIR(ent->mode))) {
            errno = ENOTDIR;
            return NULL;
        }
    }
    return ent;
}
int sys_open (char *filename, intflags, mode_tmode)
Definition at line 127 of file open.c.
References dupstr(), errno, task::fd, ino_open(), kfree(), and TASK_MAX_FD.
                                                     {
    if(!current_task)
        return -1;
    char* p = dupstr(filename);
    inode_t* ino = ino_open(p, flags, mode);
    kfree(p);
    if(!ino)
        return -1;
    
    
    inode_t** fd = NULL;
    for(int i = 0; i < TASK_MAX_FD; i++) {
        if(current_task->fd[i] == 0) {
            fd = &current_task->fd[i];
            break;
        }
    }
    
    if(fd == NULL) {
        errno = EMFILE;
        return -1;
    }
    
    *fd = ino;
    return 0;
}
SYSCALL (sys_open, 10)
Variable Documentation
task_t* current_task
Current task address.
Definition at line 35 of file sched.c.
inode_t* vfs_root
Definition at line 19 of file vfs.c.
Author
Generated automatically by Doxygen for aPlus from the source code.