src/mm/paging.c
NAME
src/mm/paging.c -
SYNOPSIS
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <sys/types.h>
#include <aplus.h>
#include <aplus/mm.h>
#include <aplus/task.h>
#include <aplus/list.h>
#include <grub.h>
Macros
#define PGSIZE (BLKSIZE)
#define PGFLAGS (0x00000000)
#define PDSIZE (1024)
#define PDENTRY(x) ((uint32_t) x >> 22)
#define PTSIZE (1024)
#define PTENTRY(x) ((uint32_t) x << 10 >> 10 >> 12)
Functions
void vmm_switch (uint32_t *addr)
void vmm_enable ()
void vmm_disable ()
void * vmm_map (uint32_t *pd, void *paddr, void *vaddr, size_t len, int flags)
void vmm_umap (uint32_t *pd, void *addr, size_t len)
void * vmm_alloc (void *vaddr, size_t size, int flags)
void vmm_mapkernel (uint32_t *dest)
uint32_t * vmm_create ()
void vmm_destroy (uint32_t *vmm)
int vmm_init ()
Variables
volatile heap_t * current_heap
uint32_t memsize
uint32_t * current_vmm
uint32_t * kernel_vmm
list_t * vmm_queue
Macro Definition Documentation
#define PDENTRY(x) ((uint32_t) x >> 22)
Definition at line 38 of file paging.c.
#define PDSIZE (1024)
Definition at line 37 of file paging.c.
#define PGFLAGS (0x00000000)
Definition at line 35 of file paging.c.
#define PGSIZE (BLKSIZE)
Definition at line 34 of file paging.c.
#define PTENTRY(x) ((uint32_t) x << 10 >> 10 >> 12)
Definition at line 41 of file paging.c.
#define PTSIZE (1024)
Definition at line 40 of file paging.c.
Function Documentation
void* vmm_alloc (void *vaddr, size_tsize, intflags)
Definition at line 130 of file paging.c.
References current_vmm, halloc(), and vmm_map().
                                                     {
    void* paddr = (void*) halloc(current_heap, size);
    vmm_map(current_vmm, paddr, vaddr, size, flags);
    return paddr;
}
uint32_t* vmm_create ()
Definition at line 151 of file paging.c.
References kmalloc(), mm_align(), PDSIZE, and uint32_t.
                       {
    uint32_t* addr = (uint32_t*) mm_align((void*) kmalloc(PDSIZE * sizeof(uint32_t)));
    if(!addr)
        return NULL;
        
    memset(addr, 0, PDSIZE * sizeof(uint32_t));
    return addr;
}
void vmm_destroy (uint32_t *vmm)
Definition at line 161 of file paging.c.
References PDSIZE, and uint32_t.
                                {
    memset(vmm, 0, PDSIZE * sizeof(uint32_t));
}
void vmm_disable ()
Definition at line 65 of file paging.c.
                   {
    write_cr0(read_cr0() & ~0x80000000);
}
void vmm_enable ()
Definition at line 60 of file paging.c.
                  {
    write_cr4(read_cr4() & ~0x00000010);
    write_cr0(read_cr0() | 0x80000000);
}
int vmm_init ()
Definition at line 165 of file paging.c.
References halloc(), kernel_vmm, list_init, panic(), PDSIZE, uint32_t, vmm_enable(), vmm_mapkernel(), and vmm_switch().
               {
    kernel_vmm = (uint32_t*) halloc(current_heap, PDSIZE * sizeof(uint32_t));
    if(!kernel_vmm)
        panic("Could not initialize VMM");
    
    memset(kernel_vmm, 0, PDSIZE * sizeof(uint32_t));
    
    vmm_mapkernel(kernel_vmm);
    vmm_switch(kernel_vmm);
    vmm_enable();
    list_init(vmm_queue);
    return 0;
}
void* vmm_map (uint32_t *pd, void *paddr, void *vaddr, size_tlen, intflags)
Definition at line 72 of file paging.c.
References current_vmm, flags, halloc(), mm_align(), panic(), PDENTRY, PGSIZE, PTENTRY, PTSIZE, uint32_t, and VMM_FLAGS_DEFAULT.
                                                                             {
    if(!pd)
        return paddr;
        
    paddr = mm_align(paddr);
    vaddr = mm_align(vaddr);
        
    int pages = (len / PGSIZE) + 1;
    uint32_t pframe = (uint32_t) paddr;
    uint32_t vframe = (uint32_t) vaddr;
    
    for(int i = 0; i < pages; i++) {
        uint32_t* e = &pd[PDENTRY(vframe)];
        
        if(*e == 0) {
            uint32_t* table = (uint32_t*) halloc(current_heap, PTSIZE * sizeof(uint32_t));
            if(!table)
                panic("vmm_map(): cannot allocate more table\n");
                
            if(current_vmm)
                vmm_map(current_vmm, table, table, PTSIZE * sizeof(uint32_t), VMM_FLAGS_DEFAULT);
            
            memset(table, 0, PTSIZE * sizeof(uint32_t));
            *e = (uint32_t) table | flags;
        }
        
        uint32_t* t = (uint32_t*) (*e & ~0xFFF);
        t[PTENTRY(vframe)] = pframe | flags;
        
        pframe += PGSIZE;
        vframe += PGSIZE;
    }
    
    return vaddr;
}
void vmm_mapkernel (uint32_t *dest)
Definition at line 138 of file paging.c.
References memsize, MM_LBASE, MM_LSIZE, mm_vaddr(), VMM_FLAGS_DEFAULT, VMM_FLAGS_USER, and vmm_map().
                                   {
    // Map 8MB to low area (kernel reserved)
    vmm_map(dest, (void*) MM_LBASE, (void*) MM_LBASE, MM_LSIZE, VMM_FLAGS_DEFAULT);
    // Map all high-memory (kernel reserved)
    vmm_map(dest, (void*) 0, mm_vaddr((void*) 0), memsize, VMM_FLAGS_DEFAULT);
    // Map Linear Frame Buffer
    vmm_map(dest, (void*) 0xE0000000, (void*) 0xE0000000, 0x10000000, VMM_FLAGS_DEFAULT | VMM_FLAGS_USER);
}
void vmm_switch (uint32_t *addr)
Definition at line 54 of file paging.c.
References current_vmm, mm_paddr(), and uint32_t.
                                {
    current_vmm = addr;
    
    write_cr3((uint32_t) mm_paddr((void*) addr));
}
void vmm_umap (uint32_t *pd, void *addr, size_tlen)
Definition at line 109 of file paging.c.
References mm_align(), PDENTRY, PGSIZE, PTENTRY, and uint32_t.
                                                    {
    if(!pd)
        return;
        
    addr = mm_align(addr);
        
    int pages = (len / PGSIZE) + 1;
    
    
    for(uint32_t i = 0, frame = (uint32_t) addr; i < pages; i++, frame += PGSIZE) {
        uint32_t* e = &pd[PDENTRY(frame)];
        if((*e & 1) != 1)
            continue;
            
        uint32_t* table = (uint32_t*) (*e & ~0xFFF);
        table[PTENTRY(frame)] = 0;
    }
    
}
Variable Documentation
volatile heap_t* current_heap
Definition at line 36 of file mm.c.
uint32_t* current_vmm
Definition at line 46 of file paging.c.
uint32_t* kernel_vmm
Definition at line 47 of file paging.c.
uint32_t memsize
Definition at line 35 of file mm.c.
list_t* vmm_queue
Definition at line 49 of file paging.c.
Author
Generated automatically by Doxygen for aPlus from the source code.