src/panic.c
NAME
src/panic.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/task.h>
#include <aplus/mm.h>
#include <aplus/fs.h>
#include <aplus/list.h>
#include <errno.h>
Functions
static void dump_errno ()
Print last error number.
static void dump_cpu (regs_t *r)
Print current registers & cpu status.
static void dump_stacktrace (int count)
static void dump_task ()
Print all and current task.
static void dump_mmu ()
Print MMU State.
void panic_r (char *msg, regs_t *r)
Go in Kernel Panic, dump exception registers, halt system.
void panic (char *msg)
Go in Kernel Panic, halt system.
Variables
list_t * task_queue
List of all Task.
task_t * current_task
Current task address.
task_t * kernel_task
Kernel task address.
Function Documentation
static void dump_cpu (regs_t *r) [static]
Print current registers & cpu status.
Definition at line 25 of file panic.c.
References kprintf(), and pit_getticks().
                                {
    kprintf("CPU:\n");
    if(r) {
        kprintf("eip: 0x%8x\n", r->eip);
        kprintf("err: 0x%8x\n", r->err_code);
        kprintf("int: 0x%8x\n", r->int_no);
        kprintf("esp: 0x%8x\n", r->esp);
        kprintf("usp: 0x%8x\n", r->useresp);
    }
    kprintf("pit: %dms\n", pit_getticks());
    kprintf("\n\n");
}
static void dump_errno () [static]
Print last error number.
Definition at line 17 of file panic.c.
References errno, and kprintf().
                         {
    kprintf("errno: %d - %s\n", errno, strerror(errno));
}
static void dump_mmu () [static]
Print MMU State.
Definition at line 95 of file panic.c.
References kprintf(), mm_getheap(), heap::size, and heap::used.
                       {
    kprintf("Memory:\n");
    heap_t* h = (heap_t*) mm_getheap();
    kprintf("\tUsed: %d MB (%d Bytes)\n", (h->used / 1024 / 1024), h->used);
    kprintf("\tSize: %d MB (%d Bytes)\n", (h->size / 1024 / 1024), h->size);
    kprintf("\n\n");
}
static void dump_stacktrace (intcount) [static]
Print a stacktrace.
Definition at line 45 of file panic.c.
References __asm__(), eip, elf_kernel_lookup(), esp, kprintf(), and uint32_t.
                                       {
    kprintf("Stack trace:\n");
    
    int* esp = NULL;
    __asm__("mov eax, ebp" : "=a"(esp));
    for(int i = 0; i < count; i++) {
        int eip = *(++esp);
        kprintf("[%d] 0x%x - %s\n", i, eip, elf_kernel_lookup(eip));
        
        esp = (uint32_t*) *(--esp);
        if(!esp)
            break;
    }
    kprintf("\n\n");
}
static void dump_task () [static]
Print all and current task.
Definition at line 69 of file panic.c.
References task::exe, kprintf(), list_foreach, inode::name, task::pid, and value.
                        {
    kprintf("Task:\n");
    
    list_foreach(value, task_queue) {
        task_t* task = (task_t*) value;
        kprintf(" # %d: ", task->pid);
        
        if(task->exe)
            kprintf("%s ", task->exe->name);
        else
            kprintf("unknown ");
            
        if(task == current_task)
            kprintf("(current) ");
            
        if(task == kernel_task)
            kprintf("(kernel) ");
            
        kprintf("\n\n");
    }
}
void panic (char *msg)
Go in Kernel Panic, halt system.
Definition at line 130 of file panic.c.
References panic_r().
                      {
    panic_r(msg, NULL);
}
void panic_r (char *msg, regs_t *r)
Go in Kernel Panic, dump exception registers, halt system.
Definition at line 111 of file panic.c.
References __asm__(), dump_cpu(), dump_errno(), dump_mmu(), dump_stacktrace(), dump_task(), and kprintf().
                                   {
    __asm__ ("cli");
    kprintf("panic: \"%s\"\n", msg);
    
    
    
    dump_cpu(r);
    dump_stacktrace(6);
    dump_task();
    dump_errno();
    dump_mmu();
    for(;;);
}
Variable Documentation
task_t* current_task
Current task address.
Definition at line 37 of file sched.c.
task_t* kernel_task
Kernel task address.
Definition at line 42 of file sched.c.
list_t* task_queue
List of all Task.
Definition at line 48 of file sched.c.
Author
Generated automatically by Doxygen for aPlus from the source code.