.TH "src/include/aplus/pci.h" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/aplus/pci.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <aplus\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpci_device\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPCI_CLASS_OLD\fP   0x00"
.br
.ti -1c
.RI "#define \fBPCI_CLASS_STORAGE\fP   0x01"
.br
.ti -1c
.RI "#define \fBPCI_CLASS_NETWORK\fP   0x02"
.br
.ti -1c
.RI "#define \fBPCI_CLASS_DISPLAY\fP   0x03"
.br
.ti -1c
.RI "#define \fBPCI_CLASS_MULTIMEDIA\fP   0x04"
.br
.ti -1c
.RI "#define \fBPCI_CLASS_MEMORY\fP   0x05"
.br
.ti -1c
.RI "#define \fBPCI_CLASS_BRIDGE\fP   0x06"
.br
.ti -1c
.RI "#define \fBPCI_CLASS_SIMCOM\fP   0x07"
.br
.ti -1c
.RI "#define \fBPCI_CLASS_SYSPERIPHERAL\fP   0x08"
.br
.ti -1c
.RI "#define \fBPCI_CLASS_INPUT\fP   0x09"
.br
.ti -1c
.RI "#define \fBPCI_CLASS_DOCK\fP   0x0A"
.br
.ti -1c
.RI "#define \fBPCI_CLASS_PROCESSOR\fP   0x0B"
.br
.ti -1c
.RI "#define \fBPCI_CLASS_SERIAL\fP   0x0C"
.br
.ti -1c
.RI "#define \fBPCI_CLASS_MISC\fP   0xFF"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBpci_device\fP \fBpci_device_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PCI_CLASS_BRIDGE   0x06"

.PP
Definition at line 14 of file pci\&.h\&.
.SS "#define PCI_CLASS_DISPLAY   0x03"

.PP
Definition at line 11 of file pci\&.h\&.
.SS "#define PCI_CLASS_DOCK   0x0A"

.PP
Definition at line 18 of file pci\&.h\&.
.SS "#define PCI_CLASS_INPUT   0x09"

.PP
Definition at line 17 of file pci\&.h\&.
.SS "#define PCI_CLASS_MEMORY   0x05"

.PP
Definition at line 13 of file pci\&.h\&.
.SS "#define PCI_CLASS_MISC   0xFF"

.PP
Definition at line 21 of file pci\&.h\&.
.SS "#define PCI_CLASS_MULTIMEDIA   0x04"

.PP
Definition at line 12 of file pci\&.h\&.
.SS "#define PCI_CLASS_NETWORK   0x02"

.PP
Definition at line 10 of file pci\&.h\&.
.SS "#define PCI_CLASS_OLD   0x00"

.PP
Definition at line 8 of file pci\&.h\&.
.SS "#define PCI_CLASS_PROCESSOR   0x0B"

.PP
Definition at line 19 of file pci\&.h\&.
.SS "#define PCI_CLASS_SERIAL   0x0C"

.PP
Definition at line 20 of file pci\&.h\&.
.SS "#define PCI_CLASS_SIMCOM   0x07"

.PP
Definition at line 15 of file pci\&.h\&.
.SS "#define PCI_CLASS_STORAGE   0x01"

.PP
Definition at line 9 of file pci\&.h\&.
.SS "#define PCI_CLASS_SYSPERIPHERAL   0x08"

.PP
Definition at line 16 of file pci\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBpci_device\fP  \fBpci_device_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
