src/arch/pci.c
NAME
src/arch/pci.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/pci.h>
#include <aplus/mm.h>
#include <stdint.h>
#include <string.h>
#include <errno.h>
Macros
#define PCI_CONFIG_ADDRESS 0x0CF8
#define PCI_CONFIG_DATA 0x0CFC
#define PCI_MAX_DEVICES 65536
#define PCI_MAX_BUS 255
#define PCI_MAX_DEV 32
#define PCI_MAX_FUNC 8
Functions
static int pci_get_address (uint8_t bus, uint8_t dev, uint8_t func, uint8_t offset)
static uint32_t pci_config_read (uint8_t bus, uint8_t dev, uint8_t func, uint8_t offset)
static uint32_t pci_get_device_id (pci_device_t *device)
static uint32_t pci_get_vendor_id (pci_device_t *device)
static uint32_t pci_get_intr_pin (pci_device_t *device)
static uint32_t pci_get_intr_line (pci_device_t *device)
static uint32_t pci_get_revision (pci_device_t *device)
static uint32_t pci_get_class (pci_device_t *device)
static uint32_t pci_get_header_type (pci_device_t *device)
static uint32_t pci_get_bar (pci_device_t *device, uint8_t bar)
static uint32_t pci_get_iobase (pci_device_t *device)
static uint32_t pci_get_membase (pci_device_t *device)
static void pci_load_device (pci_device_t *device, uint8_t bus, uint8_t dev, uint8_t func)
pci_device_t * pci_find_by_id (uint32_t vendorID, uint32_t deviceID)
int pci_find_by_class (pci_device_t **rdevs, uint32_t class, uint32_t length)
int pci_init ()
Variables
pci_device_t * pci_devices = NULL
Macro Definition Documentation
#define PCI_CONFIG_ADDRESS 0x0CF8
Definition at line 11 of file pci.c.
#define PCI_CONFIG_DATA 0x0CFC
Definition at line 12 of file pci.c.
#define PCI_MAX_BUS 255
Definition at line 14 of file pci.c.
#define PCI_MAX_DEV 32
Definition at line 15 of file pci.c.
#define PCI_MAX_DEVICES 65536
Definition at line 13 of file pci.c.
#define PCI_MAX_FUNC 8
Definition at line 16 of file pci.c.
Function Documentation
static uint32_t pci_config_read (uint8_tbus, uint8_tdev, uint8_tfunc, uint8_toffset) [static]
Definition at line 26 of file pci.c.
References PCI_CONFIG_ADDRESS, PCI_CONFIG_DATA, and pci_get_address().
                                                                                        {
    outl(PCI_CONFIG_ADDRESS, pci_get_address(bus, dev, func, offset));
    
    if(offset % 4 == 0)
        return inl(PCI_CONFIG_DATA);
    return (inl(PCI_CONFIG_DATA) >> ((offset % 4) * 8));
}
int pci_find_by_class (pci_device_t **rdevs, uint32_tclass, uint32_tlength)
Definition at line 131 of file pci.c.
References length, and PCI_MAX_DEVICES.
                                                                             {
    int j = 0;
    for(int i = 0; i < PCI_MAX_DEVICES && j < length; i++) {
        if(pci_devices[i].pci_class != class)
            continue;
        rdevs[j++] = &pci_devices[i];
    }
    return j;
}
pci_device_t* pci_find_by_id (uint32_tvendorID, uint32_tdeviceID)
Definition at line 120 of file pci.c.
References PCI_MAX_DEVICES.
                                                                   {
    for(int i = 0; i < PCI_MAX_DEVICES; i++) {
        if(pci_devices[i].vendorID != vendorID && pci_devices[i].deviceID != deviceID)
            continue;
        return &pci_devices[i];
    }
    return NULL;
}
static int pci_get_address (uint8_tbus, uint8_tdev, uint8_tfunc, uint8_toffset) [static]
Definition at line 22 of file pci.c.
                                                                                   {
    return 0x80000000 | (bus << 16) | (dev << 11) | (func << 8) | (offset & 0xFC);
}
static uint32_t pci_get_bar (pci_device_t *device, uint8_tbar) [static]
Definition at line 65 of file pci.c.
References pci_device::bus, pci_device::dev, pci_device::func, pci_config_read(), pci_get_header_type(), and uint8_t.
                                                               {
    if(bar >= 6)
        return 0;
    uint8_t header = pci_get_header_type(device);
    if(header == 0x02 || (header == 0x01 && bar < 2))
        return 0;
    uint8_t reg = 0x10 + (0x04 * bar);
    return pci_config_read(device->bus, device->dev, device->func, reg);
}
static uint32_t pci_get_class (pci_device_t *device) [static]
Definition at line 56 of file pci.c.
References pci_device::bus, pci_device::dev, pci_device::func, and pci_config_read().
                                                    {
    return pci_config_read(device->bus, device->dev, device->func, 0x0B) & 0xFF;
}
static uint32_t pci_get_device_id (pci_device_t *device) [static]
Definition at line 36 of file pci.c.
References pci_device::bus, pci_device::dev, pci_device::func, and pci_config_read().
                                                        {
    return pci_config_read(device->bus, device->dev, device->func, 2) & 0xFFFF;
}
static uint32_t pci_get_header_type (pci_device_t *device) [static]
Definition at line 60 of file pci.c.
References pci_device::bus, pci_device::dev, pci_device::func, and pci_config_read().
                                                          {
    return pci_config_read(device->bus, device->dev, device->func, 0x0E) & 0x7F;
}
static uint32_t pci_get_intr_line (pci_device_t *device) [static]
Definition at line 48 of file pci.c.
References pci_device::bus, pci_device::dev, pci_device::func, and pci_config_read().
                                                        {
    return pci_config_read(device->bus, device->dev, device->func, 0x3C) & 0xFF;
}
static uint32_t pci_get_intr_pin (pci_device_t *device) [static]
Definition at line 44 of file pci.c.
References pci_device::bus, pci_device::dev, pci_device::func, and pci_config_read().
                                                       {
    return pci_config_read(device->bus, device->dev, device->func, 0x3D) & 0xFF;
}
static uint32_t pci_get_iobase (pci_device_t *device) [static]
Definition at line 77 of file pci.c.
References pci_get_bar(), pci_get_header_type(), uint32_t, and uint8_t.
                                                     {
    uint8_t bars = 6 - pci_get_header_type(device) * 4;
    uint8_t i = 0;
    while(i < bars) {
        uint32_t bar = pci_get_bar(device, i++);
        if(bar & 0x01)
            return bar & 0xFFFFFFFC;
    }
    return 0;
}
static uint32_t pci_get_membase (pci_device_t *device) [static]
Definition at line 90 of file pci.c.
References pci_get_bar(), pci_get_header_type(), uint32_t, and uint8_t.
                                                      {
    uint8_t bars = 6 - pci_get_header_type(device) * 4;
    uint8_t i = 0;
    while(i < bars) {
        uint32_t bar = pci_get_bar(device, i++);
        if((bar & 0x01) == 0)
            return bar & 0xFFFFFFF0;
    }
    return 0;
}
static uint32_t pci_get_revision (pci_device_t *device) [static]
Definition at line 52 of file pci.c.
References pci_device::bus, pci_device::dev, pci_device::func, and pci_config_read().
                                                       {
    return pci_config_read(device->bus, device->dev, device->func, 0x08) & 0xFF;
}
static uint32_t pci_get_vendor_id (pci_device_t *device) [static]
Definition at line 40 of file pci.c.
References pci_device::bus, pci_device::dev, pci_device::func, and pci_config_read().
                                                        {
    return pci_config_read(device->bus, device->dev, device->func, 0) & 0xFFFF;
}
int pci_init ()
Definition at line 144 of file pci.c.
References kmalloc(), kprintf(), pci_config_read(), pci_load_device(), PCI_MAX_BUS, PCI_MAX_DEV, PCI_MAX_DEVICES, PCI_MAX_FUNC, and uint32_t.
               {
    pci_devices = (pci_device_t*) kmalloc(PCI_MAX_DEVICES * sizeof(pci_device_t));
    memset(pci_devices, 0xFF, PCI_MAX_DEVICES * sizeof(pci_device_t));
    int i = 0;
    for(int bus = 0; bus < PCI_MAX_BUS; bus++) {
        for(int dev = 0; dev < PCI_MAX_DEV; dev++) {
            for(int func = 0; func < PCI_MAX_FUNC; func++) {
                uint32_t vendor = pci_config_read(bus, dev, func, 0) & 0xFFFF;
                if(vendor == 0xFFFF || vendor == 0)
                    continue;
                pci_load_device(&pci_devices[i], bus, dev, func);
#if 1
                kprintf("pci: %d:%d.%d: [%x:%x] (rev %x class %x iobase %x mmio %x type %x int %d pin %d)\n",
                            pci_devices[i].bus,
                            pci_devices[i].dev,
                            pci_devices[i].func,
                            pci_devices[i].vendorID,
                            pci_devices[i].deviceID,
                            pci_devices[i].revision,
                            pci_devices[i].pci_class,
                            pci_devices[i].iobase,
                            pci_devices[i].membase,
                            pci_devices[i].header,
                            pci_devices[i].intr_line,
                            pci_devices[i].intr_pin);
#endif
                i++;
            }
        }
    }
    kprintf("pci: loaded %d devices\n", i);
    return 0;
}
static void pci_load_device (pci_device_t *device, uint8_tbus, uint8_tdev, uint8_tfunc) [static]
Definition at line 103 of file pci.c.
References pci_device::bus, pci_device::dev, pci_device::deviceID, pci_device::func, pci_device::header, pci_device::intr_line, pci_device::intr_pin, pci_device::iobase, pci_device::membase, pci_device::pci_class, pci_get_class(), pci_get_device_id(), pci_get_header_type(), pci_get_intr_line(), pci_get_intr_pin(), pci_get_iobase(), pci_get_membase(), pci_get_revision(), pci_get_vendor_id(), pci_device::revision, and pci_device::vendorID.
                                                                                          {
    device->bus = bus;
    device->dev = dev;
    device->func = func;
    device->vendorID = pci_get_vendor_id(device);
    device->deviceID = pci_get_device_id(device);
    device->revision = pci_get_revision(device);
    device->pci_class = pci_get_class(device);
    device->iobase = pci_get_iobase(device);
    device->membase = pci_get_membase(device);
    device->header = pci_get_header_type(device);
    device->intr_pin = pci_get_intr_pin(device);
    device->intr_line = pci_get_intr_line(device);
}
Variable Documentation
pci_device_t* pci_devices = NULL
Definition at line 19 of file pci.c.
Author
Generated automatically by Doxygen for aPlus from the source code.