.TH "pci_device" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pci_device \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pci\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint16_t\fP \fBvendorID\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBdeviceID\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBbus\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBdev\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBfunc\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBrevision\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBpci_class\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBiobase\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBmembase\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBheader\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBintr_pin\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBintr_line\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file pci\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint8_t\fP pci_device::bus"

.PP
Definition at line 27 of file pci\&.h\&.
.SS "\fBuint8_t\fP pci_device::dev"

.PP
Definition at line 28 of file pci\&.h\&.
.SS "\fBuint16_t\fP pci_device::deviceID"

.PP
Definition at line 25 of file pci\&.h\&.
.SS "\fBuint8_t\fP pci_device::func"

.PP
Definition at line 29 of file pci\&.h\&.
.SS "\fBuint8_t\fP pci_device::header"

.PP
Definition at line 36 of file pci\&.h\&.
.SS "\fBuint8_t\fP pci_device::intr_line"

.PP
Definition at line 38 of file pci\&.h\&.
.SS "\fBuint8_t\fP pci_device::intr_pin"

.PP
Definition at line 37 of file pci\&.h\&.
.SS "\fBuint32_t\fP pci_device::iobase"

.PP
Definition at line 33 of file pci\&.h\&.
.SS "\fBuint32_t\fP pci_device::membase"

.PP
Definition at line 34 of file pci\&.h\&.
.SS "\fBuint32_t\fP pci_device::pci_class"

.PP
Definition at line 32 of file pci\&.h\&.
.SS "\fBuint8_t\fP pci_device::revision"

.PP
Definition at line 30 of file pci\&.h\&.
.SS "\fBuint16_t\fP pci_device::vendorID"

.PP
Definition at line 24 of file pci\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
