src/fs/pipe.c
NAME
src/fs/pipe.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/fs.h>
#include <aplus/bufio.h>
#include <aplus/mm.h>
#include <aplus/spinlock.h>
#include <aplus/task.h>
#include <stdio.h>
#include <stddef.h>
#include <stdint.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
Data Structures
struct pipeinfo
Typedefs
typedef struct pipeinfo pipeinfo_t
Functions
int pipe_read (inode_t *inode, char *ptr, int len)
int pipe_write (inode_t *inode, char *ptr, int len)
void pipe_flush (inode_t *inode)
int pipe_create (inode_t inodes[2])
Variables
task_t * current_task
Current task address.
Typedef Documentation
typedef struct pipeinfo pipeinfo_t
Function Documentation
int pipe_create (inode_tinodes[2])
Definition at line 63 of file pipe.c.
References inode::atime, bufio_alloc(), inode::ctime, inode::flush, inode::gid, task::gid, kmalloc(), inode::mode, inode::mtime, name, pipe_flush(), pipe_read(), pipe_write(), inode::read, pipeinfo::read_offset, inode::size, pipeinfo::stream, sys_time(), inode::uid, task::uid, inode::userdata, inode::write, and pipeinfo::write_offset.
                                   {
    pipeinfo_t* pipe = (pipeinfo_t*) kmalloc(sizeof(pipeinfo_t));
    pipe->stream = (bufio_t*) bufio_alloc(BUFSIZ);
    pipe->read_offset = 0;
    pipe->write_offset = 0;
    for(int i = 0; i < 2; i++) {
        memset((void*) &inodes[i], 0, sizeof(inode_t));
        
        inodes[i].atime = inodes[i].mtime = inodes[i].ctime = sys_time(NULL);
        inodes[i].read = pipe_read;
        inodes[i].write = pipe_write;
        inodes[i].flush = pipe_flush;
        inodes[i].uid = current_task->uid;
        inodes[i].gid = current_task->gid;
        inodes[i].mode = S_IFIFO;
        inodes[i].userdata = (void*) pipe;
        inodes[i].size = (size_t) BUFSIZ;
    }
    
    
    strcpy(inodes[0].name, "[pipe:read]");
    strcpy(inodes[1].name, "[pipe:write]");
    
    return 0;
}
void pipe_flush (inode_t *inode)
Definition at line 54 of file pipe.c.
References bufio_free(), kfree(), pipeinfo::stream, and inode::userdata.
                                {
    pipeinfo_t* pipe = inode->userdata;
    
    bufio_free(pipe->stream);
    kfree(pipe);
}
int pipe_read (inode_t *inode, char *ptr, intlen)
Definition at line 27 of file pipe.c.
References bufio_read(), bufio_seek(), bufio_tell(), pipeinfo::read_offset, bufio::size, spinlock_waiton, pipeinfo::stream, inode::userdata, and pipeinfo::write_offset.
                                                  {
    pipeinfo_t* pipe = inode->userdata;
    
    spinlock_waiton(pipe->read_offset + len > pipe->write_offset);
    
    bufio_seek(pipe->stream, pipe->read_offset % pipe->stream->size, SEEK_SET);
    
    size_t tolen = 0;
    while((tolen = bufio_read(pipe->stream, (void*) ((off_t) ptr + (off_t) tolen), len)) < len)
        bufio_seek(pipe->stream, 0, SEEK_SET);
        
    pipe->write_offset = bufio_tell(pipe->stream);
    return (int) len;
}
int pipe_write (inode_t *inode, char *ptr, intlen)
Definition at line 42 of file pipe.c.
References bufio_seek(), bufio_tell(), bufio_write(), bufio::size, pipeinfo::stream, inode::userdata, and pipeinfo::write_offset.
                                                   {
    pipeinfo_t* pipe = inode->userdata;
    bufio_seek(pipe->stream, pipe->write_offset % pipe->stream->size, SEEK_SET);
    
    size_t tolen = 0;
    while((tolen = bufio_write(pipe->stream, (void*) ((off_t) ptr + (off_t) tolen), len)) < len)
        bufio_seek(pipe->stream, 0, SEEK_SET);
        
    pipe->write_offset = bufio_tell(pipe->stream);
    return (int) len;
}
Variable Documentation
task_t* current_task
Current task address.
Definition at line 35 of file sched.c.
Author
Generated automatically by Doxygen for aPlus from the source code.