.TH "pipeinfo" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pipeinfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBbufio_t\fP * \fBstream\fP"
.br
.ti -1c
.RI "off_t \fBread_offset\fP"
.br
.ti -1c
.RI "off_t \fBwrite_offset\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 20 del file pipe\&.c\&.
.SH "Documentazione dei campi"
.PP 
.SS "off_t pipeinfo::read_offset"

.PP
Definizione alla linea 22 del file pipe\&.c\&.
.SS "\fBbufio_t\fP* pipeinfo::stream"

.PP
Definizione alla linea 21 del file pipe\&.c\&.
.SS "off_t pipeinfo::write_offset"

.PP
Definizione alla linea 23 del file pipe\&.c\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
