.TH "pthread_spinlock" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_spinlock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pthread\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "int \fBinterlock\fP"
.br
.ti -1c
.RI "\fBpthread_mutex_t\fP \fBmutex\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 149 del file pthread\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "int pthread_spinlock::interlock"

.PP
Definizione alla linea 150 del file pthread\&.h\&.
.SS "\fBpthread_mutex_t\fP pthread_spinlock::mutex"

.PP
Definizione alla linea 151 del file pthread\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
