usr/src/libpthread/src/pthread_spin.c
NAME
usr/src/libpthread/src/pthread_spin.c -
SYNOPSIS
#include <stdint.h>
#include <pthread.h>
#include 'pthread_internal.h'
Functions
PUBLIC int pthread_spin_init (pthread_spinlock_t *lock, int pshared)
PUBLIC int pthread_spin_destroy (pthread_spinlock_t *lock)
PUBLIC int pthread_spin_lock (pthread_spinlock_t *lock)
PUBLIC int pthread_spin_trylock (pthread_spinlock_t *lock)
PUBLIC int pthread_spin_unlock (pthread_spinlock_t *lock)
Function Documentation
PUBLIC int pthread_spin_destroy (pthread_spinlock_t *lock)
Definition at line 19 of file pthread_spin.c.
References errno, pthread_spinlock::interlock, pthread_spinlock::mutex, and pthread_mutex_destroy().
                                                          {
    if(!lock) {
        errno = EINVAL;
        return 1;
    }
    lock->interlock = 0;
    pthread_mutex_destroy(&lock->mutex);
    return 0;
}
PUBLIC int pthread_spin_init (pthread_spinlock_t *lock, intpshared)
Definition at line 7 of file pthread_spin.c.
References errno, pthread_spinlock::interlock, pthread_spinlock::mutex, and pthread_mutex_init().
                                                                    {
    if(!lock) {
        errno = EINVAL;
        return 1;
    }
    lock->interlock = 0;
    pthread_mutex_init(&lock->mutex, NULL);
    return 0;
}
PUBLIC int pthread_spin_lock (pthread_spinlock_t *lock)
Definition at line 31 of file pthread_spin.c.
References errno, pthread_spinlock::interlock, pthread_spinlock::mutex, and pthread_mutex_lock().
                                                       {
    if(!lock) {
        errno = EINVAL;
        return 1;
    }
    if(pthread_mutex_lock(&lock->mutex) == 0)
        lock->interlock = 1;
    else
        return 1; /* errno already setted */
    return 0;
}
PUBLIC int pthread_spin_trylock (pthread_spinlock_t *lock)
Definition at line 45 of file pthread_spin.c.
References errno, pthread_spinlock::interlock, pthread_spinlock::mutex, and pthread_mutex_trylock().
                                                          {
    if(!lock) {
        errno = EINVAL;
        return 1;
    }
    if(pthread_mutex_trylock(&lock->mutex) == 0)
        lock->interlock = 1;
    else
        return 1; /* errno already setted */
    return 0;
}
PUBLIC int pthread_spin_unlock (pthread_spinlock_t *lock)
Definition at line 59 of file pthread_spin.c.
References errno, pthread_spinlock::interlock, pthread_spinlock::mutex, and pthread_mutex_unlock().
                                                         {
    if(!lock) {
        errno = EINVAL;
        return 1;
    }
    if(pthread_mutex_unlock(&lock->mutex) == 0)
        lock->interlock = 0;
    else
        return 1; /* errno already setted */
    
    return 0;
}
Author
Generated automatically by Doxygen for aPlus from the source code.