.TH "pthread_rwlock" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_rwlock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pthread\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpthread_mutex_t\fP \fBrdmutex\fP"
.br
.ti -1c
.RI "\fBpthread_mutex_t\fP \fBwrmutex\fP"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBshared_waiters\fP"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBexclusive_waiters\fP"
.br
.ti -1c
.RI "int \fBnum_shared_waiters\fP"
.br
.ti -1c
.RI "int \fBnum_exclusive_waiters\fP"
.br
.ti -1c
.RI "\fBpthread_t\fP \fBowner\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 133 of file pthread\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBhandle_t\fP pthread_rwlock::exclusive_waiters"

.PP
Definition at line 137 of file pthread\&.h\&.
.SS "int pthread_rwlock::num_exclusive_waiters"

.PP
Definition at line 139 of file pthread\&.h\&.
.SS "int pthread_rwlock::num_shared_waiters"

.PP
Definition at line 138 of file pthread\&.h\&.
.SS "\fBpthread_t\fP pthread_rwlock::owner"

.PP
Definition at line 140 of file pthread\&.h\&.
.SS "\fBpthread_mutex_t\fP pthread_rwlock::rdmutex"

.PP
Definition at line 134 of file pthread\&.h\&.
.SS "\fBhandle_t\fP pthread_rwlock::shared_waiters"

.PP
Definition at line 136 of file pthread\&.h\&.
.SS "\fBpthread_mutex_t\fP pthread_rwlock::wrmutex"

.PP
Definition at line 135 of file pthread\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
