.TH "pthread_attr" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_attr \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pthread\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "void * \fBstackaddr\fP"
.br
.ti -1c
.RI "size_t \fBstacksize\fP"
.br
.ti -1c
.RI "int \fBdetachstate\fP"
.br
.ti -1c
.RI "struct sched_param \fBparam\fP"
.br
.ti -1c
.RI "int \fBinheritsched\fP"
.br
.ti -1c
.RI "int \fBcontentionscope\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 57 del file pthread\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "int pthread_attr::contentionscope"

.PP
Definizione alla linea 63 del file pthread\&.h\&.
.SS "int pthread_attr::detachstate"

.PP
Definizione alla linea 60 del file pthread\&.h\&.
.SS "int pthread_attr::inheritsched"

.PP
Definizione alla linea 62 del file pthread\&.h\&.
.SS "struct sched_param pthread_attr::param"

.PP
Definizione alla linea 61 del file pthread\&.h\&.
.SS "void* pthread_attr::stackaddr"

.PP
Definizione alla linea 58 del file pthread\&.h\&.
.SS "size_t pthread_attr::stacksize"

.PP
Definizione alla linea 59 del file pthread\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
