.TH "usr/src/libpthread/src/pthread_internal.h" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libpthread/src/pthread_internal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB__pthread_key\fP"
.br
.ti -1c
.RI "struct \fBpthread_context\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPRIVATE\fP   static"
.br
.ti -1c
.RI "#define \fBPUBLIC\fP"
.br
.ti -1c
.RI "#define \fBEXTERN\fP   extern"
.br
.ti -1c
.RI "#define \fBPTHREAD_KEYS_MAX\fP   64"
.br
.ti -1c
.RI "#define \fBPTHREAD_STACK_MIN\fP   4096"
.br
.ti -1c
.RI "#define \fBPTHREAD_THREADS_MAX\fP   2048"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__pthread_key\fP \fB__pthread_key_t\fP"
.br
.ti -1c
.RI "typedef struct \fBpthread_context\fP \fBpthread_context_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsched_yield\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EXTERN   extern"

.PP
Definition at line 20 of file pthread_internal\&.h\&.
.SS "#define PRIVATE   static"

.PP
Definition at line 11 of file pthread_internal\&.h\&.
.SS "#define PTHREAD_KEYS_MAX   64"

.PP
Definition at line 25 of file pthread_internal\&.h\&.
.SS "#define PTHREAD_STACK_MIN   4096"

.PP
Definition at line 26 of file pthread_internal\&.h\&.
.SS "#define PTHREAD_THREADS_MAX   2048"

.PP
Definition at line 27 of file pthread_internal\&.h\&.
.SS "#define PUBLIC"

.PP
Definition at line 15 of file pthread_internal\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB__pthread_key\fP  \fB__pthread_key_t\fP"

.SS "typedef struct \fBpthread_context\fP  \fBpthread_context_t\fP"

.SH "Function Documentation"
.PP 
.SS "int sched_yield (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
