.TH "pthread_rwlockattr" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_rwlockattr \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pthread\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBpshared\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 127 of file pthread\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int pthread_rwlockattr::pshared"

.PP
Definition at line 128 of file pthread\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
