.TH "pthread_condattr" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_condattr \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pthread\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "int \fBpshared\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 101 del file pthread\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "int pthread_condattr::pshared"

.PP
Definizione alla linea 102 del file pthread\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
