.TH "usr/src/libpthread/src/pthread_once.c" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libpthread/src/pthread_once.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include 'pthread_internal\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "\fBPUBLIC\fP int \fBpthread_once\fP (\fBpthread_once_t\fP *once_control, void(*init_routine)(void))"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "\fBPUBLIC\fP int \fBpthread_once\fP (\fBpthread_once_t\fP *once_control, void(*)(void)init_routine)"

.PP
Definizione alla linea 7 del file pthread_once\&.c\&.
.PP
Referenzia errno\&.
.PP
.nf
7                                                                                   {
8     errno = ENOSYS;
9     return 1;
10 }
.fi
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
