.TH "usr/src/libpthread/src/pthread_cancel.c" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libpthread/src/pthread_cancel.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include 'pthread_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPUBLIC\fP int \fBpthread_cancel\fP (\fBpthread_t\fP thread)"
.br
.ti -1c
.RI "\fBPUBLIC\fP int \fBpthread_setcancelstate\fP (int state, int *oldstate)"
.br
.ti -1c
.RI "\fBPUBLIC\fP int \fBpthread_setcanceltype\fP (int \fBtype\fP, int *oldtype)"
.br
.ti -1c
.RI "\fBPUBLIC\fP void \fBpthread_testcancel\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBPUBLIC\fP int pthread_cancel (\fBpthread_t\fPthread)"

.PP
Definition at line 7 of file pthread_cancel\&.c\&.
.PP
References pthread_detach()\&.
.PP
.nf
7                                             {
8     return pthread_detach(thread);
9 }
.fi
.SS "\fBPUBLIC\fP int pthread_setcancelstate (intstate, int *oldstate)"

.PP
Definition at line 12 of file pthread_cancel\&.c\&.
.PP
References errno\&.
.PP
.nf
12                                                             {
13     errno = ENOSYS;
14     return 1;
15 }
.fi
.SS "\fBPUBLIC\fP int pthread_setcanceltype (inttype, int *oldtype)"

.PP
Definition at line 18 of file pthread_cancel\&.c\&.
.PP
References errno\&.
.PP
.nf
18                                                          {
19     errno = ENOSYS;
20     return 1;
21 }
.fi
.SS "\fBPUBLIC\fP void pthread_testcancel (void)"

.PP
Definition at line 23 of file pthread_cancel\&.c\&.
.PP
.nf
23                                      {
24     /* Boh ?? */
25 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
