.TH "pthread_once" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_once \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pthread\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "volatile int \fBdone\fP"
.br
.ti -1c
.RI "int \fBstarted\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 67 del file pthread\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "volatile int pthread_once::done"

.PP
Definizione alla linea 68 del file pthread\&.h\&.
.SS "int pthread_once::started"

.PP
Definizione alla linea 69 del file pthread\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
