usr/src/libpthread/src/pthread_create.c
NAME
usr/src/libpthread/src/pthread_create.c -
SYNOPSIS
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include 'pthread_internal.h'
Functions
EXTERN void __pthread_init_queue (void)
PRIVATE void __pthread_handler__ (pthread_context_t *ctx)
PUBLIC int pthread_create (pthread_t *thread, const pthread_attr_t *attr, void *(*start)(void *), void *arg)
Variables
EXTERN uint32_t __pthread_counts
EXTERN pthread_context_t * __pthread_queue
Function Documentation
PRIVATE void __pthread_handler__ (pthread_context_t *ctx)
Definition at line 24 of file pthread_create.c.
References pthread_context::entry, pthread_context::param, and pthread_exit().
                                                         {
#endif
    if(ctx == NULL)
        _exit(-1);
    if(ctx->entry == NULL)
        _exit(-1);
    pthread_exit(ctx->entry(ctx->param));
}
EXTERN void __pthread_init_queue (void)
Definition at line 24 of file pthread_queue.c.
References __current_thread, __os_gettid, __pthread_dnit(), pthread_context::attr, pthread_context::cond, pthread_once::done, pthread_context::entry, pthread_context::exitval, pthread_context::next, pthread_context::once, pthread_context::param, pthread_once::started, and pthread_context::tid.
                                   {
    static int init = 0;
    if(init)
        return;
    init++;
    __current_thread.tid = __os_gettid();
    __current_thread.entry = NULL;
    __current_thread.param = NULL;
    __current_thread.exitval = NULL;
    __current_thread.once.done = 0;
    __current_thread.once.started = -1;
    __current_thread.cond = NULL;
    __current_thread.next = NULL;
    memset(&__current_thread.attr, 0, sizeof(pthread_attr_t));
    atexit(__pthread_dnit);
}
PUBLIC int pthread_create (pthread_t *thread, const pthread_attr_t *attr, void *(*)(void *)start, void *arg)
Definition at line 37 of file pthread_create.c.
References __os_thread_create, __pthread_counts, __pthread_handler__(), __pthread_init_queue(), __pthread_queue, pthread_context::attr, pthread_once::done, pthread_context::entry, errno, pthread_attr::inheritsched, pthread_context::next, pthread_context::once, pthread_context::param, pthread_attr::param, pthread_attr_setschedparam(), PTHREAD_INHERIT_SCHED, pthread_self(), PTHREAD_THREADS_MAX, pthread_once::started, and pthread_context::tid.
                                                                                                           {
    __pthread_init_queue();
    if(!thread) {
        errno = EINVAL;
        return -1;
    }
    if(__pthread_counts > PTHREAD_THREADS_MAX) {
        errno = EAGAIN;
        return -1;
    }
    pthread_context_t* ctx = malloc(sizeof(pthread_context_t));
    memset(ctx, 0, sizeof(pthread_context_t));
    ctx->entry = start;
    ctx->param = arg;
    ctx->once.done = 0;
    ctx->once.started = -1;
    ctx->next = 0;
    if(attr)
        memcpy(&ctx->attr, attr, sizeof(pthread_attr_t));
    if(ctx->attr.inheritsched == PTHREAD_INHERIT_SCHED) {
        pthread_t px = pthread_self();
        if(px) {
            pthread_context_t* inh = (pthread_context_t*) px;
            pthread_attr_setschedparam(&ctx->attr, &inh->attr.param);
        }
    }
    __pthread_counts += 1;
    *thread = (pthread_t) ctx;
    
    
    ctx->next = __pthread_queue;
    __pthread_queue = ctx;
        
    ctx->tid = __os_thread_create(__pthread_handler__, ctx, ctx->attr.param.sched_priority);
    return 0;
}
Variable Documentation
EXTERN uint32_t __pthread_counts
Definition at line 10 of file pthread_create.c.
EXTERN pthread_context_t* __pthread_queue
Definition at line 11 of file pthread_create.c.
Author
Generated automatically by Doxygen for aPlus from the source code.