.TH "pthread_attr" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_attr \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pthread\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBstackaddr\fP"
.br
.ti -1c
.RI "size_t \fBstacksize\fP"
.br
.ti -1c
.RI "int \fBdetachstate\fP"
.br
.ti -1c
.RI "struct sched_param \fBparam\fP"
.br
.ti -1c
.RI "int \fBinheritsched\fP"
.br
.ti -1c
.RI "int \fBcontentionscope\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file pthread\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int pthread_attr::contentionscope"

.PP
Definition at line 63 of file pthread\&.h\&.
.SS "int pthread_attr::detachstate"

.PP
Definition at line 60 of file pthread\&.h\&.
.SS "int pthread_attr::inheritsched"

.PP
Definition at line 62 of file pthread\&.h\&.
.SS "struct sched_param pthread_attr::param"

.PP
Definition at line 61 of file pthread\&.h\&.
.SS "void* pthread_attr::stackaddr"

.PP
Definition at line 58 of file pthread\&.h\&.
.SS "size_t pthread_attr::stacksize"

.PP
Definition at line 59 of file pthread\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
