usr/src/libpthread/src/pthread_barrier.c
NAME
usr/src/libpthread/src/pthread_barrier.c -
SYNOPSIS
#include <stdint.h>
#include <sched.h>
#include <time.h>
#include <pthread.h>
#include 'pthread_internal.h'
Functions
PUBLIC int pthread_barrier_init (pthread_barrier_t *barrier, const pthread_barrierattr_t *attr, unsigned int count)
PUBLIC int pthread_barrier_destroy (pthread_barrier_t *barrier)
PUBLIC int pthread_barrier_wait (pthread_barrier_t *barrier)
Function Documentation
PUBLIC int pthread_barrier_destroy (pthread_barrier_t *barrier)
Definition at line 29 of file pthread_barrier.c.
References pthread_barrier::curr_height, errno, and pthread_barrier::init_height.
                                                               {
    if(barrier == NULL) {
        errno = EINVAL;
        return -1;
    }
    barrier->curr_height = 0;
    barrier->init_height = 0;
    
    return 0;
}
PUBLIC int pthread_barrier_init (pthread_barrier_t *barrier, const pthread_barrierattr_t *attr, unsigned intcount)
Definition at line 9 of file pthread_barrier.c.
References pthread_barrier::curr_height, errno, pthread_barrier::init_height, pthread_barrier::owner, and pthread_self().
                                                                                                                   {
    if(barrier == NULL) {
        errno = EINVAL;
        return -1;
    }
    if(count == 0) {
        errno = EINVAL;
        return -1;
    }
    barrier->curr_height = 0;
    barrier->init_height = count;
    barrier->owner = pthread_self();
    
    return 0;
}
PUBLIC int pthread_barrier_wait (pthread_barrier_t *barrier)
Definition at line 43 of file pthread_barrier.c.
References pthread_barrier::curr_height, errno, pthread_barrier::init_height, pthread_barrier::owner, PTHREAD_BARRIER_SERIAL_THREAD, pthread_self(), and sched_yield().
                                                            {
    if(barrier == NULL) {
        errno = EINVAL;
        return -1;
    }
    barrier->curr_height += 1;
    while(barrier->curr_height < barrier->init_height)
        sched_yield();
    if(pthread_self() == barrier->owner)
        return PTHREAD_BARRIER_SERIAL_THREAD;
    return 0;
}
Author
Generated automatically by Doxygen for aPlus from the source code.