usr/src/libpthread/include/pthread.h
NAME
usr/src/libpthread/include/pthread.h -
SYNOPSIS
#include <stdint.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sched.h>
#include <unistd.h>
Data Structures
struct pthread_attr
struct pthread_once
struct pthread_mutexattr
struct pthread_mutex
struct pthread_condattr
struct pthread_cond
struct pthread_barrierattr
struct pthread_barrier
struct pthread_rwlockattr
struct pthread_rwlock
struct pthread_spinlock
Macros
#define _POSIX_THREADS
#define PTHREAD_CREATE_JOINABLE 0
#define PTHREAD_CREATE_DETACHED 1
#define PTHREAD_INHERIT_SCHED 0
#define PTHREAD_EXPLICIT_SCHED 1
#define PTHREAD_SCOPE_PROCESS 0
#define PTHREAD_SCOPE_SYSTEM 1
#define PTHREAD_CANCEL_ENABLE 0
#define PTHREAD_CANCEL_DISABLE 1
#define PTHREAD_PROCESS_PRIVATE 0
#define PTHREAD_PROCESS_SHARED 1
#define PTHREAD_ONCE_INIT { 0, -1 }
#define PTHREAD_MUTEX_NORMAL 0
#define PTHREAD_MUTEX_RECURSIVE 1
#define PTHREAD_MUTEX_ERRORCHECK 2
#define PTHREAD_MUTEX_DEFAULT PTHREAD_MUTEX_NORMAL
#define PTHREAD_MUTEX_INITIALIZER { 0, 0, -1, -1, -1 }
#define PTHREAD_ERRORCHECK_MUTEX_INITIALIZER_NP { 0, 0, -1, -1, -1 }
#define PTHREAD_COND_INITIALIZER ((pthread_cond_t) -1)
#define PTHREAD_BARRIER_SERIAL_THREAD ~0
#define PTHREAD_RWLOCK_INITIALIZER { PTHREAD_MUTEX_INITIALIZER, 0, 0, 0, 0, 0, 0 }
#define SPINLOCK_UNLOCKED 1
#define SPINLOCK_LOCKED 2
#define SPINLOCK_USEMUTEX 3
#define PTHREAD_SPINLOCK_INITIALIZER { 0, 0 }
Typedefs
typedef uint32_t tls_t
typedef uint32_t handle_t
typedef handle_t pthread_t
typedef tls_t pthread_key_t
typedef struct pthread_attr pthread_attr_t
typedef struct pthread_once pthread_once_t
typedef struct pthread_mutexattr pthread_mutexattr_t
typedef struct pthread_mutex pthread_mutex_t
typedef struct pthread_condattr pthread_condattr_t
typedef struct pthread_cond pthread_cond_t
typedef struct pthread_barrierattr pthread_barrierattr_t
typedef struct pthread_barrier pthread_barrier_t
typedef struct pthread_rwlockattr pthread_rwlockattr_t
typedef struct pthread_rwlock pthread_rwlock_t
typedef struct pthread_spinlock pthread_spinlock_t
Functions
int pthread_attr_init (pthread_attr_t *attr)
int pthread_attr_destroy (pthread_attr_t *attr)
int pthread_attr_getdetachstate (const pthread_attr_t *attr, int *detachstate)
int pthread_attr_setdetachstate (pthread_attr_t *attr, int detachstate)
int pthread_attr_getstackaddr (const pthread_attr_t *attr, void **stackaddr)
int pthread_attr_setstackaddr (pthread_attr_t *attr, void *stackaddr)
int pthread_attr_getstacksize (const pthread_attr_t *attr, size_t *stacksize)
int pthread_attr_setstacksize (pthread_attr_t *attr, size_t stacksize)
int pthread_attr_getschedparam (const pthread_attr_t *attr, struct sched_param *param)
int pthread_attr_setschedparam (pthread_attr_t *attr, const struct sched_param *param)
int pthread_attr_getschedpolicy (pthread_attr_t *attr, int *policy)
int pthread_attr_setschedpolicy (pthread_attr_t *attr, int policy)
int pthread_attr_getinheritsched (pthread_attr_t *attr, int *inheritsched)
int pthread_attr_setinheritsched (pthread_attr_t *attr, int inheritsched)
int pthread_attr_getscope (const pthread_attr_t *attr, int *contentionscope)
int pthread_attr_setscope (pthread_attr_t *attr, int contentionscope)
int pthread_create (pthread_t *thread, const pthread_attr_t *attr, void *(*start)(void *), void *arg)
int pthread_detach (pthread_t thread)
int pthread_equal (pthread_t t1, pthread_t t2)
void pthread_exit (void *value_ptr)
int pthread_join (pthread_t thread, void **value_ptr)
pthread_t pthread_self (void)
int pthread_cancel (pthread_t thread)
int pthread_setcancelstate (int state, int *oldstate)
int pthread_setcanceltype (int type, int *oldtype)
void pthread_testcancel (void)
int pthread_once (pthread_once_t *once_control, void(*init_routine)(void))
int pthread_setschedparam (pthread_t thread, int policy, const struct sched_param *param)
int pthread_getschedparam (pthread_t thread, int *policy, struct sched_param *param)
int pthread_setconcurrency (int level)
int pthread_getconcurrency (void)
int pthread_key_create (pthread_key_t *key, void(*destructor)(void *))
int pthread_key_delete (pthread_key_t key)
int pthread_setspecific (pthread_key_t key, const void *value)
void * pthread_getspecific (pthread_key_t key)
int pthread_mutexattr_init (pthread_mutexattr_t *attr)
int pthread_mutexattr_destroy (pthread_mutexattr_t *attr)
int pthread_mutexattr_getpshared (const pthread_mutexattr_t *attr, int *pshared)
int pthread_mutexattr_setpshared (pthread_mutexattr_t *attr, int pshared)
int pthread_mutexattr_gettype (pthread_mutexattr_t *attr, int *kind)
int pthread_mutexattr_settype (pthread_mutexattr_t *attr, int kind)
int pthread_mutex_init (pthread_mutex_t *mutex, const pthread_mutexattr_t *attr)
int pthread_mutex_destroy (pthread_mutex_t *mutex)
int pthread_mutex_lock (pthread_mutex_t *mutex)
int pthread_mutex_timedlock (pthread_mutex_t *mutex, const struct timespec *abstime)
int pthread_mutex_trylock (pthread_mutex_t *mutex)
int pthread_mutex_unlock (pthread_mutex_t *mutex)
int pthread_condattr_init (pthread_condattr_t *attr)
int pthread_condattr_destroy (pthread_condattr_t *attr)
int pthread_condattr_getpshared (const pthread_condattr_t *attr, int *pshared)
int pthread_condattr_setpshared (pthread_condattr_t *attr, int pshared)
int pthread_cond_init (pthread_cond_t *cond, const pthread_condattr_t *attr)
int pthread_cond_destroy (pthread_cond_t *cond)
int pthread_cond_wait (pthread_cond_t *cond, pthread_mutex_t *mutex)
int pthread_cond_timedwait (pthread_cond_t *cond, pthread_mutex_t *mutex, const struct timespec *abstime)
int pthread_cond_signal (pthread_cond_t *cond)
int pthread_cond_broadcast (pthread_cond_t *cond)
int pthread_barrierattr_init (pthread_barrierattr_t *attr)
int pthread_barrierattr_destroy (pthread_barrierattr_t *attr)
int pthread_barrierattr_getpshared (const pthread_barrierattr_t *attr, int *pshared)
int pthread_barrierattr_setpshared (pthread_barrierattr_t *attr, int pshared)
int pthread_barrier_init (pthread_barrier_t *barrier, const pthread_barrierattr_t *attr, unsigned int count)
int pthread_barrier_destroy (pthread_barrier_t *barrier)
int pthread_barrier_wait (pthread_barrier_t *barrier)
int pthread_rwlockattr_init (pthread_rwlockattr_t *attr)
int pthread_rwlockattr_destroy (pthread_rwlockattr_t *attr)
int pthread_rwlockattr_getpshared (const pthread_rwlockattr_t *attr, int *pshared)
int pthread_rwlockattr_setpshared (pthread_rwlockattr_t *attr, int pshared)
int pthread_rwlock_init (pthread_rwlock_t *lock, const pthread_rwlockattr_t *attr)
int pthread_rwlock_destroy (pthread_rwlock_t *lock)
int pthread_rwlock_tryrdlock (pthread_rwlock_t *lock)
int pthread_rwlock_trywrlock (pthread_rwlock_t *lock)
int pthread_rwlock_rdlock (pthread_rwlock_t *lock)
int pthread_rwlock_timedrdlock (pthread_rwlock_t *lock, const struct timespec *abstime)
int pthread_rwlock_wrlock (pthread_rwlock_t *lock)
int pthread_rwlock_timedwrlock (pthread_rwlock_t *lock, const struct timespec *abstime)
int pthread_rwlock_unlock (pthread_rwlock_t *lock)
int pthread_spin_init (pthread_spinlock_t *lock, int pshared)
int pthread_spin_destroy (pthread_spinlock_t *lock)
int pthread_spin_lock (pthread_spinlock_t *lock)
int pthread_spin_trylock (pthread_spinlock_t *lock)
int pthread_spin_unlock (pthread_spinlock_t *lock)
Macro Definition Documentation
#define _POSIX_THREADS
Definition at line 32 of file pthread.h.
#define PTHREAD_BARRIER_SERIAL_THREAD ~0
Definition at line 114 of file pthread.h.
#define PTHREAD_CANCEL_DISABLE 1
Definition at line 50 of file pthread.h.
#define PTHREAD_CANCEL_ENABLE 0
Definition at line 49 of file pthread.h.
#define PTHREAD_COND_INITIALIZER ((pthread_cond_t) -1)
Definition at line 110 of file pthread.h.
#define PTHREAD_CREATE_DETACHED 1
Definition at line 41 of file pthread.h.
#define PTHREAD_CREATE_JOINABLE 0
Definition at line 40 of file pthread.h.
#define PTHREAD_ERRORCHECK_MUTEX_INITIALIZER_NP { 0, 0, -1, -1, -1 }
Definition at line 98 of file pthread.h.
#define PTHREAD_EXPLICIT_SCHED 1
Definition at line 44 of file pthread.h.
#define PTHREAD_INHERIT_SCHED 0
Definition at line 43 of file pthread.h.
#define PTHREAD_MUTEX_DEFAULT PTHREAD_MUTEX_NORMAL
Definition at line 79 of file pthread.h.
#define PTHREAD_MUTEX_ERRORCHECK 2
Definition at line 78 of file pthread.h.
#define PTHREAD_MUTEX_INITIALIZER { 0, 0, -1, -1, -1 }
Definition at line 97 of file pthread.h.
#define PTHREAD_MUTEX_NORMAL 0
Definition at line 76 of file pthread.h.
#define PTHREAD_MUTEX_RECURSIVE 1
Definition at line 77 of file pthread.h.
#define PTHREAD_ONCE_INIT { 0, -1 }
Definition at line 72 of file pthread.h.
#define PTHREAD_PROCESS_PRIVATE 0
Definition at line 52 of file pthread.h.
#define PTHREAD_PROCESS_SHARED 1
Definition at line 53 of file pthread.h.
#define PTHREAD_RWLOCK_INITIALIZER { PTHREAD_MUTEX_INITIALIZER, 0, 0, 0, 0, 0, 0 }
Definition at line 143 of file pthread.h.
#define PTHREAD_SCOPE_PROCESS 0
Definition at line 46 of file pthread.h.
#define PTHREAD_SCOPE_SYSTEM 1
Definition at line 47 of file pthread.h.
#define PTHREAD_SPINLOCK_INITIALIZER { 0, 0 }
Definition at line 155 of file pthread.h.
#define SPINLOCK_LOCKED 2
Definition at line 147 of file pthread.h.
#define SPINLOCK_UNLOCKED 1
Definition at line 146 of file pthread.h.
#define SPINLOCK_USEMUTEX 3
Definition at line 148 of file pthread.h.
Typedef Documentation
typedef uint32_t handle_t
Definition at line 36 of file pthread.h.
typedef struct pthread_attr pthread_attr_t
typedef struct pthread_barrier pthread_barrier_t
typedef struct pthread_barrierattr pthread_barrierattr_t
typedef struct pthread_cond pthread_cond_t
typedef struct pthread_condattr pthread_condattr_t
typedef tls_t pthread_key_t
Definition at line 38 of file pthread.h.
typedef struct pthread_mutex pthread_mutex_t
typedef struct pthread_mutexattr pthread_mutexattr_t
typedef struct pthread_once pthread_once_t
typedef struct pthread_rwlock pthread_rwlock_t
typedef struct pthread_rwlockattr pthread_rwlockattr_t
typedef struct pthread_spinlock pthread_spinlock_t
typedef handle_t pthread_t
Definition at line 37 of file pthread.h.
typedef uint32_t tls_t
Definition at line 35 of file pthread.h.
Function Documentation
int pthread_attr_destroy (pthread_attr_t *attr)
Definition at line 28 of file pthread_attr.c.
References errno.
                                                      {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    memset(attr, 0, sizeof(pthread_attr_t));
    return 0;
}
int pthread_attr_getdetachstate (const pthread_attr_t *attr, int *detachstate)
Definition at line 38 of file pthread_attr.c.
References pthread_attr::detachstate, and errno.
                                                                                     {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    *detachstate = attr->detachstate;
    return 0;
}
int pthread_attr_getinheritsched (pthread_attr_t *attr, int *inheritsched)
Definition at line 133 of file pthread_attr.c.
References errno, and pthread_attr::inheritsched.
                                                                                 {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    *inheritsched = attr->inheritsched;
    return 0;
}
int pthread_attr_getschedparam (const pthread_attr_t *attr, struct sched_param *param)
Definition at line 100 of file pthread_attr.c.
References errno, and pthread_attr::param.
                                                                                             {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    memcpy(param, &attr->param, sizeof(struct sched_param));
    return 0;
}
int pthread_attr_getschedpolicy (pthread_attr_t *attr, int *policy)
Definition at line 123 of file pthread_attr.c.
References errno.
                                                                          {
    errno = ENOSYS;
    return -1;
}
int pthread_attr_getscope (const pthread_attr_t *attr, int *contentionscope)
Definition at line 153 of file pthread_attr.c.
References pthread_attr::contentionscope, and errno.
                                                                                   {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    *contentionscope = attr->contentionscope;
    return 0;
}
int pthread_attr_getstackaddr (const pthread_attr_t *attr, void **stackaddr)
Definition at line 58 of file pthread_attr.c.
References errno, and pthread_attr::stackaddr.
                                                                                   {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    *stackaddr = attr->stackaddr;
    return 0;
}
int pthread_attr_getstacksize (const pthread_attr_t *attr, size_t *stacksize)
Definition at line 79 of file pthread_attr.c.
References errno, and pthread_attr::stacksize.
                                                                                    {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    *stacksize = attr->stacksize;
    return 0;
}
int pthread_attr_init (pthread_attr_t *attr)
Definition at line 12 of file pthread_attr.c.
References pthread_attr::contentionscope, pthread_attr::detachstate, errno, pthread_attr::inheritsched, pthread_attr::param, PTHREAD_STACK_MIN, pthread_attr::stackaddr, and pthread_attr::stacksize.
                                                   {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    attr->stackaddr = 0;
    attr->stacksize = PTHREAD_STACK_MIN;
    attr->detachstate = 0;
    attr->param.sched_priority = 0;
    attr->inheritsched = 0;
    attr->contentionscope = 0;
    
    return 0;
}
int pthread_attr_setdetachstate (pthread_attr_t *attr, intdetachstate)
Definition at line 48 of file pthread_attr.c.
References pthread_attr::detachstate, and errno.
                                                                              {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    attr->detachstate = detachstate;
    return 0;
}
int pthread_attr_setinheritsched (pthread_attr_t *attr, intinheritsched)
Definition at line 143 of file pthread_attr.c.
References errno, and pthread_attr::inheritsched.
                                                                                {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    attr->inheritsched = inheritsched;
    return 0;
}
int pthread_attr_setschedparam (pthread_attr_t *attr, const struct sched_param *param)
Definition at line 112 of file pthread_attr.c.
References errno, and pthread_attr::param.
                                                                                             {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    memcpy(&attr->param, param, sizeof(struct sched_param));
    return 0;
}
int pthread_attr_setschedpolicy (pthread_attr_t *attr, intpolicy)
Definition at line 128 of file pthread_attr.c.
References errno.
                                                                         {
    errno = ENOSYS;
    return -1;
}
int pthread_attr_setscope (pthread_attr_t *attr, intcontentionscope)
Definition at line 163 of file pthread_attr.c.
References pthread_attr::contentionscope, and errno.
                                                                            {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    attr->contentionscope = contentionscope;
    return 0;
}
int pthread_attr_setstackaddr (pthread_attr_t *attr, void *stackaddr)
Definition at line 68 of file pthread_attr.c.
References errno, and pthread_attr::stackaddr.
                                                                            {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    attr->stackaddr = stackaddr;
    return 0;
}
int pthread_attr_setstacksize (pthread_attr_t *attr, size_tstacksize)
Definition at line 89 of file pthread_attr.c.
References errno, and pthread_attr::stacksize.
                                                                             {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    attr->stacksize = stacksize;
    return 0;
}
int pthread_barrier_destroy (pthread_barrier_t *barrier)
Definition at line 29 of file pthread_barrier.c.
References pthread_barrier::curr_height, errno, and pthread_barrier::init_height.
                                                               {
    if(barrier == NULL) {
        errno = EINVAL;
        return -1;
    }
    barrier->curr_height = 0;
    barrier->init_height = 0;
    
    return 0;
}
int pthread_barrier_init (pthread_barrier_t *barrier, const pthread_barrierattr_t *attr, unsigned intcount)
Definition at line 9 of file pthread_barrier.c.
References pthread_barrier::curr_height, errno, pthread_barrier::init_height, pthread_barrier::owner, and pthread_self().
                                                                                                                   {
    if(barrier == NULL) {
        errno = EINVAL;
        return -1;
    }
    if(count == 0) {
        errno = EINVAL;
        return -1;
    }
    barrier->curr_height = 0;
    barrier->init_height = count;
    barrier->owner = pthread_self();
    
    return 0;
}
int pthread_barrier_wait (pthread_barrier_t *barrier)
Definition at line 43 of file pthread_barrier.c.
References pthread_barrier::curr_height, errno, pthread_barrier::init_height, pthread_barrier::owner, PTHREAD_BARRIER_SERIAL_THREAD, pthread_self(), and sched_yield().
                                                            {
    if(barrier == NULL) {
        errno = EINVAL;
        return -1;
    }
    barrier->curr_height += 1;
    while(barrier->curr_height < barrier->init_height)
        sched_yield();
    if(pthread_self() == barrier->owner)
        return PTHREAD_BARRIER_SERIAL_THREAD;
    return 0;
}
int pthread_barrierattr_destroy (pthread_barrierattr_t *attr)
Definition at line 20 of file pthread_barrierattr.c.
References errno, and pthread_barrierattr::pshared.
                                                                    {
    if(attr == NULL) {
        errno = EINVAL;
        return -1;
    }
    attr->pshared = 0;
    return 0;
}
int pthread_barrierattr_getpshared (const pthread_barrierattr_t *attr, int *pshared)
Definition at line 31 of file pthread_barrierattr.c.
References errno, and pthread_barrierattr::pshared.
                                                                                           {
    if(attr == NULL) {
        errno = EINVAL;
        return -1;
    }
    if(pshared == NULL) {
        errno = EINVAL;
        return -1;
    }
    
    *pshared = attr->pshared;
    return 0;
}
int pthread_barrierattr_init (pthread_barrierattr_t *attr)
Definition at line 9 of file pthread_barrierattr.c.
References errno, and pthread_barrierattr::pshared.
                                                                 {
    if(attr == NULL) {
        errno = EINVAL;
        return -1;
    }
    attr->pshared = 0;
    return 0;
}
int pthread_barrierattr_setpshared (pthread_barrierattr_t *attr, intpshared)
Definition at line 47 of file pthread_barrierattr.c.
References errno, and pthread_barrierattr::pshared.
                                                                                    {
    if(attr == NULL) {
        errno = EINVAL;
        return -1;
    }
    attr->pshared = pshared;
    return 0;
}
int pthread_cancel (pthread_tthread)
Definition at line 7 of file pthread_cancel.c.
References pthread_detach().
                                            {
    return pthread_detach(thread);
}
int pthread_cond_broadcast (pthread_cond_t *cond)
Definition at line 116 of file pthread_cond.c.
References __pthread_queue, pthread_context::cond, errno, pthread_context::next, pthread_cond::semaphore, and pthread_cond::waiting.
                                                        {
    if(!__pthread_queue) {
        errno = ESRCH;
        return -1;
    }
    pthread_context_t* tmp = __pthread_queue;
    while(tmp) {
        if(tmp->cond == cond) {
            if(tmp->cond->waiting) {
                tmp->cond->semaphore = 0;
            }
        }
        tmp = tmp->next;
    }
    return 0;
}
int pthread_cond_destroy (pthread_cond_t *cond)
Definition at line 25 of file pthread_cond.c.
References errno, pthread_cond::semaphore, and pthread_cond::waiting.
                                                      {
    if(!cond) {
        errno = EINVAL;
        return -1;
    }
    if(cond->waiting) {
        errno = EBUSY;
        return -1;
    }
    cond->waiting = 0;
    cond->semaphore = 0;
    
    return 0;
}
int pthread_cond_init (pthread_cond_t *cond, const pthread_condattr_t *attr)
Definition at line 13 of file pthread_cond.c.
References errno, pthread_cond::semaphore, and pthread_cond::waiting.
                                                                                   {
    if(!cond) {
        errno = EINVAL;
        return -1;
    }
    cond->waiting = 0;
    cond->semaphore = 0;
    return 0;
}
int pthread_cond_signal (pthread_cond_t *cond)
Definition at line 93 of file pthread_cond.c.
References __pthread_queue, pthread_context::cond, errno, pthread_context::next, pthread_cond::semaphore, and pthread_cond::waiting.
                                                     {
    if(!__pthread_queue) {
        errno = ESRCH;
        return -1;
    }
    pthread_context_t* tmp = __pthread_queue;
    while(tmp) {
        if(tmp->cond == cond) {
            if(tmp->cond->waiting) {
                tmp->cond->semaphore = 0;
                return 0;
            }
        }
        tmp = tmp->next;
    }
    errno = ESRCH;
    return -1;
}
int pthread_cond_timedwait (pthread_cond_t *cond, pthread_mutex_t *mutex, const struct timespec *abstime)
Definition at line 44 of file pthread_cond.c.
References pthread_context::cond, errno, pthread_mutex::owner, pthread_mutex_unlock(), pthread_self(), sched_yield(), pthread_cond::semaphore, and pthread_cond::waiting.
                                                                                                                {
        if(!cond) {
        errno = EINVAL;
        return -1;
    }
    if(!mutex) {
        errno = EINVAL;
        return -1;
    }
    if(mutex->owner != pthread_self()) {
        errno = EINVAL;
        return -1;
    }
    pthread_context_t* ctx = (pthread_context_t*) pthread_self();
    if(!ctx) {
        errno = EINVAL;
        return -1;
    }
    ctx->cond = cond;
    ctx->cond->waiting = 1;
    ctx->cond->semaphore = 1;
    int t0;
    if(abstime)
        t0 = time(NULL) + abstime->tv_sec;
    else
        t0 = ~0;
    while(ctx->cond->semaphore == 1 && (time(NULL) < t0))
        sched_yield();
    ctx->cond->waiting = 0;
    ctx->cond->semaphore = 0;
    ctx->cond = 0;
    pthread_mutex_unlock(mutex);
    return 0;
}
int pthread_cond_wait (pthread_cond_t *cond, pthread_mutex_t *mutex)
Definition at line 88 of file pthread_cond.c.
References pthread_cond_timedwait().
                                                                           {
    return pthread_cond_timedwait(cond, mutex, NULL);
}
int pthread_condattr_destroy (pthread_condattr_t *attr)
Definition at line 18 of file pthread_condattr.c.
References errno, and pthread_condattr::pshared.
                                                              {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    attr->pshared = 0;
    return 0;
}
int pthread_condattr_getpshared (const pthread_condattr_t *attr, int *pshared)
Definition at line 29 of file pthread_condattr.c.
References errno, and pthread_condattr::pshared.
                                                                                     {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    
    *pshared = attr->pshared;
    return 0;
}
int pthread_condattr_init (pthread_condattr_t *attr)
Definition at line 7 of file pthread_condattr.c.
References errno, and pthread_condattr::pshared.
                                                           {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    attr->pshared = 0;
    return 0;
}
int pthread_condattr_setpshared (pthread_condattr_t *attr, intpshared)
Definition at line 41 of file pthread_condattr.c.
References errno, and pthread_condattr::pshared.
                                                                              {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    attr->pshared = pshared;
    return 0;
}
int pthread_create (pthread_t *thread, const pthread_attr_t *attr, void *(*)(void *)start, void *arg)
Definition at line 37 of file pthread_create.c.
References __os_thread_create, __pthread_counts, __pthread_handler__(), __pthread_init_queue(), __pthread_queue, pthread_context::attr, pthread_once::done, pthread_context::entry, errno, pthread_attr::inheritsched, pthread_context::next, pthread_context::once, pthread_context::param, pthread_attr::param, pthread_attr_setschedparam(), PTHREAD_INHERIT_SCHED, pthread_self(), PTHREAD_THREADS_MAX, pthread_once::started, and pthread_context::tid.
                                                                                                           {
    __pthread_init_queue();
    if(!thread) {
        errno = EINVAL;
        return -1;
    }
    if(__pthread_counts > PTHREAD_THREADS_MAX) {
        errno = EAGAIN;
        return -1;
    }
    pthread_context_t* ctx = malloc(sizeof(pthread_context_t));
    memset(ctx, 0, sizeof(pthread_context_t));
    ctx->entry = start;
    ctx->param = arg;
    ctx->once.done = 0;
    ctx->once.started = -1;
    ctx->next = 0;
    if(attr)
        memcpy(&ctx->attr, attr, sizeof(pthread_attr_t));
    if(ctx->attr.inheritsched == PTHREAD_INHERIT_SCHED) {
        pthread_t px = pthread_self();
        if(px) {
            pthread_context_t* inh = (pthread_context_t*) px;
            pthread_attr_setschedparam(&ctx->attr, &inh->attr.param);
        }
    }
    __pthread_counts += 1;
    *thread = (pthread_t) ctx;
    
    
    ctx->next = __pthread_queue;
    __pthread_queue = ctx;
        
    ctx->tid = __os_thread_create(__pthread_handler__, ctx, ctx->attr.param.sched_priority);
    return 0;
}
int pthread_detach (pthread_tthread)
Definition at line 12 of file pthread_detach.c.
References __os_thread_kill, __pthread_queue, pthread_once::done, errno, pthread_context::once, and pthread_context::tid.
                                            {
    if(!thread) {
        errno = EINVAL;
        return -1;
    }
    if(!__pthread_queue) {
        errno = ESRCH;
        return -1;
    }
    pthread_context_t* ctx = (pthread_context_t*) thread;
    if(__os_thread_kill(ctx->tid, SIGTERM) == 0)
        ctx->once.done = 1;
    else {
        errno = ESRCH;
        return -1;
    }
    __pthread_counts -= 1;
    pthread_context_t* tmp = __pthread_queue;
    if(tmp->next) {
        while(tmp->next) {
            if(tmp->next == ctx) {
                tmp->next = ctx->next;
                break;
            }
            tmp = tmp->next;
        }
    } else {
        if(__pthread_queue == ctx)
            __pthread_queue = 0;
    }
    return 0;
}
int pthread_equal (pthread_tt1, pthread_tt2)
Definition at line 7 of file pthread_equal.c.
References pthread_context::tid.
                                                     {
    pthread_context_t* c1 = (pthread_context_t*) t1;
    pthread_context_t* c2 = (pthread_context_t*) t2;
    return (c1->tid == c2->tid);
}
void pthread_exit (void *value_ptr)
Definition at line 8 of file pthread_exit.c.
References pthread_context::exitval, pthread_detach(), and pthread_self().
                                          {
    pthread_t ptx = pthread_self();
    pthread_context_t* ctx = (pthread_context_t*) ptx;
    if(ptx) {
        ctx->exitval = value_ptr;
        pthread_detach(ptx);
    }else
        abort();
    for(;;);
}
int pthread_getconcurrency (void)
Definition at line 57 of file pthread_sched.c.
References pthread_context::attr, errno, pthread_attr::param, and pthread_self().
                                        {
    pthread_t thread = pthread_self();
    if(!thread) {
        errno = ESRCH;
        return -1;
    }
    pthread_context_t* ctx = (pthread_context_t*) thread;
    return ctx->attr.param.sched_priority;
}
int pthread_getschedparam (pthread_tthread, int *policy, struct sched_param *param)
Definition at line 26 of file pthread_sched.c.
References errno, sched_getparam(), and pthread_context::tid.
                                                                                           {
    if(!thread) {
        errno = EINVAL;
        return -1;
    }
    if(param == NULL) {
        errno = EINVAL;
        return -1;
    }
    
    pthread_context_t* ctx = (pthread_context_t*) thread;
    if((*policy = sched_getparam(ctx->tid, param)) != -1)
        return 0;
    
    return -1;
}
void* pthread_getspecific (pthread_key_tkey)
Definition at line 65 of file pthread_key.c.
References __pthread_keys, errno, PTHREAD_KEYS_MAX, and __pthread_key::value.
                                                    {
    if(key > PTHREAD_KEYS_MAX) {
        errno = EINVAL;
        return 0;
    }
    if(__pthread_keys[key].used == 0) {
        errno = EINVAL;
        return 0;
    }
    return __pthread_keys[key].value;
}
int pthread_join (pthread_tthread, void **value_ptr)
Definition at line 8 of file pthread_join.c.
References pthread_once::done, errno, pthread_context::exitval, pthread_context::once, and sched_yield().
                                                            {
    if(!thread) {
        errno = EINVAL;
        return -1;
    }
    pthread_context_t* ctx = (pthread_context_t*) thread;
    while(ctx->once.done == 0)
        sched_yield();
    if(value_ptr)
        *value_ptr = ctx->exitval;
    return 0;
}
int pthread_key_create (pthread_key_t *key, void(*)(void *)destructor)
Definition at line 9 of file pthread_key.c.
References __pthread_keys, __pthread_key::dtor, errno, PTHREAD_KEYS_MAX, __pthread_key::used, and __pthread_key::value.
                                                                              {
    if(!key) {
        errno = EINVAL;
        return -1;
    }
    int i;
    for(i = 0; i < PTHREAD_KEYS_MAX; i++) {
        if(__pthread_keys[i].used == 0) {
            __pthread_keys[i].used = 1;
            __pthread_keys[i].dtor = destructor;
            __pthread_keys[i].value = NULL;
            *key = i;
            return 0;
        }
    }
    errno = EAGAIN;
    return -1;
}
int pthread_key_delete (pthread_key_tkey)
Definition at line 32 of file pthread_key.c.
References __pthread_keys, __pthread_key::dtor, errno, PTHREAD_KEYS_MAX, __pthread_key::used, __pthread_key::value, and value.
                                                 {
    if(key > PTHREAD_KEYS_MAX) {
        errno = EINVAL;
        return -1;
    }
    if(__pthread_keys[key].dtor)
        __pthread_keys[key].dtor(__pthread_keys[key].value);
    __pthread_keys[key].used = 0;
    __pthread_keys[key].dtor = 0;
    __pthread_keys[key].value = NULL;
    
    return 0;
}
int pthread_mutex_destroy (pthread_mutex_t *mutex)
Definition at line 46 of file pthread_mutex.c.
References errno, pthread_mutex::event, pthread_mutex::kind, pthread_mutex::lock, pthread_mutex::owner, pthread_mutex::recursion, and pthread_mutex::time.
                                                         {
    if(!mutex) {
        errno = EINVAL;
        return -1;
    }
    if(mutex->lock == 1) {
        errno = EBUSY;
        return -1;
    }
    mutex->lock = 0;
    mutex->recursion = 0;
    mutex->kind = 0;
    mutex->owner = 0;
    mutex->event = 0;
    mutex->time = 0;
    return 0;
}
int pthread_mutex_init (pthread_mutex_t *mutex, const pthread_mutexattr_t *attr)
Definition at line 26 of file pthread_mutex.c.
References errno, pthread_mutex::event, pthread_mutexattr::kind, pthread_mutex::kind, pthread_mutex::lock, pthread_mutex::owner, PTHREAD_MUTEX_DEFAULT, pthread_mutex::recursion, and pthread_mutex::time.
                                                                                       {
    if(!mutex) {
        errno = EINVAL;
        return -1;
    }
    mutex->lock = 0;
    mutex->recursion = 0;
    mutex->kind = PTHREAD_MUTEX_DEFAULT;
    mutex->owner = 0;
    mutex->event = 0;
    mutex->time = 0;
    if(attr)
        mutex->kind = attr->kind;
    return 0;
}
int pthread_mutex_lock (pthread_mutex_t *mutex)
Definition at line 67 of file pthread_mutex.c.
References __locked_mtx(), errno, pthread_mutex::kind, pthread_mutex::lock, pthread_mutex::owner, PTHREAD_MUTEX_ERRORCHECK, PTHREAD_MUTEX_RECURSIVE, pthread_self(), pthread_mutex::recursion, and sched_yield().
                                                      {
    if(!mutex) {
        errno = EINVAL;
        return -1;
    }
    if(mutex->owner != pthread_self()) {
        while(__locked_mtx(mutex))
            sched_yield();
        
        mutex->owner = pthread_self();
        mutex->recursion = 0;
        mutex->lock = 1;
    } else if(mutex->kind == PTHREAD_MUTEX_ERRORCHECK) {
        errno = EDEADLK;
        return -1;
    }
    if(mutex->kind == PTHREAD_MUTEX_RECURSIVE)
        mutex->recursion += 1;
    return 0;
}
int pthread_mutex_timedlock (pthread_mutex_t *mutex, const struct timespec *abstime)
Definition at line 92 of file pthread_mutex.c.
References errno, pthread_mutex_lock(), and pthread_mutex::time.
                                                                                           {
    if(abstime == NULL) {
        errno = EINVAL;
        return -1;
    }
    if(pthread_mutex_lock(mutex) == 0)
        mutex->time = time(NULL) + abstime->tv_sec;
    else
        return -1;
    return 0;
}
int pthread_mutex_trylock (pthread_mutex_t *mutex)
Definition at line 107 of file pthread_mutex.c.
References __locked_mtx(), errno, pthread_mutex::kind, pthread_mutex::lock, pthread_mutex::owner, PTHREAD_MUTEX_ERRORCHECK, PTHREAD_MUTEX_RECURSIVE, pthread_self(), and pthread_mutex::recursion.
                                                         {
    if(!mutex) {
        errno = EINVAL;
        return -1;
    }
    if(mutex->owner != pthread_self()) {
        if(__locked_mtx(mutex)) {
            errno = EBUSY;
            return -1;
        }
        mutex->owner = pthread_self();
        mutex->recursion = 0;
        mutex->lock = 1;
    } else if(mutex->kind == PTHREAD_MUTEX_ERRORCHECK) {
        errno = EDEADLK;
        return -1;
    }
    if(mutex->kind == PTHREAD_MUTEX_RECURSIVE)
        mutex->recursion += 1;
    return 0;
}
int pthread_mutex_unlock (pthread_mutex_t *mutex)
Definition at line 133 of file pthread_mutex.c.
References errno, pthread_mutex::kind, pthread_mutex::lock, pthread_mutex::owner, PTHREAD_MUTEX_ERRORCHECK, PTHREAD_MUTEX_RECURSIVE, pthread_self(), and pthread_mutex::recursion.
                                                        {
    if(!mutex) {
        errno = EINVAL;
        return -1;
    }
    if(mutex->owner == pthread_self()) {
        if(mutex->kind == PTHREAD_MUTEX_RECURSIVE) {
            if(--(mutex->recursion))
                return 0;
        }
        mutex->owner = 0;
        mutex->lock = 0;
    } else if(mutex->kind == PTHREAD_MUTEX_ERRORCHECK) {
        errno = EPERM;
        return -1;
    }
    return 0;
}
int pthread_mutexattr_destroy (pthread_mutexattr_t *attr)
Definition at line 20 of file pthread_mutexattr.c.
References errno, pthread_mutexattr::kind, and pthread_mutexattr::pshared.
                                                                {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    attr->pshared = 0;
    attr->kind = 0;
    
    return 0;
}
int pthread_mutexattr_getpshared (const pthread_mutexattr_t *attr, int *pshared)
Definition at line 32 of file pthread_mutexattr.c.
References errno, and pthread_mutexattr::pshared.
                                                                                       {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    *pshared = attr->pshared;
    return 0;
}
int pthread_mutexattr_gettype (pthread_mutexattr_t *attr, int *kind)
Definition at line 52 of file pthread_mutexattr.c.
References errno, and pthread_mutexattr::kind.
                                                                           {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    *kind = attr->kind;
    return 0;
}
int pthread_mutexattr_init (pthread_mutexattr_t *attr)
Definition at line 8 of file pthread_mutexattr.c.
References errno, pthread_mutexattr::kind, pthread_mutexattr::pshared, and PTHREAD_MUTEX_DEFAULT.
                                                             {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    attr->pshared = 0;
    attr->kind = PTHREAD_MUTEX_DEFAULT;
    
    return 0;
}
int pthread_mutexattr_setpshared (pthread_mutexattr_t *attr, intpshared)
Definition at line 42 of file pthread_mutexattr.c.
References errno, and pthread_mutexattr::pshared.
                                                                                {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    attr->pshared = pshared;
    return 0;
}
int pthread_mutexattr_settype (pthread_mutexattr_t *attr, intkind)
Definition at line 62 of file pthread_mutexattr.c.
References errno, and pthread_mutexattr::kind.
                                                                          {
    if(!attr) {
        errno = EINVAL;
        return -1;
    }
    attr->kind = kind;
    return 0;
}
int pthread_once (pthread_once_t *once_control, void(*)(void)init_routine)
Definition at line 7 of file pthread_once.c.
References errno.
                                                                                  {
    errno = ENOSYS;
    return -1;
}
int pthread_rwlock_destroy (pthread_rwlock_t *lock)
Definition at line 34 of file pthread_rwlock.c.
References errno, pthread_rwlock::exclusive_waiters, pthread_rwlock::num_exclusive_waiters, pthread_rwlock::num_shared_waiters, pthread_rwlock::owner, pthread_mutex_destroy(), pthread_self(), pthread_rwlock::rdmutex, pthread_rwlock::shared_waiters, and pthread_rwlock::wrmutex.
                                                          {
    if(lock == NULL) {
        errno = EINVAL;
        return -1;
    }
    pthread_t thread = pthread_self();
    if(!thread) {
        errno = EFAULT;
        return -1;
    }
    if(thread != lock->owner) {
        errno = EPERM;
        return -1;
    }
    pthread_mutex_destroy(&lock->rdmutex);
    pthread_mutex_destroy(&lock->wrmutex);
    lock->shared_waiters = (handle_t) 0;
    lock->exclusive_waiters = (handle_t) 0;
    lock->num_shared_waiters = 0;
    lock->num_exclusive_waiters = 0;
    lock->owner = 0;
    
    return 0;
}
int pthread_rwlock_init (pthread_rwlock_t *lock, const pthread_rwlockattr_t *attr)
Definition at line 10 of file pthread_rwlock.c.
References errno, pthread_rwlock::exclusive_waiters, pthread_rwlock::num_exclusive_waiters, pthread_rwlock::num_shared_waiters, pthread_rwlock::owner, pthread_mutex_init(), pthread_self(), pthread_rwlock::rdmutex, pthread_rwlock::shared_waiters, and pthread_rwlock::wrmutex.
                                                                                         {
    if(lock == NULL) {
        errno = EINVAL;
        return -1;
    }
    pthread_t thread = pthread_self();
    if(!thread) {
        errno = EFAULT;
        return -1;
    }
    pthread_mutex_init(&lock->rdmutex, NULL);
    pthread_mutex_init(&lock->wrmutex, NULL);
    lock->shared_waiters = (handle_t) 0;
    lock->exclusive_waiters = (handle_t) 0;
    lock->num_shared_waiters = 0;
    lock->num_exclusive_waiters = 0;
    lock->owner = thread;
    return 0;
}
int pthread_rwlock_rdlock (pthread_rwlock_t *lock)
Definition at line 81 of file pthread_rwlock.c.
References errno, pthread_mutex_lock(), and pthread_rwlock::rdmutex.
                                                         {
    if(lock == NULL) {
        errno = EINVAL;
        return -1;
    }
    return pthread_mutex_lock(&lock->rdmutex);
}
int pthread_rwlock_timedrdlock (pthread_rwlock_t *lock, const struct timespec *abstime)
Definition at line 90 of file pthread_rwlock.c.
References errno, pthread_mutex_timedlock(), and pthread_rwlock::rdmutex.
                                                                                              {
    if(lock == NULL) {
        errno = EINVAL;
        return -1;
    }
    return pthread_mutex_timedlock(&lock->rdmutex, abstime);
}
int pthread_rwlock_timedwrlock (pthread_rwlock_t *lock, const struct timespec *abstime)
Definition at line 108 of file pthread_rwlock.c.
References errno, pthread_mutex_timedlock(), and pthread_rwlock::wrmutex.
                                                                                              {
    if(lock == NULL) {
        errno = EINVAL;
        return -1;
    }
    return pthread_mutex_timedlock(&lock->wrmutex, abstime);
}
int pthread_rwlock_tryrdlock (pthread_rwlock_t *lock)
Definition at line 63 of file pthread_rwlock.c.
References errno, pthread_mutex_trylock(), and pthread_rwlock::rdmutex.
                                                            {
    if(lock == NULL) {
        errno = EINVAL;
        return -1;
    }
    return pthread_mutex_trylock(&lock->rdmutex);
}
int pthread_rwlock_trywrlock (pthread_rwlock_t *lock)
Definition at line 72 of file pthread_rwlock.c.
References errno, pthread_mutex_trylock(), and pthread_rwlock::wrmutex.
                                                            {
    if(lock == NULL) {
        errno = EINVAL;
        return -1;
    }
    return pthread_mutex_trylock(&lock->wrmutex);
}
int pthread_rwlock_unlock (pthread_rwlock_t *lock)
Definition at line 117 of file pthread_rwlock.c.
References errno, pthread_mutex_unlock(), pthread_rwlock::rdmutex, and pthread_rwlock::wrmutex.
                                                         {
    if(lock == NULL) {
        errno = EINVAL;
        return -1;
    }
    if(pthread_mutex_unlock(&lock->rdmutex) != 0)
        return -1;
    if(pthread_mutex_unlock(&lock->wrmutex) != 0)
        return -1;
    return 0;
}
int pthread_rwlock_wrlock (pthread_rwlock_t *lock)
Definition at line 99 of file pthread_rwlock.c.
References errno, pthread_mutex_lock(), and pthread_rwlock::wrmutex.
                                                         {
    if(lock == NULL) {
        errno = EINVAL;
        return -1;
    }
    return pthread_mutex_lock(&lock->wrmutex);
}
int pthread_rwlockattr_destroy (pthread_rwlockattr_t *attr)
Definition at line 19 of file pthread_rwlockattr.c.
References errno, and pthread_rwlockattr::pshared.
                                                                  {
    if(attr == NULL) {
        errno = EINVAL;
        return -1;
    }
    attr->pshared = 0;
    return 0;
}
int pthread_rwlockattr_getpshared (const pthread_rwlockattr_t *attr, int *pshared)
Definition at line 29 of file pthread_rwlockattr.c.
References errno, and pthread_rwlockattr::pshared.
                                                                                         {
    if(attr == NULL) {
        errno = EINVAL;
        return -1;
    }
    if(pshared == NULL) {
        errno = EINVAL;
        return -1;
    }
    *pshared = attr->pshared;
    return 0;
}
int pthread_rwlockattr_init (pthread_rwlockattr_t *attr)
Definition at line 9 of file pthread_rwlockattr.c.
References errno, and pthread_rwlockattr::pshared.
                                                               {
    if(attr == NULL) {
        errno = EINVAL;
        return -1;
    }
    attr->pshared = 0;
    return 0;
}
int pthread_rwlockattr_setpshared (pthread_rwlockattr_t *attr, intpshared)
Definition at line 44 of file pthread_rwlockattr.c.
References errno, and pthread_rwlockattr::pshared.
                                                                                  {
    if(attr == NULL) {
        errno = EINVAL;
        return -1;
    }
    attr->pshared = pshared;
    return 0;
}
pthread_t pthread_self (void)
Definition at line 10 of file pthread_self.c.
References __os_gettid, __pthread_queue, errno, pthread_context::next, and pthread_context::tid.
                                    {
    if(!__pthread_queue) {
        errno = ESRCH;
        return -1;
    }
    int tid = __os_gettid();
    pthread_context_t* tmp = __pthread_queue;
    while(tmp) {
        if(tmp->tid == tid)
            return (pthread_t) tmp;
        tmp = tmp->next;
    }
    errno = ESRCH;
    return -1;
}
int pthread_setcancelstate (intstate, int *oldstate)
Definition at line 12 of file pthread_cancel.c.
References errno.
                                                            {
    errno = ENOSYS;
    return -1;
}
int pthread_setcanceltype (inttype, int *oldtype)
Definition at line 18 of file pthread_cancel.c.
References errno.
                                                         {
    errno = ENOSYS;
    return -1;
}
int pthread_setconcurrency (intlevel)
Definition at line 44 of file pthread_sched.c.
References pthread_context::attr, errno, pthread_attr::param, and pthread_self().
                                             {
    pthread_t thread = pthread_self();
    if(!thread) {
        errno = ESRCH;
        return -1;
    }
    pthread_context_t* ctx = (pthread_context_t*) thread;
    ctx->attr.param.sched_priority = level;
    return 0;
}
int pthread_setschedparam (pthread_tthread, intpolicy, const struct sched_param *param)
Definition at line 11 of file pthread_sched.c.
References errno, sched_setparam(), and pthread_context::tid.
                                                                                                {
    if(!thread) {
        errno = EINVAL;
        return -1;
    }
    if(param == NULL) {
        errno = EINVAL;
        return -1;
    }
    pthread_context_t* ctx = (pthread_context_t*) thread;
    return sched_setparam(ctx->tid, param);
}
int pthread_setspecific (pthread_key_tkey, const void *value)
Definition at line 49 of file pthread_key.c.
References __pthread_keys, errno, PTHREAD_KEYS_MAX, and __pthread_key::value.
                                                                     {
    if(key > PTHREAD_KEYS_MAX) {
        errno = EINVAL;
        return -1;
    }
    if(__pthread_keys[key].used == 0) {
        errno = EINVAL;
        return -1;
    }
    __pthread_keys[key].value = (void*) value;
    return 0;
}
int pthread_spin_destroy (pthread_spinlock_t *lock)
Definition at line 19 of file pthread_spin.c.
References errno, pthread_spinlock::interlock, pthread_spinlock::mutex, and pthread_mutex_destroy().
                                                          {
    if(!lock) {
        errno = EINVAL;
        return -1;
    }
    lock->interlock = 0;
    pthread_mutex_destroy(&lock->mutex);
    return 0;
}
int pthread_spin_init (pthread_spinlock_t *lock, intpshared)
Definition at line 7 of file pthread_spin.c.
References errno, pthread_spinlock::interlock, pthread_spinlock::mutex, and pthread_mutex_init().
                                                                    {
    if(!lock) {
        errno = EINVAL;
        return -1;
    }
    lock->interlock = 0;
    pthread_mutex_init(&lock->mutex, NULL);
    return 0;
}
int pthread_spin_lock (pthread_spinlock_t *lock)
Definition at line 31 of file pthread_spin.c.
References errno, pthread_spinlock::interlock, pthread_spinlock::mutex, and pthread_mutex_lock().
                                                       {
    if(!lock) {
        errno = EINVAL;
        return -1;
    }
    if(pthread_mutex_lock(&lock->mutex) == 0)
        lock->interlock = 1;
    else
        return -1; /* errno already setted */
    return 0;
}
int pthread_spin_trylock (pthread_spinlock_t *lock)
Definition at line 45 of file pthread_spin.c.
References errno, pthread_spinlock::interlock, pthread_spinlock::mutex, and pthread_mutex_trylock().
                                                          {
    if(!lock) {
        errno = EINVAL;
        return -1;
    }
    if(pthread_mutex_trylock(&lock->mutex) == 0)
        lock->interlock = 1;
    else
        return -1; /* errno already setted */
    return 0;
}
int pthread_spin_unlock (pthread_spinlock_t *lock)
Definition at line 59 of file pthread_spin.c.
References errno, pthread_spinlock::interlock, pthread_spinlock::mutex, and pthread_mutex_unlock().
                                                         {
    if(!lock) {
        errno = EINVAL;
        return -1;
    }
    if(pthread_mutex_unlock(&lock->mutex) == 0)
        lock->interlock = 0;
    else
        return -1; /* errno already setted */
    
    return 0;
}
void pthread_testcancel (void)
Definition at line 23 of file pthread_cancel.c.
                                     {
    /* Boh ?? */
}
Author
Generated automatically by Doxygen for aPlus from the source code.