.TH "pthread_mutex" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_mutex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pthread\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "int \fBlock\fP"
.br
.ti -1c
.RI "int \fBrecursion\fP"
.br
.ti -1c
.RI "int \fBkind\fP"
.br
.ti -1c
.RI "\fBpthread_t\fP \fBowner\fP"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBevent\fP"
.br
.ti -1c
.RI "int \fBtime\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 87 del file pthread\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "\fBhandle_t\fP pthread_mutex::event"

.PP
Definizione alla linea 92 del file pthread\&.h\&.
.SS "int pthread_mutex::kind"

.PP
Definizione alla linea 90 del file pthread\&.h\&.
.SS "int pthread_mutex::lock"

.PP
Definizione alla linea 88 del file pthread\&.h\&.
.SS "\fBpthread_t\fP pthread_mutex::owner"

.PP
Definizione alla linea 91 del file pthread\&.h\&.
.SS "int pthread_mutex::recursion"

.PP
Definizione alla linea 89 del file pthread\&.h\&.
.SS "int pthread_mutex::time"

.PP
Definizione alla linea 93 del file pthread\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
