.TH "pthread_cond" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pthread_cond \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pthread\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "int \fBwaiting\fP"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBsemaphore\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 105 del file pthread\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "\fBhandle_t\fP pthread_cond::semaphore"

.PP
Definizione alla linea 107 del file pthread\&.h\&.
.SS "int pthread_cond::waiting"

.PP
Definizione alla linea 106 del file pthread\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
