src/fs/ramdev.c
NAME
src/fs/ramdev.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/fs.h>
#include <aplus/task.h>
#include <aplus/bufio.h>
#include <stdint.h>
#include <unistd.h>
#include <dirent.h>
#include <fcntl.h>
Functions
int ramdev_read (inode_t *ino, char *buf, int size)
int ramdev_write (inode_t *ino, char *buf, int size)
void ramdev_flush (inode_t *ino)
inode_t * mkramdev (char *path, uint32_t addr, uint32_t size)
Variables
task_t * current_task
Current task address.
Function Documentation
inode_t* mkramdev (char *path, uint32_taddr, uint32_tsize)
Definition at line 76 of file ramdev.c.
References bufio_alloc_raw(), task::fd, inode::flush, ramdev_flush(), ramdev_read(), ramdev_write(), inode::read, inode::size, size, sys_close(), sys_open(), inode::userdata, and inode::write.
                                                            {
    int fd = sys_open(path, O_CREAT | O_EXCL | O_TRUNC, S_IFCHR);
    if(fd < 0)
        return NULL;
    inode_t* ino = (inode_t*) current_task->fd[fd];
    sys_close(fd);
    ino->read = ramdev_read;
    ino->write = ramdev_write;
    ino->flush = ramdev_flush;
    ino->userdata = (void*) bufio_alloc_raw((void*) addr, size);
    ino->size = size;
    return ino;
}
void ramdev_flush (inode_t *ino)
Definition at line 65 of file ramdev.c.
References bufio_free(), and inode::userdata.
                                {
    if(!ino)
        return;
    if(!ino->userdata)
        return;
    bufio_free(ino->userdata);
}
int ramdev_read (inode_t *ino, char *buf, intsize)
Definition at line 15 of file ramdev.c.
References bufio_read(), bufio_seek(), inode::position, inode::size, size, and inode::userdata.
                                                   {
    if(!ino)
        return 0;
    if(!buf)
        return 0;
    if(size > ino->size)
        size = ino->size;
    if(ino->position > ino->size)
        ino->position = ino->size;
    if(ino->position + size > ino->size)
        size = ino->size - ino->position;
    if(!size)
        return 0;
    bufio_seek(ino->userdata, ino->position, SEEK_SET);
    size = bufio_read(ino->userdata, buf, size);
    ino->position += size;
    return size;
}
int ramdev_write (inode_t *ino, char *buf, intsize)
Definition at line 40 of file ramdev.c.
References bufio_seek(), bufio_write(), inode::position, inode::size, size, and inode::userdata.
                                                    {
    if(!ino)
        return 0;
    if(!buf)
        return 0;
    if(size > ino->size)
        size = ino->size;
    if(ino->position > ino->size)
        ino->position = ino->size;
    if(ino->position + size > ino->size)
        size = ino->size - ino->position;
    if(!size)
        return 0;
    bufio_seek(ino->userdata, ino->position, SEEK_SET);
    size = bufio_write(ino->userdata, buf, size);
    ino->position += size;
    return size;
}
Variable Documentation
task_t* current_task
Current task address.
Definition at line 35 of file sched.c.
Author
Generated automatically by Doxygen for aPlus from the source code.