.TH "usr/src/libposix/src/readdir.c" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/readdir.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dirent\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'config\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBdirent\fP * \fBreaddir\fP (\fBDIR\fP *\fBd\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct \fBdirent\fP* readdir (\fBDIR\fP *d)"

.PP
Definition at line 15 of file readdir\&.c\&.
.PP
References errno\&.
.PP
.nf
15                                {
16     if(d == NULL) {
17         errno = EINVAL;
18         return NULL;
19     }
20 
21     return __os_readdir(d);
22 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
