.TH "src/syscall/sbrk.c" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syscall/sbrk.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <aplus\&.h>\fP
.br
\fC#include <aplus/syscall\&.h>\fP
.br
\fC#include <aplus/task\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBsys_sbrk\fP (ptrdiff_t increment)"
.br
.ti -1c
.RI "\fBSYSCALL\fP (\fBsys_sbrk\fP, 12)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* sys_sbrk (ptrdiff_tincrement)"

.PP
Definition at line 6 of file sbrk\&.c\&.
.PP
References schedule_sbrk()\&.
.PP
.nf
6                                     {
7     return (void*) schedule_sbrk(increment);
8 }
.fi
.SS "SYSCALL (\fBsys_sbrk\fP, 12)"

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
