.TH "usr/src/libposix/src/seekdir.c" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/seekdir.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dirent\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBseekdir\fP (\fBDIR\fP *d, off_t \fBoffset\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void seekdir (\fBDIR\fP *d, off_toffset)"

.PP
Definition at line 13 of file seekdir\&.c\&.
.PP
References offset, and __DIR::position\&.
.PP
.nf
13                                    {
14     if(d)
15         d->position = offset;
16 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
