.TH "usr/src/libposix/src/seekdir.c" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/seekdir.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dirent\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "void \fBseekdir\fP (\fBDIR\fP *\fBd\fP, off_t \fBoffset\fP)"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "void seekdir (\fBDIR\fP *d, off_toffset)"

.PP
Definizione alla linea 13 del file seekdir\&.c\&.
.PP
Referenzia offset, e __DIR::position\&.
.PP
.nf
13                                    {
14     if(d)
15         d->position = offset;
16 }
.fi
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
