.TH "usr/src/libposix/src/sleep.c" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/sleep.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBnanosleep\fP (struct timespec *ts, struct timespec *tr)"
.br
.ti -1c
.RI "unsigned \fBsleep\fP (unsigned seconds)"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "int nanosleep (struct timespec *ts, struct timespec *tr)"

.SS "unsigned sleep (unsignedseconds)"

.PP
Definizione alla linea 8 del file sleep\&.c\&.
.PP
Referenzia errno, e nanosleep()\&.
.PP
.nf
8                                  {
9     struct timespec ts;
10 
11     ts\&.tv_sec = seconds;
12     ts\&.tv_nsec = 0;
13     if (!nanosleep(&ts,&ts)) return 0;
14     if (errno == EINTR) return ts\&.tv_sec;
15     return -1;
16 }
.fi
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
