.TH "src/net/slirp/slirp.h" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/net/slirp/slirp.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSLIRP_PACKET_END\fP   0xC0"
.br
.ti -1c
.RI "#define \fBSLIRP_PACKET_ESC\fP   0xDB"
.br
.ti -1c
.RI "#define \fBSLIRP_PACKET_ESC_END\fP   0xDC"
.br
.ti -1c
.RI "#define \fBSLIRP_PACKET_ESC_ESC\fP   0xDD"
.br
.ti -1c
.RI "#define \fBSLIRP_BUFSIZ\fP   1006"
.br
.ti -1c
.RI "#define \fBSLIRP_MTU\fP   65536"
.br
.ti -1c
.RI "#define \fBSLIRP_MAGIC\fP   0x100200FF"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SLIRP_BUFSIZ   1006"

.PP
Definition at line 9 of file slirp\&.h\&.
.SS "#define SLIRP_MAGIC   0x100200FF"

.PP
Definition at line 12 of file slirp\&.h\&.
.SS "#define SLIRP_MTU   65536"

.PP
Definition at line 10 of file slirp\&.h\&.
.SS "#define SLIRP_PACKET_END   0xC0"

.PP
Definition at line 4 of file slirp\&.h\&.
.SS "#define SLIRP_PACKET_ESC   0xDB"

.PP
Definition at line 5 of file slirp\&.h\&.
.SS "#define SLIRP_PACKET_ESC_END   0xDC"

.PP
Definition at line 6 of file slirp\&.h\&.
.SS "#define SLIRP_PACKET_ESC_ESC   0xDD"

.PP
Definition at line 7 of file slirp\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
