.TH "slirpcard" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slirpcard \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBmagic\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBbuffer\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBused\fP"
.br
.ti -1c
.RI "int \fBoffset\fP"
.br
.ti -1c
.RI "int \fBioport\fP"
.br
.ti -1c
.RI "\fBnetif_t\fP * \fBnetif\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file slirp\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint8_t\fP* slirpcard::buffer"

.PP
Definition at line 18 of file slirp\&.c\&.
.SS "int slirpcard::ioport"

.PP
Definition at line 22 of file slirp\&.c\&.
.SS "\fBuint32_t\fP slirpcard::magic"

.PP
Definition at line 17 of file slirp\&.c\&.
.SS "\fBnetif_t\fP* slirpcard::netif"

.PP
Definition at line 23 of file slirp\&.c\&.
.SS "int slirpcard::offset"

.PP
Definition at line 21 of file slirp\&.c\&.
.SS "\fBuint8_t\fP slirpcard::used"

.PP
Definition at line 19 of file slirp\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
