src/syscall/stat.c
NAME
src/syscall/stat.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/syscall.h>
#include <aplus/fs.h>
#include <aplus/task.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/stat.h>
#include <dirent.h>
Functions
int sys_stat (const char *filename, struct stat *st)
SYSCALL (sys_stat, 13)
Variables
task_t * current_task
Current task address.
Function Documentation
int sys_stat (const char *filename, struct stat *st)
Definition at line 15 of file stat.c.
References errno, kprintf(), sys_close(), sys_fstat(), and sys_open().
                                                    {
    int fd = sys_open(filename, O_RDONLY, 0644);
    if(fd < 0) {
        kprintf("sys_stat: %s.", strerror(errno));
        return -1;
    }
    int ret = sys_fstat(fd, st);
    sys_close(fd);
    return ret;
}
SYSCALL (sys_stat, 13)
Variable Documentation
task_t* current_task
Current task address.
Definition at line 35 of file sched.c.
Author
Generated automatically by Doxygen for aPlus from the source code.