src/arch/i386/syscall.c
NAME
src/arch/i386/syscall.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/spinlock.h>
#include <aplus/syscall.h>
#include <aplus/attribute.h>
#include <errno.h>
Macros
#define NSYSCALLS 1024
Functions
int syscall_init ()
int syscall_invoke (int idx, int p0, int p1, int p2, int p3, int p4)
int syscall_handler (regs_t *r)
Variables
static void ** syscall_handlers = NULL
Macro Definition Documentation
#define NSYSCALLS 1024
Definition at line 12 of file syscall.c.
Function Documentation
int syscall_handler (regs_t *r)
Definition at line 95 of file syscall.c.
References syscall_invoke().
                               {
    return syscall_invoke(r->eax, r->ebx, r->ecx, r->edx, r->esi, r->edi);
}
int syscall_init ()
Definition at line 16 of file syscall.c.
References attribute(), __syscall::handler, kmalloc(), kprintf(), list_destroy, list_foreach, NSYSCALLS, __syscall::number, list::size, syscall_handlers, and value.
                   {
    list_t* syslist = attribute("syscall");
    syscall_handlers = (void**) kmalloc(sizeof(void*) * NSYSCALLS);
    memset(syscall_handlers, 0, sizeof(void*) * NSYSCALLS);
    list_foreach(value, syslist) {
        syscall_t* sys = (syscall_t*) value;
        if(syscall_handlers[sys->number])
            kprintf("syscall: duplicate number of %d handler\n");
        syscall_handlers[sys->number] = sys->handler;
    }
    kprintf("syscall: loaded %d handlers\n", syslist->size);
    list_destroy(syslist);
#ifdef DEBUG
    
    for(int i = 0, s = 0; i < NSYSCALLS; i++) {
        if(syscall_handlers[i] == NULL) {
            if(!s)
                continue;
            if(s > 1)
                kprintf("\t%d..%d\n", i - s, i - 1);
            else
                kprintf("\t%d\n", i - s);
            s = 0;
        } else
            s++;
    }
#endif
    return 0;
}
int syscall_invoke (intidx, intp0, intp1, intp2, intp3, intp4)
Definition at line 57 of file syscall.c.
References __asm__(), elf_kernel_lookup(), errno, kprintf(), sys_getpid(), and syscall_handlers.
                                                                    {
    void* handler = syscall_handlers[idx];
    if(handler == NULL) {
        errno = ENOSYS;
        return -1;
    }
#ifdef SYSCALL_DEBUG
    kprintf("syscall: %d call %s [%d] (%x, %x, %x, %x, %x);\n", sys_getpid(), elf_kernel_lookup(handler), idx, p0, p1, p2, p3, p4);
#endif
    int r = 0;
    __asm__ (
        "push ebx \n"
        "push ecx \n"
        "push edx \n"
        "push esi \n"
        "push edi \n"
        "call eax \n"
        "add esp, 20 \n"
        : "=a"(r)
        : "a"(handler), "b"(p4), "c"(p3), "d"(p2), "S"(p1), "D"(p0)
    );
#ifdef SYSCALL_DEBUG
    kprintf("% returned %x\n", r);
#endif
    return r;
}
Variable Documentation
void** syscall_handlers = NULL [static]
Definition at line 14 of file syscall.c.
Author
Generated automatically by Doxygen for aPlus from the source code.