.TH "src/include/aplus/syscall.h" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/aplus/syscall.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <aplus\&.h>\fP
.br
\fC#include <aplus/attribute\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB__syscall\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSYSCALL\fP(h, n)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB__syscall\fP \fBsyscall_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SYSCALL(h, n)"
\fBValue:\fP
.PP
.nf
static syscall_t syscall_##n = {                                      \
        (void*) h, (int) n                                                  \
    };                                                                      \\
	ATTRIBUTE("syscall", syscall_##n)
.fi
.PP
Definition at line 15 of file syscall\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB__syscall\fP  \fBsyscall_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
