.TH "src/include/aplus/task.h" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/aplus/task.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <aplus\&.h>\fP
.br
\fC#include <aplus/fs\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <setjmp\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtask_env\fP"
.br
.ti -1c
.RI "struct \fBtask\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTASK_MAX_FD\fP   512"
.br
.ti -1c
.RI "#define \fBTASK_STACKSIZE\fP   0x1000"
.br
.ti -1c
.RI "#define \fBTASK_STACKADDR\fP   0xF0000000"
.br
.ti -1c
.RI "#define \fBTASK_STATE_ALIVE\fP   0"
.br
.ti -1c
.RI "#define \fBTASK_STATE_ZOMBIE\fP   1"
.br
.ti -1c
.RI "#define \fBTASK_STATE_DEAD\fP   2"
.br
.ti -1c
.RI "#define \fBTASK_PRIORITY_MIN\fP   1"
.br
.ti -1c
.RI "#define \fBTASK_PRIORITY_LOW\fP   5"
.br
.ti -1c
.RI "#define \fBTASK_PRIORITY_REGULAR\fP   15"
.br
.ti -1c
.RI "#define \fBTASK_PRIORITY_HIGH\fP   30"
.br
.ti -1c
.RI "#define \fBTASK_PRIORITY_MAX\fP   50"
.br
.ti -1c
.RI "#define \fBUID_SUPERUSER\fP   1000"
.br
.ti -1c
.RI "#define \fBGID_SUPERUSER\fP   1000"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBtask\fP \fBtask_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBtask_env\fP \fB__attribute__\fP ((packed)) task_env_t"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBedi\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBesi\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBebx\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBecx\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBeax\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBedx\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBeflags\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBebp\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBeip\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GID_SUPERUSER   1000"

.PP
Definition at line 52 of file task\&.h\&.
.SS "#define TASK_MAX_FD   512"

.PP
Definition at line 35 of file task\&.h\&.
.SS "#define TASK_PRIORITY_HIGH   30"

.PP
Definition at line 47 of file task\&.h\&.
.SS "#define TASK_PRIORITY_LOW   5"

.PP
Definition at line 45 of file task\&.h\&.
.SS "#define TASK_PRIORITY_MAX   50"

.PP
Definition at line 48 of file task\&.h\&.
.SS "#define TASK_PRIORITY_MIN   1"

.PP
Definition at line 44 of file task\&.h\&.
.SS "#define TASK_PRIORITY_REGULAR   15"

.PP
Definition at line 46 of file task\&.h\&.
.SS "#define TASK_STACKADDR   0xF0000000"

.PP
Definition at line 38 of file task\&.h\&.
.SS "#define TASK_STACKSIZE   0x1000"

.PP
Definition at line 37 of file task\&.h\&.
.SS "#define TASK_STATE_ALIVE   0"

.PP
Definition at line 40 of file task\&.h\&.
.SS "#define TASK_STATE_DEAD   2"

.PP
Definition at line 42 of file task\&.h\&.
.SS "#define TASK_STATE_ZOMBIE   1"

.PP
Definition at line 41 of file task\&.h\&.
.SS "#define UID_SUPERUSER   1000"

.PP
Definition at line 51 of file task\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBtask\fP  \fBtask_t\fP"

.SH "Function Documentation"
.PP 
.SS "struct \fBtask_env\fP __attribute__ ((packed))"

.PP
Definition at line 44 of file desc\&.c\&.
.PP
.nf
46                        {
47     uint16_t limit;
48     uint32_t base;
49 } __attribute__((packed)) gdt_ptr_t;
.fi
.SH "Variable Documentation"
.PP 
.SS "\fBuint32_t\fP eax"

.PP
Definition at line 16 of file task\&.h\&.
.SS "\fBuint32_t\fP ebp"

.PP
Definition at line 19 of file task\&.h\&.
.SS "\fBuint32_t\fP ebx"

.PP
Definition at line 14 of file task\&.h\&.
.SS "\fBuint32_t\fP ecx"

.PP
Definition at line 15 of file task\&.h\&.
.SS "\fBuint32_t\fP edi"

.PP
Definition at line 12 of file task\&.h\&.
.SS "\fBuint32_t\fP edx"

.PP
Definition at line 17 of file task\&.h\&.
.SS "\fBuint32_t\fP eflags"

.PP
Definition at line 18 of file task\&.h\&.
.SS "\fBuint32_t\fP eip"

.PP
Definition at line 20 of file task\&.h\&.
.SS "\fBuint32_t\fP esi"

.PP
Definition at line 13 of file task\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
