.TH "task" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <task\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pid_t \fBpid\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   task_env_t * \fBenv\fP"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBstack\fP"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBcr3\fP"
.br
.ti -1c
.RI "   pid_t \fBowner\fP"
.br
.ti -1c
.RI "} \fBcontext\fP"
.br
.ti -1c
.RI "uid_t \fBuid\fP"
.br
.ti -1c
.RI "gid_t \fBgid\fP"
.br
.ti -1c
.RI "\fBinode_t\fP * \fBcwd\fP"
.br
.ti -1c
.RI "\fBinode_t\fP * \fBexe\fP"
.br
.ti -1c
.RI "\fBinode_t\fP * \fBfd\fP [\fBTASK_MAX_FD\fP]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBvaddr\fP"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBptr\fP"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBlength\fP"
.br
.ti -1c
.RI "} \fBimage\fP"
.br
.ti -1c
.RI "void(* \fBsignal_handler\fP )(int)"
.br
.ti -1c
.RI "int \fBsignal_sig\fP"
.br
.ti -1c
.RI "char ** \fBargv\fP"
.br
.ti -1c
.RI "char ** \fBenvp\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBstate\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBpriority\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBclock\fP"
.br
.ti -1c
.RI "int \fBexitcode\fP"
.br
.ti -1c
.RI "struct \fBtask\fP * \fBparent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 90 of file task\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char** task::argv"

.PP
Definition at line 119 of file task\&.h\&.
.SS "\fBuint32_t\fP task::clock"

.PP
Definition at line 124 of file task\&.h\&.
.SS "struct { \&.\&.\&. }   task::context"

.SS "\fBuint32_t\fP task::cr3"

.PP
Definition at line 97 of file task\&.h\&.
.SS "\fBinode_t\fP* task::cwd"

.PP
Definition at line 105 of file task\&.h\&.
.SS "task_env_t* task::env"

.PP
Definition at line 94 of file task\&.h\&.
.SS "char** task::envp"

.PP
Definition at line 120 of file task\&.h\&.
.SS "\fBinode_t\fP* task::exe"

.PP
Definition at line 106 of file task\&.h\&.
.SS "int task::exitcode"

.PP
Definition at line 125 of file task\&.h\&.
.SS "\fBinode_t\fP* task::fd[\fBTASK_MAX_FD\fP]"

.PP
Definition at line 107 of file task\&.h\&.
.SS "gid_t task::gid"

.PP
Definition at line 103 of file task\&.h\&.
.SS "struct { \&.\&.\&. }   task::image"

.SS "\fBuint32_t\fP task::length"

.PP
Definition at line 112 of file task\&.h\&.
.SS "pid_t task::owner"

.PP
Definition at line 98 of file task\&.h\&.
.SS "struct \fBtask\fP* task::parent"

.PP
Definition at line 128 of file task\&.h\&.
.SS "pid_t task::pid"

.PP
Definition at line 91 of file task\&.h\&.
.SS "\fBuint32_t\fP task::priority"

.PP
Definition at line 123 of file task\&.h\&.
.SS "\fBuint32_t\fP task::ptr"

.PP
Definition at line 111 of file task\&.h\&.
.SS "void(* task::signal_handler)(int)"

.PP
Definition at line 115 of file task\&.h\&.
.SS "int task::signal_sig"

.PP
Definition at line 116 of file task\&.h\&.
.SS "\fBuint32_t\fP task::stack"

.PP
Definition at line 95 of file task\&.h\&.
.SS "\fBuint32_t\fP task::state"

.PP
Definition at line 122 of file task\&.h\&.
.SS "uid_t task::uid"

.PP
Definition at line 102 of file task\&.h\&.
.SS "\fBuint32_t\fP task::vaddr"

.PP
Definition at line 110 of file task\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
