.TH "task_env" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task_env \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <task\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBedi\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBesi\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBebx\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBecx\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBeax\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBedx\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBeflags\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBebp\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBeip\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 59 del file task\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "\fBuint32_t\fP task_env::eax"

.PP
Definizione alla linea 64 del file task\&.h\&.
.SS "\fBuint32_t\fP task_env::ebp"

.PP
Definizione alla linea 67 del file task\&.h\&.
.SS "\fBuint32_t\fP task_env::ebx"

.PP
Definizione alla linea 62 del file task\&.h\&.
.SS "\fBuint32_t\fP task_env::ecx"

.PP
Definizione alla linea 63 del file task\&.h\&.
.SS "\fBuint32_t\fP task_env::edi"

.PP
Definizione alla linea 60 del file task\&.h\&.
.SS "\fBuint32_t\fP task_env::edx"

.PP
Definizione alla linea 65 del file task\&.h\&.
.SS "\fBuint32_t\fP task_env::eflags"

.PP
Definizione alla linea 66 del file task\&.h\&.
.SS "\fBuint32_t\fP task_env::eip"

.PP
Definizione alla linea 68 del file task\&.h\&.
.SS "\fBuint32_t\fP task_env::esi"

.PP
Definizione alla linea 61 del file task\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
