src/arch/i386/task.c
NAME
src/arch/i386/task.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/spinlock.h>
#include <aplus/task.h>
#include <aplus/mm.h>
#include <aplus/list.h>
#include <aplus/fs.h>
#include <setjmp.h>
Functions
__asm__ ('.global task_context_switch		\n''task_context_switch:				\n''	push ebp						\n''	mov ebp, esp					\n''	pushf							\n''	push edx						\n''	push eax						\n''	push ecx						\n''	push ebx						\n''	push esi						\n''	push edi						\n''	mov eax, [ebp + 8]				\n''	mov edx, [ebp + 12]				\n''	mov [eax], esp					\n''	mov esp, [edx]					\n''	pop edi							\n''	pop esi							\n''	pop ebx							\n''	pop ecx							\n''	pop eax							\n''	pop edx							\n''	popf							\n''	pop ebp							\n''	sti								\n''ret								\n')
void task_context_switch (task_env_t **old, task_env_t **new)
void task_switch_ack ()
task_t * task_clone (void *entry, void *arg, void *stack, int flags)
void task_switch (task_t *newtask)
static int __fork_child ()
task_t * task_fork ()
int task_init ()
Variables
task_t * current_task
Current task address.
task_t * kernel_task
Kernel task address.
list_t * task_queue
List of all Task.
uint32_t * kernel_vmm
uint32_t * current_vmm
volatile inode_t * vfs_root
static jmp_buf __fork_buf
Function Documentation
__asm__ ('.global task_context_switch \n''task_context_switch: \n'' push ebp \n'' movebp, esp\n''pushf\n''push edx\n''push eax\n''push ecx\n''push ebx\n''push esi\n''push edi\n''moveax, [ebp + 8] \n''movedx, [ebp + 12] \n''mov[eax], esp\n''movesp, [edx] \n''pop edi\n''pop esi\n''pop ebx\n''pop ecx\n''pop eax\n''pop edx\n''popf\n''pop ebp\n''sti\n''ret\n')
static int __fork_child () [static]
Definition at line 152 of file task.c.
References __fork_buf, task::context, task::cr3, kmalloc(), mm_align(), mm_paddr(), TASK_STACKSIZE, uint32_t, uint8_t, VMM_FLAGS_DEFAULT, VMM_FLAGS_USER, and vmm_map().
                          {
    uint32_t oldesp = __fork_buf->esp;
    uint32_t stack = (uint32_t) mm_align(kmalloc(TASK_STACKSIZE));
    for(int i = 0; i < TASK_STACKSIZE; i++)
        ((uint8_t*) stack)[i] = ((uint8_t*) (oldesp & ~0xFFF)) [i];
    vmm_map(current_task->context.cr3, mm_paddr((void*) stack), (oldesp & ~0xFFF), TASK_STACKSIZE, VMM_FLAGS_DEFAULT | VMM_FLAGS_USER);
    longjmp(__fork_buf, 1);
    return 0;
}
task_t* task_clone (void *entry, void *arg, void *stack, intflags)
Definition at line 54 of file task.c.
References task::clock, CLONE_FILES, CLONE_FS, CLONE_PARENT, CLONE_SIGHAND, CLONE_VM, task::context, task::cr3, current_task, task::cwd, task::env, task::exe, task::fd, task::gid, task::image, kmalloc(), kvmalloc(), task::length, list_add(), mm_paddr(), task::owner, task::parent, task::pid, task::priority, task::ptr, schedule_nextpid(), task::signal_handler, task::signal_sig, task::stack, task::state, TASK_MAX_FD, TASK_STACKSIZE, TASK_STATE_ALIVE, task::uid, uint32_t, task::vaddr, vmm_create(), vmm_map(), and vmm_mapkernel().
                                                                   {
    if(entry == NULL)
        return NULL;
    if(stack == NULL)
        stack = (void*) ((int)kvmalloc(TASK_STACKSIZE * 2) + TASK_STACKSIZE);
    memset(stack, 0, TASK_STACKSIZE);
    task_t* child = (task_t*) kmalloc(sizeof(task_t));
    memset(child, 0, sizeof(task_t));
    child->pid = schedule_nextpid();
    child->exe = current_task->exe;
    child->uid = current_task->uid;
    child->gid = current_task->gid;
    
    child->state = TASK_STATE_ALIVE;
    child->priority = current_task->priority;
    child->clock = 0;
    if(flags & CLONE_FILES) {
        for(int i = 0; i < TASK_MAX_FD; i++)
            child->fd[i] = current_task->fd[i];
    }
    if(flags & CLONE_FS)
        child->cwd = current_task->cwd;
    else
        child->cwd = (inode_t*) vfs_root;
    if(flags & CLONE_PARENT)
        child->parent = current_task->parent;
    else
        child->parent = current_task;
    if(flags & CLONE_SIGHAND) {
        child->signal_handler = current_task->signal_handler;
        child->signal_sig = current_task->signal_sig;
    }
    child->image.vaddr = current_task->image.vaddr;
    child->image.length = current_task->image.length;
    child->image.ptr = current_task->image.ptr;
    if(flags & CLONE_VM) {
        child->context.cr3 = current_task->context.cr3;
        child->context.owner = current_task->pid;
    } else {
        child->context.owner = child->pid;
        child->context.cr3 = vmm_create();
        vmm_mapkernel(child->context.cr3);
        if(current_task->image.vaddr && current_task->image.length) {
            void* addr = (void*) kvmalloc(child->image.length);
            memcpy(addr, (void*) child->image.vaddr, child->image.length);
            vmm_map(child->context.cr3, mm_paddr(addr), child->image.vaddr, child->image.length);
        }
    }
    
    child->context.stack = (uint32_t) stack - TASK_STACKSIZE;
    child->context.env = (task_env_t*) ((uint32_t) stack - sizeof(task_env_t));
    child->context.env->eax = (uint32_t) arg;
    child->context.env->eip = (uint32_t) entry;
    child->context.env->ebp = (uint32_t) child->context.env;
    
    list_add(task_queue, (listval_t) child);
    return child;
}
void task_context_switch (task_env_t **old, task_env_t **new)
task_t* task_fork ()
Definition at line 169 of file task.c.
References __fork_buf, __fork_child(), CLONE_FILES, CLONE_FS, CLONE_SIGHAND, schedule_disable(), schedule_enable(), task_clone(), and task_switch().
                    {
    if(!current_task)
        return NULL;
    schedule_disable();
    task_t* child = task_clone(__fork_child, NULL, NULL, CLONE_FILES | CLONE_FS | CLONE_SIGHAND);
    if(setjmp(__fork_buf) == 1) {
        schedule_enable();
        return NULL;
    }
    task_switch(child);
    return child;
}
int task_init ()
Definition at line 187 of file task.c.
References task::context, task::cr3, task::cwd, task::env, task::gid, kernel_vmm, kmalloc(), list_add(), task::parent, task::pid, task::priority, schedule_nextpid(), task::stack, task::state, TASK_PRIORITY_REGULAR, TASK_STATE_ALIVE, task_switch(), task::uid, and uint32_t.
                {
    extern uint32_t kernel_stack;
    
    kernel_task = current_task = (task_t*) kmalloc(sizeof(task_t));
    memset(current_task, 0, sizeof(task_t));
    
    
    current_task->context.env = (task_env_t*) 0;
    current_task->context.cr3 = (uint32_t) kernel_vmm;
    current_task->context.stack = (uint32_t) &kernel_stack;
    
    
    current_task->pid = schedule_nextpid();
    current_task->cwd = (inode_t*) vfs_root;
    current_task->uid = (uid_t) 0;
    current_task->gid = (gid_t) 0;
    
    current_task->state = TASK_STATE_ALIVE;
    current_task->priority = TASK_PRIORITY_REGULAR;
    current_task->parent = NULL;
    list_add(task_queue, (listval_t) current_task);
    task_switch(current_task);
    return 0;
}
void task_switch (task_t *newtask)
Definition at line 136 of file task.c.
References task::context, task::cr3, current_task, task::env, task_context_switch(), task_switch_ack(), and vmm_switch().
                                  {
    
    task_t* old = current_task;
    current_task = newtask;
    vmm_switch(current_task->context.cr3);
    task_switch_ack();
    task_context_switch(&old->context.env, &current_task->context.env);
}
void task_switch_ack ()
Definition at line 50 of file task.c.
                       {
    outb(0x20, 0x20);
}
Variable Documentation
jmp_buf __fork_buf [static]
Definition at line 150 of file task.c.
task_t* current_task
Current task address.
Definition at line 37 of file sched.c.
uint32_t* current_vmm
Definition at line 46 of file paging.c.
task_t* kernel_task
Kernel task address.
Definition at line 42 of file sched.c.
uint32_t* kernel_vmm
Definition at line 47 of file paging.c.
list_t* task_queue
List of all Task.
Definition at line 48 of file sched.c.
volatile inode_t* vfs_root
Definition at line 19 of file vfs.c.
Author
Generated automatically by Doxygen for aPlus from the source code.