.TH "usr/src/libposix/src/telldir.c" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/telldir.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dirent\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "off_t \fBtelldir\fP (\fBDIR\fP *\fBd\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "off_t telldir (\fBDIR\fP *d)"

.PP
Definition at line 11 of file telldir\&.c\&.
.PP
References errno, and __DIR::position\&.
.PP
.nf
11                       {
12     if(d == NULL) {
13         errno = EINVAL;
14         return -1;
15     }
16 
17     return d->position;
18 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
