.TH "usr/src/libposix/src/tty.c" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/tty.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <termios\&.h>\fP
.br
\fC#include <sys/ioctl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "pid_t \fBtcgetpgrp\fP (int fd)"
.br
.ti -1c
.RI "int \fBtcsetpgrp\fP (int fd, pid_t pgrp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "pid_t tcgetpgrp (intfd)"

.PP
Definition at line 6 of file tty\&.c\&.
.PP
.nf
6                         {
7     pid_t pgrp;
8     if(ioctl(fd, TIOCGPGRP, &pgrp) != 0)
9         return -1;
10 
11     return pgrp;
12 }
.fi
.SS "int tcsetpgrp (intfd, pid_tpgrp)"

.PP
Definition at line 14 of file tty\&.c\&.
.PP
.nf
14                                   {
15     return ioctl(fd, TIOCSPGRP, &pgrp);
16 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
