src/fs/tty.c
NAME
src/fs/tty.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/fs.h>
#include <aplus/task.h>
#include <aplus/spinlock.h>
#include <aplus/list.h>
#include <aplus/tty.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <sys/termios.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/stat.h>
Functions
static void __default_tty_output (tty_t *tty, void *ptr, size_t size)
int tty_ioctl (inode_t *ino, int cmd, void *buf)
int tty_write (inode_t *ino, char *ptr, int size)
int tty_read (inode_t *ino, char *ptr, int size)
void tty_flush (inode_t *ino)
int tty_open (int *master, int *slave, char *name, struct termios *ios, struct winsize *win)
int tty_init ()
Variables
task_t * current_task
Current task address.
task_t * kernel_task
Kernel task address.
list_t * ttydevs = NULL
cc_t ttydefchars [NCCS]
Function Documentation
static void __default_tty_output (tty_t *tty, void *ptr, size_tsize) [static]
Definition at line 32 of file tty.c.
References kprintf(), and size.
                                                                     {
    char* ctr = (char*) ptr;
    
    for(int i = 0; i < size; i++)
        kprintf("%c", ctr[i]);
}
void tty_flush (inode_t *ino)
Definition at line 221 of file tty.c.
References kfree(), list_remove(), and inode::userdata.
                             {
    if(!ino)
        return;
    if(!ino->userdata)
        return;
    list_remove(ttydevs, (listval_t) ino->userdata);
    kfree(ino->userdata);
}
int tty_init ()
Definition at line 307 of file tty.c.
References errno, task::fd, kprintf(), name, sys_close(), sys_symlink(), and tty_open().
               {
    int master, slave;
    char name[32];
    if(tty_open(&master, &slave, name, NULL, NULL) != 0) {
        kprintf("tty_open: failed with %d (%s)\n", errno, strerror(errno));
        return -1;
    }
    kprintf("tty: created device at %s\n", name);
    sys_symlink(name, "/dev/stdin");
    sys_symlink(name, "/dev/stdout");
    sys_symlink(name, "/dev/stderr");
    inode_t* ino = current_task->fd[master];
    sys_close(master);
    sys_close(slave);
    
    kernel_task->fd[STDIN_FILENO] = ino;
    kernel_task->fd[STDOUT_FILENO] = ino;
    kernel_task->fd[STDERR_FILENO] = ino;
    return 0;
}
int tty_ioctl (inode_t *ino, intcmd, void *buf)
Definition at line 39 of file tty.c.
References errno, tty::exclmode, tty::fg, tty::ibuffer, tty::id, im_superuser(), tty::ios, tty::isize, tty::lock, tty::osize, spinlock_lock(), spinlock_unlock(), inode::userdata, tty::win, and winsize.
                                                {
    if(!ino) {
        errno = EINVAL;
        return -1;
    }
    tty_t* tty = ino->userdata;
    if(!tty) {
        errno = ENOTTY;
        return -1;
    }
    spinlock_lock(&tty->lock);
    errno = 0;
    switch(cmd) {
        case TCGETS:
            memcpy(buf, &tty->ios, sizeof(struct termios));
            break;
        case TCSETS:
        case TCSETSW:
        case TCSETSF:
            memcpy(&tty->ios, buf, sizeof(struct termios));
            break;
        case TCGETA:
        case TCSETA:
        case TCSETAW:
        case TCSETAF:
            errno = ENOSYS;
            break;
        case TIOCGLCKTRMIOS:
        case TIOCSLCKTRMIOS:
            if(!im_superuser())
                errno = EPERM;
            else
                errno = ENOSYS;
            break;
        case TIOCGWINSZ:
            memcpy(buf, &tty->win, sizeof(struct winsize));
            break;
        case TIOCSWINSZ:
            memcpy(&tty->win, buf, sizeof(struct winsize));
            break;
        case TCSBRK:
        case TCSBRKP:
            break;
        case TIOCSBRK:
        case TIOCCBRK:
            break;
        case TCXONC:
            errno = ENOSYS;
            break;
        case FIONREAD:
            *(int*) buf = tty->isize;
            break;
        case TIOCOUTQ:
            *(int*) buf = tty->osize;
            break;
        case TCFLSH:
            switch(*(int*) buf) {
                case TCIFLUSH:
                    tty->isize = 0;
                    break;
                case TCOFLUSH:
                    tty->osize = 0;
                    break;
                case TCIOFLUSH:
                    tty->isize = tty->osize = 0;
                    break;
                default:
                    errno = EINVAL;
            }
            break;
        case TIOCSTI:
            while(*(char*) buf)
                tty->ibuffer[tty->isize++] = *(char*) buf++;
            break;
        case TIOCCONS:
        case TIOCSCTTY:
            if(!im_superuser())
                errno = EPERM;
            else
                errno = ENOSYS;
            break;
        case TIOCGPGRP:
            *(pid_t*) buf = tty->fg;
            break;
        case TIOCSPGRP:
            tty->fg = *(pid_t*) buf;
            break;
        case TIOCGSID:
            *(pid_t*) buf = tty->id;
            break;
        case TIOCEXCL:
            tty->exclmode = 1;
            break;
        case TIOCNXCL:
            tty->exclmode = 0;
            break;
        case TIOCGETD:
        case TIOCSETD:
            errno = ENOSYS;
            break;
        default:
#ifdef ENOIOCTLCMD
            errno = ENOIOCTLCMD;
#else
            errno = ENOSYS;
#endif
            break;
    }
    spinlock_unlock(&tty->lock);
    if(errno == 0)
        return 0;
    
    return -1;
}
int tty_open (int *master, int *slave, char *name, struct termios *ios, struct winsize *win)
Definition at line 233 of file tty.c.
References __default_tty_output(), tty::bg, errno, tty::exclmode, task::fd, tty::fg, inode::flush, tty::id, inode::ioctl, tty::ios, tty::isize, kmalloc(), ksprintf(), list_add(), list_init, list_size, tty::lock, tty::osize, tty::output, task::pid, inode::read, sys_open(), tty_flush(), tty_ioctl(), tty_read(), tty_write(), TTYDEF_IOS_CFLAG, TTYDEF_IOS_IFLAG, TTYDEF_IOS_LFLAG, TTYDEF_IOS_OFLAG, TTYDEF_WIN_COLS, TTYDEF_WIN_ROWS, ttydefchars, inode::userdata, tty::win, winsize, and inode::write.
                                                                                            {
    if(ttydevs == NULL) {
        list_init(ttydevs);
    }
    if(!master || !slave) {
        errno = EINVAL;
        return -1;
    }
    char fname[32];
    memset(fname, 0, 32);
    ksprintf(fname, "/dev/tty%d", (int) list_size(ttydevs));
    int fd = sys_open(fname, O_CREAT | O_EXCL | O_RDWR, S_IFCHR);
    if(fd < 0) {
        errno = ENOENT;
        return -1;
    }
    inode_t* ino = current_task->fd[fd];
    tty_t* tty = kmalloc(sizeof(tty_t));
    ino->read = tty_read;
    ino->write = tty_write;
    ino->ioctl = tty_ioctl;
    ino->flush = tty_flush;
    ino->userdata = tty;
    tty->ios.c_iflag = TTYDEF_IOS_IFLAG;
    tty->ios.c_oflag = TTYDEF_IOS_OFLAG;
    tty->ios.c_cflag = TTYDEF_IOS_CFLAG;
    tty->ios.c_lflag = TTYDEF_IOS_LFLAG;
    
    memcpy(tty->ios.c_cc, ttydefchars, sizeof(cc_t) * NCCS);
    tty->win.ws_row = TTYDEF_WIN_ROWS;
    tty->win.ws_col = TTYDEF_WIN_COLS;
    tty->win.ws_xpixel = 0; /* unused */
    tty->win.ws_ypixel = 0; /* unused */
    tty->lock = 0;
    tty->isize = 0;
    tty->osize = 0;
    tty->exclmode = 0;
    tty->fg = current_task->pid;
    tty->bg = -1;
    tty->id = list_size(ttydevs);
    tty->output = __default_tty_output;
    list_add(ttydevs, (listval_t) tty);
    if(name)
        strcpy(name, fname);
    if(ios)
        memcpy(ios, &tty->ios, sizeof(struct termios));
    if(win)
        memcpy(win, &tty->win, sizeof(struct winsize));
        
    *master = fd;
    *slave = fd;
    return 0;
}
int tty_read (inode_t *ino, char *ptr, intsize)
Definition at line 190 of file tty.c.
References errno, tty::ibuffer, tty::isize, tty::lock, tty::output, size, spinlock_lock(), spinlock_unlock(), spinlock_waiton, and inode::userdata.
                                                {
    if(!ino)
        return 0;
    if(!ptr)
        return 0;
    
    if(!size)
        return 0;
    tty_t* tty = ino->userdata;
    if(!tty) {
        errno = ENOTTY;
        return -1;
    }
    spinlock_lock(&tty->lock);
    spinlock_waiton(size > tty->isize);
    memcpy(ptr, tty->ibuffer, tty->isize);
    tty->isize -= size;
    if(tty->output)
        tty->output(tty, ptr, size);
    spinlock_unlock(&tty->lock);
    return size;
}
int tty_write (inode_t *ino, char *ptr, intsize)
Definition at line 162 of file tty.c.
References errno, tty::lock, tty::obuffer, tty::output, size, spinlock_lock(), spinlock_unlock(), and inode::userdata.
                                                 {
    if(!ino)
        return 0;
    
    if(!ptr)
        return 0;
    if(!size)
        return 0;
    tty_t* tty = ino->userdata;
    if(!tty) {
        errno = ENOTTY;
        return -1;
    }
    spinlock_lock(&tty->lock);
    memcpy(tty->obuffer, ptr, size);
    if(tty->output)
        tty->output(tty, ptr, size);
    spinlock_unlock(&tty->lock);
    return size;
}
Variable Documentation
task_t* current_task
Current task address.
Definition at line 35 of file sched.c.
task_t* kernel_task
Kernel task address.
Definition at line 40 of file sched.c.
cc_t ttydefchars[NCCS]
Initial value:
= {
    
    
    
}
Definition at line 25 of file tty.c.
list_t* ttydevs = NULL
Definition at line 23 of file tty.c.
Author
Generated automatically by Doxygen for aPlus from the source code.