.TH "usr/src/libposix/src/uid.c" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/uid.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uid_t \fBgetuid\fP (void)"
.br
.ti -1c
.RI "uid_t \fBgeteuid\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uid_t geteuid (void)"

.PP
Definition at line 13 of file uid\&.c\&.
.PP
References getuid()\&.
.PP
.nf
13                     {
14     return getuid();
15 }
.fi
.SS "uid_t getuid (void)"

.PP
Definition at line 5 of file uid\&.c\&.
.PP
.nf
5                    {
6     struct stat st;
7     if(fstat(STDIN_FILENO, &st) != 0)
8         return -1;
9 
10     return st\&.st_uid;
11 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
