.TH "src/syscall/umount.c" 3 "Wed Nov 12 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syscall/umount.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <aplus\&.h>\fP
.br
\fC#include <aplus/fs\&.h>\fP
.br
\fC#include <aplus/task\&.h>\fP
.br
\fC#include <aplus/list\&.h>\fP
.br
\fC#include <aplus/attribute\&.h>\fP
.br
\fC#include <aplus/syscall\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsys_umount2\fP (const char *file, int \fBflags\fP)"
.br
.ti -1c
.RI "int \fBsys_umount\fP (const char *file)"
.br
.ti -1c
.RI "\fBSYSCALL\fP (\fBsys_umount\fP, 25)"
.br
.ti -1c
.RI "\fBSYSCALL\fP (\fBsys_umount2\fP, 26)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtask_t\fP * \fBcurrent_task\fP"
.br
.RI "\fICurrent task address\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int sys_umount (const char *file)"

.PP
Definition at line 48 of file umount\&.c\&.
.PP
References sys_umount2()\&.
.PP
.nf
48                                  {
49     return sys_umount2(file, 0);
50 }
.fi
.SS "int sys_umount2 (const char *file, intflags)"

.PP
Definition at line 20 of file umount\&.c\&.
.PP
References inode::chown, inode::creat, inode::dev, errno, task::fd, inode::finddir, inode::flush, inode::mode, inode::readdir, sys_close(), sys_open(), and inode::unlink\&.
.PP
.nf
20                                              {
21     if(!file) {
22         errno = EINVAL;
23         return -1;
24     }
25 
26     int fd = sys_open(file, O_RDONLY, 0644);
27     if(fd < 0) {
28         errno = ENOENT;
29         return -1;
30     }
31 
32     inode_t* ino = current_task->fd[fd];
33     sys_close(fd);
34 
35     ino->readdir = NULL;
36     ino->finddir = NULL;
37     ino->creat = NULL;
38     ino->unlink = NULL;
39     ino->flush = NULL;
40     ino->chown = NULL;
41 
42     ino->dev = (dev_t) 0;
43     ino->mode &= ~S_IFMT;
44 
45     return 0;
46 }
.fi
.SS "SYSCALL (\fBsys_umount\fP, 25)"

.SS "SYSCALL (\fBsys_umount2\fP, 26)"

.SH "Variable Documentation"
.PP 
.SS "\fBtask_t\fP* current_task"

.PP
Current task address\&. 
.PP
Definition at line 35 of file sched\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
