src/syscall/umount.c
NAME
src/syscall/umount.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/fs.h>
#include <aplus/task.h>
#include <aplus/list.h>
#include <aplus/attribute.h>
#include <aplus/syscall.h>
#include <stdint.h>
#include <unistd.h>
#include <dirent.h>
#include <fcntl.h>
#include <sys/types.h>
#include <errno.h>
Functions
int sys_umount2 (const char *file, int flags)
int sys_umount (const char *file)
SYSCALL (sys_umount, 25)
SYSCALL (sys_umount2, 26)
Variables
task_t * current_task
Current task address.
Function Documentation
int sys_umount (const char *file)
Definition at line 48 of file umount.c.
References sys_umount2().
                                 {
    return sys_umount2(file, 0);
}
int sys_umount2 (const char *file, intflags)
Definition at line 20 of file umount.c.
References inode::chown, inode::creat, inode::dev, errno, task::fd, inode::finddir, inode::flush, inode::mode, inode::readdir, sys_close(), sys_open(), and inode::unlink.
                                             {
    if(!file) {
        errno = EINVAL;
        return -1;
    }
    int fd = sys_open(file, O_RDONLY, 0644);
    if(fd < 0) {
        errno = ENOENT;
        return -1;
    }
    inode_t* ino = current_task->fd[fd];
    sys_close(fd);
    ino->readdir = NULL;
    ino->finddir = NULL;
    ino->creat = NULL;
    ino->unlink = NULL;
    ino->flush = NULL;
    ino->chown = NULL;
    ino->dev = (dev_t) 0;
    ino->mode &= ~S_IFMT;
    return 0;
}
SYSCALL (sys_umount, 25)
SYSCALL (sys_umount2, 26)
Variable Documentation
task_t* current_task
Current task address.
Definition at line 35 of file sched.c.
Author
Generated automatically by Doxygen for aPlus from the source code.