src/syscall/unlink.c
NAME
src/syscall/unlink.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/syscall.h>
#include <aplus/fs.h>
#include <aplus/task.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/stat.h>
#include <dirent.h>
#include <stdio.h>
Functions
static char * dupstr (char *s)
int sys_unlink (const char *pathname)
SYSCALL (sys_unlink, 15)
Variables
task_t * current_task
Current task address.
inode_t * vfs_root
Function Documentation
static char* dupstr (char *s) [static]
Definition at line 18 of file unlink.c.
References kmalloc().
                             {
    char* p = (char*) kmalloc(strlen(s) + 1);
    strcpy(p, s);
    return p;
}
int sys_unlink (const char *pathname)
Definition at line 26 of file unlink.c.
References task::cwd, dupstr(), errno, fs_finddir(), fs_unlink(), kfree(), kprintf(), inode::link, inode::mode, and vfs_root.
                                     {
    if(!pathname) {
        errno = EINVAL;
        return -1;
    }
    inode_t* cwd = NULL;
    if(pathname[0] == '/')
        cwd = vfs_root;
    else
        cwd = current_task->cwd;
    
    if(!cwd) {
        if(!vfs_root) {
            kprintf("sys_unlink: no root found for cwd.");
        
            errno = ENOENT;
            return -1;
        }
        
        cwd = vfs_root;
    }
    
    
    if(pathname[0] == '/')
        pathname++;
        
    if(pathname[0] == 0) {
        errno = EPERM;
        return -1;
    }
    
    char* b = dupstr((char*) pathname);
    char* s = b;
    char* p = s;
    
    while(*s) {
        if((p = strchr(s, '/'))) {
            *p++ = 0;
        
            cwd = (inode_t*) fs_finddir(cwd, s);
            if(!cwd) {
                errno = ENOENT;
                return -1;
            }
            while(S_ISLNK(cwd->mode))
                if(cwd->link)
                    cwd = cwd->link;
                else
                    break;
            s = p;
        } else
            break;
    }
    if(*s == 0) {
        errno = ENOENT;
        return -1;
    }
    int ret = fs_unlink(cwd, s);
    kfree(b);
    
    return ret;
}
SYSCALL (sys_unlink, 15)
Variable Documentation
task_t* current_task
Current task address.
Definition at line 37 of file sched.c.
inode_t* vfs_root
Definition at line 19 of file vfs.c.
Author
Generated automatically by Doxygen for aPlus from the source code.