.TH "vesaInfo_t" 3 "Dom 9 Nov 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vesaInfo_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grub\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "char \fBsignature\fP [4]"
.br
.ti -1c
.RI "unsigned short \fBversion\fP"
.br
.ti -1c
.RI "unsigned int \fBoem_string_ptr\fP"
.br
.ti -1c
.RI "unsigned int \fBcapabilities\fP"
.br
.ti -1c
.RI "unsigned int \fBvideo_mode_ptr\fP"
.br
.ti -1c
.RI "unsigned short \fBtotal_memory\fP"
.br
.ti -1c
.RI "unsigned int \fBoem_software_rev\fP"
.br
.ti -1c
.RI "char * \fBoem_vendor_name\fP"
.br
.ti -1c
.RI "char * \fBoem_product_name\fP"
.br
.ti -1c
.RI "char * \fBoem_product_rev\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 26 del file grub\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "unsigned int vesaInfo_t::capabilities"

.PP
Definizione alla linea 30 del file grub\&.h\&.
.SS "char* vesaInfo_t::oem_product_name"

.PP
Definizione alla linea 35 del file grub\&.h\&.
.SS "char* vesaInfo_t::oem_product_rev"

.PP
Definizione alla linea 36 del file grub\&.h\&.
.SS "unsigned int vesaInfo_t::oem_software_rev"

.PP
Definizione alla linea 33 del file grub\&.h\&.
.SS "unsigned int vesaInfo_t::oem_string_ptr"

.PP
Definizione alla linea 29 del file grub\&.h\&.
.SS "char* vesaInfo_t::oem_vendor_name"

.PP
Definizione alla linea 34 del file grub\&.h\&.
.SS "char vesaInfo_t::signature[4]"

.PP
Definizione alla linea 27 del file grub\&.h\&.
.SS "unsigned short vesaInfo_t::total_memory"

.PP
Definizione alla linea 32 del file grub\&.h\&.
.SS "unsigned short vesaInfo_t::version"

.PP
Definizione alla linea 28 del file grub\&.h\&.
.SS "unsigned int vesaInfo_t::video_mode_ptr"

.PP
Definizione alla linea 31 del file grub\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per aPlus a partire dal codice sorgente\&.
