.TH "vesaInfo_t" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vesaInfo_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grub\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBsignature\fP [4]"
.br
.ti -1c
.RI "unsigned short \fBversion\fP"
.br
.ti -1c
.RI "unsigned int \fBoem_string_ptr\fP"
.br
.ti -1c
.RI "unsigned int \fBcapabilities\fP"
.br
.ti -1c
.RI "unsigned int \fBvideo_mode_ptr\fP"
.br
.ti -1c
.RI "unsigned short \fBtotal_memory\fP"
.br
.ti -1c
.RI "unsigned int \fBoem_software_rev\fP"
.br
.ti -1c
.RI "char * \fBoem_vendor_name\fP"
.br
.ti -1c
.RI "char * \fBoem_product_name\fP"
.br
.ti -1c
.RI "char * \fBoem_product_rev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file grub\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int vesaInfo_t::capabilities"

.PP
Definition at line 30 of file grub\&.h\&.
.SS "char* vesaInfo_t::oem_product_name"

.PP
Definition at line 35 of file grub\&.h\&.
.SS "char* vesaInfo_t::oem_product_rev"

.PP
Definition at line 36 of file grub\&.h\&.
.SS "unsigned int vesaInfo_t::oem_software_rev"

.PP
Definition at line 33 of file grub\&.h\&.
.SS "unsigned int vesaInfo_t::oem_string_ptr"

.PP
Definition at line 29 of file grub\&.h\&.
.SS "char* vesaInfo_t::oem_vendor_name"

.PP
Definition at line 34 of file grub\&.h\&.
.SS "char vesaInfo_t::signature[4]"

.PP
Definition at line 27 of file grub\&.h\&.
.SS "unsigned short vesaInfo_t::total_memory"

.PP
Definition at line 32 of file grub\&.h\&.
.SS "unsigned short vesaInfo_t::version"

.PP
Definition at line 28 of file grub\&.h\&.
.SS "unsigned int vesaInfo_t::video_mode_ptr"

.PP
Definition at line 31 of file grub\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
