.TH "vesaModeInfo_t" 3 "Sun Nov 9 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vesaModeInfo_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grub\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned short \fBattributes\fP"
.br
.ti -1c
.RI "unsigned char \fBwinA\fP"
.br
.ti -1c
.RI "unsigned char \fBwinB\fP"
.br
.ti -1c
.RI "unsigned short \fBgranularity\fP"
.br
.ti -1c
.RI "unsigned short \fBwinsize\fP"
.br
.ti -1c
.RI "unsigned short \fBsegmentA\fP"
.br
.ti -1c
.RI "unsigned short \fBsegmentB\fP"
.br
.ti -1c
.RI "unsigned int \fBrealFctPtr\fP"
.br
.ti -1c
.RI "unsigned short \fBpitch\fP"
.br
.ti -1c
.RI "unsigned short \fBXres\fP"
.br
.ti -1c
.RI "unsigned short \fBYres\fP"
.br
.ti -1c
.RI "unsigned char \fBWchar\fP"
.br
.ti -1c
.RI "unsigned char \fBYchar\fP"
.br
.ti -1c
.RI "unsigned char \fBplanes\fP"
.br
.ti -1c
.RI "unsigned char \fBbpp\fP"
.br
.ti -1c
.RI "unsigned char \fBbanks\fP"
.br
.ti -1c
.RI "unsigned char \fBmemory_model\fP"
.br
.ti -1c
.RI "unsigned char \fBbank_size\fP"
.br
.ti -1c
.RI "unsigned char \fBimage_pages\fP"
.br
.ti -1c
.RI "unsigned char \fBreserved0\fP"
.br
.ti -1c
.RI "unsigned char \fBred_mask\fP"
.br
.ti -1c
.RI "unsigned char \fBred_position\fP"
.br
.ti -1c
.RI "unsigned char \fBgreen_mask\fP"
.br
.ti -1c
.RI "unsigned char \fBgreen_position\fP"
.br
.ti -1c
.RI "unsigned char \fBblue_mask\fP"
.br
.ti -1c
.RI "unsigned char \fBblue_position\fP"
.br
.ti -1c
.RI "unsigned char \fBrsv_mask\fP"
.br
.ti -1c
.RI "unsigned char \fBrsv_position\fP"
.br
.ti -1c
.RI "unsigned char \fBdirectcolor_attributes\fP"
.br
.ti -1c
.RI "unsigned int \fBphysbase\fP"
.br
.ti -1c
.RI "unsigned int \fBreserved1\fP"
.br
.ti -1c
.RI "short \fBreserved2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file grub\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned short vesaModeInfo_t::attributes"

.PP
Definition at line 40 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::bank_size"

.PP
Definition at line 50 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::banks"

.PP
Definition at line 49 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::blue_mask"

.PP
Definition at line 55 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::blue_position"

.PP
Definition at line 55 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::bpp"

.PP
Definition at line 49 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::directcolor_attributes"

.PP
Definition at line 57 of file grub\&.h\&.
.SS "unsigned short vesaModeInfo_t::granularity"

.PP
Definition at line 42 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::green_mask"

.PP
Definition at line 54 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::green_position"

.PP
Definition at line 54 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::image_pages"

.PP
Definition at line 50 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::memory_model"

.PP
Definition at line 50 of file grub\&.h\&.
.SS "unsigned int vesaModeInfo_t::physbase"

.PP
Definition at line 59 of file grub\&.h\&.
.SS "unsigned short vesaModeInfo_t::pitch"

.PP
Definition at line 46 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::planes"

.PP
Definition at line 49 of file grub\&.h\&.
.SS "unsigned int vesaModeInfo_t::realFctPtr"

.PP
Definition at line 45 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::red_mask"

.PP
Definition at line 53 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::red_position"

.PP
Definition at line 53 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::reserved0"

.PP
Definition at line 51 of file grub\&.h\&.
.SS "unsigned int vesaModeInfo_t::reserved1"

.PP
Definition at line 60 of file grub\&.h\&.
.SS "short vesaModeInfo_t::reserved2"

.PP
Definition at line 61 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::rsv_mask"

.PP
Definition at line 56 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::rsv_position"

.PP
Definition at line 56 of file grub\&.h\&.
.SS "unsigned short vesaModeInfo_t::segmentA"

.PP
Definition at line 44 of file grub\&.h\&.
.SS "unsigned short vesaModeInfo_t::segmentB"

.PP
Definition at line 44 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::Wchar"

.PP
Definition at line 49 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::winA"

.PP
Definition at line 41 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::winB"

.PP
Definition at line 41 of file grub\&.h\&.
.SS "unsigned short vesaModeInfo_t::winsize"

.PP
Definition at line 43 of file grub\&.h\&.
.SS "unsigned short vesaModeInfo_t::Xres"

.PP
Definition at line 48 of file grub\&.h\&.
.SS "unsigned char vesaModeInfo_t::Ychar"

.PP
Definition at line 49 of file grub\&.h\&.
.SS "unsigned short vesaModeInfo_t::Yres"

.PP
Definition at line 48 of file grub\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
