src/fs/vfs.c
NAME
src/fs/vfs.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/fs.h>
#include <aplus/list.h>
#include <stdint.h>
#include <stddef.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <dirent.h>
#include <errno.h>
Functions
void vfs_map (inode_t *inode)
void vfs_umap (inode_t *inode)
inode_t * vfs_mapped (inode_t *parent, char *name)
inode_t * vfs_mapped_at_index (inode_t *parent, int index)
int vfs_mapped_count (inode_t *parent)
int vfs_chroot (inode_t *root)
int vfs_init ()
Variables
static list_t * list_inodes = 0
static uint32_t nextinode = 0
inode_t * vfs_root
Function Documentation
int vfs_chroot (inode_t *root)
Definition at line 72 of file vfs.c.
References inode::parent.
                              {
    vfs_root = root;
    vfs_root->parent = 0;
    
    return 0;
}
int vfs_init ()
Definition at line 81 of file vfs.c.
References inode::atime, inode::chown, inode::creat, inode::ctime, inode::dev, devfs_mount(), inode::finddir, inode::flush, inode::gid, GID_ROOT, inode::ino, inode::ioctl, kmalloc(), inode::link, list_add(), list_init, inode::mode, inode::mtime, inode::name, nextinode, inode::nlink, inode::parent, inode::rdev, inode::read, inode::readdir, inode::rename, inode::size, sys_time(), inode::uid, UID_ROOT, inode::unlink, vfs_map(), and inode::write.
               {
    list_init(list_inodes);
    
    
    vfs_root = (inode_t*) kmalloc(sizeof(inode_t));
    vfs_root->name[0] = '/';
    vfs_root->name[1] = 0;
    
    vfs_root->dev = (dev_t) 0;
    vfs_root->ino = (ino_t) nextinode++;
    vfs_root->mode = S_IFDIR;
    vfs_root->nlink = 0;
    vfs_root->uid = UID_ROOT;
    vfs_root->gid = GID_ROOT;
    vfs_root->rdev = (dev_t) 0;
    vfs_root->size = (size_t) 0;
    vfs_root->atime = vfs_root->ctime = vfs_root->mtime = sys_time(NULL);
    vfs_root->parent = (inode_t*) NULL;
    vfs_root->link = (inode_t*) NULL;
    
    vfs_root->read = NULL;
    vfs_root->write = NULL;
    vfs_root->readdir = NULL;
    vfs_root->finddir = NULL;
    vfs_root->creat = NULL;
    vfs_root->rename = NULL;
    vfs_root->unlink = NULL;
    vfs_root->chown = NULL;
    vfs_root->flush = NULL;
    vfs_root->ioctl = NULL;
    
    list_add(list_inodes, (listval_t) vfs_root);
    vfs_map((inode_t*) devfs_mount());
    
    return 0;
}
void vfs_map (inode_t *inode)
Definition at line 22 of file vfs.c.
References inode::ino, list_add(), and nextinode.
                             {
    inode->ino = (ino_t) nextinode++;
    list_add(list_inodes, (listval_t) inode);
}
inode_t* vfs_mapped (inode_t *parent, char *name)
Definition at line 32 of file vfs.c.
References list_foreach, inode::name, inode::parent, and value.
                                                 {
    list_foreach(tmp, list_inodes) {
        inode_t* value = (inode_t*) tmp;
        
        if(value->parent == parent)
            if(strcmp(value->name, name) == 0)
                return value;
    }
    
    return NULL;
}
inode_t* vfs_mapped_at_index (inode_t *parent, intindex)
Definition at line 44 of file vfs.c.
References list_foreach, inode::parent, and value.
                                                         {
    list_foreach(tmp, list_inodes) {
        inode_t* value = (inode_t*) tmp;
        
        if(value->parent == parent)
            index--;
            
        if(index == -1)
            return value;
    }
    
    return NULL;
}
int vfs_mapped_count (inode_t *parent)
Definition at line 58 of file vfs.c.
References list_foreach, inode::parent, and value.
                                      {
    int index = 0;
    
    list_foreach(tmp, list_inodes) {
        inode_t* value = (inode_t*) tmp;
        
        if(value->parent == parent)
            index++;
    }
    
    return index;
}
void vfs_umap (inode_t *inode)
Definition at line 27 of file vfs.c.
References kfree(), and list_remove().
                              {
    list_remove(list_inodes, (listval_t) inode);
    kfree(inode);
}
Variable Documentation
list_t* list_inodes = 0 [static]
Definition at line 16 of file vfs.c.
uint32_t nextinode = 0 [static]
Definition at line 17 of file vfs.c.
inode_t* vfs_root
Definition at line 19 of file vfs.c.
Author
Generated automatically by Doxygen for aPlus from the source code.