.TH "usr/src/libposix/src/wait.c" 3 "Sun Nov 16 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libposix/src/wait.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "pid_t \fBwait3\fP (int *status, int options, void *rusage)"
.br
.ti -1c
.RI "pid_t \fBwait4\fP (pid_t pid, int *status, int options, void *rusage)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "pid_t wait3 (int *status, intoptions, void *rusage)"

.PP
Definition at line 7 of file wait\&.c\&.
.PP
.nf
7                                                     {
8     return waitpid(-1, status, options);
9 }
.fi
.SS "pid_t wait4 (pid_tpid, int *status, intoptions, void *rusage)"

.PP
Definition at line 11 of file wait\&.c\&.
.PP
.nf
11                                                                {
12     return waitpid(pid, status, options);   
13 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
