src/syscall/waitpid.c
NAME
src/syscall/waitpid.c -
SYNOPSIS
#include <aplus.h>
#include <aplus/syscall.h>
#include <aplus/fs.h>
#include <aplus/task.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/wait.h>
#include <sys/types.h>
Functions
int sys_waitpid (pid_t pid, int *status, int options)
SYSCALL (sys_waitpid, 31)
Variables
task_t * current_task
Current task address.
Function Documentation
int sys_waitpid (pid_tpid, int *status, intoptions)
Definition at line 15 of file waitpid.c.
References errno, task::pid, schedule_child(), schedule_getbypid(), and schedule_wait().
                                                     {
    if(current_task == NULL) {
        errno = EFAULT;
        return -1;
    }
    task_t* child = NULL;
    if(pid == -1)
        child = (task_t*) schedule_child();
    else
        child = (task_t*) schedule_getbypid(pid);
    if(child == NULL) {
        errno = ECHILD;
        return -1;
    }
    if(options == WNOHANG)
        return child->pid;
    int exitcode = schedule_wait(child);
    if(status)
        *status = exitcode;
    return child->pid;
}
SYSCALL (sys_waitpid, 31)
Variable Documentation
task_t* current_task
Current task address.
Definition at line 37 of file sched.c.
Author
Generated automatically by Doxygen for aPlus from the source code.