.TH "usr/src/libatk/src/include/atk/widget.h" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usr/src/libatk/src/include/atk/widget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <atk\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB__atk_widget_private\fP"
.br
.ti -1c
.RI "struct \fBatk_widget\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBATK_WIDGET_FLAGS_ENABLED\fP   0x01"
.br
.ti -1c
.RI "#define \fBATK_WIDGET_FLAGS_FOCUS\fP   0x02"
.br
.ti -1c
.RI "#define \fBATK_WIDGET_FLAGS_TOPMOST\fP   0x04"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBatk_widget\fP \fBatk_widget_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ATK_WIDGET_FLAGS_ENABLED   0x01"

.PP
Definition at line 8 of file widget\&.h\&.
.SS "#define ATK_WIDGET_FLAGS_FOCUS   0x02"

.PP
Definition at line 9 of file widget\&.h\&.
.SS "#define ATK_WIDGET_FLAGS_TOPMOST   0x04"

.PP
Definition at line 10 of file widget\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBatk_widget\fP \fBatk_widget_t\fP"

.PP
Definition at line 6 of file widget\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
