.TH "src/syscall/yield.c" 3 "Fri Nov 14 2014" "Version 0.1" "aPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syscall/yield.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <aplus\&.h>\fP
.br
\fC#include <aplus/syscall\&.h>\fP
.br
\fC#include <aplus/task\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsys_yield\fP ()"
.br
.ti -1c
.RI "\fBSYSCALL\fP (\fBsys_yield\fP, 23)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void sys_yield ()"

.PP
Definition at line 6 of file yield\&.c\&.
.PP
References schedule_yield()\&.
.PP
.nf
6                  {
7     schedule_yield();
8 }
.fi
.SS "SYSCALL (\fBsys_yield\fP, 23)"

.SH "Author"
.PP 
Generated automatically by Doxygen for aPlus from the source code\&.
