#!/bin/sh

if [ -z $1 ]; then
    echo "Usage: $0 <setup>"
    exit 1
fi

setup=$1



apt update
apt upgrade
apt install -y      \
    build-essential \
    gcc             \
    g++             \
    nasm            \
    automake        \
    autoconf        \
    parted          \
    e2fsprogs       \
    grub-pc         \
    zip             \
    sudo            \
    fontconfig      \
    python3         \
    python3-pip     \
    python3-setuptools

pip3 install -r docs/requirements.txt


./configure $setup
./makew install






