#!/bin/bash

mkdir -p root
mkdir -p root/boot
mkdir -p root/boot/grub
mkdir -p root/dev
mkdir -p root/etc
mkdir -p root/etc/fonts
mkdir -p root/etc/init.d
mkdir -p root/home
mkdir -p root/home/root
mkdir -p root/home/antonio
mkdir -p root/mnt
mkdir -p root/opt
mkdir -p root/proc
mkdir -p root/srv
mkdir -p root/srv/http
mkdir -p root/sys
mkdir -p root/tmp
mkdir -p root/usr
mkdir -p root/usr/include
mkdir -p root/usr/sbin
mkdir -p root/usr/share
mkdir -p root/usr/lib
mkdir -p root/usr/lib/modules
mkdir -p root/usr/bin
mkdir -p root/var
mkdir -p root/var/cache

ln -sf usr/sbin root
ln -sf usr/bin root
ln -sf usr/lib root
ln -sf usr/lib root
ln -sf xsh root/bin/sh
ln -sf ../usr/share/zoneinfo/Europe/Rome root/etc/localtime