#!/bin/bash

kargs='root=/dev/sda1 rootfs=ext2'
margs=''

echo -e "\
menuentry \"aPlus\" { \n\
    multiboot /aplus $kargs"

echo -e "\
    module /usr/lib/modules/exports"


for ko in $(find root/usr/lib/modules -type f -name *.ko); do
    test -f "$ko" || continue
    echo -e "\
    module $(echo $ko | cut -c 5-) $margs"
done

echo -e "\
    boot \n\
}"

echo ""

echo -e "\
menuentry \"aPlus - Text Mode\" { \n\
    multiboot /aplus $kargs graphics=no"

echo -e "\
    module /usr/lib/modules/exports"

for ko in $(find root/usr/lib/modules -type f -name *.ko); do
    test -f "$ko" || continue
    echo -e "\
    module $(echo $ko | cut -c 5-) $margs"
done

echo -e "\
    boot \n\
}"