#!/bin/bash

kargs='root=/dev/sda0 rootfs=ext2'
margs=''

echo -e "\
menuentry \"aPlus\" { \n\
    multiboot /aplus $kargs"

echo -e "\
    module /usr/lib/modules/exports"


for ko in root/usr/lib/modules/*.ko; do
    test -f "$ko" || continue
    echo -e "\
    module /usr/lib/modules/$(basename $ko) $margs"
done

echo -e "\
    boot \n\
}"

echo ""

echo -e "\
menuentry \"aPlus - Text Mode\" { \n\
    multiboot /aplus $kargs graphics=no"

echo -e "\
    module /usr/lib/modules/exports"

for ko in root/usr/lib/modules/*.ko; do
    test -f "$ko" || continue
    echo -e "\
    module /usr/lib/modules/$(basename $ko) $margs graphics=no"
done

echo -e "\
    boot \n\
}"