#!/bin/bash

# Usage
#   hdd-mount [SOURCE]

explorer="dolphin"
tmp="/tmp/aplus-hdd"
output="$1"




function losetup_new_device {

    local output=$1
    local offset=$2

    if [ -z $output ]; then
        echo "losetup_new_device: output is empty"
        exit 1
    fi

    if [ -z $offset ]; then
        offset=0
    fi


    local device=$(sudo losetup -f)

    if [ -z $device ]; then
        echo "losetup_new_device: no free device found"
        exit 1
    fi


    sudo losetup $device $output -o $offset

    if [ $? -ne 0 ]; then
        echo "losetup_new_device: losetup failed"
        exit 1
    fi


    echo $device

}



# Map the partitions from the image file
part=$(losetup_new_device $output 1048576)

# Mount the filesystem via loopback
mkdir -p $tmp/p1
sudo mount $part $tmp/p1

if which $explorer; then
    $explorer $tmp/p1
fi
