#!/bin/bash

arch=""
flags=""

case $1 in

    i[3-7]86)
        arch="i386"

        flags=""
        flags="$flags -drive id=disk,file=hdd.img,if=none,format=raw -device ich9-ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0"
        flags="$flags -drive id=cdrom,file=cdrom.iso,if=none,format=raw -device ide-cd,drive=cdrom,bus=ahci.1"
        flags="$flags -boot c"
        flags="$flags -m 512"
        flags="$flags -M accel=kvm"
        flags="$flags -smp 1"
        flags="$flags -vga std"
        flags="$flags -soundhw ac97"
        flags="$flags -device pcnet,netdev=net0"
        flags="$flags -netdev user,id=net0,hostfwd=tcp::8888-:8888"
        ;;
    
    x86_64)
        arch="x86_64"

        flags=""
        flags="$flags -drive id=disk,file=aplus.img,if=none,format=raw -device ich9-ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0"
        flags="$flags -boot c"
        flags="$flags -m 128"
        flags="$flags -M q35,accel=kvm"
        flags="$flags -cpu kvm64,+x2apic,+pdpe1gb,+rdtscp,+fxsr"
        flags="$flags -smp 1"
        flags="$flags -vga std"
        flags="$flags -soundhw ac97"
        flags="$flags -device e1000,netdev=net0"
        flags="$flags -netdev user,id=net0,hostfwd=tcp::8888-:8888"
        ;;

    *)
        echo "run-vm: unknown ARCH \"$1\""
        exit 1
        ;;

esac

#if ! which qemu-system-$arch.exe &> /dev/null; then
#    echo "run-vm: qemu-system-$arch not found, you should try to install \"qemu-arch-extra\" package"
#    exit 1
#fi

debug=""
if [ ! -z $2 ]; then
    debug="-S"
fi

#sudo trace-cmd record -e kvm/* qemu-system-$arch -d int -display gtk -serial stdio -no-reboot -no-shutdown -s $debug $flags
#sudo trace-cmd report > trace.log
#rm -f trace.dat

qemu-system-$arch -display gtk -serial stdio -no-reboot -no-shutdown -s $debug $flags