#!/bin/bash

qemu-img convert -f raw -O vmdk aplus.img aplus.vmdk

touch /tmp/aplus.log
tail -f /tmp/aplus.log &

VBoxManage internalcommands sethduuid aplus.vmdk e5b5beee-4ea9-42c7-acc7-319816745411
VBoxManage startvm aplus

while VBoxManage list runningvms | grep aplus &> /dev/null; do
    sleep 1
done

kill %1 &> /dev/null
rm aplus.vmdk
