#!/bin/dash

case "$1" in
    start)
        exec /sbin/sync --daemon
        ;;
    stop | status | restart)
        ;;
    *)
        echo "Usage: `basename $0` {start|stop|status|restart}"
        exit 1
    esac