cmake_minimum_required(VERSION 3.1)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)


set(TARGET           "" CACHE STRING "Build Target")
set(TOOLCHAIN        "" CACHE STRING "Toolchain Path")
set(TOOLCHAIN_PREFIX "" CACHE STRING "Toolchain Target Path")


set(CMAKE_CROSSCOMPILING TRUE)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER   ${TOOLCHAIN}/bin/${TARGET}-aplus-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN}/bin/${TARGET}-aplus-g++)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN}/bin/${TARGET}-aplus-gcc)



set(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN} CACHE INTERNAL "")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH CACHE INTERNAL "")
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY CACHE INTERNAL "")
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY CACHE INTERNAL "")
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY CACHE INTERNAL "")

if(NOT ${TARGET} STREQUAL "")
    include("${CMAKE_SOURCE_DIR}/cmake/toolchain-${TARGET}.cmake")
endif()