name: deploy

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Install Dependencies
      working-directory: ${{github.workspace}}
      shell: bash
      run: sudo apt update && sudo apt upgrade && sudo apt install -y build-essential gcc g++ nasm parted e2fsprogs automake autoconf grub-pc python3 python3-dev python3-pip python3-venv python3-wheel python3-setuptools sudo fontconfig zip

    - name: Setup environment
      working-directory: ${{github.workspace}}
      shell: bash
      run: pip3 install -r docs/requirements.txt && ./configure x86_64

    - name: Build Image
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./makew dist
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ${{github.workspace}}/aplus-*.tar.gz
          ${{github.workspace}}/aplus-*.tar.xz
          ${{github.workspace}}/aplus-*.zip
