name: release

on:
  push:
    branches: main
    
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2 
    
    - name: Release x86_64
      working-directory: ${{github.workspace}}
      shell: bash
      run: ci/release.sh x86_64
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "latest"
        title: "Development Release ${{ github.sha }}"
        files: |
          ${{github.workspace}}/release-aplus-*.tar.gz
          ${{github.workspace}}/release-aplus-*.tar.xz
          ${{github.workspace}}/release-aplus-*.zip
