#!/bin/bash

PATH=/usr/local/bin:/usr/bin:/bin

# cd to the directory of the image so we can work with just filenames
dir="$(dirname "$1")"
cd "$dir" || exit 1
base="$(basename "$1" .png)"

# create a WebP version of the PNG
cwebp -preset icon "$base".png -o "$base".webp -quiet
rm -f "$base.png"

# delete the WebP file if it is equal size or larger than the original PNG
#if [[ `stat -c '%s' "$base".webp` -ge `stat -c '%s' "$base".png` ]]; then
#    echo "Deleting WebP file that is no smaller than PNG"
#    rm -f "$base".webp
#fi

# delete the WebP file if it is size 0
if [[ -f "$base".webp && ! -s "$base".webp ]]; then
    echo "Deleting empty WebP file"
    rm -f "$base".webp
fi
